import {createHash} from "node:crypto";
import {chmod, copyFile, lstat, mkdir, readFile, readdir, rename, rm, writeFile} from "node:fs/promises";
import {dirname, isAbsolute, join, relative, resolve, sep} from "node:path";

const VERSION=/^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$/;
const REL=/^@?[A-Za-z0-9][A-Za-z0-9@._/-]{0,239}$/;
const HEX=/^[a-f0-9]{64}$/;
const ROLES=new Set(["controller","agent"]);

export function safeVersion(value){if(typeof value!=="string"||value.length>128||!VERSION.test(value)||value.includes(".."))throw new Error("ERR_INSTALL_VERSION");return value;}
export function compareVersions(a,b){safeVersion(a);safeVersion(b);const [ac,ap]=a.split("-",2),[bc,bp]=b.split("-",2),an=ac.split(".").map(Number),bn=bc.split(".").map(Number);for(let i=0;i<3;i++)if(an[i]!==bn[i])return an[i]<bn[i]?-1:1;if(ap===bp)return 0;if(ap===undefined)return 1;if(bp===undefined)return -1;return ap<bp?-1:ap>bp?1:0;}
export function safeRole(value){if(!ROLES.has(value))throw new Error("ERR_INSTALL_ROLE");return value;}
export function safeRelative(value){if(typeof value!=="string"||!REL.test(value)||isAbsolute(value)||value.split("/").some(part=>part===""||part==="."||part===".."))throw new Error("ERR_INSTALL_PATH");return value;}
export function contained(root,path){const r=resolve(root),p=resolve(path);return p===r||p.startsWith(r+sep);}
export function sha256(bytes){return createHash("sha256").update(bytes).digest("hex");}
function canonicalFiles(files){return [...files].sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0).map(f=>`${f.path}\0${f.sha256}\0${f.size}\n`).join("");}
export function verifyManifest(input){
 if(!input||input.schemaVersion!==1||!ROLES.has(input.role))throw new Error("ERR_INSTALL_MANIFEST");
 safeVersion(input.version);
 if(!Array.isArray(input.files)||input.files.length<1||input.files.length>4096)throw new Error("ERR_INSTALL_MANIFEST");
 const seen=new Set();
 for(const f of input.files){safeRelative(f?.path);if(seen.has(f.path)||!Number.isSafeInteger(f.size)||f.size<0||!HEX.test(f.sha256)||![0o644,0o755].includes(f.mode))throw new Error("ERR_INSTALL_MANIFEST");seen.add(f.path);}
 const p=input.provenance;
 if(!p||p.unsigned!==true||typeof p.builder!=="string"||!/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/.test(p.builder)||typeof p.sourceCommit!=="string"||!/^[a-f0-9]{40}(?:[a-f0-9]{24})?$/.test(p.sourceCommit)||!HEX.test(p.inventoryDigest)||p.inventoryDigest!==sha256(canonicalFiles(input.files)))throw new Error("ERR_INSTALL_PROVENANCE");
 return Object.freeze({...input,files:Object.freeze(input.files.map(f=>Object.freeze({...f}))),provenance:Object.freeze({...p})});
}
export function platformLayout(platform,root="/"){
 if(platform==="windows"&&process.platform==="win32"&&root==="/")root=resolve("\\");
 if(typeof root!=="string"||root.length<1||root.length>4096||root.includes("\0")||!isAbsolute(root)||resolve(root)!==root)throw new Error("ERR_INSTALL_ROOT");
 if(platform==="linux")return Object.freeze({platform,root:resolve(root),installRoot:resolve(root,"opt/lan-model-manager"),releaseRoot:resolve(root,"opt/lan-model-manager/releases"),stateRoot:resolve(root,"var/lib/lan-model-manager"),configRoot:resolve(root,"etc/lan-model-manager"),logRoot:resolve(root,"var/log/lan-model-manager"),serviceRoot:resolve(root,"etc/systemd/system"),accountRoot:resolve(root,"usr/lib/sysusers.d"),tmpfilesRoot:resolve(root,"usr/lib/tmpfiles.d")});
 if(platform==="windows")return Object.freeze({platform,root:resolve(root),installRoot:resolve(root,"Program Files/LANModelManager"),releaseRoot:resolve(root,"Program Files/LANModelManager/releases"),stateRoot:resolve(root,"ProgramData/LANModelManager/state"),configRoot:resolve(root,"ProgramData/LANModelManager/config"),logRoot:resolve(root,"ProgramData/LANModelManager/log"),serviceRoot:resolve(root,"ProgramData/LANModelManager/service"),accountRoot:resolve(root,"ProgramData/LANModelManager/service"),tmpfilesRoot:resolve(root,"ProgramData/LANModelManager/service")});
 throw new Error("ERR_INSTALL_PLATFORM");
}
function assertLayout(layout){for(const [key,value] of Object.entries(layout))if(key!=="platform"&&key!=="root"&&!contained(layout.root,value))throw new Error("ERR_INSTALL_ROOT");}
async function exists(path){try{await lstat(path);return true;}catch(e){if(e?.code==="ENOENT")return false;throw e;}}
async function rejectSymlinkAncestors(root,target){if(!contained(root,target))throw new Error("ERR_INSTALL_ROOT");let current=resolve(root);try{if((await lstat(current)).isSymbolicLink())throw new Error("ERR_INSTALL_SYMLINK");}catch(e){if(e?.code!=="ENOENT")throw e;}for(const part of relative(current,resolve(target)).split(sep).filter(Boolean)){current=join(current,part);try{const info=await lstat(current);if(info.isSymbolicLink())throw new Error("ERR_INSTALL_SYMLINK");}catch(e){if(e?.code==="ENOENT")return;throw e;}}}
async function secureLayout(plan){for(const path of [plan.layout.installRoot,plan.layout.releaseRoot,plan.layout.stateRoot,plan.layout.configRoot,plan.layout.logRoot,plan.layout.serviceRoot,plan.layout.accountRoot,plan.layout.tmpfilesRoot,plan.release,plan.pointer])await rejectSymlinkAncestors(plan.layout.root,path);}
async function atomicWrite(path,bytes,mode=0o644){await mkdir(dirname(path),{recursive:true,mode:0o755});const tmp=`${path}.tmp-${process.pid}`;await writeFile(tmp,bytes,{mode,flag:"wx"});await chmod(tmp,mode);await rename(tmp,path);}
async function readCurrent(layout,role){const path=join(layout.installRoot,`${role}.current`);try{return safeVersion((await readFile(path,"utf8")).trim());}catch(e){if(e?.code==="ENOENT")return null;throw e;}}
function serviceFiles(layout,role){if(layout.platform==="linux")return [join(layout.serviceRoot,`lan-model-${role}.service`),join(layout.accountRoot,"lan-model-manager.conf"),join(layout.tmpfilesRoot,"lan-model-manager.conf")];return [join(layout.serviceRoot,`lan-model-${role}.service.json`)];}
function linuxUnit(role){const account=`lanmodel-${role}`,state=`/var/lib/lan-model-manager/${role}`,config=`/etc/lan-model-manager/${role}`;return `[Unit]\nDescription=LAN Model Manager ${role}\nAfter=network-online.target\nWants=network-online.target\nConditionPathExists=/opt/lan-model-manager/${role}.current\n\n[Service]\nType=simple\nUser=${account}\nGroup=${account}\nExecStart=/opt/lan-model-manager/bin/launch ${role}\nRestart=on-failure\nRestartSec=5s\nTimeoutStopSec=30s\nUMask=${role==="agent"?"0077":"0027"}\n${role==="agent"?`Environment=LANMM_STATE_DIR=${state}\nEnvironment=LANMM_CERT_DIR=${state}/cert\nEnvironment=LANMM_CACHE_DIR=${state}/cache`:`Environment=LANMM_DATA_DIR=${state}`}\nNoNewPrivileges=yes\nPrivateTmp=yes\nProtectSystem=strict\nProtectHome=${role==="agent"?"read-only":"yes"}\nReadWritePaths=${state} /var/log/lan-model-manager\nRestrictSUIDSGID=yes\nLockPersonality=yes\n\n[Install]\nWantedBy=multi-user.target\n`;}
const SYSUSERS=`u lanmodel-controller - "LAN Model Manager Controller" /var/lib/lan-model-manager/controller /usr/sbin/nologin\nu lanmodel-agent - "LAN Model Manager Host Agent" /var/lib/lan-model-manager/agent /usr/sbin/nologin\n`;
const TMPFILES=`d /var/lib/lan-model-manager/controller 0700 lanmodel-controller lanmodel-controller -\nd /var/lib/lan-model-manager/agent 0700 lanmodel-agent lanmodel-agent -\nd /etc/lan-model-manager/controller 0750 root lanmodel-controller -\nd /etc/lan-model-manager/agent 0750 root lanmodel-agent -\nd /var/log/lan-model-manager 0750 root root -\n`;
const LINUX_LAUNCHER=`#!/bin/sh\nset -eu\nrole=\${1-}\ncase "$role" in controller|agent) ;; *) exit 64;; esac\nbase=/opt/lan-model-manager\nversion=$(cat "$base/$role.current")\ncase "$version" in *[!0-9A-Za-z.-]*|*..*|'') exit 65;; esac\nexec "$base/releases/$role/$version/bin/lan-model-$role"\n`;
function windowsDescriptor(role){const name=role==="agent"?"LANModelAgent":"LANModelController",state=`%ProgramData%\\LANModelManager\\state\\${role}`,environment=role==="agent"?[`LANMM_STATE_DIR=${state}`,`LANMM_CERT_DIR=${state}\\cert`,`LANMM_CACHE_DIR=${state}\\cache`]:[`LANMM_DATA_DIR=${state}`];return JSON.stringify({schemaVersion:1,name,role,account:`NT SERVICE\\${name}`,startup:"disabled",startAfterInstall:false,firewallChanges:false,environment,stateAcl:"service-modify;system-admin-full",preserveStateOnUninstall:true},null,2)+"\n";}
async function writeHostDefinitions(plan){if(plan.layout.platform==="linux"){await atomicWrite(join(plan.layout.installRoot,"bin/launch"),LINUX_LAUNCHER,0o755);await atomicWrite(join(plan.layout.serviceRoot,`lan-model-${plan.role}.service`),linuxUnit(plan.role));await atomicWrite(join(plan.layout.accountRoot,"lan-model-manager.conf"),SYSUSERS);await atomicWrite(join(plan.layout.tmpfilesRoot,"lan-model-manager.conf"),TMPFILES);return;}await atomicWrite(join(plan.layout.serviceRoot,`lan-model-${plan.role}.service.json`),windowsDescriptor(plan.role));}
export function installPlan({platform,root="/",role,version,purge=false}){safeRole(role);safeVersion(version);const l=platformLayout(platform,root);assertLayout(l);return Object.freeze({layout:l,role,version,purge:Boolean(purge),release:join(l.releaseRoot,role,version),pointer:join(l.installRoot,`${role}.current`),state:join(l.stateRoot,role),config:join(l.configRoot,role),serviceFiles:Object.freeze(serviceFiles(l,role))});}
async function verifyPayload(payload,manifest){
 for(const file of manifest.files){const source=resolve(payload,...file.path.split("/"));if(!contained(payload,source))throw new Error("ERR_INSTALL_PATH");const bytes=await readFile(source);if(bytes.length!==file.size||sha256(bytes)!==file.sha256)throw new Error("ERR_INSTALL_CHECKSUM");}
}
async function copyPayload(payload,stage,manifest){for(const file of manifest.files){const source=resolve(payload,...file.path.split("/")),target=resolve(stage,...file.path.split("/"));if(!contained(stage,target))throw new Error("ERR_INSTALL_PATH");await mkdir(dirname(target),{recursive:true,mode:0o755});await copyFile(source,target);await chmod(target,file.mode);}}
export async function installRelease(options){
 const {payload,manifest:raw,platform=process.platform==="win32"?"windows":"linux",root="/",dryRun=false}=options??{},manifest=verifyManifest(raw),plan=installPlan({platform,root,role:manifest.role,version:manifest.version});assertLayout(plan.layout);await secureLayout(plan);
 const manifestRole=manifest.role,oldVersion=await readCurrent(plan.layout,manifestRole);await verifyPayload(resolve(payload),manifest);if(oldVersion&&compareVersions(manifest.version,oldVersion)<0)throw new Error("ERR_INSTALL_DOWNGRADE");if(oldVersion===manifest.version){const installed=JSON.parse(await readFile(join(plan.release,"install-manifest.json"),"utf8"));if(verifyManifest(installed).provenance.inventoryDigest!==manifest.provenance.inventoryDigest)throw new Error("ERR_INSTALL_VERSION_CONFLICT");return Object.freeze({changed:false,rolledBack:false,oldVersion,newVersion:manifest.version,actions:Object.freeze([`verify:${manifest.provenance.inventoryDigest}`,"noop:same-version"])});}
 const actions=[`verify:${manifest.provenance.inventoryDigest}`,`stage:${plan.release}`,`switch:${oldVersion??"none"}->${manifest.version}`];if(options.restart)actions.push(`restart:${manifestRole}`);if(options.healthCheck)actions.push(`health:${manifestRole}`);
 if(dryRun)return Object.freeze({changed:false,rolledBack:false,oldVersion,newVersion:manifest.version,actions:Object.freeze(actions)});
 await mkdir(plan.layout.installRoot,{recursive:true,mode:0o755});await mkdir(plan.layout.releaseRoot,{recursive:true,mode:0o755});await mkdir(plan.state,{recursive:true,mode:0o700});await mkdir(plan.config,{recursive:true,mode:0o750});await mkdir(plan.layout.logRoot,{recursive:true,mode:0o750});await writeHostDefinitions(plan);
 const stage=`${plan.release}.staging-${process.pid}`;await rm(stage,{recursive:true,force:true});
 try{await mkdir(stage,{recursive:true,mode:0o755});await copyPayload(resolve(payload),stage,manifest);await atomicWrite(join(stage,"install-manifest.json"),JSON.stringify(manifest,null,2)+"\n");if(await exists(plan.release))await rm(plan.release,{recursive:true,force:true});await mkdir(dirname(plan.release),{recursive:true,mode:0o755});await rename(stage,plan.release);await atomicWrite(plan.pointer,manifest.version+"\n");
  try{if(options.restart)await options.restart({role:manifestRole,version:manifest.version,release:plan.release});if(options.healthCheck&&await options.healthCheck({role:manifestRole,version:manifest.version,release:plan.release})!==true)throw new Error("ERR_INSTALL_HEALTH");}
  catch(error){if(oldVersion)await atomicWrite(plan.pointer,oldVersion+"\n");else await rm(plan.pointer,{force:true});if(options.restart&&oldVersion)await options.restart({role:manifestRole,version:oldVersion,release:join(plan.layout.releaseRoot,manifestRole,oldVersion),rollback:true});return Object.freeze({changed:false,rolledBack:true,oldVersion,newVersion:manifest.version,actions:Object.freeze([...actions,"rollback"]),error:error instanceof Error?error.message:"ERR_INSTALL_HEALTH"});}
  return Object.freeze({changed:true,rolledBack:false,oldVersion,newVersion:manifest.version,actions:Object.freeze(actions)});
 }finally{await rm(stage,{recursive:true,force:true});}
}
export async function uninstall(options){const {platform=process.platform==="win32"?"windows":"linux",root="/",role,purge=false,dryRun=false}=options??{};safeRole(role);const l=platformLayout(platform,root);assertLayout(l);const probe=installPlan({platform,root:l.root,role,version:"0.0.0"});await secureLayout(probe);const paths=[join(l.releaseRoot,role),join(l.installRoot,`${role}.current`),serviceFiles(l,role)[0]];if(purge)paths.push(join(l.stateRoot,role),join(l.configRoot,role));if(!dryRun)for(const path of paths)await rm(path,{recursive:true,force:true});return Object.freeze({changed:!dryRun,purge:Boolean(purge),preserved:purge?Object.freeze([]):Object.freeze([join(l.stateRoot,role),join(l.configRoot,role)]),removed:Object.freeze(paths)});}
export async function inventoryTree(root){const out=[];async function walk(dir,prefix=""){for(const name of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name<b.name?-1:a.name>b.name?1:0)){const rel=prefix?`${prefix}/${name.name}`:name.name;safeRelative(rel);if(name.isDirectory())await walk(join(dir,name.name),rel);else if(name.isFile()){const bytes=await readFile(join(dir,name.name));out.push({path:rel,size:bytes.length,sha256:sha256(bytes),mode:rel.startsWith("bin/")||rel.endsWith(".sh")||rel.endsWith(".ps1")?0o755:0o644});}else throw new Error("ERR_INSTALL_PAYLOAD_TYPE");}}await walk(resolve(root));return Object.freeze(out.map(x=>Object.freeze(x)));}
export function createManifest({role,version,files,sourceCommit,builder="lan-model-manager-packager"}){safeRole(role);safeVersion(version);const normalized=files.map(f=>({...f,path:safeRelative(f.path)}));return verifyManifest({schemaVersion:1,role,version,files:normalized,provenance:{unsigned:true,builder,sourceCommit,inventoryDigest:sha256(canonicalFiles(normalized))}});}
