import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp, mkdir, readFile, writeFile, access, symlink} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {createManifest,installPlan,installRelease,inventoryTree,safeRelative,uninstall,verifyManifest} from "../core.js";

const COMMIT="9f9f243e76991e4fd5e8365001f2074bdfe44ffd";
async function payload(root:string,version:string,body:string,role="agent"){const dir=join(root,`payload-${version}`);await mkdir(join(dir,"bin"),{recursive:true});await writeFile(join(dir,"bin",role==="agent"?"lan-model-agent":"lan-model-controller"),body,{mode:0o755});const files=await inventoryTree(dir);return{dir,manifest:createManifest({role,version,files,sourceCommit:COMMIT})};}
async function present(path:string){try{await access(path);return true}catch{return false}}

test("dry-run validates bytes and reports canonical rootless plan without mutation",async()=>{const root=await mkdtemp(join(tmpdir(),"lmm-install-")),p=await payload(root,"1.0.0","v1");const result=await installRelease({payload:p.dir,manifest:p.manifest,platform:"linux",root,dryRun:true});assert.equal(result.changed,false);assert.match(result.actions[1]!,/releases\/agent\/1\.0\.0$/);assert.equal(await present(join(root,"opt")),false);});

test("upgrade stages side-by-side, rolls back failed health, and preserves state",async()=>{const root=await mkdtemp(join(tmpdir(),"lmm-upgrade-")),v1=await payload(root,"1.0.0","v1"),v2=await payload(root,"1.1.0","v2"),restarts:string[]=[];await installRelease({payload:v1.dir,manifest:v1.manifest,platform:"linux",root,healthCheck:async()=>true});const plan=installPlan({platform:"linux",root,role:"agent",version:"1.0.0"});await writeFile(join(plan.state,"enrollment.key"),"keep-secret",{mode:0o600});const failed=await installRelease({payload:v2.dir,manifest:v2.manifest,platform:"linux",root,restart:async x=>{restarts.push(`${x.version}:${Boolean(x.rollback)}`)},healthCheck:async()=>false});assert.equal(failed.rolledBack,true);assert.equal((await readFile(plan.pointer,"utf8")).trim(),"1.0.0");assert.equal(await readFile(join(plan.state,"enrollment.key"),"utf8"),"keep-secret");assert.equal(await readFile(join(plan.layout.releaseRoot,"agent","1.1.0","bin","lan-model-agent"),"utf8"),"v2");assert.deepEqual(restarts,["1.1.0:false","1.0.0:true"]);});

test("Windows upgrade rolls back the pointer and preserves enrollment state",async()=>{const root=await mkdtemp(join(tmpdir(),"lmm-win-upgrade-")),v1=await payload(root,"1.0.0","v1"),v2=await payload(root,"1.1.0","v2");await installRelease({payload:v1.dir,manifest:v1.manifest,platform:"windows",root});const plan=installPlan({platform:"windows",root,role:"agent",version:"1.0.0"});await writeFile(join(plan.state,"enrollment.key"),"keep");const result=await installRelease({payload:v2.dir,manifest:v2.manifest,platform:"windows",root,healthCheck:async()=>false});assert.equal(result.rolledBack,true);assert.equal((await readFile(plan.pointer,"utf8")).trim(),"1.0.0");assert.equal(await readFile(join(plan.state,"enrollment.key"),"utf8"),"keep");});

test("successful switch and uninstall preserve data unless purge is explicit",async()=>{const root=await mkdtemp(join(tmpdir(),"lmm-uninstall-")),v1=await payload(root,"2.0.0","ok");await installRelease({payload:v1.dir,manifest:v1.manifest,platform:"linux",root});const plan=installPlan({platform:"linux",root,role:"agent",version:"2.0.0"});await writeFile(join(plan.state,"identity.crt"),"certificate");const kept=await uninstall({platform:"linux",root,role:"agent"});assert.deepEqual(kept.preserved,[plan.state,plan.config]);assert.equal(await readFile(join(plan.state,"identity.crt"),"utf8"),"certificate");await uninstall({platform:"linux",root,role:"agent",purge:true});assert.equal(await present(plan.state),false);});

test("repeat install is idempotent and downgrade is denied",async()=>{const root=await mkdtemp(join(tmpdir(),"lmm-idempotent-")),v2=await payload(root,"2.0.0","v2"),v1=await payload(root,"1.9.0","v1");await installRelease({payload:v2.dir,manifest:v2.manifest,platform:"linux",root});const same=await installRelease({payload:v2.dir,manifest:v2.manifest,platform:"linux",root});assert.equal(same.changed,false);assert.deepEqual(same.actions.slice(-1),["noop:same-version"]);await assert.rejects(installRelease({payload:v1.dir,manifest:v1.manifest,platform:"linux",root}),/ERR_INSTALL_DOWNGRADE/);});

test("pre-existing symlink ancestors cannot redirect privileged writes",async()=>{const root=await mkdtemp(join(tmpdir(),"lmm-link-root-")),outside=await mkdtemp(join(tmpdir(),"lmm-link-out-")),p=await payload(root,"1.0.0","good");await mkdir(join(root,"opt"),{recursive:true});await symlink(outside,join(root,"opt","lan-model-manager"));await assert.rejects(installRelease({payload:p.dir,manifest:p.manifest,platform:"linux",root}),/ERR_INSTALL_SYMLINK/);assert.equal(await present(join(outside,"releases")),false);});

test("checksum, provenance, traversal, and unbounded inputs fail closed",async()=>{const root=await mkdtemp(join(tmpdir(),"lmm-invalid-")),p=await payload(root,"1.0.0","good");await writeFile(join(p.dir,"bin","lan-model-agent"),"tampered");await assert.rejects(installRelease({payload:p.dir,manifest:p.manifest,platform:"linux",root}),/ERR_INSTALL_CHECKSUM/);assert.throws(()=>safeRelative("../escape"),/ERR_INSTALL_PATH/);assert.throws(()=>verifyManifest({...p.manifest,files:[...p.manifest.files,{...p.manifest.files[0],path:"bin/other"}]}),/ERR_INSTALL_PROVENANCE/);assert.throws(()=>installPlan({platform:"linux",root,role:"agent",version:"x"}),/ERR_INSTALL_VERSION/);});

test("Windows service environments are deterministic and strictly role-bound",async()=>{const expected={controller:["LANMM_DATA_DIR=%ProgramData%\\LANModelManager\\state\\controller"],agent:["LANMM_STATE_DIR=%ProgramData%\\LANModelManager\\state\\agent","LANMM_CERT_DIR=%ProgramData%\\LANModelManager\\state\\agent\\cert","LANMM_CACHE_DIR=%ProgramData%\\LANModelManager\\state\\agent\\cache"]};for(const role of ["controller","agent"] as const){const root=await mkdtemp(join(tmpdir(),`lmm-win-${role}-`)),p=await payload(root,"3.1.0",role,role);await installRelease({payload:p.dir,manifest:p.manifest,platform:"windows",root});const plan=installPlan({platform:"windows",root,role,version:"3.1.0"}),descriptor=JSON.parse(await readFile(plan.serviceFiles[0]!,"utf8"));assert.deepEqual(descriptor.environment,expected[role]);assert.equal(descriptor.environment.some((entry:string)=>role==="controller"?/^LANMM_(?:STATE|CERT|CACHE)_DIR=/.test(entry):/^LANMM_DATA_DIR=/.test(entry)),false);}const template=JSON.parse(await readFile(new URL("../templates/windows/service-descriptor.json",import.meta.url),"utf8"));assert.deepEqual(template.environments,expected);const ps=await readFile(new URL("../templates/windows/Install-LANModelService.ps1",import.meta.url),"utf8");assert.match(ps,/\$serviceEnvironment=if\(\$Role -eq 'agent'\)\{\s*@\("LANMM_STATE_DIR=\$state","LANMM_CERT_DIR=\$\(Join-Path \$state 'cert'\)","LANMM_CACHE_DIR=\$\(Join-Path \$state 'cache'\)"\)\s*\}else\{\s*@\("LANMM_DATA_DIR=\$state"\)\s*\}/);assert.match(ps,/-Value \$serviceEnvironment/);});

test("Linux definitions are disabled until explicitly enabled and Windows uses virtual accounts",async()=>{for(const platform of ["linux","windows"] as const){const root=await mkdtemp(join(tmpdir(),`lmm-${platform}-`)),p=await payload(root,"3.0.0","binary");await installRelease({payload:p.dir,manifest:p.manifest,platform,root});const plan=installPlan({platform,root,role:"agent",version:"3.0.0"});if(platform==="linux"){const unit=await readFile(plan.serviceFiles[0]!,"utf8");assert.match(unit,/User=lanmodel-agent/);assert.match(unit,/NoNewPrivileges=yes/);assert.match(unit,/LANMM_STATE_DIR=/);assert.doesNotMatch(unit,/systemctl|enable --now/);}else{const descriptor=JSON.parse(await readFile(plan.serviceFiles[0]!,"utf8"));assert.equal(descriptor.account,"NT SERVICE\\LANModelAgent");assert.equal(descriptor.startup,"disabled");assert.equal(descriptor.firewallChanges,false);}}const ps=await readFile(new URL("../templates/windows/Install-LANModelService.ps1",import.meta.url),"utf8");assert.match(ps,/StartupType Disabled/);assert.match(ps,/if\(\$Activate/);assert.match(ps,/ERR_UPGRADE_ROLLBACK/);assert.match(ps,/ValidateSet\('controller','agent'\)/);});
