export type FleetHealth = "active" | "degraded" | "offline" | "revoked";
export interface FleetCounts { hosts:number; active:number; degraded:number; offline:number; revoked:number; providers:number; models:number }
export interface Host { hostId:string; displayName:string; platform:"linux"|"darwin"|"windows"; health:FleetHealth; observedAt:string; idle:boolean; providerCount:number; modelCount:number }
export interface Provider { providerId:string; hostId:string; kind:"ollama"|"lmstudio"; health:"ready"|"degraded"|"unavailable"|"failed"; version:string; versionKnown:boolean; observedAt:string }
export interface Model { modelId:string; providerId:string; hostId:string; canonicalName:string; state:"available"|"installed"|"running"; type:"llm"|"embedding"|"unknown"; digestKnown:boolean; observedAt:string }
export interface Job { jobId:string; state:string; hostId:string; submittedAt:string; updatedAt:string; attempt:number }
export interface AuditEvent { sequence:number; occurredAt:string; actorKind:string; action:string; outcome:string; hostId:string|null }
export interface Page<T> { items:readonly T[]; nextCursor:string|null; counts:FleetCounts }
export type ApiEnvelope<T>={ok:true;value:T}|{ok:false;error:{code:string;message:string}};
export class ApiError extends Error { constructor(readonly status:number,readonly code:string,message:string){super(message);this.name="ApiError";} }
const record=(v:unknown):v is Record<string,unknown>=>typeof v==="object"&&v!==null&&!Array.isArray(v);
export function parseEnvelope<T>(value:unknown):T { if(!record(value)||typeof value.ok!=="boolean")throw new ApiError(502,"INVALID_RESPONSE","The controller returned an invalid response.");if(value.ok===true&&"value" in value)return value.value as T;if(value.ok===false&&record(value.error)&&typeof value.error.code==="string"&&typeof value.error.message==="string")throw new ApiError(400,value.error.code,value.error.message);throw new ApiError(502,"INVALID_RESPONSE","The controller returned an invalid response."); }
export interface ApiClient { summary(signal?:AbortSignal):Promise<FleetCounts>; hosts(signal?:AbortSignal):Promise<Page<Host>>; providers(hostId:string,signal?:AbortSignal):Promise<readonly Provider[]>; models(hostId:string,signal?:AbortSignal):Promise<readonly Model[]>; jobs(signal?:AbortSignal):Promise<readonly Job[]>; audit(signal?:AbortSignal):Promise<readonly AuditEvent[]> }
export function createApiClient(fetcher:typeof fetch=fetch):ApiClient { const get=async<T>(path:string,signal?:AbortSignal):Promise<T>=>{const response=await fetcher(`/api/v1${path}`,{method:"GET",credentials:"same-origin",headers:{accept:"application/json"},...(signal?{signal}:{})});let body:unknown;try{body=await response.json();}catch{throw new ApiError(response.status,"INVALID_RESPONSE","The controller returned unreadable data.");}if(!response.ok){try{return parseEnvelope<T>(body);}catch(error){if(error instanceof ApiError)throw new ApiError(response.status,error.code,error.message);throw error;}}return parseEnvelope<T>(body);};return{summary:s=>get("/fleet/summary",s),hosts:s=>get("/fleet/hosts?limit=200",s),providers:(id,s)=>get(`/fleet/hosts/${encodeURIComponent(id)}/providers`,s),models:(id,s)=>get(`/fleet/hosts/${encodeURIComponent(id)}/models`,s),jobs:async s=>(await get<{items:readonly Job[]}>("/jobs?state=running&limit=100",s)).items,audit:async s=>(await get<{items:readonly AuditEvent[]}>("/audit?limit=100",s)).items};}
