export type FleetHealth = "active" | "degraded" | "offline" | "revoked";
export interface FleetCounts { hosts:number; active:number; degraded:number; offline:number; revoked:number; providers:number; models:number }
export interface Host { hostId:string; displayName:string; platform:"linux"|"darwin"|"windows"; health:FleetHealth; observedAt:string; idle:boolean; providerCount:number; modelCount:number }
export interface Provider { providerId:string; hostId:string; kind:"ollama"|"lmstudio"; health:"ready"|"degraded"|"unavailable"|"failed"; version:string; versionKnown:boolean; observedAt:string }
export interface Model { modelId:string; providerId:string; hostId:string; canonicalName:string; state:"available"|"installed"|"running"; type:"llm"|"embedding"|"unknown"; observedAt:string }
export interface Job { jobId:string; state:string; hostId:string; submittedAt:string; updatedAt:string; attempt:number }
export interface AuditEvent { sequence:number; occurredAt:string; actorKind:string; action:string; outcome:string; hostId:string|null }
export interface Page<T> { items:readonly T[]; nextCursor:string|null; counts:FleetCounts }
export class ApiError extends Error { constructor(readonly status:number,readonly code:string,message:string){super(message);this.name="ApiError";} }
export class InvalidResponseError extends ApiError { constructor(status=502,message="The controller returned an invalid response."){super(status,"INVALID_RESPONSE",message);this.name="InvalidResponseError";} }
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
function exact(value:unknown,keys:readonly string[]):Record<string,unknown>{try{if(typeof value!=="object"||value===null||Array.isArray(value))throw 0;const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)throw 0;const own=Reflect.ownKeys(value),descriptors=Object.getOwnPropertyDescriptors(value);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k)||!descriptors[k]||!("value" in descriptors[k]!)))throw 0;return Object.fromEntries(keys.map(k=>[k,descriptors[k]!.value]));}catch{throw new InvalidResponseError();}}
const id=(v:unknown)=>typeof v==="string"&&ID.test(v)?v:(()=>{throw new InvalidResponseError();})();
const text=(v:unknown,empty=false)=>typeof v==="string"&&(empty||v.trim().length>0)?v.trim():(()=>{throw new InvalidResponseError();})();
const integer=(v:unknown)=>typeof v==="number"&&Number.isSafeInteger(v)&&v>=0?v:(()=>{throw new InvalidResponseError();})();
const bool=(v:unknown)=>typeof v==="boolean"?v:(()=>{throw new InvalidResponseError();})();
const time=(v:unknown)=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v))?v:(()=>{throw new InvalidResponseError();})();
const member=<T extends string>(v:unknown,values:readonly T[]):T=>typeof v==="string"&&values.includes(v as T)?v as T:(()=>{throw new InvalidResponseError();})();
function arrayValues(value:unknown,max:number):unknown[]{try{if(!Array.isArray(value)||value.length>max)throw 0;const keys=Reflect.ownKeys(value),descriptors=Object.getOwnPropertyDescriptors(value);if(keys.some(key=>key!=="length"&&(typeof key!=="string"||!/^(0|[1-9]\d*)$/.test(key)))||value.length!==keys.length-1)throw 0;const result:unknown[]=[];for(let index=0;index<value.length;index++){const descriptor=descriptors[String(index)];if(!descriptor||!("value" in descriptor))throw 0;result.push(descriptor.value);}return result;}catch{throw new InvalidResponseError();}}
export function parseEnvelope(value:unknown):unknown{let d:Record<string,unknown>;try{d=exact(value,["ok","value"]);}catch{d=exact(value,["ok","error"]);}if(d.ok===true&&"value" in d)return d.value;if(d.ok===false&&"error" in d){const error=exact(d.error,["code","message"]);throw new ApiError(400,text(error.code),text(error.message));}throw new InvalidResponseError();}
export function parseFleetCounts(value:unknown):FleetCounts{const d=exact(value,["hosts","active","degraded","offline","revoked","providers","models"]);return Object.freeze({hosts:integer(d.hosts),active:integer(d.active),degraded:integer(d.degraded),offline:integer(d.offline),revoked:integer(d.revoked),providers:integer(d.providers),models:integer(d.models)});}
export function parseHost(value:unknown):Host{const d=exact(value,["hostId","displayName","platform","health","observedAt","idle","providerCount","modelCount"]);return Object.freeze({hostId:id(d.hostId),displayName:text(d.displayName),platform:member(d.platform,["linux","darwin","windows"]),health:member(d.health,["active","degraded","offline","revoked"]),observedAt:time(d.observedAt),idle:bool(d.idle),providerCount:integer(d.providerCount),modelCount:integer(d.modelCount)});}
export function parseProvider(value:unknown):Provider{const d=exact(value,["providerId","hostId","kind","health","version","versionKnown","observedAt"]);return Object.freeze({providerId:id(d.providerId),hostId:id(d.hostId),kind:member(d.kind,["ollama","lmstudio"]),health:member(d.health,["ready","degraded","unavailable","failed"]),version:text(d.version,true),versionKnown:bool(d.versionKnown),observedAt:time(d.observedAt)});}
export function parseModel(value:unknown):Model{const d=exact(value,["modelId","providerId","hostId","canonicalName","state","type","observedAt"]);return Object.freeze({modelId:id(d.modelId),providerId:id(d.providerId),hostId:id(d.hostId),canonicalName:text(d.canonicalName),state:member(d.state,["available","installed","running"]),type:member(d.type,["llm","embedding","unknown"]),observedAt:time(d.observedAt)});}
export function parseFleetPage(value:unknown):Page<Host>{const d=exact(value,["items","nextCursor","counts"]),items=arrayValues(d.items,200);if(!(d.nextCursor===null||typeof d.nextCursor==="string"&&ID.test(d.nextCursor)))throw new InvalidResponseError();return Object.freeze({items:Object.freeze(items.map(parseHost)),nextCursor:d.nextCursor as string|null,counts:parseFleetCounts(d.counts)});}
export function parseProviders(value:unknown):readonly Provider[]{return Object.freeze(arrayValues(value,10_000).map(parseProvider));}
export function parseModels(value:unknown):readonly Model[]{return Object.freeze(arrayValues(value,10_000).map(parseModel));}
export interface ApiClient { summary(signal?:AbortSignal):Promise<FleetCounts>; hosts(signal?:AbortSignal,cursor?:string):Promise<Page<Host>>; loadHosts(signal?:AbortSignal):Promise<readonly Host[]>; providers(hostId:string,signal?:AbortSignal):Promise<readonly Provider[]>; models(hostId:string,signal?:AbortSignal):Promise<readonly Model[]>; jobs(signal?:AbortSignal):Promise<readonly Job[]>; audit(signal?:AbortSignal):Promise<readonly AuditEvent[]> }
export function createApiClient(fetcher:typeof fetch=fetch):ApiClient{const request=async(path:string,signal?:AbortSignal):Promise<unknown>=>{const response=await fetcher(`/api/v1${path}`,{method:"GET",credentials:"same-origin",headers:{accept:"application/json"},...(signal?{signal}:{})});let body:unknown;try{body=await response.json();}catch{throw new InvalidResponseError(response.status,"The controller returned unreadable data.");}if(!response.ok){try{parseEnvelope(body);}catch(error){if(error instanceof ApiError)throw new ApiError(response.status,error.code,error.message);throw error;}throw new InvalidResponseError(response.status);}return parseEnvelope(body);};const hosts=async(signal?:AbortSignal,cursor="")=>parseFleetPage(await request(`/fleet/hosts?limit=200${cursor?`&cursor=${encodeURIComponent(cursor)}`:""}`,signal));return{summary:async s=>parseFleetCounts(await request("/fleet/summary",s)),hosts,async loadHosts(signal){const result:Host[]=[],seen=new Set<string>();let cursor="";for(let pages=0;pages<10_000;pages++){if(signal?.aborted)throw new DOMException("Aborted","AbortError");const page=await hosts(signal,cursor);result.push(...page.items);if(page.nextCursor===null)return Object.freeze(result);if(seen.has(page.nextCursor))throw new InvalidResponseError(502,"The controller returned a cursor cycle.");seen.add(page.nextCursor);cursor=page.nextCursor;}throw new InvalidResponseError(502,"The controller returned too many pages.");},providers:async(idValue,s)=>parseProviders(await request(`/fleet/hosts/${encodeURIComponent(id(idValue))}/providers`,s)),models:async(idValue,s)=>parseModels(await request(`/fleet/hosts/${encodeURIComponent(id(idValue))}/models`,s)),jobs:async s=>{const value=await request("/jobs?state=running&limit=100",s);if(typeof value!=="object"||value===null||!Array.isArray((value as {items?:unknown}).items))throw new InvalidResponseError();return Object.freeze((value as {items:Job[]}).items);},audit:async s=>{const value=await request("/audit?limit=100",s);if(typeof value!=="object"||value===null||!Array.isArray((value as {items?:unknown}).items))throw new InvalidResponseError();return Object.freeze((value as {items:AuditEvent[]}).items);}};}
