export interface AuthStatus { readonly initialized:boolean; readonly authenticated:boolean }
export interface AuthSession { readonly authenticated:true; readonly csrfToken:string }
export interface SignedOut { readonly authenticated:false }
export interface AuthCredentials { readonly username:string; readonly password:string }
export interface AuthClient { status(signal?:AbortSignal):Promise<AuthStatus>; bootstrap(credentials:AuthCredentials,signal?:AbortSignal):Promise<AuthSession>; login(credentials:AuthCredentials,signal?:AbortSignal):Promise<AuthSession>; refreshCsrf(signal?:AbortSignal):Promise<AuthSession>; logout(csrfToken:string,signal?:AbortSignal):Promise<SignedOut> }
export class AuthApiError extends Error { constructor(readonly status:number,readonly code:string,message:string){super(message);this.name="AuthApiError";} }
export class InvalidAuthResponseError extends AuthApiError { constructor(status=502){super(status,"INVALID_RESPONSE","The controller returned an invalid response.");this.name="InvalidAuthResponseError";} }
const TOKEN=/^[A-Za-z0-9_-]{43}$/;
const CODE=/^[A-Z][A-Z0-9_]{0,63}$/;
function exact(value:unknown,keys:readonly string[]):Record<string,unknown>{try{if(typeof value!=="object"||value===null||Array.isArray(value))throw 0;const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)throw 0;const own=Reflect.ownKeys(value),descriptors=Object.getOwnPropertyDescriptors(value);if(own.length!==keys.length||own.some(key=>typeof key!=="string"||!keys.includes(key)||!descriptors[key]||!("value" in descriptors[key]!)))throw 0;return Object.fromEntries(keys.map(key=>[key,descriptors[key]!.value]));}catch{throw new InvalidAuthResponseError();}}
function envelope(value:unknown,status:number):unknown{let data:Record<string,unknown>;try{data=exact(value,["ok","value"]);}catch{data=exact(value,["ok","error"]);}if(data.ok===true&&"value" in data)return data.value;if(data.ok===false&&"error" in data){const error=exact(data.error,["code","message"]);if(typeof error.code!=="string"||!CODE.test(error.code)||typeof error.message!=="string"||error.message.length<1||error.message.length>256)throw new InvalidAuthResponseError(status);throw new AuthApiError(status,error.code,error.message);}throw new InvalidAuthResponseError(status);}
export function parseAuthStatus(value:unknown):AuthStatus{const data=exact(value,["initialized","authenticated"]);if(typeof data.initialized!=="boolean"||typeof data.authenticated!=="boolean"||data.authenticated&&!data.initialized)throw new InvalidAuthResponseError();return Object.freeze({initialized:data.initialized,authenticated:data.authenticated});}
export function parseAuthSession(value:unknown):AuthSession{const data=exact(value,["authenticated","csrfToken"]);if(data.authenticated!==true||typeof data.csrfToken!=="string"||!TOKEN.test(data.csrfToken))throw new InvalidAuthResponseError();return Object.freeze({authenticated:true,csrfToken:data.csrfToken});}
export function parseSignedOut(value:unknown):SignedOut{const data=exact(value,["authenticated"]);if(data.authenticated!==false)throw new InvalidAuthResponseError();return Object.freeze({authenticated:false});}
export function createAuthClient(fetcher:typeof fetch=fetch):AuthClient{const request=async(path:string,method:"GET"|"POST",signal?:AbortSignal,body?:AuthCredentials,csrf?:string):Promise<unknown>=>{const response=await fetcher(`/auth/v1/${path}`,{method,credentials:"same-origin",headers:{accept:"application/json",...(body?{"content-type":"application/json"}:{}),...(csrf?{"x-csrf-token":csrf}:{})},...(body?{body:JSON.stringify(body)}:{}),...(signal?{signal}:{})});let data:unknown;try{data=await response.json();}catch{throw new InvalidAuthResponseError(response.status);}const value=envelope(data,response.status);if(!response.ok)throw new InvalidAuthResponseError(response.status);return value;};const client:AuthClient={status:async(signal?:AbortSignal)=>parseAuthStatus(await request("status","GET",signal)),bootstrap:async(credentials:AuthCredentials,signal?:AbortSignal)=>parseAuthSession(await request("bootstrap","POST",signal,credentials)),login:async(credentials:AuthCredentials,signal?:AbortSignal)=>parseAuthSession(await request("login","POST",signal,credentials)),refreshCsrf:async(signal?:AbortSignal)=>parseAuthSession(await request("csrf","POST",signal)),logout:async(csrfToken:string,signal?:AbortSignal)=>{if(!TOKEN.test(csrfToken))throw new AuthApiError(403,"FORBIDDEN","A valid CSRF token is required.");return parseSignedOut(await request("logout","POST",signal,undefined,csrfToken));}};return Object.freeze(client);}
