import React,{ useEffect,useState,type FormEvent,type ReactNode } from "react";
import { createAuthClient,type AuthClient,type AuthCredentials } from "./auth-api.js";

type EntryMode="setup"|"login";
const defaultAuthClient=createAuthClient();
type GateState={kind:"loading"}|{kind:"entry";mode:EntryMode}|{kind:"authenticated";csrfToken:string}|{kind:"error"};
export function AuthGate({client=defaultAuthClient,children}:{client?:AuthClient;children:(csrfToken:string,logout:()=>void,loggingOut:boolean)=>ReactNode}){const[state,setState]=useState<GateState>({kind:"loading"}),[retry,setRetry]=useState(0),[loggingOut,setLoggingOut]=useState(false),[logoutError,setLogoutError]=useState(false);useEffect(()=>{const controller=new AbortController();setState({kind:"loading"});void client.status(controller.signal).then(async status=>{if(!status.authenticated)return{kind:"entry",mode:status.initialized?"login":"setup"}as GateState;const session=await client.refreshCsrf(controller.signal);return{kind:"authenticated",csrfToken:session.csrfToken}as GateState;}).then(next=>{if(!controller.signal.aborted)setState(next);},error=>{if(!controller.signal.aborted&&!(error instanceof Error&&error.name==="AbortError"))setState({kind:"error"});});return()=>controller.abort();},[client,retry]);const submit=async(mode:EntryMode,credentials:AuthCredentials)=>{const session=mode==="setup"?await client.bootstrap(credentials):await client.login(credentials);setState({kind:"authenticated",csrfToken:session.csrfToken});};const logout=()=>{if(state.kind!=="authenticated"||loggingOut)return;setLoggingOut(true);setLogoutError(false);void client.logout(state.csrfToken).then(()=>setState({kind:"entry",mode:"login"}),()=>{setState({kind:"authenticated",csrfToken:state.csrfToken});setLogoutError(true);}).finally(()=>setLoggingOut(false));};if(state.kind==="loading")return <AuthFrame><div className="authStatus" role="status"><span className="authSpinner" aria-hidden="true"/>Checking controller session…</div></AuthFrame>;if(state.kind==="error")return <AuthFrame><div className="authStatus" role="alert"><h1>Controller unavailable</h1><p>Authentication status could not be loaded.</p><button type="button" onClick={()=>setRetry(value=>value+1)}>Retry</button></div></AuthFrame>;if(state.kind==="entry")return <AuthForm mode={state.mode} onSubmit={submit}/>;return <>{logoutError&&<div className="sessionError" role="alert">Sign out failed. Try again.</div>}{children(state.csrfToken,logout,loggingOut)}</>;}
function AuthFrame({children}:{children:ReactNode}){return <main className="authPage"><section className="authCard" aria-labelledby="auth-title"><div className="authBrand" aria-hidden="true">LM</div>{children}</section></main>}
export function AuthForm({mode,onSubmit}:{mode:EntryMode;onSubmit:(mode:EntryMode,credentials:AuthCredentials)=>Promise<void>}){const[username,setUsername]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),setup=mode==="setup";async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;if(setup&&password!==confirm){setError("Passwords do not match.");return;}const credentials={username,password};setUsername("");setPassword("");setConfirm("");setBusy(true);setError(null);try{await onSubmit(mode,credentials);}catch{setError(setup?"Setup could not be completed. Check the fields and try again.":"Invalid username or password.");}finally{setBusy(false);}}return <AuthFrame><p className="eyebrow">LAN Model Manager</p><h1 id="auth-title">{setup?"Create the first owner":"Operator sign in"}</h1><p className="authIntro">{setup?"Set up the controller owner account. This account controls the operator console.":"Sign in to access the operator console."}</p>{error&&<div className="authError" role="alert">{error}</div>}<form className="authForm" onSubmit={submit}><label>Username<input name="username" value={username} onChange={event=>setUsername(event.currentTarget.value)} autoComplete="username" required minLength={1} maxLength={64} pattern="[A-Za-z0-9][A-Za-z0-9._-]{0,63}" disabled={busy}/></label><label>Password<input name="password" type="password" value={password} onChange={event=>setPassword(event.currentTarget.value)} autoComplete={setup?"new-password":"current-password"} required minLength={12} maxLength={1024} disabled={busy}/></label>{setup&&<><label>Confirm password<input name="confirmPassword" type="password" value={confirm} onChange={event=>setConfirm(event.currentTarget.value)} autoComplete="new-password" required minLength={12} maxLength={1024} disabled={busy}/></label><p className="authHint">Use at least 12 characters.</p></>}<button type="submit" disabled={busy}>{busy?(setup?"Creating owner…":"Signing in…"):(setup?"Create owner":"Sign in")}</button></form></AuthFrame>}
