import test from "node:test";import assert from "node:assert/strict";import { InvalidResponseError,createApiClient,parseFleetCounts,parseFleetPage,parseHost,parseModel,parseProvider,type Host } from "./api.js";import { defaultHostSort,emptyHostFilter,filterAndSortHosts } from "./view-model.js";import { healthLabel,hostHash,parseHostHash } from "./fleet-view.js";
const counts={hosts:2,active:1,degraded:0,offline:0,revoked:1,providers:2,models:2};const host=(hostId:string,displayName:string,modelCount=0):Host=>({hostId,displayName,platform:"linux",health:"active",observedAt:"2026-09-28T10:00:00.000Z",idle:true,providerCount:1,modelCount});
test("fleet public DTOs are exact, bounded, and fail closed",()=>{assert.deepEqual(parseFleetCounts(counts),counts);assert.equal(parseHost(host("a","Alpha")).hostId,"a");assert.equal(parseProvider({providerId:"p",hostId:"a",kind:"ollama",health:"ready",version:"1",versionKnown:true,observedAt:"2026-09-28T10:00:00.000Z"}).kind,"ollama");assert.equal(parseModel({modelId:"m",providerId:"p",hostId:"a",canonicalName:"model",state:"installed",type:"llm",observedAt:"2026-09-28T10:00:00.000Z"}).modelId,"m");assert.throws(()=>parseHost({...host("a","Alpha"),endpoint:"private"}),InvalidResponseError);assert.throws(()=>parseFleetCounts({...counts,extra:1}),InvalidResponseError);assert.throws(()=>parseFleetPage({items:new Array(201).fill(host("a","Alpha")),nextCursor:null,counts}),InvalidResponseError);});
test("fleet parsers never invoke accessors or leak hostile proxies",()=>{let invoked=false;const hostile=Object.defineProperty({},"hostId",{get(){invoked=true;return"host";}});assert.throws(()=>parseHost(hostile),InvalidResponseError);assert.equal(invoked,false);assert.throws(()=>parseFleetCounts(new Proxy({}, {ownKeys(){throw new Error("hostile");}})),InvalidResponseError);const sparse:unknown[]=[];sparse.length=1;assert.throws(()=>parseFleetPage({items:sparse,nextCursor:null,counts}),InvalidResponseError);const accessor:unknown[]=[];Object.defineProperty(accessor,"0",{get(){invoked=true;return host("a","Alpha");},enumerable:true});accessor.length=1;assert.throws(()=>parseFleetPage({items:accessor,nextCursor:null,counts}),InvalidResponseError);assert.equal(invoked,false);});
test("host pagination follows cursors, validates pages, and rejects cycles",async()=>{const calls:string[]=[];const fetcher=(async(url:string)=>{calls.push(String(url));const second=String(url).includes("cursor=b");return{ok:true,status:200,json:async()=>({ok:true,value:{items:[second?host("b","Beta"):host("a","Alpha")],nextCursor:second?null:"b",counts}})}}) as unknown as typeof fetch;const result=await createApiClient(fetcher).loadHosts();assert.deepEqual(result.map(value=>value.hostId),["a","b"]);assert.equal(calls.length,2);const cycle=(async()=>({ok:true,status:200,json:async()=>({ok:true,value:{items:[],nextCursor:"again",counts}})})) as unknown as typeof fetch;await assert.rejects(createApiClient(cycle).loadHosts(),InvalidResponseError);});
test("HTTP error status cannot smuggle a successful envelope",async()=>{const fetcher=(async()=>({ok:false,status:500,json:async()=>({ok:true,value:counts})})) as unknown as typeof fetch;await assert.rejects(createApiClient(fetcher).summary(),InvalidResponseError);});
test("host pagination propagates AbortError and never returns partial state",async()=>{const controller=new AbortController(),fetcher=(async(_url:string,init?:RequestInit)=>new Promise((_resolve,reject)=>{init?.signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true});})) as unknown as typeof fetch;const pending=createApiClient(fetcher).loadHosts(controller.signal);controller.abort();await assert.rejects(pending,error=>error instanceof Error&&error.name==="AbortError");});
test("sorting filters deterministically with ascending host-id ties",()=>{const hosts=[{...host("b","Beta",9),health:"revoked" as const},{...host("a","Alpha",9),health:"active" as const},{...host("c","Gamma",1),health:"degraded" as const}];assert.deepEqual(filterAndSortHosts(hosts,emptyHostFilter(),{field:"modelCount",dir:"desc"}).map(value=>value.hostId),["a","b","c"]);assert.deepEqual(filterAndSortHosts(hosts,{platform:"all",health:"active",query:"alp"},defaultHostSort()).map(value=>value.hostId),["a"]);});
test("fleet deep links round-trip and reject unsafe values",()=>{assert.equal(parseHostHash(hostHash("host-a")),"host-a");for(const value of ["#/fleet","#/fleet/host/","#/fleet/host/bad%2Fid","#/fleet/host/%E0%A4%A"])assert.equal(parseHostHash(value),null);assert.equal(healthLabel("revoked"),"revoked");});
