import type { JsonValue,TransportSignedEnvelope,TransportVerifier,TransportRequestBounds } from "@lan-model-manager/core";import { TRANSPORT_DEFAULT_REQUEST_BOUNDS,enforceTransportBounds,parseTransportSignedEnvelope,verifyTransportSignedEnvelope } from "@lan-model-manager/core";import type { CertificateRepository } from "../certificate-repository.js";import { PersistentReplayStore,type ReplayDecision } from "./replay-store.js";
export interface ManagedServer{listen(port:number,host:string,callback:()=>void):void;close(callback?:(error?:Error)=>void):void}
export interface ControllerTransportOptions{readonly certificateRepository:CertificateRepository;readonly replayStore:PersistentReplayStore;readonly verifier:(certificatePem:string)=>TransportVerifier|null;readonly clock?:()=>string;readonly bounds?:TransportRequestBounds;readonly serverFactory?:()=>ManagedServer}
export type TransportAcceptResult={readonly ok:true;readonly envelope:TransportSignedEnvelope}|{readonly ok:false;readonly error:string};
const COMMAND_RESULT_BOUNDS:TransportRequestBounds=Object.freeze({...TRANSPORT_DEFAULT_REQUEST_BOUNDS,maxRequestBytes:768*1024,maxRequestBodyBytes:512*1024});
export class ControllerTransport{private server:ManagedServer|null=null;private readonly clock:()=>string;private readonly bounds:TransportRequestBounds;constructor(private readonly options:ControllerTransportOptions){this.clock=options.clock??(()=>new Date().toISOString());this.bounds=options.bounds??TRANSPORT_DEFAULT_REQUEST_BOUNDS;}
 start(port:number,host:string,callback:()=>void=()=>{}):void{if(this.server||!this.options.serverFactory)throw new Error("ERR_TRANSPORT_LIFECYCLE");const server=this.options.serverFactory();this.server=server;try{server.listen(port,host,callback)}catch(error){this.server=null;throw error;}}
 stop():void{const current=this.server;this.server=null;if(current)current.close();}
 accept(input:unknown):TransportAcceptResult{const parsed=parseTransportSignedEnvelope(input);if(!parsed.ok)return{ok:false,error:parsed.error};const env=parsed.value,record=this.options.certificateRepository.getBySerial(env.certSerial,env.certFingerprint);if(!record||record.status!=="active"||record.binding.candidateId!==env.hostId)return{ok:false,error:"ERR_CERTIFICATE_TRUST"};const verifier=this.options.verifier(record.certificatePem);if(!verifier||verifier.certificate.fingerprint!==env.certFingerprint)return{ok:false,error:"ERR_CERTIFICATE_TRUST"};const verified=verifyTransportSignedEnvelope(env,verifier);if(!verified.ok)return{ok:false,error:verified.error};const encoded=Buffer.byteLength(JSON.stringify(env));const selectedBounds=env.messageType==="agent.command.result"?COMMAND_RESULT_BOUNDS:this.bounds;const bound=enforceTransportBounds(env as TransportSignedEnvelope<JsonValue>,selectedBounds,{requestBytes:encoded,requestFields:Reflect.ownKeys(env).length,bodyBytes:Buffer.byteLength(JSON.stringify(env.payload)),headerBytes:0,headerCount:0,headerNames:[],headerValues:[],bodyDepth:1,serialLength:env.certSerial.length,fingerprintLength:env.certFingerprint.length,hostIdLength:env.hostId.length,nonceLength:env.nonce.length,sequence:env.sequence});if(bound!=="ok")return{ok:false,error:`ERR_${bound.toUpperCase()}`};const replay:ReplayDecision=this.options.replayStore.check(env,this.clock());if(replay!=="accepted")return{ok:false,error:`ERR_REPLAY_${replay.toUpperCase()}`};return{ok:true,envelope:env};}}
