import test from "node:test";import assert from "node:assert/strict";import{generateKeyPairSync,sign,verify}from"node:crypto";import{artifactManifestPayload,authenticateArtifactManifest,createArtifactStage,parseArtifactManifest,parseArtifactStage,transitionArtifactStage,type ArtifactAuthenticator,type ArtifactManifest}from"./artifact.js";
const NOW="2026-09-28T12:00:00.000Z",LATER="2026-09-28T12:00:01.000Z",DIGEST="a".repeat(64),keys=generateKeyPairSync("ec",{namedCurve:"prime256v1"});
function unsigned(overrides:Record<string,unknown>={}):ArtifactManifest{return{schemaVersion:1,artifactId:"artifact-1",modelId:"acme/model",revision:"rev-1",format:"gguf",sizeBytes:10,digest:{algorithm:"sha256",value:DIGEST},provenance:{kind:"approved-source",sourceId:"catalog-1",sourceRevision:"source-rev",observedAt:NOW},issuedAt:NOW,expiresAt:"2026-09-28T13:00:00.000Z",signerId:"controller-1",signature:{algorithm:"ecdsa-p256-sha256",value:"A".repeat(86)},...overrides} as ArtifactManifest;}
function manifest(overrides:Record<string,unknown>={}):ArtifactManifest{const base=unsigned(overrides),signature=sign("sha256",artifactManifestPayload(base)!,keys.privateKey).toString("base64url");return{...base,signature:{algorithm:"ecdsa-p256-sha256",value:signature}};}
const auth:ArtifactAuthenticator={isSignerAuthorized:id=>id==="controller-1",verify:input=>verify("sha256",input.payload,keys.publicKey,input.signature)};
test("manifest parser is strict bounded detached and immutable",()=>{const value=manifest(),parsed=parseArtifactManifest(value);assert.equal(parsed.ok,true);if(parsed.ok){assert.equal(Object.getPrototypeOf(parsed.value),null);assert.equal(Object.isFrozen(parsed.value),true);assert.equal(Object.isFrozen(parsed.value.digest),true);assert.equal(Object.isFrozen(parsed.value.provenance),true);}for(const bad of [{...value,extra:true},{...value,sizeBytes:0},{...value,digest:{algorithm:"sha256",value:"A".repeat(64)}},{...value,expiresAt:NOW}])assert.equal(parseArtifactManifest(bad).ok,false);let calls=0;const hostile=Object.defineProperty({},"artifactId",{get(){calls++;return"artifact";}});assert.equal(parseArtifactManifest(hostile).ok,false);assert.equal(calls,0);});
test("authentication binds every signed manifest field and authorized signer",()=>{const value=manifest(),accepted=authenticateArtifactManifest(value,auth,LATER);assert.equal(accepted.ok,true);if(accepted.ok)assert.match(accepted.manifestDigest,/^[a-f0-9]{64}$/);assert.deepEqual(authenticateArtifactManifest({...value,modelId:"other/model"},auth,LATER),{ok:false,error:"ERR_ARTIFACT_SIGNATURE"});assert.deepEqual(authenticateArtifactManifest(value,{...auth,isSignerAuthorized:()=>false},LATER),{ok:false,error:"ERR_ARTIFACT_SIGNER"});assert.deepEqual(authenticateArtifactManifest(value,auth,"2026-09-28T14:00:00.000Z"),{ok:false,error:"ERR_ARTIFACT_EXPIRED"});});
test("canonical payload and manifest digest are deterministic",()=>{const a=manifest(),b={signature:a.signature,signerId:a.signerId,expiresAt:a.expiresAt,issuedAt:a.issuedAt,provenance:a.provenance,digest:a.digest,sizeBytes:a.sizeBytes,format:a.format,revision:a.revision,modelId:a.modelId,artifactId:a.artifactId,schemaVersion:a.schemaVersion};assert.deepEqual(artifactManifestPayload(a),artifactManifestPayload(b as ArtifactManifest));assert.equal(artifactManifestPayload(Object.defineProperty({},"artifactId",{get(){throw new Error("hostile");}})),null);assert.equal(authenticateArtifactManifest(a,auth,LATER).ok,true);});
test("authenticated staging progresses append verify commit without overflow",()=>{let stage=createArtifactStage(manifest(),auth,"stage-1",LATER);assert.ok(stage);stage=transitionArtifactStage(stage,{type:"append",bytes:4,at:"2026-09-28T12:00:02.000Z"});assert.equal(stage?.status,"receiving");assert.equal(transitionArtifactStage(stage,{type:"append",bytes:7,at:"2026-09-28T12:00:03.000Z"}),null);stage=transitionArtifactStage(stage,{type:"append",bytes:6,at:"2026-09-28T12:00:03.000Z"});assert.equal(stage?.status,"received");stage=transitionArtifactStage(stage,{type:"verify",digest:DIGEST,at:"2026-09-28T12:00:04.000Z"});assert.equal(stage?.status,"verified");stage=transitionArtifactStage(stage,{type:"commit",at:"2026-09-28T12:00:05.000Z"});assert.equal(stage?.status,"committed");assert.equal(Object.isFrozen(stage),true);assert.equal(transitionArtifactStage(stage,{type:"append",bytes:1,at:"2026-09-28T12:00:06.000Z"}),null);});
test("digest mismatch quarantines permanently with stable code",()=>{let stage=createArtifactStage(manifest(),auth,"stage-1",LATER)!;stage=transitionArtifactStage(stage,{type:"append",bytes:10,at:"2026-09-28T12:00:02.000Z"})!;stage=transitionArtifactStage(stage,{type:"verify",digest:"b".repeat(64),at:"2026-09-28T12:00:03.000Z"})!;assert.equal(stage.status,"quarantined");assert.equal(stage.quarantineCode,"digest-mismatch");assert.equal(transitionArtifactStage(stage,{type:"commit",at:"2026-09-28T12:00:04.000Z"}),null);assert.equal(parseArtifactStage({...stage,status:"verified"}).ok,false);assert.equal(parseArtifactStage({...stage,status:"allocated",receivedBytes:1,computedDigest:null,verifiedAt:null,quarantineCode:null}).ok,false);});
test("unauthenticated or expired manifests never allocate staging",()=>{const value=manifest();assert.equal(createArtifactStage({...value,artifactId:"tampered"},auth,"stage-1",LATER),null);assert.equal(createArtifactStage(value,auth,"bad/stage",LATER),null);assert.equal(createArtifactStage(value,auth,"stage-1","2026-09-28T14:00:00.000Z"),null);});
