import { createHash } from "node:crypto";
import type { JsonValue, ParseResult } from "./protocol.js";
import type { PolicyOperation } from "./policy.js";

export interface OperationCapability { readonly operation:PolicyOperation; readonly targetKind:string; readonly targetId:string; readonly hostId:string; readonly modelId:string|null; readonly requestDigest:string; readonly expiresAt:string }
export type CommandOperation="probe"|"inventory"|"estimate"|"load"|"set-options"|"drain"|"unload"|"install"|"remove-managed-artifact";
export interface CommandRequest { readonly requestId:string; readonly jobId:string; readonly hostId:string; readonly operation:CommandOperation; readonly idempotencyKey:string; readonly sequence:number; readonly deadline:string; readonly capability:OperationCapability; readonly params:JsonValue|null }
export interface CommandResponse { readonly requestId:string; readonly jobId:string; readonly hostId:string; readonly sequence:number; readonly status:"accepted"|"running"|"succeeded"|"failed"|"cancelled"; readonly progress:number|null; readonly observedAt:string; readonly observation:JsonValue|null; readonly errorCode:string|null }

const OPS=new Set<unknown>(["probe","inventory","estimate","load","set-options","drain","unload","install","remove-managed-artifact"]), ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/, TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const fail=<T>(error:string):ParseResult<T>=>({ok:false,error});
const freeze=<T>(value:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),value)) as T;
function exact(value:unknown,keys:string[]){try{if(typeof value!=="object"||value===null||Array.isArray(value))return null;const prototype=Object.getPrototypeOf(value),own=Reflect.ownKeys(value),descriptors=Object.getOwnPropertyDescriptors(value);return(prototype===Object.prototype||prototype===null)&&own.length===keys.length&&own.every(key=>typeof key==="string"&&keys.includes(key))&&keys.every(key=>descriptors[key]&&"value" in descriptors[key])?descriptors:null;}catch{return null;}}

function canonicalDomain(value:unknown):boolean { if(value===null||typeof value==="boolean")return true;if(typeof value==="string")return /^[\x20-\x7e]*$/.test(value);if(typeof value==="number")return Number.isSafeInteger(value);if(Array.isArray(value))return value.every(canonicalDomain);if(typeof value==="object"){const prototype=Object.getPrototypeOf(value);return(prototype===Object.prototype||prototype===null)&&Object.keys(value).every(key=>/^[\x20-\x7e]+$/.test(key)&&canonicalDomain((value as Record<string,unknown>)[key]));}return false;}
/** Canonical JSON over the deliberately bounded ASCII/safe-integer command domain. */
function canonical(value:unknown):string { if(value===null)return"null"; if(typeof value==="string"||typeof value==="boolean")return JSON.stringify(value); if(typeof value==="number"){if(!Number.isFinite(value))throw new Error("ERR_COMMAND_DIGEST");return JSON.stringify(value);} if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`; if(typeof value==="object"){const object=value as Record<string,unknown>;return`{${Object.keys(object).sort().map(key=>`${JSON.stringify(key)}:${canonical(object[key])}`).join(",")}}`;} throw new Error("ERR_COMMAND_DIGEST"); }
/** Digest of every execution-relevant request field, excluding only the digest itself. */
export function commandAuthorizationDigest(request:Omit<CommandRequest,"capability">&{readonly capability:Omit<OperationCapability,"requestDigest">|OperationCapability}):string { const capability=request.capability; const bound={requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,operation:request.operation,idempotencyKey:request.idempotencyKey,sequence:request.sequence,deadline:request.deadline,capability:{operation:capability.operation,targetKind:capability.targetKind,targetId:capability.targetId,hostId:capability.hostId,modelId:capability.modelId,expiresAt:capability.expiresAt},params:request.params}; return createHash("sha256").update(canonical(bound)).digest("hex"); }

function targetMatches(request:CommandRequest):boolean { const capability=request.capability,params=request.params&&typeof request.params==="object"&&!Array.isArray(request.params)?request.params as Record<string,unknown>:null; if(capability.targetKind==="host"&&(capability.targetId!==request.hostId||capability.modelId!==null))return false; if(capability.targetKind==="model"&&(capability.modelId===null||capability.targetId!==capability.modelId))return false; if(params&&Object.hasOwn(params,"modelId")&&params.modelId!==capability.modelId)return false; if(params&&Object.hasOwn(params,"hostId")&&params.hostId!==request.hostId)return false; return true; }

export function parseCommandRequest(value:unknown):ParseResult<CommandRequest>{const keys=["requestId","jobId","hostId","operation","idempotencyKey","sequence","deadline","capability","params"],descriptors=exact(value,keys);if(!descriptors)return fail("ERR_COMMAND_REQUEST");const ids=[descriptors.requestId!.value,descriptors.jobId!.value,descriptors.hostId!.value,descriptors.idempotencyKey!.value],sequence=descriptors.sequence!.value,deadline=descriptors.deadline!.value,capDescriptors=exact(descriptors.capability!.value,["operation","targetKind","targetId","hostId","modelId","requestDigest","expiresAt"]),params=descriptors.params!.value;if(ids.some(item=>typeof item!=="string"||!ID.test(item))||!OPS.has(descriptors.operation!.value)||!Number.isSafeInteger(sequence)||sequence<1||typeof deadline!=="string"||!TIME.test(deadline)||Number.isNaN(Date.parse(deadline))||!capDescriptors||params!==null&&typeof params!=="object")return fail("ERR_COMMAND_REQUEST");const cap=Object.fromEntries(Object.keys(capDescriptors).map(key=>[key,capDescriptors[key]!.value])) as unknown as OperationCapability;if(!ID.test(String(cap.targetKind))||!ID.test(String(cap.targetId))||!ID.test(String(cap.hostId))||(cap.modelId!==null&&!ID.test(String(cap.modelId)))||typeof cap.requestDigest!=="string"||!/^[a-f0-9]{64}$/.test(cap.requestDigest)||typeof cap.expiresAt!=="string"||!TIME.test(cap.expiresAt)||cap.operation!==commandPolicyOperation(descriptors.operation!.value as CommandOperation)||cap.hostId!==descriptors.hostId!.value)return fail("ERR_COMMAND_CAPABILITY");const text=JSON.stringify(params);if(!canonicalDomain(params)||Buffer.byteLength(text)>32768||/("endpoint"|"url"|"address"|"command"|"shell")\s*:/.test(text))return fail("ERR_COMMAND_BOUNDS");const request=freeze<CommandRequest>({...Object.fromEntries(keys.filter(key=>key!=="capability").map(key=>[key,descriptors[key]!.value])),capability:freeze<OperationCapability>({...cap})});if(!targetMatches(request)||commandAuthorizationDigest(request)!==cap.requestDigest)return fail("ERR_COMMAND_CAPABILITY");return{ok:true,value:request};}
export function parseCommandResponse(value:unknown):ParseResult<CommandResponse>{const keys=["requestId","jobId","hostId","sequence","status","progress","observedAt","observation","errorCode"],descriptors=exact(value,keys);if(!descriptors)return fail("ERR_COMMAND_RESPONSE");const ids=[descriptors.requestId!.value,descriptors.jobId!.value,descriptors.hostId!.value],sequence=descriptors.sequence!.value,status=descriptors.status!.value,progress=descriptors.progress!.value,time=descriptors.observedAt!.value,error=descriptors.errorCode!.value;if(ids.some(item=>typeof item!=="string"||!ID.test(item))||!Number.isSafeInteger(sequence)||sequence<1||!new Set(["accepted","running","succeeded","failed","cancelled"]).has(status)||(progress!==null&&(!Number.isSafeInteger(progress)||progress<0||progress>100))||typeof time!=="string"||!TIME.test(time)||(error!==null&&(typeof error!=="string"||!/^[A-Z][A-Z0-9_]{0,63}$/.test(error)))||(status==="failed"&&error===null))return fail("ERR_COMMAND_RESPONSE");return{ok:true,value:freeze(Object.fromEntries(keys.map(key=>[key,descriptors[key]!.value])))};}
const MAP:Record<CommandOperation,PolicyOperation>={probe:"observe",inventory:"provider-status",estimate:"model-status",load:"model-load","set-options":"model-set-options",drain:"model-drain",unload:"model-unload",install:"artifact-install","remove-managed-artifact":"artifact-remove"};
export function commandPolicyOperation(value:CommandOperation):PolicyOperation{return MAP[value];}
export function capabilityMatches(request:CommandRequest,now:string):boolean{const capability=request.capability;return capability.operation===commandPolicyOperation(request.operation)&&capability.hostId===request.hostId&&targetMatches(request)&&commandAuthorizationDigest(request)===capability.requestDigest&&Date.parse(now)<Date.parse(capability.expiresAt)&&Date.parse(now)<Date.parse(request.deadline);}
export function responseMatches(request:CommandRequest,response:CommandResponse):boolean{return request.requestId===response.requestId&&request.jobId===response.jobId&&request.hostId===response.hostId&&request.sequence===response.sequence;}
