import { createHash } from "node:crypto";
import type { JsonValue, ParseResult } from "./protocol.js";
import type { PolicyOperation } from "./policy.js";

export interface OperationCapability { readonly operation:PolicyOperation; readonly targetKind:string; readonly targetId:string; readonly hostId:string; readonly modelId:string|null; readonly requestDigest:string; readonly expiresAt:string }
export type CommandOperation="probe"|"inventory"|"estimate"|"load"|"set-options"|"drain"|"unload"|"install"|"remove-managed-artifact"|"inference.chat";
export interface InferenceChatCommandMessage {readonly role:"system"|"user"|"assistant"|"tool";readonly contentBase64:string}
export interface InferenceChatCommandParams {readonly providerId:string;readonly modelId:string;readonly model:string;readonly requestId:string;readonly maxRequestBytes:number;readonly maxResponseBytes:number;readonly messages:readonly InferenceChatCommandMessage[];readonly temperatureMilli:number|null;readonly maxTokens:number|null}
export interface ArtifactInstallCommandParams {readonly providerId:string;readonly model:string;readonly manifest:Readonly<{schemaVersion:1;artifactId:string;modelId:string;revision:string;format:string;sizeBytes:number;digest:Readonly<{algorithm:"sha256";value:string}>;provenance:Readonly<{kind:"approved-source";sourceId:string;sourceRevision:string|null;observedAt:string}>;issuedAt:string;expiresAt:string;signerId:string;signature:Readonly<{algorithm:"ecdsa-p256-sha256";value:string}>}>;readonly manifestDigest:string;readonly downloadTicket:string}
export interface CommandRequest { readonly requestId:string; readonly jobId:string; readonly hostId:string; readonly operation:CommandOperation; readonly idempotencyKey:string; readonly sequence:number; readonly deadline:string; readonly capability:OperationCapability; readonly params:JsonValue|null }
export interface CommandResponse { readonly requestId:string; readonly jobId:string; readonly hostId:string; readonly sequence:number; readonly status:"accepted"|"running"|"succeeded"|"failed"|"cancelled"; readonly progress:number|null; readonly observedAt:string; readonly observation:JsonValue|null; readonly errorCode:string|null }

const OPS=new Set<unknown>(["probe","inventory","estimate","load","set-options","drain","unload","install","remove-managed-artifact","inference.chat"]), ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/, MODEL=/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$/, BASE64=/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/, TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const fail=<T>(error:string):ParseResult<T>=>({ok:false,error});
const freeze=<T>(value:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),value)) as T;
function exact(value:unknown,keys:string[]){try{if(typeof value!=="object"||value===null||Array.isArray(value))return null;const prototype=Object.getPrototypeOf(value),own=Reflect.ownKeys(value),descriptors=Object.getOwnPropertyDescriptors(value);return(prototype===Object.prototype||prototype===null)&&own.length===keys.length&&own.every(key=>typeof key==="string"&&keys.includes(key))&&keys.every(key=>descriptors[key]&&"value" in descriptors[key])?descriptors:null;}catch{return null;}}

function canonicalDomain(value:unknown):boolean { if(value===null||typeof value==="boolean")return true;if(typeof value==="string")return /^[\x20-\x7e]*$/.test(value);if(typeof value==="number")return Number.isSafeInteger(value);if(Array.isArray(value))return value.every(canonicalDomain);if(typeof value==="object"){const prototype=Object.getPrototypeOf(value);return(prototype===Object.prototype||prototype===null)&&Object.keys(value).every(key=>/^[\x20-\x7e]+$/.test(key)&&canonicalDomain((value as Record<string,unknown>)[key]));}return false;}
/** Canonical JSON over the deliberately bounded ASCII/safe-integer command domain. */
function canonical(value:unknown):string { if(value===null)return"null"; if(typeof value==="string"||typeof value==="boolean")return JSON.stringify(value); if(typeof value==="number"){if(!Number.isFinite(value))throw new Error("ERR_COMMAND_DIGEST");return JSON.stringify(value);} if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`; if(typeof value==="object"){const object=value as Record<string,unknown>;return`{${Object.keys(object).sort().map(key=>`${JSON.stringify(key)}:${canonical(object[key])}`).join(",")}}`;} throw new Error("ERR_COMMAND_DIGEST"); }
/** Digest of every execution-relevant request field, excluding only the digest itself. */
export function commandAuthorizationDigest(request:Omit<CommandRequest,"capability">&{readonly capability:Omit<OperationCapability,"requestDigest">|OperationCapability}):string { const capability=request.capability; const bound={requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,operation:request.operation,idempotencyKey:request.idempotencyKey,sequence:request.sequence,deadline:request.deadline,capability:{operation:capability.operation,targetKind:capability.targetKind,targetId:capability.targetId,hostId:capability.hostId,modelId:capability.modelId,expiresAt:capability.expiresAt},params:request.params}; return createHash("sha256").update(canonical(bound)).digest("hex"); }

function targetMatches(request:CommandRequest):boolean { const capability=request.capability,params=request.params&&typeof request.params==="object"&&!Array.isArray(request.params)?request.params as Record<string,unknown>:null; if(capability.targetKind==="host"&&(capability.targetId!==request.hostId||capability.modelId!==null))return false; if(capability.targetKind==="model"&&(capability.modelId===null||capability.targetId!==capability.modelId))return false; if(params&&Object.hasOwn(params,"modelId")&&params.modelId!==capability.modelId)return false; if(params&&Object.hasOwn(params,"hostId")&&params.hostId!==request.hostId)return false; return true; }

export function parseInferenceChatCommandParams(value:unknown):ParseResult<InferenceChatCommandParams>{const keys=["providerId","modelId","model","requestId","maxRequestBytes","maxResponseBytes","messages","temperatureMilli","maxTokens"],d=exact(value,keys);if(!d)return fail("ERR_INFERENCE_CHAT_PARAMS");const providerId=d.providerId!.value,modelId=d.modelId!.value,model=d.model!.value,requestId=d.requestId!.value,maxRequestBytes=d.maxRequestBytes!.value,maxResponseBytes=d.maxResponseBytes!.value,messages=d.messages!.value,temperatureMilli=d.temperatureMilli!.value,maxTokens=d.maxTokens!.value;if(typeof providerId!=="string"||!ID.test(providerId)||typeof modelId!=="string"||!ID.test(modelId)||typeof model!=="string"||!MODEL.test(model)||typeof requestId!=="string"||!ID.test(requestId)||!Number.isSafeInteger(maxRequestBytes)||maxRequestBytes<1||maxRequestBytes>524288||!Number.isSafeInteger(maxResponseBytes)||maxResponseBytes<1||maxResponseBytes>262144||!Array.isArray(messages)||messages.length<1||messages.length>64||(temperatureMilli!==null&&(!Number.isSafeInteger(temperatureMilli)||temperatureMilli<0||temperatureMilli>2000))||(maxTokens!==null&&(!Number.isSafeInteger(maxTokens)||maxTokens<1||maxTokens>131072)))return fail("ERR_INFERENCE_CHAT_PARAMS");let decodedBytes=0;const output:InferenceChatCommandMessage[]=[];for(const item of messages){const md=exact(item,["role","contentBase64"]);if(!md||!["system","user","assistant","tool"].includes(md.role!.value)||typeof md.contentBase64!.value!=="string"||!BASE64.test(md.contentBase64!.value))return fail("ERR_INFERENCE_CHAT_PARAMS");const content=Buffer.from(md.contentBase64!.value,"base64");if(content.length<1||content.length>65536||(decodedBytes+=content.length)>262144)return fail("ERR_INFERENCE_CHAT_PARAMS");try{new TextDecoder("utf-8",{fatal:true}).decode(content);}catch{return fail("ERR_INFERENCE_CHAT_PARAMS");}output.push(Object.freeze({role:md.role!.value,contentBase64:md.contentBase64!.value} as InferenceChatCommandMessage));}const result=freeze<InferenceChatCommandParams>({providerId,modelId,model,requestId,maxRequestBytes,maxResponseBytes,messages:Object.freeze(output),temperatureMilli,maxTokens});if(Buffer.byteLength(JSON.stringify(result))>maxRequestBytes)return fail("ERR_INFERENCE_CHAT_PARAMS");return{ok:true,value:result};}

export function parseArtifactInstallCommandParams(value:unknown):ParseResult<ArtifactInstallCommandParams>{const d=exact(value,["providerId","model","manifest","manifestDigest","downloadTicket"]);if(!d)return fail("ERR_ARTIFACT_INSTALL_PARAMS");const providerId=d.providerId!.value,model=d.model!.value,manifestDigest=d.manifestDigest!.value,downloadTicket=d.downloadTicket!.value,m=d.manifest!.value;if(typeof providerId!=="string"||!ID.test(providerId)||typeof model!=="string"||!MODEL.test(model)||typeof manifestDigest!=="string"||!/^[a-f0-9]{64}$/.test(manifestDigest)||typeof downloadTicket!=="string"||!/^[a-f0-9]{64}$/.test(downloadTicket))return fail("ERR_ARTIFACT_INSTALL_PARAMS");const md=exact(m,["schemaVersion","artifactId","modelId","revision","format","sizeBytes","digest","provenance","issuedAt","expiresAt","signerId","signature"]);if(!md||md.schemaVersion!.value!==1||typeof md.artifactId!.value!=="string"||!ID.test(md.artifactId!.value)||typeof md.modelId!.value!=="string"||!MODEL.test(md.modelId!.value)||typeof md.revision!.value!=="string"||!ID.test(md.revision!.value)||md.format!.value!=="gguf"||!Number.isSafeInteger(md.sizeBytes!.value)||md.sizeBytes!.value<1||typeof md.signerId!.value!=="string"||!ID.test(md.signerId!.value))return fail("ERR_ARTIFACT_INSTALL_PARAMS");const dg=exact(md.digest!.value,["algorithm","value"]),pv=exact(md.provenance!.value,["kind","sourceId","sourceRevision","observedAt"]),sg=exact(md.signature!.value,["algorithm","value"]);if(!dg||dg.algorithm!.value!=="sha256"||typeof dg.value!.value!=="string"||!/^[a-f0-9]{64}$/.test(dg.value!.value)||!pv||pv.kind!.value!=="approved-source"||typeof pv.sourceId!.value!=="string"||!ID.test(pv.sourceId!.value)||(pv.sourceRevision!.value!==null&&(typeof pv.sourceRevision!.value!=="string"||!ID.test(pv.sourceRevision!.value)))||![pv.observedAt!.value,md.issuedAt!.value,md.expiresAt!.value].every(v=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v)))||!sg||sg.algorithm!.value!=="ecdsa-p256-sha256"||typeof sg.value!.value!=="string"||!/^[-_A-Za-z0-9]{80,128}$/.test(sg.value!.value))return fail("ERR_ARTIFACT_INSTALL_PARAMS");return{ok:true,value:freeze({providerId,model,manifest:m,manifestDigest,downloadTicket})};}

export function parseCommandRequest(value:unknown):ParseResult<CommandRequest>{const keys=["requestId","jobId","hostId","operation","idempotencyKey","sequence","deadline","capability","params"],descriptors=exact(value,keys);if(!descriptors)return fail("ERR_COMMAND_REQUEST");const ids=[descriptors.requestId!.value,descriptors.jobId!.value,descriptors.hostId!.value,descriptors.idempotencyKey!.value],sequence=descriptors.sequence!.value,deadline=descriptors.deadline!.value,capDescriptors=exact(descriptors.capability!.value,["operation","targetKind","targetId","hostId","modelId","requestDigest","expiresAt"]),params=descriptors.params!.value;if(ids.some(item=>typeof item!=="string"||!ID.test(item))||!OPS.has(descriptors.operation!.value)||!Number.isSafeInteger(sequence)||sequence<1||typeof deadline!=="string"||!TIME.test(deadline)||Number.isNaN(Date.parse(deadline))||!capDescriptors||params!==null&&typeof params!=="object")return fail("ERR_COMMAND_REQUEST");const cap=Object.fromEntries(Object.keys(capDescriptors).map(key=>[key,capDescriptors[key]!.value])) as unknown as OperationCapability;if(!ID.test(String(cap.targetKind))||!ID.test(String(cap.targetId))||!ID.test(String(cap.hostId))||(cap.modelId!==null&&!ID.test(String(cap.modelId)))||typeof cap.requestDigest!=="string"||!/^[a-f0-9]{64}$/.test(cap.requestDigest)||typeof cap.expiresAt!=="string"||!TIME.test(cap.expiresAt)||cap.operation!==commandPolicyOperation(descriptors.operation!.value as CommandOperation)||cap.hostId!==descriptors.hostId!.value)return fail("ERR_COMMAND_CAPABILITY");const text=JSON.stringify(params),limit=descriptors.operation!.value==="inference.chat"?524288:32768;if(!canonicalDomain(params)||Buffer.byteLength(text)>limit||/("endpoint"|"url"|"address"|"command"|"shell"|"header"|"option"|"path")\s*:/.test(text)||(descriptors.operation!.value==="inference.chat"&&(!parseInferenceChatCommandParams(params).ok||(params as Record<string,unknown>).requestId!==descriptors.requestId!.value))||(descriptors.operation!.value==="install"&&!parseArtifactInstallCommandParams(params).ok))return fail("ERR_COMMAND_BOUNDS");const request=freeze<CommandRequest>({...Object.fromEntries(keys.filter(key=>key!=="capability").map(key=>[key,descriptors[key]!.value])),capability:freeze<OperationCapability>({...cap})});if(!targetMatches(request)||commandAuthorizationDigest(request)!==cap.requestDigest)return fail("ERR_COMMAND_CAPABILITY");return{ok:true,value:request};}
export function parseCommandResponse(value:unknown):ParseResult<CommandResponse>{const keys=["requestId","jobId","hostId","sequence","status","progress","observedAt","observation","errorCode"],descriptors=exact(value,keys);if(!descriptors)return fail("ERR_COMMAND_RESPONSE");const ids=[descriptors.requestId!.value,descriptors.jobId!.value,descriptors.hostId!.value],sequence=descriptors.sequence!.value,status=descriptors.status!.value,progress=descriptors.progress!.value,time=descriptors.observedAt!.value,error=descriptors.errorCode!.value;if(ids.some(item=>typeof item!=="string"||!ID.test(item))||!Number.isSafeInteger(sequence)||sequence<1||!new Set(["accepted","running","succeeded","failed","cancelled"]).has(status)||(progress!==null&&(!Number.isSafeInteger(progress)||progress<0||progress>100))||typeof time!=="string"||!TIME.test(time)||(error!==null&&(typeof error!=="string"||!/^[A-Z][A-Z0-9_]{0,63}$/.test(error)))||(status==="failed"&&error===null))return fail("ERR_COMMAND_RESPONSE");return{ok:true,value:freeze(Object.fromEntries(keys.map(key=>[key,descriptors[key]!.value])))};}
const MAP:Record<CommandOperation,PolicyOperation>={probe:"observe",inventory:"provider-status",estimate:"model-status",load:"model-load","set-options":"model-set-options",drain:"model-drain",unload:"model-unload",install:"artifact-install","remove-managed-artifact":"artifact-remove","inference.chat":"model-inference"};
export function commandPolicyOperation(value:CommandOperation):PolicyOperation{return MAP[value];}
export function capabilityMatches(request:CommandRequest,now:string):boolean{const capability=request.capability;return capability.operation===commandPolicyOperation(request.operation)&&capability.hostId===request.hostId&&targetMatches(request)&&commandAuthorizationDigest(request)===capability.requestDigest&&Date.parse(now)<Date.parse(capability.expiresAt)&&Date.parse(now)<Date.parse(request.deadline);}
export function responseMatches(request:CommandRequest,response:CommandResponse):boolean{return request.requestId===response.requestId&&request.jobId===response.jobId&&request.hostId===response.hostId&&request.sequence===response.sequence;}
