import type { JsonValue,ParseResult } from "./protocol.js";import type { PolicyOperation } from "./policy.js";
export interface OperationCapability{readonly operation:PolicyOperation;readonly targetKind:string;readonly targetId:string;readonly hostId:string;readonly modelId:string|null;readonly requestDigest:string;readonly expiresAt:string}
export type CommandOperation="probe"|"inventory"|"estimate"|"load"|"set-options"|"drain"|"unload"|"install"|"remove-managed-artifact";export interface CommandRequest{readonly requestId:string;readonly jobId:string;readonly hostId:string;readonly operation:CommandOperation;readonly idempotencyKey:string;readonly sequence:number;readonly deadline:string;readonly capability:OperationCapability;readonly params:JsonValue|null}export interface CommandResponse{readonly requestId:string;readonly jobId:string;readonly hostId:string;readonly sequence:number;readonly status:"accepted"|"running"|"succeeded"|"failed"|"cancelled";readonly progress:number|null;readonly observedAt:string;readonly observation:JsonValue|null;readonly errorCode:string|null}
const OPS=new Set<unknown>(["probe","inventory","estimate","load","set-options","drain","unload","install","remove-managed-artifact"]),ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/,TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;const fail=<T>(e:string):ParseResult<T>=>({ok:false,error:e}),freeze=<T>(v:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),v)) as T;
function exact(v:unknown,keys:string[]){try{if(typeof v!=="object"||v===null||Array.isArray(v))return null;const p=Object.getPrototypeOf(v),own=Reflect.ownKeys(v),d=Object.getOwnPropertyDescriptors(v);return(p===Object.prototype||p===null)&&own.length===keys.length&&own.every(k=>typeof k==="string"&&keys.includes(k))&&keys.every(k=>d[k]&&"value" in d[k])?d:null;}catch{return null;}}
export function parseCommandRequest(v:unknown):ParseResult<CommandRequest>{const keys=["requestId","jobId","hostId","operation","idempotencyKey","sequence","deadline","capability","params"],d=exact(v,keys);if(!d)return fail("ERR_COMMAND_REQUEST");const ids=[d.requestId!.value,d.jobId!.value,d.hostId!.value,d.idempotencyKey!.value],seq=d.sequence!.value,deadline=d.deadline!.value,cap=d.capability!.value,params=d.params!.value;if(ids.some(v=>typeof v!=="string"||!ID.test(v))||!OPS.has(d.operation!.value)||!Number.isSafeInteger(seq)||seq<1||typeof deadline!=="string"||!TIME.test(deadline)||Number.isNaN(Date.parse(deadline))||typeof cap!=="object"||cap===null||params!==null&&typeof params!=="object")return fail("ERR_COMMAND_REQUEST");const text=JSON.stringify(params);if(Buffer.byteLength(text)>32768||/("endpoint"|"url"|"address"|"command"|"shell")\s*:/.test(text))return fail("ERR_COMMAND_BOUNDS");return{ok:true,value:freeze(Object.fromEntries(keys.map(k=>[k,d[k]!.value])))};}
export function parseCommandResponse(v:unknown):ParseResult<CommandResponse>{const keys=["requestId","jobId","hostId","sequence","status","progress","observedAt","observation","errorCode"],d=exact(v,keys);if(!d)return fail("ERR_COMMAND_RESPONSE");const ids=[d.requestId!.value,d.jobId!.value,d.hostId!.value],seq=d.sequence!.value,status=d.status!.value,progress=d.progress!.value,time=d.observedAt!.value,error=d.errorCode!.value;if(ids.some(v=>typeof v!=="string"||!ID.test(v))||!Number.isSafeInteger(seq)||seq<1||!(new Set(["accepted","running","succeeded","failed","cancelled"])).has(status)||(progress!==null&&(!Number.isSafeInteger(progress)||progress<0||progress>100))||typeof time!=="string"||!TIME.test(time)||(error!==null&&(typeof error!=="string"||!/^[A-Z][A-Z0-9_]{0,63}$/.test(error)))||(status==="failed"&&error===null))return fail("ERR_COMMAND_RESPONSE");return{ok:true,value:freeze(Object.fromEntries(keys.map(k=>[k,d[k]!.value])))};}
const MAP:Record<CommandOperation,PolicyOperation>={probe:"observe",inventory:"provider-status",estimate:"model-status",load:"model-load","set-options":"model-set-options",drain:"model-drain",unload:"model-unload",install:"artifact-install","remove-managed-artifact":"artifact-remove"};export function commandPolicyOperation(v:CommandOperation):PolicyOperation{return MAP[v]}
export function capabilityMatches(request:CommandRequest,now:string):boolean{const c=request.capability;return c.operation===commandPolicyOperation(request.operation)&&c.hostId===request.hostId&&c.requestDigest.length===64&&Date.parse(now)<Date.parse(c.expiresAt);}
export function responseMatches(request:CommandRequest,response:CommandResponse):boolean{return request.requestId===response.requestId&&request.jobId===response.jobId&&request.hostId===response.hostId&&request.sequence===response.sequence;}
