import assert from "node:assert/strict";
import test from "node:test";
import { capabilityMatches,commandAuthorizationDigest,parseCommandRequest,parseCommandResponse,responseMatches } from "./command.js";
const NOW="2026-09-28T08:00:00.000Z";
function request(overrides:any={}) { const {capability:capOverride,...rest}=overrides;const base:any={requestId:"request-1",jobId:"job-1",hostId:"host-1",operation:"load",idempotencyKey:"idem-1",sequence:1,deadline:"2026-09-28T08:30:00.000Z",capability:{operation:"model-load",targetKind:"model",targetId:"model-1",hostId:"host-1",modelId:"model-1",expiresAt:"2026-09-28T09:00:00.000Z",...capOverride},params:{modelId:"model-1"},...rest};base.capability.requestDigest=commandAuthorizationDigest(base);return base; }
test("strict command request binds exact command, target and parameters",()=>{const value=request(),parsed=parseCommandRequest(value);assert.ok(parsed.ok);if(!parsed.ok)return;assert.equal(capabilityMatches(parsed.value,NOW),true);assert.equal(parseCommandRequest({...value,params:{modelId:"model-2"}}).ok,false);assert.equal(parseCommandRequest(request({capability:{targetId:"model-2"}})).ok,false);assert.equal(parseCommandRequest(request({params:{url:"https://bad"}})).ok,false);let called=false;assert.equal(parseCommandRequest(Object.defineProperty({},"requestId",{get(){called=true}})).ok,false);assert.equal(called,false);});
test("digest is deterministic across key order and changes every execution field",()=>{const one=request(),two=request({params:{z:2,modelId:"model-1",a:1}}),three=request({params:{a:1,modelId:"model-1",z:2}});assert.equal(two.capability.requestDigest,three.capability.requestDigest);assert.notEqual(one.capability.requestDigest,two.capability.requestDigest);assert.equal(one.capability.requestDigest,"18157150e00ef46bd7ea4fb4dbf7ae26485441b92d6d9ef5c55ba2614a0cf83e");});
test("inference chat command accepts only bounded exact provider/model/message fields",()=>{const modelId="ollama-"+"a".repeat(64),value=request({requestId:"chat-1",jobId:"chat-job-1",operation:"inference.chat",capability:{operation:"model-inference",targetKind:"model",targetId:modelId,modelId},params:{providerId:"ollama-1",modelId,model:"qwen:latest",requestId:"chat-1",maxRequestBytes:524288,maxResponseBytes:262144,messages:[{role:"user",contentBase64:Buffer.from("héllo").toString("base64")}],temperatureMilli:250,maxTokens:16}});assert.ok(parseCommandRequest(value).ok);for(const params of [{...value.params,url:"http://bad"},{...value.params,requestId:"other"},{...value.params,messages:[{role:"user",contentBase64:"***"}]},{...value.params,temperatureMilli:2001}])assert.equal(parseCommandRequest(request({...value,capability:{...value.capability,requestDigest:undefined},params})).ok,false);});
test("responses require exact binding and stable errors",()=>{const q=parseCommandRequest(request()),r=parseCommandResponse({requestId:"request-1",jobId:"job-1",hostId:"host-1",sequence:1,status:"failed",progress:null,observedAt:NOW,observation:null,errorCode:"ADAPTER_FAILED"});assert.ok(q.ok&&r.ok);if(q.ok&&r.ok)assert.equal(responseMatches(q.value,r.value),true);});
