import { isIPv4, isIPv6 } from "node:net";
import { CURRENT_PROTOCOL_VERSION, isProtocolVersionCompatible, parseProtocolVersion, parseUtcTimestamp, type ParseResult, type ProtocolVersion, type UtcTimestamp } from "./protocol.js";

export const DISCOVERY_MIN_TTL_SECONDS=1;
export const DISCOVERY_MAX_TTL_SECONDS=3600;
export type DiscoveryPlatform="linux"|"darwin"|"windows";
export interface DiscoveryAdvertisement {readonly id:string;readonly displayName:string;readonly protocolVersion:ProtocolVersion;readonly agentPort:number;readonly platform:DiscoveryPlatform}
export interface DiscoveryCandidate extends DiscoveryAdvertisement {readonly address:string;readonly firstSeen:UtcTimestamp;readonly lastSeen:UtcTimestamp;readonly expiresAt:UtcTimestamp;readonly ttlSeconds:number;readonly trustState:"untrusted"}
export interface DiscoveryCandidateInput extends DiscoveryAdvertisement {readonly address:string;readonly observedAt:UtcTimestamp;readonly ttlSeconds:number}
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const NAME=/^[^\u0000-\u001f\u007f]+$/;
function fields(input:unknown,keys:readonly string[]):Record<string,PropertyDescriptor>|null {try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const proto=Object.getPrototypeOf(input);if(proto!==Object.prototype&&proto!==null)return null;const own=Reflect.ownKeys(input);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k)))return null;const d=Object.getOwnPropertyDescriptors(input);if(keys.some(k=>!d[k]||!("value" in d[k])))return null;return d;}catch{return null;}}
function canonicalAddress(input:unknown):string|null {if(typeof input!=="string"||input.includes("%"))return null;if(isIPv4(input))return input;if(!isIPv6(input))return null;try{const canonical=new URL(`http://[${input}]/`).hostname.slice(1,-1);return canonical===input?input:null;}catch{return null;}}
function frozen<T>(value:Record<string,unknown>):T{return Object.freeze(Object.assign(Object.create(null),value)) as T;}
export function parseDiscoveryAdvertisement(input:unknown):ParseResult<DiscoveryAdvertisement>{const d=fields(input,["id","displayName","protocolVersion","agentPort","platform"]);if(!d)return{ok:false,error:"ERR_DISCOVERY_OBJECT"};const id=d.id!.value,name=d.displayName!.value,port=d.agentPort!.value,platform=d.platform!.value,version=parseProtocolVersion(d.protocolVersion!.value);if(typeof id!=="string"||!ID.test(id))return{ok:false,error:"ERR_DISCOVERY_ID"};if(typeof name!=="string"||Buffer.byteLength(name,"utf8")<1||Buffer.byteLength(name,"utf8")>128||!NAME.test(name))return{ok:false,error:"ERR_DISCOVERY_NAME"};if(!version.ok||!isProtocolVersionCompatible(CURRENT_PROTOCOL_VERSION,version.value))return{ok:false,error:"ERR_DISCOVERY_PROTOCOL"};if(typeof port!=="number"||!Number.isSafeInteger(port)||port<1||port>65535)return{ok:false,error:"ERR_DISCOVERY_PORT"};if(platform!=="linux"&&platform!=="darwin"&&platform!=="windows")return{ok:false,error:"ERR_DISCOVERY_PLATFORM"};return{ok:true,value:frozen<DiscoveryAdvertisement>({id,displayName:name,protocolVersion:version.value,agentPort:port,platform})};}
export function parseDiscoveryCandidate(input:unknown):ParseResult<DiscoveryCandidate>{const d=fields(input,["id","displayName","protocolVersion","agentPort","platform","address","observedAt","ttlSeconds"]);if(!d)return{ok:false,error:"ERR_DISCOVERY_OBJECT"};const advertisement=parseDiscoveryAdvertisement({id:d.id!.value,displayName:d.displayName!.value,protocolVersion:d.protocolVersion!.value,agentPort:d.agentPort!.value,platform:d.platform!.value});if(!advertisement.ok)return advertisement;const address=canonicalAddress(d.address!.value),observed=parseUtcTimestamp(d.observedAt!.value),ttl=d.ttlSeconds!.value;if(address===null)return{ok:false,error:"ERR_DISCOVERY_ADDRESS"};if(!observed.ok)return{ok:false,error:"ERR_DISCOVERY_TIME"};if(typeof ttl!=="number"||!Number.isSafeInteger(ttl)||ttl<DISCOVERY_MIN_TTL_SECONDS||ttl>DISCOVERY_MAX_TTL_SECONDS)return{ok:false,error:"ERR_DISCOVERY_TTL"};const expires=new Date(Date.parse(observed.value)+ttl*1000).toISOString();if(expires.length!==24)return{ok:false,error:"ERR_DISCOVERY_TIME"};return{ok:true,value:frozen<DiscoveryCandidate>({...advertisement.value,address,firstSeen:observed.value,lastSeen:observed.value,expiresAt:expires as UtcTimestamp,ttlSeconds:ttl,trustState:"untrusted"})};}
export function refreshDiscoveryCandidate(existing:unknown,input:unknown):ParseResult<DiscoveryCandidate>{const prior=existing as DiscoveryCandidate;const next=parseDiscoveryCandidate(input);if(!next.ok)return next;const d=fields(prior,["id","displayName","protocolVersion","agentPort","platform","address","firstSeen","lastSeen","expiresAt","ttlSeconds","trustState"]);if(!d||prior.trustState!=="untrusted"||prior.id!==next.value.id||prior.address!==next.value.address||Date.parse(next.value.lastSeen)<Date.parse(prior.lastSeen))return{ok:false,error:"ERR_DISCOVERY_REFRESH"};return{ok:true,value:frozen<DiscoveryCandidate>({...next.value,firstSeen:prior.firstSeen})};}
