import type { ParseResult } from "./protocol.js";
export interface FallbackPolicy{readonly version:1;readonly enabled:boolean;readonly allowedModels:readonly string[];readonly allowedProviders:readonly string[];readonly allowedFormats:readonly string[];readonly maxCandidates:number}
export interface FallbackChoice{readonly candidateId:string;readonly model:string;readonly provider:string|null;readonly format:string|null;readonly exact:boolean;readonly capabilityScore:number;readonly placementScore:number}
export interface FallbackDecision{readonly candidateId:string|null;readonly model:string|null;readonly substituted:boolean;readonly reasons:readonly string[]}
const ID=/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$/,REASONS=Object.freeze(["EXACT_MODEL","FALLBACK_SELECTED","FALLBACK_DISABLED","FALLBACK_NOT_ALLOWED","NO_ELIGIBLE_FALLBACK"]);
const fail=<T>(error:string):ParseResult<T>=>({ok:false,error});
function fields(value:unknown,keys:readonly string[]):Record<string,PropertyDescriptor>|null{try{if(typeof value!=="object"||value===null||Array.isArray(value))return null;const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)return null;const own=Reflect.ownKeys(value),d=Object.getOwnPropertyDescriptors(value);if(own.length!==keys.length||own.some(key=>typeof key!=="string"||!keys.includes(key)||!d[key]||!("value" in d[key]!)))return null;return d;}catch{return null;}}
function strings(value:unknown,max:number):readonly string[]|null{try{if(!Array.isArray(value)||value.length>max)return null;const d=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(value);if(keys.length!==value.length+1)return null;const out:string[]=[],seen=new Set<string>();for(let i=0;i<value.length;i++){const item=d[String(i)];if(!item||!("value" in item)||typeof item.value!=="string"||!ID.test(item.value)||seen.has(item.value))return null;seen.add(item.value);out.push(item.value);}return Object.freeze(out);}catch{return null;}}
export function parseFallbackPolicy(value:unknown):ParseResult<FallbackPolicy>{const d=fields(value,["version","enabled","allowedModels","allowedProviders","allowedFormats","maxCandidates"]);if(!d)return fail("ERR_FALLBACK_POLICY");const models=strings(d.allowedModels!.value,128),providers=strings(d.allowedProviders!.value,32),formats=strings(d.allowedFormats!.value,32),max=d.maxCandidates!.value;if(d.version!.value!==1||typeof d.enabled!.value!=="boolean"||!models||!providers||!formats||!Number.isSafeInteger(max)||max<1||max>128)return fail("ERR_FALLBACK_POLICY");const out=Object.assign(Object.create(null),{version:1 as const,enabled:d.enabled!.value,allowedModels:models,allowedProviders:providers,allowedFormats:formats,maxCandidates:max});return{ok:true,value:Object.freeze(out)};}
function choice(value:unknown):FallbackChoice|null{const d=fields(value,["candidateId","model","provider","format","exact","capabilityScore","placementScore"]);if(!d||typeof d.candidateId!.value!=="string"||!ID.test(d.candidateId!.value)||typeof d.model!.value!=="string"||!ID.test(d.model!.value)||typeof d.exact!.value!=="boolean")return null;for(const key of ["provider","format"]){const v=d[key]!.value;if(v!==null&&(typeof v!=="string"||!ID.test(v)))return null;}for(const key of ["capabilityScore","placementScore"]){const v=d[key]!.value;if(!Number.isSafeInteger(v)||v<0||v>10_000_000)return null;}return Object.freeze({candidateId:d.candidateId!.value,model:d.model!.value,provider:d.provider!.value,format:d.format!.value,exact:d.exact!.value,capabilityScore:d.capabilityScore!.value,placementScore:d.placementScore!.value});}
function decision(candidateId:string|null,model:string|null,substituted:boolean,reasons:readonly string[]):FallbackDecision{const out=Object.assign(Object.create(null),{candidateId,model,substituted,reasons:Object.freeze([...reasons])});return Object.freeze(out);}
export function rankFallback(requestedModel:string,policyInput:unknown,input:readonly FallbackChoice[]):FallbackDecision{try{if(!ID.test(requestedModel))return decision(null,null,false,["NO_ELIGIBLE_FALLBACK"]);const parsed=parseFallbackPolicy(policyInput);if(!parsed.ok||!Array.isArray(input)||input.length>parsed.value.maxCandidates)return decision(null,null,false,["NO_ELIGIBLE_FALLBACK"]);const policy=parsed.value,seen=new Set<string>(),eligible:FallbackChoice[]=[];for(const raw of input){const item=choice(raw);if(!item||seen.has(item.candidateId))return decision(null,null,false,["NO_ELIGIBLE_FALLBACK"]);seen.add(item.candidateId);if(item.model===requestedModel){eligible.push({...item,exact:true});continue;}if(!policy.enabled)continue;if(!policy.allowedModels.includes(item.model))continue;if(policy.allowedProviders.length&&(!item.provider||!policy.allowedProviders.includes(item.provider)))continue;if(policy.allowedFormats.length&&(!item.format||!policy.allowedFormats.includes(item.format)))continue;eligible.push(item);}eligible.sort((a,b)=>Number(b.exact)-Number(a.exact)||b.capabilityScore-a.capabilityScore||b.placementScore-a.placementScore||a.model.localeCompare(b.model)||a.candidateId.localeCompare(b.candidateId));const best=eligible[0];if(best)return decision(best.candidateId,best.model,!best.exact,[best.exact?"EXACT_MODEL":"FALLBACK_SELECTED"]);return decision(null,null,false,[policy.enabled?"NO_ELIGIBLE_FALLBACK":"FALLBACK_DISABLED"]);}catch{return decision(null,null,false,["NO_ELIGIBLE_FALLBACK"]);}}
