import type { ParseResult } from "./protocol.js";
export type QueueReason="QUEUE_DISABLED"|"QUEUE_OVERLOAD"|"QUEUE_TIMEOUT"|"QUEUE_CANCELLED"|"QUEUE_DRAINING"|"QUEUE_STALE";
export interface QueuePolicy{readonly enabled:boolean;readonly maxActive:number;readonly maxActivePerToken:number;readonly maxActivePerTarget:number;readonly maxWaiting:number;readonly maxWaitingPerToken:number;readonly maxWaitingPerTarget:number;readonly maxWaitMs:number}
export interface QueuePermit{release():void}
export type QueueAcquireResult={readonly ok:true;readonly permit:QueuePermit}|{readonly ok:false;readonly reason:QueueReason};
export interface QueueRequest{readonly tokenId:string;readonly targetId:string;readonly signal:AbortSignal;readonly revalidate:()=>boolean|Promise<boolean>}
export interface QueueSnapshot{readonly active:number;readonly waiting:number;readonly targets:readonly Readonly<{targetId:string;active:number;waiting:number}>[]}
export interface QueueScheduler{now():number;schedule(delayMs:number,callback:()=>void):unknown;cancel(handle:unknown):void}
export interface InferenceQueue{acquire(request:QueueRequest):Promise<QueueAcquireResult>;stopTarget(targetId:string):void;stopAll():void;snapshot():QueueSnapshot;dispose():void}
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
function fields(value:unknown,keys:readonly string[]):Record<string,PropertyDescriptor>|null{try{if(typeof value!=="object"||value===null||Array.isArray(value))return null;const p=Object.getPrototypeOf(value);if(p!==Object.prototype&&p!==null)return null;const own=Reflect.ownKeys(value),d=Object.getOwnPropertyDescriptors(value);if(own.length!==keys.length||own.some(key=>typeof key!=="string"||!keys.includes(key)||!d[key]||!("value" in d[key]!)))return null;return d;}catch{return null;}}
export function parseQueuePolicy(value:unknown):ParseResult<QueuePolicy>{const keys=["enabled","maxActive","maxActivePerToken","maxActivePerTarget","maxWaiting","maxWaitingPerToken","maxWaitingPerTarget","maxWaitMs"],d=fields(value,keys);if(!d||typeof d.enabled!.value!=="boolean")return{ok:false,error:"ERR_QUEUE_POLICY"};for(const key of keys.slice(1)){const item=d[key]!.value;if(!Number.isSafeInteger(item)||item<1||item>1_000_000_000)return{ok:false,error:"ERR_QUEUE_POLICY"};}const out=Object.assign(Object.create(null),{enabled:d.enabled!.value,maxActive:d.maxActive!.value,maxActivePerToken:d.maxActivePerToken!.value,maxActivePerTarget:d.maxActivePerTarget!.value,maxWaiting:d.maxWaiting!.value,maxWaitingPerToken:d.maxWaitingPerToken!.value,maxWaitingPerTarget:d.maxWaitingPerTarget!.value,maxWaitMs:d.maxWaitMs!.value});return{ok:true,value:Object.freeze(out)};}
interface Waiter{tokenId:string;targetId:string;signal:AbortSignal;revalidate:()=>boolean|Promise<boolean>;resolve:(value:QueueAcquireResult)=>void;settled:boolean;reserved:boolean;abort:()=>void;timer:unknown|null;sequence:number}
const defaultScheduler:QueueScheduler={now:()=>Date.now(),schedule:(delay,callback)=>setTimeout(callback,delay),cancel:handle=>clearTimeout(handle as ReturnType<typeof setTimeout>)};
function result(reason:QueueReason):QueueAcquireResult{return Object.freeze({ok:false,reason});}
export function createInferenceQueue(policyInput:QueuePolicy,scheduler:QueueScheduler=defaultScheduler):InferenceQueue{const parsed=parseQueuePolicy(policyInput);if(!parsed.ok)throw new Error("ERR_QUEUE_POLICY");const policy=parsed.value,waiting:Waiter[]=[],active=new Set<Waiter>(),stopped=new Set<string>();let stoppedAll=false,pumping=false,sequence=0,validationTail:Promise<void>=Promise.resolve();
 const count=(items:Iterable<Waiter>,key:"tokenId"|"targetId",value:string)=>{let n=0;for(const item of items)if(item[key]===value)n++;return n;};
 const capacity=(w:Waiter)=>active.size<policy.maxActive&&count(active,"tokenId",w.tokenId)<policy.maxActivePerToken&&count(active,"targetId",w.targetId)<policy.maxActivePerTarget;
 const remove=(w:Waiter)=>{const index=waiting.indexOf(w);if(index>=0)waiting.splice(index,1);};
 const settle=(w:Waiter,value:QueueAcquireResult)=>{if(w.settled)return;w.settled=true;remove(w);if(w.timer!==null)scheduler.cancel(w.timer);w.signal.removeEventListener("abort",w.abort);if(w.reserved)active.delete(w);w.resolve(value);void pump();};
 const release=(w:Waiter)=>{if(!w.reserved)return;w.reserved=false;active.delete(w);void pump();};
 const admit=async(w:Waiter)=>{w.reserved=true;active.add(w);try{const valid=await w.revalidate();if(w.settled||w.signal.aborted){release(w);if(!w.settled)settle(w,result("QUEUE_CANCELLED"));return;}if(!valid||stoppedAll||stopped.has(w.targetId)){release(w);settle(w,result(stoppedAll||stopped.has(w.targetId)?"QUEUE_DRAINING":"QUEUE_STALE"));return;}w.settled=true;if(w.timer!==null)scheduler.cancel(w.timer);w.signal.removeEventListener("abort",w.abort);w.resolve(Object.freeze({ok:true,permit:Object.freeze({release:()=>release(w)})}));}catch{release(w);settle(w,result("QUEUE_STALE"));}};
 const pump=async()=>{if(pumping)return;pumping=true;try{for(;;){let candidate:Waiter|undefined;for(const w of waiting){if(!w.settled&&capacity(w)){candidate=w;break;}}if(!candidate)break;remove(candidate);await admit(candidate);}}finally{pumping=false;}};
 const validate=async(signal:AbortSignal,fn:()=>boolean|Promise<boolean>):Promise<"ok"|"stale"|"cancel">=>{if(signal.aborted)return"cancel";return new Promise(resolve=>{let done=false;const finish=(value:"ok"|"stale"|"cancel")=>{if(done)return;done=true;signal.removeEventListener("abort",abort);resolve(value);},abort=()=>finish("cancel");signal.addEventListener("abort",abort,{once:true});Promise.resolve().then(fn).then(value=>finish(value?"ok":"stale"),()=>finish("stale"));});};
 const acquire=async(request:QueueRequest):Promise<QueueAcquireResult>=>{try{if(!ID.test(request.tokenId)||!ID.test(request.targetId)||typeof request.revalidate!=="function")return result("QUEUE_STALE");if(stoppedAll||stopped.has(request.targetId))return result("QUEUE_DRAINING");const previous=validationTail,validation=previous.then(()=>validate(request.signal,request.revalidate));validationTail=validation.then(()=>undefined,()=>undefined);let cancelListener=()=>{};const cancelled=new Promise<"cancel">(resolve=>{cancelListener=()=>resolve("cancel");if(request.signal.aborted)resolve("cancel");else request.signal.addEventListener("abort",cancelListener,{once:true});});const initial=await Promise.race([validation,cancelled]);request.signal.removeEventListener("abort",cancelListener);if(initial==="cancel")return result("QUEUE_CANCELLED");if(initial!=="ok")return result("QUEUE_STALE");return await new Promise(resolve=>{if(request.signal.aborted)return resolve(result("QUEUE_CANCELLED"));if(stoppedAll||stopped.has(request.targetId))return resolve(result("QUEUE_DRAINING"));const immediate=active.size<policy.maxActive&&count(active,"tokenId",request.tokenId)<policy.maxActivePerToken&&count(active,"targetId",request.targetId)<policy.maxActivePerTarget;if(!immediate&&!policy.enabled)return resolve(result("QUEUE_DISABLED"));if(!immediate&&(waiting.length>=policy.maxWaiting||count(waiting,"tokenId",request.tokenId)>=policy.maxWaitingPerToken||count(waiting,"targetId",request.targetId)>=policy.maxWaitingPerTarget))return resolve(result("QUEUE_OVERLOAD"));const w={} as Waiter;Object.assign(w,{tokenId:request.tokenId,targetId:request.targetId,signal:request.signal,revalidate:request.revalidate,resolve,settled:false,reserved:false,sequence:sequence++,timer:null,abort:()=>settle(w,result("QUEUE_CANCELLED"))});request.signal.addEventListener("abort",w.abort,{once:true});waiting.push(w);w.timer=scheduler.schedule(policy.maxWaitMs,()=>settle(w,result("QUEUE_TIMEOUT")));void pump();});}catch{return result("QUEUE_STALE");}};
 const stopTarget=(targetId:string)=>{if(!ID.test(targetId))return;stopped.add(targetId);for(const w of [...waiting])if(w.targetId===targetId)settle(w,result("QUEUE_DRAINING"));};
 const stopAll=()=>{stoppedAll=true;for(const w of [...waiting])settle(w,result("QUEUE_DRAINING"));};
 const snapshot=():QueueSnapshot=>{const ids=new Set<string>();for(const w of active)ids.add(w.targetId);for(const w of waiting)ids.add(w.targetId);const targets=[...ids].sort().map(targetId=>Object.freeze({targetId,active:count(active,"targetId",targetId),waiting:count(waiting,"targetId",targetId)}));return Object.freeze({active:active.size,waiting:waiting.length,targets:Object.freeze(targets)});};
 return Object.freeze({acquire,stopTarget,stopAll,snapshot,dispose:stopAll});}
export function createManualQueueScheduler(start=0):QueueScheduler&{advance(ms:number):void;pending():number}{let now=start,id=0;const tasks=new Map<number,{at:number;callback:()=>void}>();return{now:()=>now,schedule:(delay,callback)=>{const key=++id;tasks.set(key,{at:now+delay,callback});return key;},cancel:handle=>{tasks.delete(handle as number);},advance(ms){now+=ms;for(;;){const due=[...tasks].filter(([,task])=>task.at<=now).sort((a,b)=>a[1].at-b[1].at||a[0]-b[0])[0];if(!due)break;tasks.delete(due[0]);due[1].callback();}},pending:()=>tasks.size};}
