import { parseDiscoveryCandidate,type DiscoveryCandidate } from "./discovery.js";
import type { ParseResult } from "./protocol.js";
export type PairingState="created"|"presented"|"owner_confirmed"|"mutually_proven"|"consumed"|"expired"|"cancelled";
export const PAIRING_TRANSITIONS=Object.freeze({created:Object.freeze(["presented","expired","cancelled"]),presented:Object.freeze(["owner_confirmed","expired","cancelled"]),owner_confirmed:Object.freeze(["mutually_proven","expired","cancelled"]),mutually_proven:Object.freeze(["consumed","expired","cancelled"]),consumed:Object.freeze([]),expired:Object.freeze([]),cancelled:Object.freeze([])} satisfies Record<PairingState,readonly PairingState[]>);
export interface PairingBinding {readonly candidateId:string;readonly address:string;readonly port:number;readonly protocolMajor:number;readonly protocolMinor:number}
export interface PairingRecord {readonly challengeId:string;readonly state:PairingState;readonly version:number;readonly ownerId:string;readonly ownerVersion:number;readonly binding:PairingBinding;readonly codeDigest:string;readonly controllerNonceDigest:string;readonly agentNonceDigest:string|null;readonly proofDigest:string|null;readonly failedAttempts:number;readonly createdAt:string;readonly expiresAt:string;readonly updatedAt:string;readonly consumedAt:string|null;readonly terminalAt:string|null}
const HEX64=/^[a-f0-9]{64}$/,OWNER=/^[a-f0-9]{32}$/,TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;const states=new Set(Object.keys(PAIRING_TRANSITIONS));
const validTime=(v:unknown):v is string=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
function descriptors(input:unknown,keys:readonly string[]):Record<string,PropertyDescriptor>|null {try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const p=Object.getPrototypeOf(input);if(p!==Object.prototype&&p!==null)return null;const own=Reflect.ownKeys(input);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k)))return null;const d=Object.getOwnPropertyDescriptors(input);return keys.every(k=>d[k]&&"value" in d[k])?d:null;}catch{return null;}}
const frozen=<T>(o:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),o)) as T;
export function canPairingTransition(from:PairingState,to:PairingState):boolean{return (PAIRING_TRANSITIONS[from] as readonly PairingState[]|undefined)?.includes(to)??false;}
export function parsePairingCandidate(input:unknown):ParseResult<DiscoveryCandidate>{const keys=["id","displayName","protocolVersion","agentPort","platform","address","firstSeen","lastSeen","expiresAt","ttlSeconds","trustState"] as const,d=descriptors(input,keys);if(!d||d.trustState!.value!=="untrusted"||typeof d.firstSeen!.value!=="string"||typeof d.lastSeen!.value!=="string"||typeof d.expiresAt!.value!=="string")return{ok:false,error:"ERR_PAIRING_CANDIDATE"};const candidate=parseDiscoveryCandidate({id:d.id!.value,displayName:d.displayName!.value,protocolVersion:d.protocolVersion!.value,agentPort:d.agentPort!.value,platform:d.platform!.value,address:d.address!.value,observedAt:d.lastSeen!.value,ttlSeconds:d.ttlSeconds!.value});if(!candidate.ok||candidate.value.expiresAt!==d.expiresAt!.value||Date.parse(d.firstSeen!.value)>Date.parse(d.lastSeen!.value))return{ok:false,error:"ERR_PAIRING_CANDIDATE"};return{ok:true,value:frozen<DiscoveryCandidate>({...candidate.value,firstSeen:d.firstSeen!.value})};}
export function pairingBindingFromCandidate(input:unknown):ParseResult<PairingBinding>{const candidate=parsePairingCandidate(input);if(!candidate.ok)return candidate;const c=candidate.value;return{ok:true,value:frozen<PairingBinding>({candidateId:c.id,address:c.address,port:c.agentPort,protocolMajor:c.protocolVersion.major,protocolMinor:c.protocolVersion.minor})};}
export function parsePairingBinding(input:unknown):ParseResult<PairingBinding>{const d=descriptors(input,["candidateId","address","port","protocolMajor","protocolMinor"]);if(!d)return{ok:false,error:"ERR_PAIRING_BINDING"};const candidate={id:d.candidateId!.value,displayName:"binding",protocolVersion:{major:d.protocolMajor!.value,minor:d.protocolMinor!.value},agentPort:d.port!.value,platform:"linux",address:d.address!.value,observedAt:"2026-01-01T00:00:00.000Z",ttlSeconds:1};const parsed=parseDiscoveryCandidate(candidate);if(!parsed.ok)return{ok:false,error:"ERR_PAIRING_BINDING"};return{ok:true,value:frozen<PairingBinding>({candidateId:parsed.value.id,address:parsed.value.address,port:parsed.value.agentPort,protocolMajor:parsed.value.protocolVersion.major,protocolMinor:parsed.value.protocolVersion.minor})};}
export function parsePairingRecord(input:unknown):ParseResult<PairingRecord>{const keys=["challengeId","state","version","ownerId","ownerVersion","binding","codeDigest","controllerNonceDigest","agentNonceDigest","proofDigest","failedAttempts","createdAt","expiresAt","updatedAt","consumedAt","terminalAt"] as const,d=descriptors(input,keys);if(!d)return{ok:false,error:"ERR_PAIRING_RECORD"};const get=(k:string)=>d[k]!.value,challengeId=get("challengeId"),state=get("state"),version=get("version"),ownerId=get("ownerId"),ownerVersion=get("ownerVersion"),binding=parsePairingBinding(get("binding")),codeDigest=get("codeDigest"),controllerNonceDigest=get("controllerNonceDigest"),agentNonceDigest=get("agentNonceDigest"),proofDigest=get("proofDigest"),failedAttempts=get("failedAttempts"),createdAt=get("createdAt"),expiresAt=get("expiresAt"),updatedAt=get("updatedAt"),consumedAt=get("consumedAt"),terminalAt=get("terminalAt");if(typeof challengeId!=="string"||!HEX64.test(challengeId)||typeof state!=="string"||!states.has(state)||typeof version!=="number"||!Number.isSafeInteger(version)||version<1||typeof ownerId!=="string"||!OWNER.test(ownerId)||typeof ownerVersion!=="number"||!Number.isSafeInteger(ownerVersion)||ownerVersion<1||!binding.ok||typeof codeDigest!=="string"||!HEX64.test(codeDigest)||typeof controllerNonceDigest!=="string"||!HEX64.test(controllerNonceDigest)||(agentNonceDigest!==null&&(typeof agentNonceDigest!=="string"||!HEX64.test(agentNonceDigest)))||(proofDigest!==null&&(typeof proofDigest!=="string"||!HEX64.test(proofDigest)))||typeof failedAttempts!=="number"||!Number.isSafeInteger(failedAttempts)||failedAttempts<0||failedAttempts>5||!validTime(createdAt)||!validTime(expiresAt)||!validTime(updatedAt)||(consumedAt!==null&&!validTime(consumedAt))||(terminalAt!==null&&!validTime(terminalAt)))return{ok:false,error:"ERR_PAIRING_RECORD"};
const stateValue=state as PairingState,createdMs=Date.parse(createdAt),expiresMs=Date.parse(expiresAt),updatedMs=Date.parse(updatedAt);if(expiresMs<=createdMs||updatedMs<createdMs||((stateValue==="created"||stateValue==="presented"||stateValue==="owner_confirmed"||stateValue==="mutually_proven"||stateValue==="consumed")&&updatedMs>=expiresMs))return{ok:false,error:"ERR_PAIRING_RECORD"};if((stateValue==="owner_confirmed"||stateValue==="mutually_proven"||stateValue==="consumed")&&failedAttempts>=5)return{ok:false,error:"ERR_PAIRING_RECORD"};if((stateValue==="mutually_proven"||stateValue==="consumed")&&(agentNonceDigest===null||proofDigest===null))return{ok:false,error:"ERR_PAIRING_RECORD"};if(stateValue==="consumed"?(consumedAt===null||terminalAt!==null||Date.parse(consumedAt)!==updatedMs):(consumedAt!==null))return{ok:false,error:"ERR_PAIRING_RECORD"};if((stateValue==="expired"||stateValue==="cancelled")?(terminalAt===null||Date.parse(terminalAt)!==updatedMs):terminalAt!==null)return{ok:false,error:"ERR_PAIRING_RECORD"};return{ok:true,value:frozen<PairingRecord>({challengeId,state:stateValue,version,ownerId,ownerVersion,binding:binding.value,codeDigest,controllerNonceDigest,agentNonceDigest,proofDigest,failedAttempts,createdAt,expiresAt,updatedAt,consumedAt,terminalAt})};}
