import {spawnSync} from "node:child_process";
import {mkdir,readFile,readdir,rm,stat,writeFile} from "node:fs/promises";
import {dirname,resolve} from "node:path";
import {fileURLToPath,pathToFileURL} from "node:url";
import {archiveName,binaryName,checksumManifest,createTarGz,orderedPlatforms,sanitizeTarget,sha256} from "./agents.js";
import {packageInventory} from "./package-inventory.js";
import {createManifest} from "../install/core.js";

const here=dirname(fileURLToPath(import.meta.url)),root=resolve(here,"../.."),moduleDir=resolve(root,"agents/host-agent"),templateDir=resolve(root,"scripts/install/templates");
function targets(env){const raw=env.LAN_BUILD_TARGETS?.split(",").filter(Boolean)??orderedPlatforms().map(p=>`${p.os}-${p.arch}`);if(raw.length<1)throw new Error("ERR_BUILD_TARGETS");const unique=[...new Set(raw)];if(unique.some(t=>!sanitizeTarget(t)))throw new Error("ERR_BUILD_TARGETS");return unique.sort();}
function contained(base,value){const prefix=resolve(base)+"/";return resolve(value).startsWith(prefix);}
function run(command,args,options={}){const result=spawnSync(command,args,{...options,encoding:"utf8"});if(result.status!==0)throw new Error(options.error??"ERR_BUILD_COMMAND");return typeof result.stdout==="string"?result.stdout.trim():"";}
function runGo(os,arch,out,version){run("go",["build","-trimpath","-buildvcs=false",`-ldflags=-s -w -X main.version=${version}`,"-o",out,"./cmd/lan-model-agent"],{cwd:moduleDir,stdio:"inherit",env:{...process.env,CGO_ENABLED:"0",GOOS:os,GOARCH:arch},error:"ERR_GO_BUILD"});}
function sourceCommit(env){const dirty=run("git",["status","--porcelain","--untracked-files=all"],{cwd:root,error:"ERR_SOURCE_STATUS"});if(dirty&&env.LAN_ALLOW_DIRTY!=="1")throw new Error("ERR_DIRTY_SOURCE");const value=env.SOURCE_COMMIT??run("git",["rev-parse","HEAD"],{cwd:root,error:"ERR_SOURCE_COMMIT"});if(!/^[a-f0-9]{40}$/.test(value))throw new Error("ERR_SOURCE_COMMIT");return value;}
async function installerRuntime(){return[{name:"install/core.js",bytes:await readFile(resolve(root,"scripts/install/core.js")),mode:0o644},{name:"install/cli.js",bytes:await readFile(resolve(root,"scripts/install/cli.js")),mode:0o755}];}
async function payloadEntries(os,binary){const executable=await readFile(binary),entries=[{name:`bin/lan-model-agent${os==="windows"?".exe":""}`,bytes:executable,mode:0o755},...await installerRuntime()];if(os==="windows")entries.push({name:"install/Install-LANModelService.ps1",bytes:await readFile(resolve(templateDir,"windows/Install-LANModelService.ps1")),mode:0o644},{name:"install/service-descriptor.json",bytes:await readFile(resolve(templateDir,"windows/service-descriptor.json")),mode:0o644});else if(os==="linux")entries.push({name:"install/Install-LANModelService.sh",bytes:await readFile(resolve(templateDir,"linux/Install-LANModelService.sh")),mode:0o755},{name:"install/launch.sh",bytes:await readFile(resolve(templateDir,"linux/launch.sh")),mode:0o755},{name:"install/lan-model-agent.service",bytes:await readFile(resolve(templateDir,"linux/lan-model-agent.service")),mode:0o644},{name:"install/lan-model-manager.sysusers",bytes:await readFile(resolve(templateDir,"linux/lan-model-manager.sysusers")),mode:0o644},{name:"install/lan-model-manager.tmpfiles",bytes:await readFile(resolve(templateDir,"linux/lan-model-manager.tmpfiles")),mode:0o644});return entries;}
async function collectFiles(source,prefix,filter=()=>true){const entries=[];async function walk(dir,rel=""){for(const item of (await readdir(dir,{withFileTypes:true})).sort((a,b)=>a.name<b.name?-1:a.name>b.name?1:0)){const child=rel?`${rel}/${item.name}`:item.name;if(item.isDirectory())await walk(resolve(dir,item.name),child);else if(item.isFile()&&filter(child))entries.push({name:`${prefix}/${child}`,bytes:await readFile(resolve(dir,item.name)),mode:0o644});}}await walk(source);return entries;}
async function controllerEntries(){const production=name=>!name.includes(".test.")&&!name.endsWith(".map")&&!name.endsWith(".d.ts")&&!name.split("/").some(part=>part.startsWith("_")),entries=[{name:"bin/lan-model-controller",bytes:await readFile(resolve(templateDir,"linux/lan-model-controller")),mode:0o755},...await installerRuntime(),{name:"install/Install-LANModelService.sh",bytes:await readFile(resolve(templateDir,"linux/Install-LANModelService.sh")),mode:0o755},{name:"install/launch.sh",bytes:await readFile(resolve(templateDir,"linux/launch.sh")),mode:0o755},{name:"install/lan-model-controller.service",bytes:await readFile(resolve(templateDir,"linux/lan-model-controller.service")),mode:0o644},{name:"install/lan-model-manager.sysusers",bytes:await readFile(resolve(templateDir,"linux/lan-model-manager.sysusers")),mode:0o644},{name:"install/lan-model-manager.tmpfiles",bytes:await readFile(resolve(templateDir,"linux/lan-model-manager.tmpfiles")),mode:0o644},{name:"app/controller/package.json",bytes:await readFile(resolve(root,"apps/controller/package.json")),mode:0o644},{name:"node_modules/@lan-model-manager/core/package.json",bytes:await readFile(resolve(root,"packages/core/package.json")),mode:0o644}];entries.push(...await collectFiles(resolve(root,"apps/controller/dist"),"app/controller/dist",production),...await collectFiles(resolve(root,"packages/core/dist"),"node_modules/@lan-model-manager/core/dist",production),...await collectFiles(resolve(root,"apps/web/dist"),"app/web/dist"));return entries;}
export async function buildPackages(outputArg="artifacts/host-agent",env=process.env){const output=resolve(root,outputArg);if(!contained(root,output))throw new Error("ERR_OUTPUT_PATH");const scratch=resolve(root,".tmp-build/packaging"),commit=sourceCommit(env),version=env.LAN_PACKAGE_VERSION??"0.0.0";if(!/^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$/.test(version))throw new Error("ERR_PACKAGE_VERSION");await rm(output,{recursive:true,force:true});await rm(scratch,{recursive:true,force:true});await mkdir(output,{recursive:true});await mkdir(scratch,{recursive:true});const records=[];try{for(const target of targets(env)){const[os,arch]=target.split("-"),binary=resolve(scratch,binaryName(os,arch));runGo(os,arch,binary,version);const entries=await payloadEntries(os,binary),files=entries.map(e=>({path:e.name,size:e.bytes.length,sha256:sha256(e.bytes),mode:e.mode})),manifest=createManifest({role:"agent",version,files,sourceCommit:commit}),archive=createTarGz([...entries,{name:"install/install-manifest.json",bytes:Buffer.from(JSON.stringify(manifest,null,2)+"\n"),mode:0o644}]),name=archiveName(os,arch),path=resolve(output,name);await writeFile(path,archive);records.push({name,role:"agent",target,sha256:sha256(archive),size:(await stat(path)).size});}const cEntries=await controllerEntries(),cFiles=cEntries.map(e=>({path:e.name,size:e.bytes.length,sha256:sha256(e.bytes),mode:e.mode})),cManifest=createManifest({role:"controller",version,files:cFiles,sourceCommit:commit}),cArchive=createTarGz([...cEntries,{name:"install/install-manifest.json",bytes:Buffer.from(JSON.stringify(cManifest,null,2)+"\n"),mode:0o644}]),cName="lan-model-controller-linux-any.tar.gz",cPath=resolve(output,cName);await writeFile(cPath,cArchive);records.push({name:cName,role:"controller",target:"linux-any",sha256:sha256(cArchive),size:(await stat(cPath)).size});await writeFile(resolve(output,"checksums.txt"),checksumManifest(records));const inventory=packageInventory(records,commit);await writeFile(resolve(output,"package-inventory.json"),JSON.stringify(inventory,null,2)+"\n");return Object.freeze(records.map(r=>Object.freeze({...r})));}finally{await rm(scratch,{recursive:true,force:true});}}
if(import.meta.url===pathToFileURL(process.argv[1]??"").href)buildPackages(process.argv[2]).then(r=>console.log(`built ${r.length} unsigned package(s)`)).catch(error=>{console.error(error instanceof Error?error.message:"ERR_BUILD");process.exitCode=1;});
