import test from "node:test";import assert from "node:assert/strict";import { AdmissionError,createAdmissionController } from "./admission-accounting.js";
const NOW="2026-09-28T12:00:00.000Z";
function controller(){const events:string[]=[];return{admissions:createAdmissionController({clock:()=>NOW,audit:event=>events.push(event.action)}),events};}
test("unknown targets and malformed identifiers fail closed",()=>{const x=controller();for(const call of [()=>x.admissions.snapshot("target"),()=>x.admissions.acquire("target"),()=>x.admissions.register("bad/id")])assert.throws(call,AdmissionError);x.admissions.register("target");assert.throws(()=>x.admissions.acquire("target","bad/id"),AdmissionError);});
test("duplicate lease ids never overwrite or leak accounting",()=>{const x=controller();x.admissions.register("target");const lease=x.admissions.acquire("target","request-1");assert.throws(()=>x.admissions.acquire("target","request-1"),(error:unknown)=>error instanceof AdmissionError&&error.code==="ERR_ADMISSION_DUPLICATE");assert.equal(x.admissions.snapshot("target").active,1);lease.release();lease.release();assert.equal(x.admissions.snapshot("target").active,0);});
test("drain stops new admission and waits for accepted work",async()=>{const x=controller();x.admissions.register("target");const first=x.admissions.acquire("target","one"),second=x.admissions.acquire("target","two"),drained=x.admissions.stopAdmission("target");assert.throws(()=>x.admissions.acquire("target","three"),(error:unknown)=>error instanceof AdmissionError&&error.code==="ERR_ADMISSION_DRAINING");let done=false;void drained.then(()=>{done=true;});first.release();await Promise.resolve();assert.equal(done,false);second.release();await drained;assert.equal(done,true);assert.deepEqual(x.admissions.snapshot("target"),{active:0,draining:true,observedAt:NOW});});
test("cancellation propagation and accounting are exactly once",()=>{const x=controller();x.admissions.register("target");const lease=x.admissions.acquire("target","one");let cancelled=0;assert.equal(lease.onCancel(()=>cancelled++),true);assert.equal(x.admissions.cancel("target","one"),true);assert.equal(x.admissions.cancel("target","one"),false);lease.cancel();lease.release();assert.equal(cancelled,1);assert.equal(x.admissions.snapshot("target").active,0);assert.deepEqual(x.events.filter(value=>value==="lease-cancelled"),["lease-cancelled"]);});
test("drain hook runs once and observer failure cannot weaken drain",async()=>{let hooks=0;const admissions=createAdmissionController({clock:()=>NOW,onDrain:()=>{hooks++;throw new Error("observer failed");}});admissions.register("target");await admissions.stopAdmission("target");await admissions.stopAdmission("target");assert.equal(hooks,1);assert.equal(admissions.snapshot("target").draining,true);});

test("audit observer failures cannot corrupt accounting",async()=>{const admissions=createAdmissionController({clock:()=>NOW,audit:()=>{throw new Error("observer failed");}});admissions.register("target");const lease=admissions.acquire("target","one"),drained=admissions.stopAdmission("target");lease.release();await drained;assert.deepEqual(admissions.snapshot("target"),{active:0,draining:true,observedAt:NOW});});

test("forget refuses active leases or drain waiters",async()=>{const x=controller();x.admissions.register("target");const lease=x.admissions.acquire("target","one"),drained=x.admissions.stopAdmission("target");assert.throws(()=>x.admissions.forget("target"),(error:unknown)=>error instanceof AdmissionError&&error.code==="ERR_ADMISSION_ACTIVE");lease.release();await drained;x.admissions.forget("target");assert.throws(()=>x.admissions.snapshot("target"),AdmissionError);});
