import { createHash, randomBytes } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import { parseCommandRequest, parseCommandResponse, responseMatches, signTransportSignedEnvelope, type CommandRequest, type CommandResponse, type JsonValue, type TransportSigner } from "@lan-model-manager/core";
import type { CertificateRepository } from "./certificate-repository.js";
import type { CommandWire } from "./command-dispatch.js";
import { CommandDispatcher } from "./command-dispatch.js";
import type { JobStores } from "./jobs-store.js";
import type { ControllerTransport } from "./transport/controller-transport.js";

type State="queued"|"leased"|"completed"|"cancelled"|"expired";
type Row={job_id:string;host_id:string;request_json:string;request_digest:string;state:State;lease_until:string|null;result_json:string|null};
export type AgentCommandPoll={readonly command:CommandRequest|null;readonly cancelledJobIds:readonly string[]};
export type AgentCommandOutcome={readonly ok:true;readonly result:AgentCommandPoll}|{readonly ok:false;readonly error:string};
const terminal=new Set(["succeeded","failed","timed-out","cancelled"]);
function digest(request:CommandRequest):string{return createHash("sha256").update(JSON.stringify(request)).digest("hex");}
function decode(row:Row):CommandRequest|null{try{const parsed=parseCommandRequest(JSON.parse(row.request_json));return parsed.ok&&digest(parsed.value)===row.request_digest?parsed.value:null;}catch{return null;}}

/** Persistent queue whose lease, result, authoritative job and audit mutations share SQLite transactions. */
export class AgentCommandStore implements CommandWire {
  constructor(private readonly db:DatabaseSync,private readonly clock:()=>string=()=>new Date().toISOString(),private readonly leaseMs=30_000,private readonly stores?:JobStores){if(!Number.isSafeInteger(leaseMs)||leaseMs<1||leaseMs>300_000)throw new Error("ERR_COMMAND_STORE");}
  private transaction<T>(fn:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const value=fn();this.db.exec("COMMIT");return value;}catch(error){try{this.db.exec("ROLLBACK");}catch{}throw error;}}
  send(input:CommandRequest):unknown { const parsed=parseCommandRequest(input);if(!parsed.ok)throw new Error("ERR_COMMAND_STORE");const request=parsed.value,now=this.clock(),sum=digest(request);return this.transaction(()=>{const existing=this.db.prepare("SELECT * FROM agent_commands WHERE job_id=?").get(request.jobId) as Row|undefined;if(existing){if(existing.request_digest!==sum||existing.host_id!==request.hostId)throw new Error("ERR_COMMAND_CONFLICT");return this.accepted(request,now);}this.db.prepare("INSERT INTO agent_commands(job_id,host_id,request_json,request_digest,state,lease_until,result_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").run(request.jobId,request.hostId,JSON.stringify(request),sum,"queued",null,null,now,now);return this.accepted(request,now);}); }
  poll(hostId:string):AgentCommandPoll { const now=this.clock();this.expire(hostId,now);return this.transaction(()=>{const cancelled=(this.db.prepare("SELECT job_id FROM agent_commands WHERE host_id=? AND state='cancelled' ORDER BY job_id LIMIT 64").all(hostId) as Array<{job_id:string}>).map(value=>value.job_id);const active=this.db.prepare("SELECT job_id FROM agent_commands WHERE host_id=? AND state='leased' AND lease_until>? LIMIT 1").get(hostId,now);if(active)return Object.freeze({command:null,cancelledJobIds:Object.freeze(cancelled)});const row=this.db.prepare("SELECT * FROM agent_commands WHERE host_id=? AND (state='queued' OR (state='leased' AND lease_until<=?)) ORDER BY created_at,job_id LIMIT 1").get(hostId,now) as Row|undefined;if(!row)return Object.freeze({command:null,cancelledJobIds:Object.freeze(cancelled)});const request=decode(row);if(!request){this.db.prepare("UPDATE agent_commands SET state='expired',lease_until=NULL,updated_at=? WHERE job_id=?").run(now,row.job_id);return Object.freeze({command:null,cancelledJobIds:Object.freeze(cancelled)});}const lease=new Date(Date.parse(now)+this.leaseMs).toISOString();this.db.prepare("UPDATE agent_commands SET state='leased',lease_until=?,updated_at=? WHERE job_id=?").run(lease,now,row.job_id);return Object.freeze({command:request,cancelledJobIds:Object.freeze(cancelled)});}); }
  complete(hostId:string,input:unknown):{request:CommandRequest;response:CommandResponse}|null { const parsed=parseCommandResponse(input);if(!parsed.ok||parsed.value.hostId!==hostId)return null;const response=parsed.value;return this.transaction(()=>{const row=this.db.prepare("SELECT * FROM agent_commands WHERE job_id=? AND host_id=?").get(response.jobId,hostId) as Row|undefined;if(!row)return null;const request=decode(row);if(!request||!responseMatches(request,response))return null;if(row.state==="completed")return row.result_json===JSON.stringify(response)?{request,response}:null;if(row.state==="cancelled"&&response.status!=="cancelled")return null;const state=response.status==="accepted"||response.status==="running"?"queued":"completed";this.db.prepare("UPDATE agent_commands SET state=?,lease_until=NULL,result_json=?,updated_at=? WHERE job_id=?").run(state,JSON.stringify(response),this.clock(),row.job_id);return{request,response};}); }
  cancel(jobId:string):boolean { return this.transaction(()=>Number(this.db.prepare("UPDATE agent_commands SET state='cancelled',lease_until=NULL,updated_at=? WHERE job_id=? AND state IN ('queued','leased')").run(this.clock(),jobId).changes)===1); }
  private expire(hostId:string,now:string):void { const rows=this.db.prepare("SELECT * FROM agent_commands WHERE host_id=? AND state IN ('queued','leased') AND json_extract(request_json,'$.deadline')<=? ORDER BY job_id LIMIT 64").all(hostId,now) as Row[];for(const row of rows){const request=decode(row);if(!request)continue;if(this.stores){this.stores.withAuditTransaction(tx=>{const job=tx.jobs.get(row.job_id);if(job&&!terminal.has(job.payload.state)){const at=new Date(Math.max(Date.parse(now),Date.parse(job.updatedAt)+1)).toISOString();tx.jobs.transition(row.job_id,"timed-out",at,{progressPercent:null,terminalCode:"TIMEOUT",terminalMessage:"deadline expired"});tx.audit.append({actorKind:"controller",actorId:"controller",action:"command-timeout",outcome:"failed",requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,details:null,occurredAt:at});}this.db.prepare("UPDATE agent_commands SET state='expired',lease_until=NULL,updated_at=? WHERE job_id=?").run(now,row.job_id);});}else this.transaction(()=>{this.db.prepare("UPDATE agent_commands SET state='expired',lease_until=NULL,updated_at=? WHERE job_id=?").run(now,row.job_id);});} }
  private accepted(request:CommandRequest,observedAt:string):CommandResponse { const at=new Date(Date.parse(observedAt)+4).toISOString();return{requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,sequence:request.sequence,status:"accepted",progress:0,observedAt:at,observation:null,errorCode:null}; }
}

export interface AgentCommandServiceOptions{readonly clock?:()=>string;readonly random?:()=>string;readonly pollIntervalMs?:number}
export class AgentCommandService {
  private readonly clock:()=>string;private readonly nonce:()=>string;private readonly dispatcher:CommandDispatcher;private readonly pollIntervalMs:number;
  constructor(private readonly transport:ControllerTransport,private readonly certificates:CertificateRepository,private readonly store:AgentCommandStore,stores:JobStores,private readonly signer:TransportSigner,options:AgentCommandServiceOptions={}){this.clock=options.clock??(()=>new Date().toISOString());this.nonce=options.random??(()=>randomBytes(16).toString("hex"));this.pollIntervalMs=options.pollIntervalMs??25;if(!Number.isSafeInteger(this.pollIntervalMs)||this.pollIntervalMs<5||this.pollIntervalMs>1000)throw new Error("ERR_COMMAND_SERVICE");this.dispatcher=new CommandDispatcher(stores,{send:()=>{throw new Error("unused");}},this.clock);}
  ingest(input:unknown,sourceAddress:string):AgentCommandOutcome { const accepted=this.transport.accept(input);if(!accepted.ok)return{ok:false,error:"ERR_COMMAND_AUTH"};const env=accepted.envelope,cert=this.certificates.getBySerial(env.certSerial,env.certFingerprint);if(!cert||cert.status!=="active"||cert.binding.candidateId!==env.hostId||cert.binding.address!==sourceAddress)return{ok:false,error:"ERR_COMMAND_BINDING"};if(env.messageType==="agent.command.poll"){if(!this.pollPayload(env.payload))return{ok:false,error:"ERR_COMMAND_INPUT"};return{ok:true,result:this.store.poll(env.hostId)};}if(env.messageType==="agent.command.result"){const settled=this.store.complete(env.hostId,env.payload);if(!settled)return{ok:false,error:"ERR_COMMAND_RESULT"};const result=this.dispatcher.settle(settled.request,settled.response);return result.ok?{ok:true,result:Object.freeze({command:null,cancelledJobIds:Object.freeze([])})}:{ok:false,error:"ERR_COMMAND_RESULT"};}return{ok:false,error:"ERR_COMMAND_INPUT"}; }
  async wait(hostId:string,initial:AgentCommandPoll,waitMs:number):Promise<AgentCommandPoll>{if(initial.command||initial.cancelledJobIds.length||waitMs===0)return initial;const end=Date.now()+waitMs;let value=initial;while(Date.now()<end){await new Promise(resolve=>setTimeout(resolve,Math.min(this.pollIntervalMs,end-Date.now())));value=this.store.poll(hostId);if(value.command||value.cancelledJobIds.length)return value;}return value;}
  signed(hostId:string,requestId:string,sequence:number,payload:AgentCommandPoll):unknown { const raw={protocolVersion:{major:1,minor:0},messageType:"controller.command.poll",hostId,requestId,sequence,sentAt:this.clock(),nonce:this.nonce(),bodyDigest:"0".repeat(64),certFingerprint:this.signer.certificate.fingerprint,certSerial:this.signer.certificate.serial,signature:"0".repeat(70),payload:payload as unknown as JsonValue};const signed=signTransportSignedEnvelope(raw,this.signer);if(!signed.ok)throw new Error("ERR_COMMAND_SIGN");return signed.value; }
  private pollPayload(value:unknown):boolean{return typeof value==="object"&&value!==null&&!Array.isArray(value)&&Reflect.ownKeys(value).length===1&&Number.isSafeInteger((value as any).waitMs)&&(value as any).waitMs>=0&&(value as any).waitMs<=30_000;}
}
