import { createHash, randomBytes } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import { parseCommandRequest, parseCommandResponse, parsePeerRelayResult, responseMatches, signTransportSignedEnvelope, type CommandRequest, type CommandResponse, type JsonValue, type PeerRelayDirective, type TransportSigner } from "@lan-model-manager/core";
import type { CertificateRepository } from "./certificate-repository.js";
import type { CommandWire } from "./command-dispatch.js";
import { CommandDispatcher } from "./command-dispatch.js";
import type { CoupledContext,JobStores } from "./jobs-store.js";
import type { ControllerTransport } from "./transport/controller-transport.js";

type State="queued"|"leased"|"completed"|"cancelled"|"expired";
type Row={job_id:string;host_id:string;request_json:string;request_digest:string;state:State;lease_until:string|null;result_json:string|null;created_at:string;updated_at:string};
export type AgentCommandPoll={readonly command:CommandRequest|null;readonly cancelledJobIds:readonly string[];readonly peerTransfer?:PeerRelayDirective|null};
export interface AgentPeerRelay { poll(hostId:string):PeerRelayDirective|null; complete(hostId:string,input:unknown):boolean }
export type AgentCommandOutcome={readonly ok:true;readonly result:AgentCommandPoll}|{readonly ok:false;readonly error:string};
const terminal=new Set(["succeeded","failed","timed-out","cancelled"]);
function digest(request:CommandRequest):string{return createHash("sha256").update(JSON.stringify(request)).digest("hex");}
function decode(row:Row):CommandRequest|null{try{const parsed=parseCommandRequest(JSON.parse(row.request_json));return parsed.ok&&digest(parsed.value)===row.request_digest?parsed.value:null;}catch{return null;}}
function lifecycleResultMatches(request:CommandRequest,response:CommandResponse,before:string,now:string):boolean{if(response.status!=="succeeded"||!["load","drain","unload"].includes(request.operation))return true;const params=request.params as Record<string,unknown>|null,observation=response.observation as Record<string,unknown>|null,seen=observation&&typeof observation.observedAt==="string"?Date.parse(observation.observedAt):NaN,current=Date.parse(now);if(!params||!observation||!Number.isFinite(seen)||!Number.isFinite(current)||seen<=Date.parse(before)||seen>current+30_000||Date.parse(response.observedAt)>current+30_000||observation.providerId!==params.providerId||observation.canonicalModelName!==params.model)return false;if(request.operation==="load")return observation.action==="load"&&observation.outcome==="succeeded"&&observation.runtimeState==="loaded";if(request.operation==="drain")return observation.action==="drain"&&observation.outcome==="succeeded"&&observation.runtimeState==="loaded"&&observation.activeRequests===0;return observation.action==="unload"&&observation.outcome==="succeeded"&&observation.runtimeState==="unloaded";}

/** Persistent queue whose lease, result, authoritative job and audit mutations share SQLite transactions. */
export class AgentCommandStore implements CommandWire {
  constructor(private readonly db:DatabaseSync,private readonly clock:()=>string=()=>new Date().toISOString(),private readonly leaseMs=30_000,private readonly stores?:JobStores,private readonly deferLifecycleSettlement=false){if(!Number.isSafeInteger(leaseMs)||leaseMs<1||leaseMs>300_000)throw new Error("ERR_COMMAND_STORE");}
  private transaction<T>(fn:()=>T):T{this.db.exec("BEGIN IMMEDIATE");try{const value=fn();this.db.exec("COMMIT");return value;}catch(error){try{this.db.exec("ROLLBACK");}catch{}throw error;}}
  send(input:CommandRequest):unknown { const parsed=parseCommandRequest(input);if(!parsed.ok)throw new Error("ERR_COMMAND_STORE");const request=parsed.value,now=this.clock(),sum=digest(request);return this.transaction(()=>{const existing=this.db.prepare("SELECT * FROM agent_commands WHERE job_id=?").get(request.jobId) as Row|undefined;if(existing){if(existing.request_digest!==sum||existing.host_id!==request.hostId)throw new Error("ERR_COMMAND_CONFLICT");return this.accepted(request,now);}this.db.prepare("INSERT INTO agent_commands(job_id,host_id,request_json,request_digest,state,lease_until,result_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").run(request.jobId,request.hostId,JSON.stringify(request),sum,"queued",null,null,now,now);return this.accepted(request,now);}); }
  poll(hostId:string):AgentCommandPoll { const now=this.clock();this.expire(hostId,now);return this.transaction(()=>{const cancelled=(this.db.prepare("SELECT job_id FROM agent_commands WHERE host_id=? AND state='cancelled' ORDER BY updated_at,job_id LIMIT 64").all(hostId) as Array<{job_id:string}>).map(value=>value.job_id);for(const[index,jobId]of cancelled.entries())this.db.prepare("UPDATE agent_commands SET updated_at=? WHERE job_id=?").run(new Date(Date.parse(now)+index+1).toISOString(),jobId);const active=this.db.prepare("SELECT job_id FROM agent_commands WHERE host_id=? AND state='leased' AND lease_until>? LIMIT 1").get(hostId,now);if(active)return Object.freeze({command:null,cancelledJobIds:Object.freeze(cancelled)});const row=this.db.prepare("SELECT * FROM agent_commands WHERE host_id=? AND (state='queued' OR (state='leased' AND lease_until<=?)) ORDER BY created_at,job_id LIMIT 1").get(hostId,now) as Row|undefined;if(!row)return Object.freeze({command:null,cancelledJobIds:Object.freeze(cancelled)});const request=decode(row);if(!request){this.db.prepare("UPDATE agent_commands SET state='expired',lease_until=NULL,updated_at=? WHERE job_id=?").run(now,row.job_id);return Object.freeze({command:null,cancelledJobIds:Object.freeze(cancelled)});}const lease=new Date(Date.parse(now)+this.leaseMs).toISOString();this.db.prepare("UPDATE agent_commands SET state='leased',lease_until=?,updated_at=? WHERE job_id=?").run(lease,now,row.job_id);return Object.freeze({command:request,cancelledJobIds:Object.freeze(cancelled)});}); }
  complete(hostId:string,input:unknown):{request:CommandRequest;response:CommandResponse;duplicate:boolean;authoritative:boolean}|null { const parsed=parseCommandResponse(input);if(!parsed.ok||parsed.value.hostId!==hostId)return null;const response=parsed.value;let output:{request:CommandRequest;response:CommandResponse;duplicate:boolean;authoritative:boolean}|null=null;const mutate=(tx?:CoupledContext)=>{const row=this.db.prepare("SELECT * FROM agent_commands WHERE job_id=? AND host_id=?").get(response.jobId,hostId) as Row|undefined;if(!row)return;const request=decode(row);if(!request||!responseMatches(request,response)||!lifecycleResultMatches(request,response,row.created_at,this.clock()))return;if(row.state==="completed"){if(row.result_json!==JSON.stringify(response))return;output={request,response,duplicate:true,authoritative:!!tx};if(tx)this.settleAuthoritative(tx,request,response);return;}const now=this.clock();if(row.state==="expired"||Date.parse(now)>=Date.parse(request.deadline)||(row.state!=="leased"&&row.state!=="cancelled")||(row.state==="cancelled"&&response.status!=="cancelled"))return;const state=response.status==="accepted"||response.status==="running"?"queued":"completed";this.db.prepare("UPDATE agent_commands SET state=?,lease_until=NULL,result_json=?,updated_at=? WHERE job_id=?").run(state,JSON.stringify(response),now,row.job_id);output={request,response,duplicate:false,authoritative:!!tx};if(tx)this.settleAuthoritative(tx,request,response);};if(this.stores)this.stores.withAuditTransaction(tx=>mutate(tx));else this.transaction(()=>mutate());return output; }
  result(jobId:string):CommandResponse|null { const row=this.db.prepare("SELECT result_json FROM agent_commands WHERE job_id=? AND state='completed'").get(jobId) as {result_json:string|null}|undefined;if(!row?.result_json)return null;try{const parsed=parseCommandResponse(JSON.parse(row.result_json));return parsed.ok?parsed.value:null;}catch{return null;} }
  defersLifecycle():boolean { return this.deferLifecycleSettlement; }
  request(jobId:string):CommandRequest|null { const row=this.db.prepare("SELECT * FROM agent_commands WHERE job_id=?").get(jobId) as Row|undefined;return row?decode(row):null; }
  async waitResult(jobId:string,deadline:string,signal:AbortSignal,pollMs=20):Promise<CommandResponse>{if(!Number.isSafeInteger(pollMs)||pollMs<5||pollMs>1000)throw new Error("ERR_COMMAND_WAIT");for(;;){if(signal.aborted)throw new DOMException("Aborted","AbortError");const remaining=Date.parse(deadline)-Date.parse(this.clock());if(remaining<=0)throw new DOMException("Timed out","TimeoutError");const value=this.result(jobId);if(value)return value;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(done,Math.min(pollMs,remaining));function done(){signal.removeEventListener("abort",abort);resolve();}function abort(){clearTimeout(timer);signal.removeEventListener("abort",abort);reject(new DOMException("Aborted","AbortError"));}signal.addEventListener("abort",abort,{once:true});});} }
  cancel(jobId:string):boolean { if(!this.stores)return this.transaction(()=>Number(this.db.prepare("UPDATE agent_commands SET state='cancelled',lease_until=NULL,updated_at=? WHERE job_id=? AND state IN ('queued','leased')").run(this.clock(),jobId).changes)===1);let changed=false;this.stores.withAuditTransaction(tx=>{const row=this.db.prepare("SELECT * FROM agent_commands WHERE job_id=?").get(jobId) as Row|undefined,request=row&&decode(row);if(!row||!request)return;const job=tx.jobs.get(jobId);if(!job||terminal.has(job.payload.state)){changed=true;return;}const now=new Date(Math.max(Date.parse(this.clock()),Date.parse(job.updatedAt)+1)).toISOString();changed=Number(this.db.prepare("UPDATE agent_commands SET state='cancelled',lease_until=NULL,updated_at=? WHERE job_id=? AND state IN ('queued','leased')").run(now,jobId).changes)===1;if(changed){tx.jobs.transition(jobId,"cancelled",now,{progressPercent:null,terminalCode:"CANCELLED",terminalMessage:"cancelled"});tx.audit.append({actorKind:"controller",actorId:"controller",action:"command-cancel",outcome:"cancelled",requestId:request.requestId,jobId,hostId:request.hostId,details:null,occurredAt:now});}});return changed; }
  private settleAuthoritative(tx:CoupledContext,request:CommandRequest,response:CommandResponse):void { const job=tx.jobs.get(request.jobId);if(!job||terminal.has(job.payload.state)||(job.payload.state==="running"&&response.status==="accepted")||(this.deferLifecycleSettlement&&response.status==="succeeded"&&["load","drain","unload"].includes(request.operation)))return;const state=({accepted:"accepted",running:"running",succeeded:"succeeded",failed:"failed",cancelled:"cancelled"}as const)[response.status];let current=job.payload.state;for(const step of ["accepted","running"]as const){if(terminal.has(current)||(state==="accepted"&&step==="running"))break;if(current===step||(current==="running"&&step==="accepted"))continue;tx.jobs.transition(request.jobId,step,new Date(Date.parse(response.observedAt)+(step==="running"?1:0)).toISOString(),{progressPercent:step==="running"?Math.min(response.progress??1,99):0,terminalCode:null,terminalMessage:null});current=step;}if(current!==state)tx.jobs.transition(request.jobId,state,new Date(Date.parse(response.observedAt)+2).toISOString(),{progressPercent:response.progress,terminalCode:response.errorCode,terminalMessage:response.errorCode});tx.audit.append({actorKind:"agent",actorId:request.hostId,action:"command-result",outcome:response.status==="succeeded"?"succeeded":response.status==="failed"?"failed":"observed",requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,details:{status:response.status},occurredAt:response.observedAt}); }
  private expire(hostId:string,now:string):void { const rows=this.db.prepare("SELECT * FROM agent_commands WHERE host_id=? AND state IN ('queued','leased') AND json_extract(request_json,'$.deadline')<=? ORDER BY job_id LIMIT 64").all(hostId,now) as Row[];for(const row of rows){const request=decode(row);if(!request)continue;if(this.stores){this.stores.withAuditTransaction(tx=>{const job=tx.jobs.get(row.job_id);if(job&&!terminal.has(job.payload.state)){const at=new Date(Math.max(Date.parse(now),Date.parse(job.updatedAt)+1)).toISOString();tx.jobs.transition(row.job_id,"timed-out",at,{progressPercent:null,terminalCode:"TIMEOUT",terminalMessage:"deadline expired"});tx.audit.append({actorKind:"controller",actorId:"controller",action:"command-timeout",outcome:"failed",requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,details:null,occurredAt:at});}this.db.prepare("UPDATE agent_commands SET state='expired',lease_until=NULL,updated_at=? WHERE job_id=?").run(now,row.job_id);});}else this.transaction(()=>{this.db.prepare("UPDATE agent_commands SET state='expired',lease_until=NULL,updated_at=? WHERE job_id=?").run(now,row.job_id);});} }
  private accepted(request:CommandRequest,observedAt:string):CommandResponse { const at=new Date(Date.parse(observedAt)+4).toISOString();return{requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,sequence:request.sequence,status:"accepted",progress:0,observedAt:at,observation:null,errorCode:null}; }
}

export interface AgentCommandServiceOptions{readonly clock?:()=>string;readonly random?:()=>string;readonly pollIntervalMs?:number;readonly peerRelay?:AgentPeerRelay}
export class AgentCommandService {
  private readonly clock:()=>string;private readonly nonce:()=>string;private readonly dispatcher:CommandDispatcher;private readonly pollIntervalMs:number;private readonly peerRelay:AgentPeerRelay|undefined;
  constructor(private readonly transport:ControllerTransport,private readonly certificates:CertificateRepository,private readonly store:AgentCommandStore,stores:JobStores,private readonly signer:TransportSigner,options:AgentCommandServiceOptions={}){this.clock=options.clock??(()=>new Date().toISOString());this.nonce=options.random??(()=>randomBytes(16).toString("hex"));this.pollIntervalMs=options.pollIntervalMs??25;this.peerRelay=options.peerRelay;if(!Number.isSafeInteger(this.pollIntervalMs)||this.pollIntervalMs<5||this.pollIntervalMs>1000)throw new Error("ERR_COMMAND_SERVICE");this.dispatcher=new CommandDispatcher(stores,{send:()=>{throw new Error("unused");}},this.clock);}
  ingest(input:unknown,sourceAddress:string):AgentCommandOutcome { const accepted=this.transport.accept(input);if(!accepted.ok)return{ok:false,error:"ERR_COMMAND_AUTH"};const env=accepted.envelope,cert=this.certificates.getBySerial(env.certSerial,env.certFingerprint);if(!cert||cert.status!=="active"||cert.binding.candidateId!==env.hostId||cert.binding.address!==sourceAddress)return{ok:false,error:"ERR_COMMAND_BINDING"};if(env.messageType==="agent.command.poll"){if(!this.pollPayload(env.payload))return{ok:false,error:"ERR_COMMAND_INPUT"};return{ok:true,result:this.poll(env.hostId)};}if(env.messageType==="agent.command.result"){if(this.peerRelay&&parsePeerRelayResult(env.payload).ok)return this.peerRelay.complete(env.hostId,env.payload)?{ok:true,result:Object.freeze({command:null,cancelledJobIds:Object.freeze([])})}:{ok:false,error:"ERR_COMMAND_RESULT"};const settled=this.store.complete(env.hostId,env.payload);if(!settled)return{ok:false,error:"ERR_COMMAND_RESULT"};const result=settled.authoritative?{ok:true as const}:this.dispatcher.settle(settled.request,settled.response);return result.ok?{ok:true,result:Object.freeze({command:null,cancelledJobIds:Object.freeze([])})}:{ok:false,error:"ERR_COMMAND_RESULT"};}return{ok:false,error:"ERR_COMMAND_INPUT"}; }
  async wait(hostId:string,initial:AgentCommandPoll,waitMs:number):Promise<AgentCommandPoll>{if(initial.command||initial.cancelledJobIds.length||waitMs===0)return initial;const end=Date.now()+waitMs;let value=initial;while(Date.now()<end){await new Promise(resolve=>setTimeout(resolve,Math.min(this.pollIntervalMs,end-Date.now())));value=this.poll(hostId);if(value.command||value.cancelledJobIds.length||value.peerTransfer)return value;}return value;}
  private poll(hostId:string):AgentCommandPoll{const value=this.store.poll(hostId),peerTransfer=this.peerRelay?.poll(hostId)??null;return this.peerRelay?Object.freeze({...value,peerTransfer}):value;}
  signed(hostId:string,requestId:string,sequence:number,payload:AgentCommandPoll):unknown { const raw={protocolVersion:{major:1,minor:0},messageType:"controller.command.poll",hostId,requestId,sequence,sentAt:this.clock(),nonce:this.nonce(),bodyDigest:"0".repeat(64),certFingerprint:this.signer.certificate.fingerprint,certSerial:this.signer.certificate.serial,signature:"0".repeat(70),payload:payload as unknown as JsonValue};const signed=signTransportSignedEnvelope(raw,this.signer);if(!signed.ok)throw new Error("ERR_COMMAND_SIGN");return signed.value; }
  private pollPayload(value:unknown):boolean{return typeof value==="object"&&value!==null&&!Array.isArray(value)&&Reflect.ownKeys(value).length===1&&Number.isSafeInteger((value as any).waitMs)&&(value as any).waitMs>=0&&(value as any).waitMs<=30_000;}
}
