import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {X509Certificate} from "node:crypto";
import {existsSync,mkdtempSync,mkdirSync,readFileSync,rmSync,symlinkSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import test from "node:test";
import {OpenSslCertificateEngine} from "./certificate-adapter.js";
import {ensureAgentPlaneMaterial} from "./agent-plane.js";
import {parseTransportParsedLeaf} from "./transport/trust-resolver.js";

function fixture(){const root=mkdtempSync(join(tmpdir(),"lanmm-agent-plane-"));new OpenSslCertificateEngine().initializeCa({directory:root,now:new Date().toISOString()});return root}
test("agent-plane material is CA-signed, exact-address, and pointer-atomic",()=>{const root=fixture();try{const material=ensureAgentPlaneMaterial(root,"192.0.2.10",{random:()=>Buffer.alloc(16,1)}),parsed=parseTransportParsedLeaf(material.certificate,material.ca);assert.ok(parsed.ok);if(parsed.ok){assert.equal(parsed.value.commonName,"controller");assert.equal(parsed.value.address,"192.0.2.10");}assert.doesNotMatch(material.ca,/PRIVATE KEY/);assert.equal(readFileSync(join(root,"agent-plane-current"),"utf8").trim(),material.generation);}finally{rmSync(root,{recursive:true,force:true})}});
test("missing active generation is recoverable without weakening pointer validation",()=>{const root=fixture();try{const missing="a".repeat(32);writeFileSync(join(root,"agent-plane-current"),`${missing}\n`,{mode:0o600});const replacement=ensureAgentPlaneMaterial(root,"192.168.50.10",{random:()=>Buffer.alloc(16,4)});assert.notEqual(replacement.generation,missing);assert.equal(readFileSync(join(root,"agent-plane-current"),"utf8").trim(),replacement.generation);}finally{rmSync(root,{recursive:true,force:true})}});
test("expired active material is replaced without deleting the prior generation",()=>{const root=fixture(),now=Date.now();try{const shortRun=(cwd:string,args:readonly string[])=>{const next=[...args];if(next[0]==="x509"){const days=next.indexOf("-days");next[days+1]="1";}execFileSync("openssl",next,{cwd,stdio:"ignore"});};const first=ensureAgentPlaneMaterial(root,"192.168.50.10",{now,random:()=>Buffer.alloc(16,5),run:shortRun});const replacement=ensureAgentPlaneMaterial(root,"192.168.50.10",{now:now+2*86400000,random:()=>Buffer.alloc(16,6)});assert.notEqual(replacement.generation,first.generation);assert.equal(existsSync(join(root,"agent-plane-generations",first.generation)),true);assert.equal(readFileSync(join(root,"agent-plane-current"),"utf8").trim(),replacement.generation);}finally{rmSync(root,{recursive:true,force:true})}});
test("advertised private-address migration publishes a replacement and preserves the prior generation",()=>{const root=fixture();try{const first=ensureAgentPlaneMaterial(root,"192.168.50.10",{random:()=>Buffer.alloc(16,7)}),replacement=ensureAgentPlaneMaterial(root,"192.168.50.11",{random:()=>Buffer.alloc(16,8)});assert.notEqual(replacement.generation,first.generation);assert.equal(new X509Certificate(replacement.certificate).checkIP("192.168.50.11"),"192.168.50.11");assert.equal(existsSync(join(root,"agent-plane-generations",first.generation)),true);}finally{rmSync(root,{recursive:true,force:true})}});
test("failed renewal preserves the previously active generation",()=>{const root=fixture(),now=Date.now();try{const first=ensureAgentPlaneMaterial(root,"192.0.2.10",{now,random:()=>Buffer.alloc(16,2)}),pointer=readFileSync(join(root,"agent-plane-current"),"utf8");assert.throws(()=>ensureAgentPlaneMaterial(root,"192.0.2.10",{now:now+24*86400000,random:()=>Buffer.alloc(16,3),run:(cwd,args)=>{if(args[0]==="x509")throw new Error("private openssl output");execFileSync("openssl",args,{cwd,stdio:"ignore"});}}),/ERR_AGENT_PLANE_CERTIFICATE/);assert.equal(readFileSync(join(root,"agent-plane-current"),"utf8"),pointer);assert.equal(ensureAgentPlaneMaterial(root,"192.0.2.10",{now,random:()=>Buffer.alloc(16,4)}).generation,first.generation);}finally{rmSync(root,{recursive:true,force:true})}});
test("symlink and partial material are rejected without replacement",()=>{for(const kind of ["directory","generation","pointer"]){const parent=mkdtempSync(join(tmpdir(),"lanmm-agent-symlink-"));try{const root=join(parent,"certs"),target=join(parent,"target");mkdirSync(target,{mode:0o700});if(kind==="directory"){symlinkSync(target,root,"dir");assert.throws(()=>ensureAgentPlaneMaterial(root,"192.0.2.10"),/ERR_AGENT_PLANE_CERTIFICATE/);continue}mkdirSync(root,{mode:0o700});new OpenSslCertificateEngine().initializeCa({directory:root,now:new Date().toISOString()});if(kind==="generation"){symlinkSync(target,join(root,"agent-plane-generations"),"dir")}else{writeFileSync(join(target,"pointer"),'"'+"a".repeat(32)+'"\n');symlinkSync(join(target,"pointer"),join(root,"agent-plane-current"))}assert.throws(()=>ensureAgentPlaneMaterial(root,"192.0.2.10"),/ERR_AGENT_PLANE_CERTIFICATE/);assert.equal(existsSync(join(root,"agent-plane-generations",kind)),false);}finally{rmSync(parent,{recursive:true,force:true})}}});
