import { commandAuthorizationDigest } from "@lan-model-manager/core";
import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { openControllerDatabase } from "./database.js";
import { createJobStores } from "./jobs-store.js";
import { AgentCommandService,AgentCommandStore } from "./agent-command-channel.js";
import { CommandDispatcher } from "./command-dispatch.js";
import { buildTransportNativeSigner,generateTransportNativeKeyPair } from "./transport/transport-signer.js";
const NOW="2026-09-29T10:00:00.000Z",AFTER="2026-09-29T10:00:00.010Z";
const capability:any={operation:"observe",targetKind:"host",targetId:"host-1",hostId:"host-1",modelId:null,expiresAt:"2026-09-29T10:05:00.000Z"};
const request:any={requestId:"request-1",jobId:"job-1",hostId:"host-1",operation:"probe",idempotencyKey:"idem-1",sequence:1,deadline:"2026-09-29T10:04:00.000Z",capability,params:{providerId:"ollama-1"}};capability.requestDigest=commandAuthorizationDigest(request);
function setup(clock:()=>string=()=>NOW){const db=openControllerDatabase(":memory:"),stores=createJobStores(db,{now:clock}),queue=new AgentCommandStore(db,clock,30_000,stores),dispatcher=new CommandDispatcher(stores,queue,clock);assert.equal(dispatcher.dispatch(request).ok,true);const cert={fingerprint:"b".repeat(64),serial:"AB",commonName:"controller",address:"127.0.0.1",spiffe:"spiffe://lanmodelmanager/controller",notBefore:"2026-09-29T09:00:00.000Z",notAfter:"2026-09-30T09:00:00.000Z",issuerFingerprint:"c".repeat(64),isCa:false} as const,signer=buildTransportNativeSigner(generateTransportNativeKeyPair().keyPem,cert);assert.ok(signer.ok);if(!signer.ok)throw new Error();const envelope=(messageType:string,payload:unknown,hostId="host-1")=>({messageType,hostId,requestId:"poll-1",sequence:2,payload});const transport={accept(input:any){return{ok:true,envelope:input}}},certificates={getBySerial(){return{status:"active",binding:{candidateId:"host-1",address:"127.0.0.1"}}}},service=new AgentCommandService(transport as never,certificates as never,queue,stores,signer.value,{clock,random:()=>"d".repeat(32)});return{db,stores,queue,service,envelope}}
test("durable queue dispatches harmless inventory command and persists bound result",()=>{const x=setup();try{const polled=x.service.ingest(x.envelope("agent.command.poll",{waitMs:30000}),"127.0.0.1");assert.ok(polled.ok);if(!polled.ok)return;assert.equal(polled.result.command?.operation,"probe");const signed=x.service.signed("host-1","poll-1",2,polled.result) as any;assert.equal(signed.payload.command.hostId,"host-1");assert.notEqual(signed.signature,"0".repeat(70));const response={requestId:"request-1",jobId:"job-1",hostId:"host-1",sequence:1,status:"succeeded",progress:100,observedAt:AFTER,observation:{health:"ready"},errorCode:null},result=x.service.ingest(x.envelope("agent.command.result",response),"127.0.0.1");assert.ok(result.ok);assert.equal(x.stores.jobs.get("job-1")?.state,"succeeded");assert.equal(x.stores.audit.count(),3);const duplicate=x.service.ingest(x.envelope("agent.command.result",response),"127.0.0.1");assert.ok(duplicate.ok);assert.equal(x.stores.audit.count(),3)}finally{x.db.close()}});
test("accepted and running results release the lease for safe repeat",()=>{const x=setup();try{const first=x.queue.poll("host-1");assert.ok(first.command);const accepted={requestId:"request-1",jobId:"job-1",hostId:"host-1",sequence:1,status:"accepted",progress:0,observedAt:AFTER,observation:null,errorCode:null};assert.ok(x.queue.complete("host-1",accepted));assert.ok(x.queue.poll("host-1").command);const running={...accepted,status:"running",progress:50};assert.ok(x.queue.complete("host-1",running));assert.ok(x.queue.poll("host-1").command);}finally{x.db.close();}});
test("host/source binding, divergent replay, expiry and cancellation fail closed",()=>{const x=setup();try{assert.equal(x.service.ingest(x.envelope("agent.command.poll",{waitMs:0}),"127.0.0.2").ok,false);const first=x.service.ingest(x.envelope("agent.command.poll",{waitMs:0}),"127.0.0.1");assert.ok(first.ok);assert.equal(x.queue.cancel("job-1"),true);const cancelled=x.service.ingest(x.envelope("agent.command.poll",{waitMs:0}),"127.0.0.1");assert.ok(cancelled.ok);if(cancelled.ok)assert.deepEqual(cancelled.result.cancelledJobIds,["job-1"]);const wrong={requestId:"request-1",jobId:"job-1",hostId:"other",sequence:1,status:"succeeded",progress:100,observedAt:AFTER,observation:null,errorCode:null};assert.equal(x.service.ingest(x.envelope("agent.command.result",wrong),"127.0.0.1").ok,false)}finally{x.db.close()}});

test("deadline expiry atomically times out authoritative job and audits",()=>{let now=NOW;const x=setup(()=>now);try{now="2026-09-29T10:04:00.001Z";assert.equal(x.queue.poll("host-1").command,null);assert.equal(x.stores.jobs.get("job-1")?.payload.state,"timed-out");assert.equal(x.stores.audit.list().at(-1)?.action,"command-timeout");assert.equal((x.db.prepare("SELECT state FROM agent_commands WHERE job_id='job-1'").get() as any).state,"expired");assert.equal(x.queue.complete("host-1",{requestId:"request-1",jobId:"job-1",hostId:"host-1",sequence:1,status:"succeeded",progress:100,observedAt:"2026-09-29T10:04:00.002Z",observation:null,errorCode:null}),null);}finally{x.db.close();}});
test("leased command survives controller restart and is recovered after lease",()=>{const dir=mkdtempSync(join(tmpdir(),"lanmm-command-")),path=join(dir,"controller.db");try{let db=openControllerDatabase(path),stores=createJobStores(db,{now:()=>NOW}),queue=new AgentCommandStore(db,()=>NOW,30_000,stores),dispatcher=new CommandDispatcher(stores,queue,()=>NOW);assert.ok(dispatcher.dispatch(request).ok);assert.ok(queue.poll("host-1").command);db.close();db=openControllerDatabase(path);stores=createJobStores(db,{now:()=>"2026-09-29T10:00:31.000Z"});queue=new AgentCommandStore(db,()=>"2026-09-29T10:00:31.000Z",30_000,stores);assert.ok(queue.poll("host-1").command);db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test("running leased command resumes idempotently after controller restart",()=>{const dir=mkdtempSync(join(tmpdir(),"lanmm-running-command-")),path=join(dir,"controller.db");try{let db=openControllerDatabase(path),stores=createJobStores(db,{now:()=>NOW}),queue=new AgentCommandStore(db,()=>NOW,30_000,stores),dispatcher=new CommandDispatcher(stores,queue,()=>NOW);assert.ok(dispatcher.dispatch(request).ok);assert.ok(queue.poll("host-1").command);assert.ok(queue.complete("host-1",{requestId:"request-1",jobId:"job-1",hostId:"host-1",sequence:1,status:"running",progress:50,observedAt:AFTER,observation:null,errorCode:null}));assert.ok(queue.poll("host-1").command);db.close();const resumed="2026-09-29T10:00:31.000Z";db=openControllerDatabase(path);stores=createJobStores(db,{now:()=>resumed});queue=new AgentCommandStore(db,()=>resumed,30_000,stores);dispatcher=new CommandDispatcher(stores,queue,()=>resumed);const replay=dispatcher.dispatch(request);assert.ok(replay.ok);if(replay.ok)assert.equal(replay.state,"running");assert.ok(queue.poll("host-1").command);db.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test("bounded long poll releases promptly when running work is requeued",async()=>{const x=setup();try{const leased=x.queue.poll("host-1");assert.ok(leased.command);const initial=x.queue.poll("host-1");const started=Date.now();setTimeout(()=>{x.queue.complete("host-1",{requestId:"request-1",jobId:"job-1",hostId:"host-1",sequence:1,status:"running",progress:50,observedAt:AFTER,observation:null,errorCode:null});},20);const result=await x.service.wait("host-1",initial,200);assert.ok(result.command);assert.ok(Date.now()-started>=15);assert.ok(Date.now()-started<200);}finally{x.db.close();}});
