import assert from "node:assert/strict";
import { createHash, generateKeyPairSync, sign, verify } from "node:crypto";
import test from "node:test";
import { artifactManifestPayload, commandAuthorizationDigest, createArtifactCacheRegistry, createArtifactStage, parseCommandRequest, transitionArtifactStage, type ArtifactAuthenticator } from "@lan-model-manager/core";
import { openControllerDatabase } from "./database.js";
import { ArtifactDownloadBroker, VerifiedRemoteArtifactInstallController } from "./artifact-delivery.js";

const NOW="2026-09-29T16:00:00.000Z",DATA=Buffer.from("small verified artifact\n"),keys=generateKeyPairSync("ec",{namedCurve:"prime256v1"});
function fixture(){const base:any={schemaVersion:1,artifactId:"artifact-1",modelId:"model-1",revision:"rev-1",format:"gguf",sizeBytes:DATA.length,digest:{algorithm:"sha256",value:createHash("sha256").update(DATA).digest("hex")},provenance:{kind:"approved-source",sourceId:"approved-1",sourceRevision:"source-rev-1",observedAt:NOW},issuedAt:NOW,expiresAt:"2026-09-29T16:10:00.000Z",signerId:"controller-1",signature:{algorithm:"ecdsa-p256-sha256",value:"A".repeat(86)}};const payload=artifactManifestPayload(base)!;base.signature.value=sign("sha256",payload,keys.privateKey).toString("base64url");return base;}
const auth:ArtifactAuthenticator={isSignerAuthorized:id=>id==="controller-1",verify:v=>verify("sha256",v.payload,keys.publicKey,v.signature)};
function verified(manifest:any){let stage=createArtifactStage(manifest,auth,"stage-1",NOW)!;stage=transitionArtifactStage(stage,{type:"append",bytes:DATA.length,at:NOW})!;return transitionArtifactStage(stage,{type:"verify",digest:manifest.digest.value,at:NOW})!;}

test("verified approved artifact issues one bounded opaque grant and protects its cache lease",()=>{const db=openControllerDatabase(":memory:"),cache=createArtifactCacheRegistry(),manifest=fixture();cache.register({artifactId:"artifact-1",modelId:"model-1",sizeBytes:DATA.length,managedTemporary:true,pinned:false,lastUsedAt:NOW});const broker=new ArtifactDownloadBroker({db,certificates:{} as never,authenticator:auth,cache,clock:()=>NOW,random:()=>Buffer.alloc(32,7),source:{async *read(){yield DATA;}}});try{const grant=broker.issue({manifest,stage:verified(manifest),hostId:"host-1"});assert.ok(grant);assert.equal(grant.ticket,"07".repeat(32));assert.equal(cache.snapshot("artifact-1").activeLeases,1);assert.throws(()=>cache.beginEviction("artifact-1"));const params=broker.installParams(grant,"ollama-1","acme/model:latest");assert.ok(params);const command:any={requestId:"request-1",jobId:"job-1",hostId:"host-1",operation:"install",idempotencyKey:"idem-1",sequence:1,deadline:"2026-09-29T16:05:00.000Z",capability:{operation:"artifact-install",targetKind:"model",targetId:"model-1",hostId:"host-1",modelId:"model-1",expiresAt:"2026-09-29T16:05:00.000Z"},params};command.capability.requestDigest=commandAuthorizationDigest(command);assert.ok(parseCommandRequest(command).ok);assert.equal(JSON.stringify(command).includes("url"),false);assert.equal(JSON.stringify(command).includes("path"),false);assert.equal(broker.revoke(grant.ticket),true);assert.equal(broker.revoke(grant.ticket),false);assert.equal(cache.snapshot("artifact-1").activeLeases,0);cache.beginEviction("artifact-1");}finally{db.close();}});

test("remote install controller dispatches only exact policy-bound install params and revokes divergence",()=>{const db=openControllerDatabase(":memory:"),cache=createArtifactCacheRegistry(),manifest=fixture();cache.register({artifactId:"artifact-1",modelId:"model-1",sizeBytes:DATA.length,managedTemporary:true,pinned:false,lastUsedAt:NOW});const broker=new ArtifactDownloadBroker({db,certificates:{} as never,authenticator:auth,cache,clock:()=>NOW,random:()=>Buffer.alloc(32,6),source:{async*read(){yield DATA;}}});let calls=0;const controller=new VerifiedRemoteArtifactInstallController(broker,{execute:()=>{calls++;return{ok:true,state:"accepted",observation:null}},cancel:()=>({ok:true,state:"cancelled",observation:null})} as never),prepared=controller.prepare({manifest,stage:verified(manifest),hostId:"host-1",providerId:"ollama-1",model:"model:latest"});assert.ok(prepared);const execution:any={intent:{hostId:"host-1"},request:{operation:"install",hostId:"host-1",params:prepared.params}};assert.equal(controller.dispatch(prepared,execution).ok,true);assert.equal(calls,1);const denied=controller.dispatch(prepared,{...execution,request:{...execution.request,params:{...prepared.params,model:"other:latest"}}});assert.equal(denied.ok,false);assert.equal(calls,1);assert.equal(cache.snapshot("artifact-1").activeLeases,0);db.close();});

test("grant creation rejects unverified, wrong-host grammar, expired, and arbitrary egress/path command surfaces",()=>{const db=openControllerDatabase(":memory:"),cache=createArtifactCacheRegistry(),manifest=fixture(),stage=verified(manifest);cache.register({artifactId:"artifact-1",modelId:"model-1",sizeBytes:DATA.length,managedTemporary:true,pinned:false,lastUsedAt:NOW});const broker=new ArtifactDownloadBroker({db,certificates:{} as never,authenticator:auth,cache,clock:()=>NOW,random:()=>Buffer.alloc(32,8),source:{async *read(){yield DATA;}}});try{assert.equal(broker.issue({manifest,stage:{...stage,status:"received",computedDigest:null,verifiedAt:null},hostId:"host-1"}),null);assert.equal(broker.issue({manifest,stage,hostId:"../host"}),null);const grant=broker.issue({manifest,stage,hostId:"host-1"});assert.ok(grant);for(const addition of [{url:"https://evil.test/x"},{path:"../../escape"},{headers:{authorization:"secret"}}]){const params:any={...broker.installParams(grant,"ollama-1","model:latest"),...addition},command:any={requestId:"request-2",jobId:"job-2",hostId:"host-1",operation:"install",idempotencyKey:"idem-2",sequence:1,deadline:"2026-09-29T16:05:00.000Z",capability:{operation:"artifact-install",targetKind:"model",targetId:"model-1",hostId:"host-1",modelId:"model-1",expiresAt:"2026-09-29T16:05:00.000Z"},params};command.capability.requestDigest=commandAuthorizationDigest(command);assert.equal(parseCommandRequest(command).ok,false);}broker.revoke(grant.ticket);}finally{db.close();}});
