import test from"node:test";import assert from"node:assert/strict";import{createHash,generateKeyPairSync,sign,verify}from"node:crypto";import{artifactManifestPayload,type ArtifactAuthenticator,type ArtifactManifest,type ArtifactStage}from"@lan-model-manager/core";import{ArtifactAcquisitionCoordinator}from"./artifact-acquisition.js";
const NOW="2026-09-28T12:00:00.000Z",data=Buffer.from("abcdefghij"),keys=generateKeyPairSync("ec",{namedCurve:"prime256v1"});function manifest(overrides:Record<string,unknown>={}):ArtifactManifest{const base={schemaVersion:1 as const,artifactId:"artifact-1",modelId:"acme/model",revision:"rev-1",format:"gguf" as const,sizeBytes:10,digest:{algorithm:"sha256" as const,value:createHash("sha256").update(data).digest("hex")},provenance:{kind:"approved-source" as const,sourceId:"catalog-1",sourceRevision:"source-rev",observedAt:NOW as never},issuedAt:NOW as never,expiresAt:"2026-09-28T13:00:00.000Z" as never,signerId:"controller-1",signature:{algorithm:"ecdsa-p256-sha256" as const,value:"A".repeat(86)},...overrides},signature=sign("sha256",artifactManifestPayload(base)!,keys.privateKey).toString("base64url");return{...base,signature:{algorithm:"ecdsa-p256-sha256",value:signature}}as unknown as ArtifactManifest;}const auth:ArtifactAuthenticator={isSignerAuthorized:id=>id==="controller-1",verify:value=>verify("sha256",value.payload,keys.publicKey,value.signature)};
function setup(options:{body?:Buffer;status?:number;length?:number|null;type?:string;authorize?:boolean;failWrite?:boolean}={}){const writes:number[]=[],stages:ArtifactStage[]=[];let fetches=0;const body=options.body??data,coordinator=new ArtifactAcquisitionCoordinator({authenticator:auth,clock:()=>"2026-09-28T12:00:01.000Z",authorize:()=>options.authorize??true,sourceFor:id=>id==="catalog-1"?{async fetch(input){fetches++;assert.equal(input.sourceId,"catalog-1");async function* stream(){yield body.subarray(0,4);yield body.subarray(4);}return{status:options.status??200,contentLength:options.length===undefined?body.length:options.length,contentType:options.type??"application/octet-stream",body:stream()};}}:null,sink:{async write(input){writes.push(input.offset);return !(options.failWrite??false);}},stages:{save:stage=>stages.push(stage)}});return{coordinator,writes,stages,fetches:()=>fetches};}
test("approved source streams bounded content through verified staging",async()=>{const x=setup(),stage=await x.coordinator.acquire(manifest(),"stage-1",new AbortController().signal);assert.equal(stage?.status,"verified");assert.equal(stage?.computedDigest,createHash("sha256").update(data).digest("hex"));assert.deepEqual(x.writes,[0,4]);assert.deepEqual(x.stages.map(value=>value.status),["allocated","receiving","received","verified"]);});
test("unauthorized source and tampered manifest never fetch",async()=>{const denied=setup({authorize:false});assert.equal(await denied.coordinator.acquire(manifest(),"stage-1",new AbortController().signal),null);assert.equal(denied.fetches(),0);const tampered=setup();assert.equal(await tampered.coordinator.acquire({...manifest(),sizeBytes:11},"stage-1",new AbortController().signal),null);assert.equal(tampered.fetches(),0);});
test("wrong response metadata short bodies and sink failures quarantine",async()=>{for(const options of [{status:206},{type:"text/plain"},{length:9},{body:Buffer.from("short")},{failWrite:true}]){const x=setup(options),stage=await x.coordinator.acquire(manifest(),"stage-1",new AbortController().signal);assert.equal(stage?.status,"quarantined");assert.equal(stage?.quarantineCode,"acquisition-failed");}});
test("full digest mismatch quarantines with digest-mismatch",async()=>{const wrong=Buffer.from("ABCDEFGHIJ"),x=setup({body:wrong}),stage=await x.coordinator.acquire(manifest(),"stage-1",new AbortController().signal);assert.equal(stage?.status,"quarantined");assert.equal(stage?.quarantineCode,"digest-mismatch");});
test("cancellation stops acquisition without exposing source details",async()=>{const controller=new AbortController();controller.abort();const x=setup(),stage=await x.coordinator.acquire(manifest(),"stage-1",controller.signal);assert.equal(stage?.status,"quarantined");assert.equal(stage?.quarantineCode,"cancelled");assert.deepEqual(x.writes,[]);assert.equal(JSON.stringify(stage).includes("endpoint"),false);});
test("non-approved provenance is rejected before source lookup",async()=>{const x=setup(),value=manifest({provenance:{kind:"peer-transfer",sourceId:"peer-1",sourceRevision:null,observedAt:NOW}});assert.equal(await x.coordinator.acquire(value,"stage-1",new AbortController().signal),null);assert.equal(x.fetches(),0);});
