import{planCacheEviction,revalidateCacheEvictionPlan,type ArtifactCacheRegistry,type CacheCapacitySnapshot,type CacheEvictionPlan,type CacheQuotaPolicy}from"@lan-model-manager/core";
export interface CacheEvictionStorage{remove(artifactId:string,signal:AbortSignal):Promise<unknown>;restore(artifactId:string,receipt:unknown):Promise<void>;recover(artifactId:string):Promise<"present"|"removed">}
export interface CacheEvictionAudit{record(event:{readonly action:"eviction-planned"|"eviction-completed"|"eviction-rolled-back"|"eviction-recovered";readonly count:number;readonly outcome:"succeeded"|"failed"}):void}
export interface CachePressureObservation{readonly freeStorageBytes:number;readonly observedAt:string;readonly observationFresh:boolean}
export interface CacheEvictionCoordinatorOptions{readonly cache:ArtifactCacheRegistry;readonly storage:CacheEvictionStorage;readonly audit:CacheEvictionAudit;readonly clock:()=>string}
export type CacheEvictionRun={readonly ok:true;readonly plan:CacheEvictionPlan;readonly evicted:readonly string[]}|{readonly ok:false;readonly code:"ERR_EVICTION_PLAN"|"ERR_EVICTION_STALE"|"ERR_EVICTION_EXECUTION";readonly evicted:readonly string[]};
function done(plan:CacheEvictionPlan,evicted:readonly string[]):CacheEvictionRun{return Object.freeze({ok:true,plan,evicted:Object.freeze([...evicted])});}function failed(code:"ERR_EVICTION_PLAN"|"ERR_EVICTION_STALE"|"ERR_EVICTION_EXECUTION",evicted:readonly string[]):CacheEvictionRun{return Object.freeze({ok:false,code,evicted:Object.freeze([...evicted])});}
export class CacheEvictionCoordinator{constructor(private readonly options:CacheEvictionCoordinatorOptions){}async relieve(policy:CacheQuotaPolicy,observation:CachePressureObservation,incomingBytes:number,signal:AbortSignal):Promise<CacheEvictionRun>{const snapshot=this.snapshot(observation),now=this.now(),decision=planCacheEviction(policy,snapshot,incomingBytes,now);if(!decision.ok)return failed("ERR_EVICTION_PLAN",[]);const plan=decision.plan;this.audit("eviction-planned",plan.victims.length,"succeeded");if(plan.victims.length===0)return done(plan,[]);if(signal.aborted||!revalidateCacheEvictionPlan(plan,policy,this.snapshot(observation),this.now()))return failed("ERR_EVICTION_STALE",[]);const reserved:string[]=[];try{for(const id of plan.victims){this.options.cache.beginEviction(id);reserved.push(id);}}catch{for(const id of reserved)try{this.options.cache.cancelEviction(id);}catch{}return failed("ERR_EVICTION_STALE",[]);}const receipts=new Map<string,unknown>();try{for(const id of reserved){if(signal.aborted)throw new DOMException("Aborted","AbortError");receipts.set(id,await this.options.storage.remove(id,signal));}for(const id of reserved)this.options.cache.finishEviction(id);this.audit("eviction-completed",reserved.length,"succeeded");return done(plan,reserved);}catch{for(const[id,receipt]of[...receipts].reverse())try{await this.options.storage.restore(id,receipt);}catch{}for(const id of reserved)try{this.options.cache.cancelEviction(id);}catch{}this.audit("eviction-rolled-back",receipts.size,"failed");return failed("ERR_EVICTION_EXECUTION",[]);}}
 async recover():Promise<void>{for(const artifact of this.options.cache.list()){if(artifact.state!=="evicting")continue;try{const state=await this.options.storage.recover(artifact.artifactId);if(state==="removed")this.options.cache.finishEviction(artifact.artifactId);else this.options.cache.cancelEviction(artifact.artifactId);this.audit("eviction-recovered",1,"succeeded");}catch{try{this.options.cache.cancelEviction(artifact.artifactId);}catch{}this.audit("eviction-recovered",1,"failed");}}}
 private snapshot(observation:CachePressureObservation):CacheCapacitySnapshot{return{freeStorageBytes:observation.freeStorageBytes as never,observedAt:observation.observedAt as never,observationFresh:observation.observationFresh,artifacts:this.options.cache.list()};}private now(){const value=this.options.clock();if(typeof value!=="string"||Number.isNaN(Date.parse(value))||new Date(value).toISOString()!==value)throw new Error("ERR_EVICTION_CLOCK");return value;}private audit(action:"eviction-planned"|"eviction-completed"|"eviction-rolled-back"|"eviction-recovered",count:number,outcome:"succeeded"|"failed"){try{this.options.audit.record(Object.freeze({action,count,outcome}));}catch{/* eviction state remains authoritative */}}}
