import assert from "node:assert/strict";import test from "node:test";import { openControllerDatabase,CONTROLLER_MIGRATIONS } from "./database.js";import { CertificateRepository } from "./certificate-repository.js";import { createControllerRepositories } from "./repositories.js";import { FleetService } from "./fleet-service.js";import type { TransportSignedEnvelope } from "@lan-model-manager/core";
const NOW="2026-09-28T05:00:00.000Z",cert="-----BEGIN CERTIFICATE-----\nQQ==\n-----END CERTIFICATE-----\n",fp="a".repeat(64),serial="ABCD";function setup(){const db=openControllerDatabase(":memory:"),certs=new CertificateRepository(db);certs.insertCa({caId:"b".repeat(64),version:1,serial:"10",fingerprint:"b".repeat(64),certificatePem:cert,notBefore:"2026-01-01T00:00:00.000Z",notAfter:"2036-01-01T00:00:00.000Z",createdAt:"2026-01-01T00:00:00.000Z"});certs.insertHost({certificateId:fp,serial,fingerprint:fp,certificatePem:cert,caId:"b".repeat(64),caVersion:1,binding:{candidateId:"agent-1",address:"192.168.1.20",port:7443,protocolMajor:1,protocolMinor:0},spiffeUri:"spiffe://lanmodelmanager/host/agent-1",challengeId:"c".repeat(64),transcriptDigest:"d".repeat(64),notBefore:"2026-01-01T00:00:00.000Z",notAfter:"2027-01-01T00:00:00.000Z",status:"active",version:1,issuedAt:NOW,revokedAt:null});let env:TransportSignedEnvelope;const transport:any={accept(){return{ok:true,envelope:env}}};const repos=createControllerRepositories(db,{now:()=>NOW}),service=new FleetService(db,transport,certs,repos,{clock:()=>NOW});return{db,certs,repos,service,set(v:TransportSignedEnvelope){env=v}};}
function envelope(sequence:number,payload:any,type="transport.heartbeat"):TransportSignedEnvelope{return{protocolVersion:{major:1,minor:0},messageType:type as any,hostId:"agent-1" as any,requestId:`request-${sequence}` as any,sequence:sequence as any,sentAt:payload.observedAt,nonce:`nonce-${sequence}` as any,bodyDigest:"e".repeat(64) as any,certFingerprint:fp,certSerial:serial,signature:"f".repeat(128),payload};}
const provider=(observedAt=NOW)=>({providerId:"ollama-1",kind:"ollama",displayName:"Ollama",endpoint:"http://127.0.0.1:11434",health:"ready",version:"1.0.0",observedAt});const model=(observedAt=NOW)=>({modelId:"model-1",providerId:"ollama-1",displayName:"acme-model",artifactState:"installed",runtimeState:"loaded-idle",activeRequests:0,sizeBytes:1024,managedTemporary:false,pinned:false,capability:{tools:false,vision:false,reasoning:false,modalities:["text"],contextWindow:4096},observedAt});
test("authenticated heartbeat atomically registers and reconciles inventory",()=>{const c=setup();try{const payload={platform:"linux",protocolMinor:0,idle:true,observedAt:NOW,sequence:1,providers:[provider()],models:[model()]};c.set(envelope(1,payload));const result=c.service.ingest({},"192.168.1.20");assert.equal(result.ok,true);assert.equal(c.repos.hosts.get("agent-1")?.online,true);assert.equal(c.repos.providers.listByHost("agent-1").length,1);assert.equal(c.repos.models.listByHost("agent-1").length,1);const row=c.db.prepare("SELECT * FROM fleet_liveness").get() as any;assert.equal(row.last_sequence,1);assert.equal(row.idle,1);}finally{c.db.close();}});
test("stale/equal and wrong-address heartbeats fail without mutation",()=>{const c=setup();try{const p={platform:"linux",protocolMinor:0,idle:true,observedAt:NOW,sequence:1,providers:[provider()],models:[model()]};c.set(envelope(1,p));assert.equal(c.service.ingest({},"192.168.1.21").ok,false);assert.equal(c.service.ingest({},"192.168.1.20").ok,true);c.set(envelope(2,p));const result=c.service.ingest({},"192.168.1.20");assert.equal(result.ok,false);assert.equal(c.repos.hosts.list().length,1);}finally{c.db.close();}});
test("revoked certificate and mismatched payload sequence are denied",()=>{const c=setup();try{const p={platform:"linux",protocolMinor:0,idle:true,observedAt:NOW,sequence:2,providers:[],models:[]};c.set(envelope(1,p));assert.equal(c.service.ingest({},"192.168.1.20").ok,false);c.certs.revoke(fp,NOW);c.set(envelope(1,{...p,sequence:1}));const denied=c.service.ingest({},"192.168.1.20");assert.equal(denied.ok,false);if(!denied.ok)assert.equal(denied.error,"ERR_HOST_REVOKED");}finally{c.db.close();}});
test("newer empty inventory removes older providers and models",()=>{const c=setup();try{const p={platform:"linux",protocolMinor:0,idle:true,observedAt:NOW,sequence:1,providers:[provider()],models:[model()]};c.set(envelope(1,p));assert.equal(c.service.ingest({},"192.168.1.20").ok,true);const later="2026-09-28T05:01:00.000Z";c.set(envelope(2,{...p,observedAt:later,sequence:2,providers:[],models:[]}));assert.equal(c.service.ingest({},"192.168.1.20").ok,true);assert.equal(c.repos.providers.listByHost("agent-1").length,0);assert.equal(c.repos.models.listByHost("agent-1").length,0);}finally{c.db.close();}});
test("migration9 records liveness",()=>{assert.ok(CONTROLLER_MIGRATIONS.length>=9);assert.equal(CONTROLLER_MIGRATIONS[8]!.name,"private-plan-fleet-liveness-v1");});
