import { commandAuthorizationDigest } from "@lan-model-manager/core";
import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { X509Certificate, createHash } from "node:crypto";
import { once } from "node:events";
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createServer } from "node:https";
import { createServer as createHttpServer } from "node:http";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { OpenSslCertificateEngine } from "./certificate-adapter.js";
import { CertificateRepository } from "./certificate-repository.js";
import { openControllerDatabase } from "./database.js";
import { createFleetAgentHttpHandler } from "./fleet-agent-http.js";
import { FleetService } from "./fleet-service.js";
import { createControllerRepositories } from "./repositories.js";
import { ControllerTransport } from "./transport/controller-transport.js";
import { PersistentReplayStore } from "./transport/replay-store.js";
import { buildTransportNativeVerifier } from "./transport/transport-signer.js";
import { buildTransportNativeSigner } from "./transport/transport-signer.js";
import { AgentCommandService, AgentCommandStore } from "./agent-command-channel.js";
import { CommandDispatcher } from "./command-dispatch.js";
import { createJobStores } from "./jobs-store.js";

function serverCertificate(root:string, caDir:string){const d=join(root,"server");mkdirSync(d,{mode:0o700});execFileSync("openssl",["genpkey","-algorithm","EC","-pkeyopt","ec_paramgen_curve:P-256","-out","key.pem"],{cwd:d,stdio:"ignore"});execFileSync("openssl",["req","-new","-key","key.pem","-subj","/CN=127.0.0.1","-addext","subjectAltName=IP:127.0.0.1","-out","request.pem"],{cwd:d,stdio:"ignore"});writeFileSync(join(d,"ext"),"basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=serverAuth\nsubjectAltName=IP:127.0.0.1\n");execFileSync("openssl",["x509","-req","-in","request.pem","-CA",join(caDir,"ca-cert.pem"),"-CAkey",join(caDir,"ca-key.pem"),"-set_serial","0x2001","-days","1","-extfile","ext","-out","cert.pem"],{cwd:d,stdio:"ignore"});return{key:readFileSync(join(d,"key.pem")),cert:readFileSync(join(d,"cert.pem"))};}

test("Go enrollment identity drives real TypeScript mTLS hello, heartbeat inventory, and restart sequence",{timeout:30_000},async()=>{
  execFileSync("go",["version"],{stdio:"ignore"});execFileSync("openssl",["version"],{stdio:"ignore"});
  const root=mkdtempSync(join(tmpdir(),"lanmm-fleet-cross-")),caDir=join(root,"ca"),agentDir=join(root,"agent");mkdirSync(agentDir,{mode:0o700});chmodSync(agentDir,0o700);
  const db=openControllerDatabase(":memory:");let server:ReturnType<typeof createServer>|undefined,fake:ReturnType<typeof createHttpServer>|undefined;let ollamaCalls=0;
  try{
    fake=createHttpServer((req,res)=>{res.setHeader("content-type","application/json");if(req.method==="GET"&&req.url==="/api/tags"){res.end(JSON.stringify({models:[{name:"qwen:latest",model:"qwen:latest",modified_at:"2026-09-29T10:00:00Z",size:123,digest:"a".repeat(64),details:{parent_model:"",format:"gguf",family:"qwen",families:["qwen"],parameter_size:"1B",quantization_level:"Q4"}}]}));return;}if(req.method==="GET"&&req.url==="/api/ps"){res.end(JSON.stringify({models:[{name:"qwen:latest",model:"qwen:latest",size:123,digest:"a".repeat(64),details:{parent_model:"",format:"gguf",family:"qwen",families:["qwen"],parameter_size:"1B",quantization_level:"Q4"},expires_at:"2026-09-29T12:00:00Z",size_vram:0,context_length:8192}]}));return;}if(req.method==="POST"&&req.url==="/api/chat"){ollamaCalls++;let body="";req.setEncoding("utf8");req.on("data",chunk=>body+=chunk);req.on("end",()=>{const value=JSON.parse(body);assert.equal(value.model,"qwen:latest");assert.equal(value.stream,false);assert.deepEqual(value.messages,[{role:"user",content:"hello over mtls"}]);res.end(JSON.stringify({model:"qwen:latest",created_at:"2026-09-29T10:00:01Z",message:{role:"assistant",content:"hello from ollama"+"x".repeat(40*1024)},done:true,done_reason:"stop",total_duration:1,load_duration:1,prompt_eval_count:4,prompt_eval_duration:1,eval_count:3,eval_duration:1}));});return;}res.writeHead(404);res.end();});fake.listen(0,"127.0.0.1");await once(fake,"listening");const fakeAddress=fake.address();assert.ok(fakeAddress&&typeof fakeAddress==="object");
    const engine=new OpenSslCertificateEngine(),now=new Date().toISOString(),ca=engine.initializeCa({directory:caDir,now});
    execFileSync("openssl",["genpkey","-algorithm","EC","-pkeyopt","ec_paramgen_curve:P-256","-out",join(agentDir,"host-key.pem")],{stdio:"ignore"});chmodSync(join(agentDir,"host-key.pem"),0o600);
    execFileSync("openssl",["req","-new","-key",join(agentDir,"host-key.pem"),"-subj","/CN=agent-1","-addext","subjectAltName=IP:127.0.0.1,URI:spiffe://lanmodelmanager/host/agent-1","-out",join(agentDir,"request.pem")],{stdio:"ignore"});
    const binding={candidateId:"agent-1",address:"127.0.0.1",port:7443,protocolMajor:1,protocolMinor:0},issued=engine.issueHost({directory:caDir,csrPem:readFileSync(join(agentDir,"request.pem"),"utf8"),binding,serial:"1234ABCD",now});
    const certificates=new CertificateRepository(db);certificates.insertCa(ca);certificates.insertHost({certificateId:issued.fingerprint,serial:issued.serial,fingerprint:issued.fingerprint,certificatePem:issued.certificatePem,caId:ca.caId,caVersion:1,binding,spiffeUri:"spiffe://lanmodelmanager/host/agent-1",challengeId:"c".repeat(64),transcriptDigest:"d".repeat(64),notBefore:issued.notBefore,notAfter:issued.notAfter,status:"active",version:1,issuedAt:now,revokedAt:null});
    const leaf=new X509Certificate(issued.certificatePem),parsed:any={fingerprint:issued.fingerprint,serial:issued.serial,commonName:"agent-1",address:"127.0.0.1",spiffe:"spiffe://lanmodelmanager/host/agent-1",notBefore:issued.notBefore,notAfter:issued.notAfter,issuerFingerprint:ca.fingerprint,isCa:false};
    const verifier=buildTransportNativeVerifier(leaf.publicKey.export({type:"spki",format:"pem"}).toString(),parsed);assert.equal(verifier.ok,true);if(!verifier.ok)return;
    const transport=new ControllerTransport({certificateRepository:certificates,replayStore:new PersistentReplayStore(db),verifier:()=>verifier.value});const transportErrors:string[]=[];const traced={accept(input:unknown){const value=transport.accept(input);if(!value.ok)transportErrors.push(value.error);return value}};const repos=createControllerRepositories(db),fleet=new FleetService(db,traced as never,certificates,repos);const tls=serverCertificate(root,caDir),serverLeaf=new X509Certificate(tls.cert),serverParsed:any={fingerprint:createHash("sha256").update(serverLeaf.raw).digest("hex"),serial:serverLeaf.serialNumber.replace(/^0+/,"")||"0",commonName:"controller",address:"127.0.0.1",spiffe:"spiffe://lanmodelmanager/controller",notBefore:new Date(serverLeaf.validFrom).toISOString(),notAfter:new Date(serverLeaf.validTo).toISOString(),issuerFingerprint:ca.fingerprint,isCa:false},serverSigner=buildTransportNativeSigner(tls.key.toString(),serverParsed);assert.ok(serverSigner.ok);if(!serverSigner.ok)return;const stores=createJobStores(db),queue=new AgentCommandStore(db),commands=new AgentCommandService(traced as never,certificates,queue,stores,serverSigner.value),dispatcher=new CommandDispatcher(stores,queue),issuedAt=new Date(),deadline=new Date(issuedAt.getTime()+120_000).toISOString(),capExpiry=new Date(issuedAt.getTime()+180_000).toISOString(),modelId=`ollama-${createHash("sha256").update(`ollama-1\0qwen:latest\0${"a".repeat(64)}`).digest("hex")}`,commandRequest={requestId:"command-request-1",jobId:"command-job-1",hostId:"agent-1",operation:"inference.chat",idempotencyKey:"command-idem-1",sequence:1,deadline,capability:{operation:"model-inference",targetKind:"model",targetId:modelId,hostId:"agent-1",modelId,requestDigest:"0".repeat(64),expiresAt:capExpiry},params:{providerId:"ollama-1",modelId,model:"qwen:latest",requestId:"command-request-1",maxRequestBytes:524288,maxResponseBytes:262144,messages:[{role:"user",contentBase64:Buffer.from("hello over mtls").toString("base64")}],temperatureMilli:250,maxTokens:16}};commandRequest.capability.requestDigest=commandAuthorizationDigest(commandRequest as never);assert.equal(dispatcher.dispatch(commandRequest).ok,true);const handler=createFleetAgentHttpHandler({fleet,certificates,commands});const responses:string[]=[];
    server=createServer({key:tls.key,cert:tls.cert,ca:ca.certificatePem,minVersion:"TLSv1.3",maxVersion:"TLSv1.3",requestCert:true,rejectUnauthorized:true},(req,res)=>{const end=res.end.bind(res);(res as any).end=(chunk?:any)=>{responses.push(String(chunk??""));return end(chunk)};handler(req,res)});server.listen(0,"127.0.0.1");await once(server,"listening");const address=server.address();assert.ok(address&&typeof address==="object");
    writeFileSync(join(agentDir,"enrollment.json"),JSON.stringify({controllerUrl:`https://127.0.0.1:${address.port}`,pinnedCaFingerprintSha256:ca.fingerprint,challengeId:"c".repeat(64),binding,certificatePem:issued.certificatePem,caPem:ca.certificatePem,enrolledAt:now})+"\n",{mode:0o600});
    const runGo=async(mode:"ok"|"reject"|"stale"="ok")=>{const child=spawn("go",["test","./internal/fleet","-run","^TestCrossLanguageFleetHelper$","-count=1","-v"],{cwd:join(resolve(import.meta.dirname,"../../.."),"agents/host-agent"),env:{...process.env,LANMM_CROSS_FLEET_CERT_DIR:agentDir,...(mode==="ok"?{LANMM_CROSS_FLEET_COMMAND:"1",LANMM_CROSS_FLEET_INFERENCE_ENDPOINT:`http://127.0.0.1:${fakeAddress.port}`}:{ }),...(mode!=="ok"?{LANMM_CROSS_FLEET_EXPECT_REJECT:"1"}:{}),...(mode==="stale"?{LANMM_CROSS_FLEET_STALE:"1"}:{})}});let output="",errors="";child.stdout.setEncoding("utf8");child.stderr.setEncoding("utf8");child.stdout.on("data",v=>output+=v);child.stderr.on("data",v=>errors+=v);const code=await new Promise<number|null>((done,rejectChild)=>{child.once("error",rejectChild);child.once("close",done)});assert.equal(code,0,output+errors+JSON.stringify({responses,transportErrors}));return output};
    const output=await runGo();const match=/LANMM_CROSS_FLEET_RESULT=(\{[^\n]+\})/.exec(output);assert.ok(match,output);assert.deepEqual(JSON.parse(match[1]!),{heartbeat:2,hello:1,resumed:3});
    assert.match(output,/LANMM_CROSS_COMMAND_RESULT=succeeded/);assert.match(output,/LANMM_CROSS_COMMAND_REPLAY=succeeded/);assert.match(output,/LANMM_CROSS_COMMAND_RESULT=succeeded:bytes=4\d{4}/);assert.doesNotMatch(output,/127\.0\.0\.1|api\/chat/);assert.equal(ollamaCalls,1);assert.equal(stores.jobs.get("command-job-1")?.state,"succeeded");assert.equal(repos.providers.listByHost("agent-1").length,1);assert.equal(repos.models.listByHost("agent-1").length,1);assert.equal((db.prepare("SELECT last_sequence FROM fleet_liveness WHERE host_id='agent-1'").get() as any).last_sequence,3);
    assert.match(await runGo("stale"),/LANMM_CROSS_FLEET_REJECTED=true/);assert.ok(responses.some(value=>value.includes("ERR_OBSERVATION_STALE")));writeFileSync(join(agentDir,"fleet-sequence"),"3\n",{mode:0o600});assert.match(await runGo("reject"),/LANMM_CROSS_FLEET_REJECTED=true/);assert.ok(transportErrors.some(value=>value.includes("REPLAY")));assert.equal((db.prepare("SELECT last_sequence FROM fleet_liveness WHERE host_id='agent-1'").get() as any).last_sequence,3);
    assert.equal(certificates.revoke(issued.fingerprint,new Date().toISOString()),true);assert.match(await runGo("reject"),/LANMM_CROSS_FLEET_REJECTED=true/);assert.equal((db.prepare("SELECT last_sequence FROM fleet_liveness WHERE host_id='agent-1'").get() as any).last_sequence,3);
  }finally{if(server)await new Promise<void>(r=>server!.close(()=>r()));if(fake)await new Promise<void>(r=>fake!.close(()=>r()));db.close();rmSync(root,{recursive:true,force:true});}
});
