import type { DatabaseSync } from "node:sqlite";import type { SessionMetadata } from "./session-types.js";import type { ControllerRepositories } from "./repositories.js";
export type FleetHealth="active"|"degraded"|"offline"|"revoked";export type FleetQueryError="ERR_FLEET_UNAUTHORIZED"|"ERR_FLEET_INPUT"|"ERR_FLEET_NOT_FOUND"|"ERR_FLEET_DATABASE";
export interface PublicHost{readonly hostId:string;readonly displayName:string;readonly platform:"linux"|"darwin"|"windows";readonly health:FleetHealth;readonly observedAt:string;readonly idle:boolean;readonly providerCount:number;readonly modelCount:number}
export interface PublicProvider{readonly providerId:string;readonly hostId:string;readonly kind:"ollama"|"lmstudio";readonly health:"ready"|"degraded"|"unavailable"|"failed";readonly version:string;readonly versionKnown:boolean;readonly observedAt:string}
export interface PublicModel{readonly modelId:string;readonly providerId:string;readonly hostId:string;readonly canonicalName:string;readonly state:"available"|"installed"|"running";readonly type:"llm"|"embedding"|"unknown";readonly digestKnown:boolean;readonly observedAt:string}
export interface FleetCounts{readonly hosts:number;readonly active:number;readonly degraded:number;readonly offline:number;readonly revoked:number;readonly providers:number;readonly models:number}
export interface FleetPage<T>{readonly items:readonly T[];readonly nextCursor:string|null;readonly counts:FleetCounts}export type FleetQueryResult<T>={readonly ok:true;readonly value:T}|{readonly ok:false;readonly error:FleetQueryError};
export interface FleetQueryOptions{readonly clock?:()=>string;readonly degradedAfterMs?:number;readonly offlineAfterMs?:number;readonly maxLimit?:number}
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/,TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;const frozen=<T>(v:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),v)) as T;const error=<T>(e:FleetQueryError):FleetQueryResult<T>=>frozen({ok:false,error:e});
function authorized(v:unknown,now:string):boolean{try{if(typeof v!=="object"||v===null||Array.isArray(v))return false;const outer=Object.getOwnPropertyDescriptors(v),outerKeys=Reflect.ownKeys(v);if(outerKeys.length!==2||!outer.ok||!("value" in outer.ok)||outer.ok.value!==true||!outer.session||!("value" in outer.session))return false;const s=outer.session.value;if(typeof s!=="object"||s===null||Array.isArray(s))return false;const keys=["ownerId","credentialVersion","sessionVersion","createdAt","lastSeenAt","absoluteExpiresAt","idleExpiresAt","revokedAt"],own=Reflect.ownKeys(s),d=Object.getOwnPropertyDescriptors(s);return own.length===keys.length&&own.every(k=>typeof k==="string"&&keys.includes(k))&&keys.every(k=>d[k]&&"value" in d[k])&&typeof d.ownerId!.value==="string"&&ID.test(d.ownerId!.value)&&Number.isSafeInteger(d.credentialVersion!.value)&&d.credentialVersion!.value>0&&Number.isSafeInteger(d.sessionVersion!.value)&&d.sessionVersion!.value>0&&d.revokedAt!.value===null&&typeof d.absoluteExpiresAt!.value==="string"&&typeof d.idleExpiresAt!.value==="string"&&Date.parse(now)<Date.parse(d.absoluteExpiresAt!.value)&&Date.parse(now)<Date.parse(d.idleExpiresAt!.value);}catch{return false;}}
function query(input:unknown,max:number):{limit:number;cursor:string;platform:string|null;health:FleetHealth|null}|null{try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const allowed=["limit","cursor","platform","health"],own=Reflect.ownKeys(input),d=Object.getOwnPropertyDescriptors(input);if(own.some(k=>typeof k!=="string"||!allowed.includes(k))||own.some(k=>typeof k==="string"&&(!d[k]||!("value" in d[k]))))return null;const limit=d.limit?.value??50,cursor=d.cursor?.value??"",platform=d.platform?.value??null,health=d.health?.value??null;if(!Number.isSafeInteger(limit)||limit<1||limit>max||typeof cursor!=="string"||(cursor!==""&&!ID.test(cursor))||(platform!==null&&!(["linux","darwin","windows"] as unknown[]).includes(platform))||(health!==null&&!(["active","degraded","offline","revoked"] as unknown[]).includes(health)))return null;return{limit,cursor,platform,health};}catch{return null;}}
export class FleetQueryService{private readonly clock:()=>string;private readonly degraded:number;private readonly offline:number;private readonly max:number;constructor(private readonly db:DatabaseSync,private readonly repositories:ControllerRepositories,options:FleetQueryOptions={}){this.clock=options.clock??(()=>new Date().toISOString());this.degraded=options.degradedAfterMs??60_000;this.offline=options.offlineAfterMs??120_000;this.max=options.maxLimit??200;if(!Number.isSafeInteger(this.degraded)||this.degraded<1||!Number.isSafeInteger(this.offline)||this.offline<=this.degraded||!Number.isSafeInteger(this.max)||this.max<1||this.max>1000)throw new Error("ERR_FLEET_INPUT");}
 refresh(session:unknown):FleetQueryResult<FleetCounts>{const now=this.clock();if(!authorized(session,now))return error("ERR_FLEET_UNAUTHORIZED");try{this.db.exec("BEGIN IMMEDIATE");const rows=this.db.prepare("SELECT l.host_id,l.last_observed_at,c.status AS cert_status FROM fleet_liveness l LEFT JOIN host_certificates c ON c.fingerprint=l.certificate_fingerprint").all() as Array<{host_id:string;last_observed_at:string;cert_status:string|null}>;for(const row of rows){const health=this.health(row.last_observed_at,row.cert_status,now);this.db.prepare("UPDATE fleet_liveness SET health=?,health_updated_at=?,revoked_at=CASE WHEN ?='revoked' THEN COALESCE(revoked_at,?) ELSE revoked_at END WHERE host_id=?").run(health,now,health,now,row.host_id);}this.db.exec("COMMIT");return{ok:true,value:this.counts(now)};}catch{try{this.db.exec("ROLLBACK")}catch{}return error("ERR_FLEET_DATABASE");}}
 listHosts(raw:unknown,session:unknown):FleetQueryResult<FleetPage<PublicHost>>{const now=this.clock();if(!authorized(session,now))return error("ERR_FLEET_UNAUTHORIZED");const q=query(raw,this.max);if(!q)return error("ERR_FLEET_INPUT");try{const providers=this.countBy("providers"),models=this.countBy("models"),live=this.liveness();let hosts=this.repositories.hosts.list().map(h=>{const l=live.get(h.hostId),health=l?this.health(l.observedAt,l.certStatus,now):"offline";return frozen<PublicHost>({hostId:h.hostId,displayName:h.displayName,platform:h.platform,health,observedAt:l?.observedAt??h.observedAt,idle:l?.idle??true,providerCount:providers.get(h.hostId)??0,modelCount:models.get(h.hostId)??0});}).filter(h=>h.hostId>q.cursor&&(!q.platform||h.platform===q.platform)&&(!q.health||h.health===q.health)).sort((a,b)=>a.hostId.localeCompare(b.hostId));const hasMore=hosts.length>q.limit;hosts=hosts.slice(0,q.limit);return{ok:true,value:frozen({items:Object.freeze(hosts),nextCursor:hasMore?hosts.at(-1)!.hostId:null,counts:this.counts(now)})};}catch{return error("ERR_FLEET_DATABASE");}}
 getHost(id:unknown,session:unknown):FleetQueryResult<PublicHost>{const now=this.clock();if(!authorized(session,now))return error("ERR_FLEET_UNAUTHORIZED");if(typeof id!=="string"||!ID.test(id))return error("ERR_FLEET_INPUT");try{const host=this.repositories.hosts.get(id);if(!host)return error("ERR_FLEET_NOT_FOUND");const live=this.liveness().get(id),health=live?this.health(live.observedAt,live.certStatus,now):"offline";return{ok:true,value:frozen({hostId:host.hostId,displayName:host.displayName,platform:host.platform,health,observedAt:live?.observedAt??host.observedAt,idle:live?.idle??true,providerCount:this.repositories.providers.listByHost(id).length,modelCount:this.repositories.models.listByHost(id).length})};}catch{return error("ERR_FLEET_DATABASE");}}
 listProviders(hostId:unknown,session:unknown):FleetQueryResult<readonly PublicProvider[]>{const now=this.clock();if(!authorized(session,now))return error("ERR_FLEET_UNAUTHORIZED");if(typeof hostId!=="string"||!ID.test(hostId))return error("ERR_FLEET_INPUT");try{return{ok:true,value:Object.freeze(this.repositories.providers.listByHost(hostId).map(p=>frozen<PublicProvider>({providerId:p.providerId,hostId:p.hostId,kind:p.kind,health:p.health,version:p.version,versionKnown:p.versionKnown,observedAt:p.observedAt})))};}catch{return error("ERR_FLEET_DATABASE");}}
 listModels(hostId:unknown,session:unknown):FleetQueryResult<readonly PublicModel[]>{const now=this.clock();if(!authorized(session,now))return error("ERR_FLEET_UNAUTHORIZED");if(typeof hostId!=="string"||!ID.test(hostId))return error("ERR_FLEET_INPUT");try{return{ok:true,value:Object.freeze(this.repositories.models.listByHost(hostId).map(m=>frozen<PublicModel>({modelId:m.modelId,providerId:m.providerId,hostId:m.hostId,canonicalName:m.canonicalName,state:m.state,type:m.type,digestKnown:m.digestKnown,observedAt:m.observedAt})))};}catch{return error("ERR_FLEET_DATABASE");}}
 summary(session:unknown):FleetQueryResult<FleetCounts>{const now=this.clock();return authorized(session,now)?{ok:true,value:this.counts(now)}:error("ERR_FLEET_UNAUTHORIZED");}
 private health(observed:string,cert:string|null,now:string):FleetHealth{if(cert==="revoked")return"revoked";const age=Math.max(0,Date.parse(now)-Date.parse(observed));return age>=this.offline?"offline":age>=this.degraded?"degraded":"active";}
 private liveness(){const map=new Map<string,{observedAt:string;idle:boolean;certStatus:string|null}>();for(const r of this.db.prepare("SELECT l.host_id,l.last_observed_at,l.idle,c.status cert_status FROM fleet_liveness l LEFT JOIN host_certificates c ON c.fingerprint=l.certificate_fingerprint").all() as Array<{host_id:string;last_observed_at:string;idle:number;cert_status:string|null}>)map.set(r.host_id,{observedAt:r.last_observed_at,idle:r.idle===1,certStatus:r.cert_status});return map;}
 private countBy(table:"providers"|"models"){const map=new Map<string,number>();for(const r of this.db.prepare(`SELECT host_id,COUNT(*) count FROM ${table} GROUP BY host_id`).all() as Array<{host_id:string;count:number}>)map.set(r.host_id,r.count);return map;}
 private counts(now:string):FleetCounts{const health=[...this.liveness().values()].map(v=>this.health(v.observedAt,v.certStatus,now)),hosts=this.repositories.hosts.list().length;return frozen({hosts,active:health.filter(v=>v==="active").length,degraded:health.filter(v=>v==="degraded").length,offline:health.filter(v=>v==="offline").length,revoked:health.filter(v=>v==="revoked").length,providers:(this.db.prepare("SELECT COUNT(*) count FROM providers").get() as {count:number}).count,models:(this.db.prepare("SELECT COUNT(*) count FROM models").get() as {count:number}).count});}}
