import { parseSessionCookieHeader } from "./cookie-parser.js";
import { requiresCsrf } from "./csrf.js";
import { originAllowed,type OriginPolicyOptions } from "./origin.js";
import type { SessionManager } from "./session-manager.js";
import type { SessionMetadata } from "./session-types.js";
export type GuardResult={readonly ok:true;readonly session:SessionMetadata}|{readonly ok:false;readonly status:401|403;readonly code:"UNAUTHORIZED"|"FORBIDDEN"};
const frozen=<T>(o:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),o)) as T;
function request(input:unknown):{method:string;cookieHeader:string;originHeader:string|null;csrfHeader:string|null}|null {try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const p=Object.getPrototypeOf(input);if(p!==Object.prototype&&p!==null)return null;const keys=Reflect.ownKeys(input),allowed=["method","cookieHeader","originHeader","csrfHeader"];if(keys.length!==allowed.length||keys.some(k=>typeof k!=="string"||!allowed.includes(k)))return null;const d=Object.getOwnPropertyDescriptors(input);if(allowed.some(k=>!d[k]||!("value" in d[k])))return null;const method=d.method!.value,cookieHeader=d.cookieHeader!.value,originHeader=d.originHeader!.value,csrfHeader=d.csrfHeader!.value;if(typeof method!=="string"||!/^[A-Z]+$/.test(method)||typeof cookieHeader!=="string"||(originHeader!==null&&typeof originHeader!=="string")||(csrfHeader!==null&&typeof csrfHeader!=="string"))return null;return{method,cookieHeader,originHeader,csrfHeader};}catch{return null;}}
export function guardManagementRequest(manager:SessionManager,allowedOrigins:readonly string[],input:unknown,originOptions:OriginPolicyOptions={}):GuardResult {const parsed=request(input);if(!parsed)return frozen({ok:false,status:401,code:"UNAUTHORIZED"});const token=parseSessionCookieHeader(parsed.cookieHeader);const session=token?manager.authenticate(token):null;if(!session)return frozen({ok:false,status:401,code:"UNAUTHORIZED"});if(requiresCsrf(parsed.method)){if(!originAllowed(parsed.originHeader,allowedOrigins,originOptions))return frozen({ok:false,status:403,code:"FORBIDDEN"});if(!parsed.csrfHeader||!manager.authenticateCsrf(token,parsed.csrfHeader))return frozen({ok:false,status:403,code:"FORBIDDEN"});}else if(parsed.originHeader!==null&&!originAllowed(parsed.originHeader,allowedOrigins,originOptions))return frozen({ok:false,status:403,code:"FORBIDDEN"});return frozen({ok:true,session});}
