import {randomBytes} from "node:crypto";
import {commandAuthorizationDigest,parseInferenceChatCommandParams,type CommandRequest} from "@lan-model-manager/core";
import type {AgentCommandStore} from "./agent-command-channel.js";
import {CommandDispatcher} from "./command-dispatch.js";
import type {ChatUpstreamRequest,ChatUpstreamResult} from "./inference-chat.js";

const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/,MODEL=/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$/;
export interface AgentChatTargetBinding {readonly hostId:string;readonly providerId:string;readonly modelId:string}
export interface AgentChatTransportOptions {readonly dispatcher:CommandDispatcher;readonly store:AgentCommandStore;readonly binding:(targetId:string,model:string)=>AgentChatTargetBinding|null;readonly clock?:()=>string;readonly random?:()=>string;readonly timeoutMs?:number;readonly maxRequestBytes?:number;readonly maxResponseBytes?:number}
function record(value:unknown,keys:readonly string[]):Record<string,unknown>|null{if(typeof value!=="object"||value===null||Array.isArray(value))return null;const proto=Object.getPrototypeOf(value);if(proto!==Object.prototype&&proto!==null)return null;const own=Reflect.ownKeys(value);if(own.length!==keys.length||own.some(key=>typeof key!=="string"||!keys.includes(key)))return null;const d=Object.getOwnPropertyDescriptors(value);if(keys.some(key=>!d[key]||!("value" in d[key]!)))return null;return Object.fromEntries(keys.map(key=>[key,d[key]!.value]));}
function sanitize(value:unknown,requestId:string,model:string,maxBytes:number):Readonly<Record<string,unknown>>|null{try{const text=JSON.stringify(value);if(text===undefined||Buffer.byteLength(text)>maxBytes)return null;const root=record(JSON.parse(text),["id","object","model","choices","usage"]);if(!root||root.id!==requestId||root.object!=="chat.completion"||root.model!==model||!Array.isArray(root.choices)||root.choices.length!==1)return null;const choice=record(root.choices[0],["index","message","finish_reason"]),message=choice&&record(choice.message,["role","content"]),usage=record(root.usage,["prompt_tokens","completion_tokens","total_tokens"]);if(!choice||choice.index!==0||!(["stop","length"] as unknown[]).includes(choice.finish_reason)||!message||message.role!=="assistant"||typeof message.content!=="string"||Buffer.byteLength(message.content)>maxBytes||!usage)return null;const prompt=usage.prompt_tokens,completion=usage.completion_tokens,total=usage.total_tokens;if(!Number.isSafeInteger(prompt)||!Number.isSafeInteger(completion)||!Number.isSafeInteger(total)||Number(prompt)<0||Number(completion)<0||total!==Number(prompt)+Number(completion))return null;return Object.freeze(JSON.parse(text) as Record<string,unknown>);}catch{return null;}}

/** Creates the injected, non-streaming controller→agent chat transport. */
export function createAgentChatTransport(options:AgentChatTransportOptions):(request:ChatUpstreamRequest)=>Promise<ChatUpstreamResult>{const clock=options.clock??(()=>new Date().toISOString()),nonce=options.random??(()=>randomBytes(12).toString("hex")),timeoutMs=options.timeoutMs??120_000,maxRequestBytes=options.maxRequestBytes??524_288,maxResponseBytes=options.maxResponseBytes??262_144;if(!Number.isSafeInteger(timeoutMs)||timeoutMs<1_000||timeoutMs>300_000||!Number.isSafeInteger(maxRequestBytes)||maxRequestBytes<1||maxRequestBytes>524_288||!Number.isSafeInteger(maxResponseBytes)||maxResponseBytes<1||maxResponseBytes>262_144)throw new Error("ERR_AGENT_CHAT_CONFIG");return async(request)=>{if(request.stream)throw new Error("ERR_AGENT_CHAT_STREAMING");const binding=options.binding(request.targetId,request.model);if(!binding||![binding.hostId,binding.providerId,binding.modelId].every(value=>ID.test(value))||!MODEL.test(request.model))throw new Error("ERR_AGENT_CHAT_TARGET");const id=nonce();if(!ID.test(id)||id.length>100)throw new Error("ERR_AGENT_CHAT_ID");const requestId=`chat-${id}`,jobId=`chat-job-${id}`,deadline=new Date(Date.parse(clock())+timeoutMs).toISOString(),expiresAt=new Date(Date.parse(deadline)+1_000).toISOString();const params={providerId:binding.providerId,modelId:binding.modelId,model:request.model,requestId,maxRequestBytes,maxResponseBytes,messages:request.messages.map(message=>Object.freeze({role:message.role,contentBase64:Buffer.from(message.content,"utf8").toString("base64")})),temperatureMilli:request.temperature===undefined?null:Math.round(request.temperature*1000),maxTokens:request.maxTokens??null};if(!parseInferenceChatCommandParams(params).ok)throw new Error("ERR_AGENT_CHAT_REQUEST");const capability={operation:"model-inference" as const,targetKind:"model",targetId:binding.modelId,hostId:binding.hostId,modelId:binding.modelId,requestDigest:"0".repeat(64),expiresAt};const command:CommandRequest={requestId,jobId,hostId:binding.hostId,operation:"inference.chat",idempotencyKey:`chat-idem-${id}`,sequence:1,deadline,capability,params};(capability as {requestDigest:string}).requestDigest=commandAuthorizationDigest(command);const dispatched=options.dispatcher.dispatch(command);if(!dispatched.ok)throw new Error("ERR_AGENT_CHAT_DISPATCH");const cancel=()=>{options.dispatcher.cancel(jobId);};request.signal.addEventListener("abort",cancel,{once:true});try{const response=await options.store.waitResult(jobId,deadline,request.signal);if(response.status!=="succeeded")throw response.status==="cancelled"?new DOMException("Aborted","AbortError"):new Error("ERR_AGENT_CHAT_RESULT");const value=sanitize(response.observation,requestId,request.model,maxResponseBytes);if(!value)throw new Error("ERR_AGENT_CHAT_RESULT");return{kind:"json",value};}catch(error){cancel();throw error;}finally{request.signal.removeEventListener("abort",cancel);}};}
