import assert from "node:assert/strict";
import test from "node:test";
import {openControllerDatabase} from "./database.js";
import {createJobStores} from "./jobs-store.js";
import {AgentCommandStore} from "./agent-command-channel.js";
import {CommandDispatcher} from "./command-dispatch.js";
import {createAgentChatTransport} from "./inference-agent-transport.js";

const modelId="ollama-"+"a".repeat(64);
function setup(){const db=openControllerDatabase(":memory:"),stores=createJobStores(db),queue=new AgentCommandStore(db),dispatcher=new CommandDispatcher(stores,queue),transport=createAgentChatTransport({dispatcher,store:queue,binding:()=>({hostId:"host-1",providerId:"ollama-1",modelId}),random:()=>"fixed",timeoutMs:10_000,maxResponseBytes:262144});return{db,stores,queue,transport};}
function upstream(signal:AbortSignal){return{targetId:"target-1",model:"qwen:latest",messages:[{role:"user" as const,content:"héllo"}],stream:false,temperature:0.25,maxTokens:16,signal};}
test("remote chat queues an exactly bound command and returns only sanitized completion fields",async()=>{const x=setup();try{const controller=new AbortController(),pending=x.transport(upstream(controller.signal)),command=x.queue.poll("host-1").command;assert.ok(command);assert.equal(command.operation,"inference.chat");assert.equal(command.capability.targetId,modelId);assert.deepEqual(command.params,{providerId:"ollama-1",modelId,model:"qwen:latest",requestId:"chat-fixed",maxRequestBytes:524288,maxResponseBytes:262144,messages:[{role:"user",contentBase64:Buffer.from("héllo").toString("base64")}],temperatureMilli:250,maxTokens:16});assert.ok(x.queue.complete("host-1",{requestId:"chat-fixed",jobId:"chat-job-fixed",hostId:"host-1",sequence:1,status:"succeeded",progress:100,observedAt:new Date(Date.now()+10).toISOString(),observation:{id:"chat-fixed",object:"chat.completion",model:"qwen:latest",choices:[{index:0,message:{role:"assistant",content:"hello"},finish_reason:"stop"}],usage:{prompt_tokens:2,completion_tokens:1,total_tokens:3}},errorCode:null}));assert.deepEqual(await pending,{kind:"json",value:{id:"chat-fixed",object:"chat.completion",model:"qwen:latest",choices:[{index:0,message:{role:"assistant",content:"hello"},finish_reason:"stop"}],usage:{prompt_tokens:2,completion_tokens:1,total_tokens:3}}});}finally{x.db.close();}});
test("remote chat propagates cancellation and rejects malformed or topology-leaking results",async()=>{const x=setup();try{const cancelled=new AbortController(),pending=x.transport(upstream(cancelled.signal));assert.ok(x.queue.poll("host-1").command);cancelled.abort();await assert.rejects(pending,error=>error instanceof DOMException&&error.name==="AbortError");assert.equal(x.stores.jobs.get("chat-job-fixed")?.state,"cancelled");}finally{x.db.close();}const y=setup();try{const pending=y.transport(upstream(new AbortController().signal));assert.ok(y.queue.poll("host-1").command);assert.ok(y.queue.complete("host-1",{requestId:"chat-fixed",jobId:"chat-job-fixed",hostId:"host-1",sequence:1,status:"succeeded",progress:100,observedAt:new Date(Date.now()+10).toISOString(),observation:{id:"chat-fixed",object:"chat.completion",model:"qwen:latest",choices:[],usage:{prompt_tokens:0,completion_tokens:0,total_tokens:0},endpoint:"http://127.0.0.1:11434"},errorCode:null}));await assert.rejects(pending,/ERR_AGENT_CHAT_RESULT/);}finally{y.db.close();}});
