import type { DatabaseSync } from "node:sqlite";
import { INFERENCE_SCOPES,InferenceTokenError,type InferenceTokenMetadata,type StoredInferenceToken } from "./inference-types.js";
const HASH=/^[a-f0-9]{64}$/,ID=/^[a-f0-9]{32}$/,OWNER=/^[a-f0-9]{32}$/,TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const validTime=(v:unknown):v is string=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
const frozen=<T>(o:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),o)) as T;
const fail=():never=>{throw new InferenceTokenError("ERR_INFERENCE_DATABASE");};
function query<T>(fn:()=>T):T{try{return fn();}catch(e){if(e instanceof InferenceTokenError)throw e;return fail();}}
const scopes=()=>Object.freeze([...INFERENCE_SCOPES]);
function decode(row:Record<string,unknown>):StoredInferenceToken {const tokenDigest=row.token_digest,tokenId=row.token_id,ownerId=row.owner_id,label=row.label,scopeJson=row.scopes_json,credentialVersion=row.credential_version,createdAt=row.created_at,lastUsedAt=row.last_used_at,expiresAt=row.expires_at,revokedAt=row.revoked_at;if(typeof tokenDigest!=="string"||!HASH.test(tokenDigest)||typeof tokenId!=="string"||!ID.test(tokenId)||typeof ownerId!=="string"||!OWNER.test(ownerId)||typeof label!=="string"||label.length<1||label.length>64||scopeJson!==JSON.stringify(INFERENCE_SCOPES)||typeof credentialVersion!=="number"||!Number.isSafeInteger(credentialVersion)||credentialVersion<1||!validTime(createdAt)||(lastUsedAt!==null&&!validTime(lastUsedAt))||(expiresAt!==null&&!validTime(expiresAt))||(revokedAt!==null&&!validTime(revokedAt)))return fail();return frozen<StoredInferenceToken>({tokenDigest,tokenId,ownerId,label,scopes:scopes(),credentialVersion,createdAt,lastUsedAt,expiresAt,revokedAt});}
function metadata(value:StoredInferenceToken):InferenceTokenMetadata{return frozen<InferenceTokenMetadata>({tokenId:value.tokenId,ownerId:value.ownerId,label:value.label,scopes:scopes(),credentialVersion:value.credentialVersion,createdAt:value.createdAt,lastUsedAt:value.lastUsedAt,expiresAt:value.expiresAt,revokedAt:value.revokedAt});}
export interface NewInferenceToken {readonly tokenDigest:string;readonly tokenId:string;readonly ownerId:string;readonly label:string;readonly credentialVersion:number;readonly createdAt:string;readonly expiresAt:string|null}
export class InferenceTokenRepository {constructor(private readonly db:DatabaseSync){}
 insert(v:NewInferenceToken):void {if(!HASH.test(v.tokenDigest)||!ID.test(v.tokenId)||!OWNER.test(v.ownerId)||typeof v.label!=="string"||v.label.length<1||v.label.length>64||v.label.trim()!==v.label||/[\u0000-\u001f\u007f]/.test(v.label)||!Number.isSafeInteger(v.credentialVersion)||v.credentialVersion<1||!validTime(v.createdAt)||(v.expiresAt!==null&&!validTime(v.expiresAt)))throw new InferenceTokenError("ERR_INFERENCE_INPUT");query(()=>this.db.prepare("INSERT INTO inference_tokens(token_digest,token_id,owner_id,label,scopes_json,credential_version,created_at,last_used_at,expires_at,revoked_at) VALUES(?,?,?,?,?, ?,?,NULL,?,NULL)").run(v.tokenDigest,v.tokenId,v.ownerId,v.label,JSON.stringify(INFERENCE_SCOPES),v.credentialVersion,v.createdAt,v.expiresAt));}
 getByDigest(digest:unknown):StoredInferenceToken|null {if(typeof digest!=="string"||!HASH.test(digest))return null;return query(()=>{const row=this.db.prepare("SELECT * FROM inference_tokens WHERE token_digest=?").get(digest) as Record<string,unknown>|undefined;return row?decode(row):null;});}
 list(ownerId:string):readonly InferenceTokenMetadata[]{if(!OWNER.test(ownerId))throw new InferenceTokenError("ERR_INFERENCE_INPUT");return Object.freeze(query(()=>(this.db.prepare("SELECT * FROM inference_tokens WHERE owner_id=? ORDER BY created_at,token_id").all(ownerId) as Record<string,unknown>[]).map(row=>metadata(decode(row)))));}
 revoke(ownerId:string,tokenId:string,now:string):boolean {if(!OWNER.test(ownerId)||!ID.test(tokenId)||!validTime(now))throw new InferenceTokenError("ERR_INFERENCE_INPUT");return query(()=>this.db.prepare("UPDATE inference_tokens SET revoked_at=? WHERE owner_id=? AND token_id=? AND revoked_at IS NULL").run(now,ownerId,tokenId).changes===1);}
 revokeAll(ownerId:string,now:string):number {if(!OWNER.test(ownerId)||!validTime(now))throw new InferenceTokenError("ERR_INFERENCE_INPUT");return query(()=>Number(this.db.prepare("UPDATE inference_tokens SET revoked_at=? WHERE owner_id=? AND revoked_at IS NULL").run(now,ownerId).changes));}
 touch(digest:string,now:string):boolean {if(!HASH.test(digest)||!validTime(now))throw new InferenceTokenError("ERR_INFERENCE_INPUT");return query(()=>this.db.prepare("UPDATE inference_tokens SET last_used_at=? WHERE token_digest=? AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at>?) AND (last_used_at IS NULL OR last_used_at<?) AND EXISTS(SELECT 1 FROM owners WHERE owners.owner_id=inference_tokens.owner_id AND owners.disabled=0 AND owners.credential_version=inference_tokens.credential_version)").run(now,digest,now,now).changes===1);}
}
