import { once } from "node:events";
import type { IncomingMessage,ServerResponse } from "node:http";
import type { InferenceApiRequest,InferenceApiResponse } from "./inference-api.js";
import { MAX_CHAT_BODY_BYTES,type ChatHttpRequest,type ChatResponse } from "./inference-chat.js";

export type InferenceRouter=(input:InferenceApiRequest)=>Promise<InferenceApiResponse>;
export type ChatRouter=(input:ChatHttpRequest)=>Promise<ChatResponse>;
const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
function invalid(status=400){return{status,headers:JSON_HEADERS,body:{error:{message:"Invalid request.",type:"invalid_request_error",code:"invalid_request"}}};}
function send(response:ServerResponse,value:{status:number;headers:Readonly<Record<string,string>>;body:Readonly<Record<string,unknown>>}){for(const[key,item]of Object.entries(value.headers))response.setHeader(key,item);response.writeHead(value.status);response.end(JSON.stringify(value.body));}
async function readBody(request:IncomingMessage):Promise<Uint8Array|null>{const declared=request.headers["content-length"];if(Array.isArray(declared)||declared!==undefined&&(!/^\d+$/.test(declared)||Number(declared)>MAX_CHAT_BODY_BYTES))return null;const chunks:Buffer[]=[];let length=0;try{for await(const chunk of request){if(!(typeof chunk==="string"||chunk instanceof Uint8Array))return null;const value=Buffer.from(chunk);length+=value.byteLength;if(length>MAX_CHAT_BODY_BYTES)return null;chunks.push(value);}return Buffer.concat(chunks,length);}catch{return null;}}
async function sendChat(response:ServerResponse,value:ChatResponse,controller:AbortController){if("body" in value){send(response,value);return;}for(const[key,item]of Object.entries(value.headers))response.setHeader(key,item);response.writeHead(200);try{for await(const event of value.stream){if(controller.signal.aborted)break;if(!response.write(event))await once(response,"drain",{signal:controller.signal});}if(!response.writableEnded)response.end();}catch{if(!controller.signal.aborted&&!response.writableEnded){response.write(`data: ${JSON.stringify({error:{message:"Inference stream failed.",type:"server_error",code:"upstream_error"}})}\n\n`);response.end("data: [DONE]\n\n");}}}
export function createInferenceHttpHandler(router:InferenceRouter,chat?:ChatRouter){return(request:IncomingMessage,response:ServerResponse)=>{const authorization=request.headers.authorization;if(Array.isArray(authorization)){send(response,invalid());return;}const path=(request.url??"").split("?",1)[0]!;if(path==="/v1/chat/completions"){if(!chat){send(response,invalid(404));return;}const contentType=request.headers["content-type"];if(Array.isArray(contentType)){send(response,invalid());return;}const controller=new AbortController();request.once("aborted",()=>controller.abort());response.once("close",()=>{if(!response.writableEnded)controller.abort();});void readBody(request).then(async body=>{if(body===null){send(response,invalid(413));return;}const value=await chat({method:request.method??"",url:path,headers:{...(authorization===undefined?{}:{authorization}),...(request.headers.cookie===undefined?{}:{cookie:request.headers.cookie})},contentType:contentType?.split(";",1)[0]?.trim().toLowerCase(),body,signal:controller.signal});await sendChat(response,value,controller);},()=>send(response,invalid())).catch(()=>{if(!response.headersSent)send(response,{status:500,headers:JSON_HEADERS,body:{error:{message:"Request failed.",type:"server_error",code:"internal_error"}}});});return;}void router({method:request.method??"",url:path,headers:{...(authorization===undefined?{}:{authorization}),...(request.headers.cookie===undefined?{}:{cookie:request.headers.cookie})}}).then(value=>send(response,value),()=>send(response,{status:500,headers:JSON_HEADERS,body:{error:{message:"Request failed.",type:"server_error",code:"internal_error"}}}));};}
