import { randomBytes } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import { equalInferenceDigest,generateInferenceToken,inferenceTokenDigest,parseAuthorizationBearer } from "./inference-bearer.js";
import { InferenceTokenRepository } from "./inference-repository.js";
import { INFERENCE_DEFAULT_TTL_MS,INFERENCE_MAX_TTL_MS,INFERENCE_MIN_TTL_MS,INFERENCE_SCOPES,InferenceTokenError,type InferenceAuthorizationResult,type InferenceTokenMetadata,type IssuedInferenceToken,type StoredInferenceToken } from "./inference-types.js";
const TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const validTime=(v:unknown):v is string=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
const frozen=<T>(o:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),o)) as T;
const unauthorized=():InferenceAuthorizationResult=>frozen({ok:false,status:401,challenge:"Bearer"});
export type ManagementAuthorizer=(authentication:unknown)=>Promise<boolean>;
export interface InferenceTokenManagerOptions {readonly clock?:()=>string;readonly random?:(size:number)=>Uint8Array;readonly defaultTtlMs?:number}
function validScopes(input:unknown):boolean {try{if(!Array.isArray(input))return false;const descriptors=Object.getOwnPropertyDescriptors(input) as Record<string,PropertyDescriptor>;const keys=Reflect.ownKeys(input);return keys.length===3&&keys.every(key=>key==="length"||key==="0"||key==="1")&&descriptors["length"]?.value===2&&descriptors["0"]!==undefined&&"value" in descriptors["0"]&&descriptors["0"].value==="inference:invoke"&&descriptors["1"]!==undefined&&"value" in descriptors["1"]&&descriptors["1"].value==="model:list";}catch{return false;}}
function issueInput(input:unknown):{label:string;ttlMs:number|null}|null {try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const proto=Object.getPrototypeOf(input);if(proto!==Object.prototype&&proto!==null)return null;const own=Reflect.ownKeys(input),allowed=["label","scopes","ttlMs"];if(own.some(k=>typeof k!=="string"||!allowed.includes(k))||!own.includes("label"))return null;const d=Object.getOwnPropertyDescriptors(input);if(own.some(k=>typeof k!=="string"||!d[k]||!("value" in d[k])))return null;const label=d.label!.value,scopeValue=d.scopes?.value,ttlValue=d.ttlMs?.value;if(typeof label!=="string"||label.length<1||label.length>64||label.trim()!==label||/[\u0000-\u001f\u007f]/.test(label))return null;if(scopeValue!==undefined&&!validScopes(scopeValue))return null;if(ttlValue!==undefined&&ttlValue!==null&&(!Number.isSafeInteger(ttlValue)||ttlValue<INFERENCE_MIN_TTL_MS||ttlValue>INFERENCE_MAX_TTL_MS))return null;return{label,ttlMs:ttlValue??null};}catch{return null;}}
export class InferenceTokenManager {private readonly repository:InferenceTokenRepository;private readonly clock:()=>string;private readonly random:(size:number)=>Uint8Array;private readonly ttl:number;
 constructor(private readonly db:DatabaseSync,private readonly authorizeManagement:ManagementAuthorizer,options:InferenceTokenManagerOptions={}){this.repository=new InferenceTokenRepository(db);this.clock=options.clock??(()=>new Date().toISOString());this.random=options.random??((size)=>randomBytes(size));this.ttl=options.defaultTtlMs??INFERENCE_DEFAULT_TTL_MS;if(!Number.isSafeInteger(this.ttl)||this.ttl<INFERENCE_MIN_TTL_MS||this.ttl>INFERENCE_MAX_TTL_MS)throw new InferenceTokenError("ERR_INFERENCE_INPUT");}
 private now():string {const value=this.clock();if(!validTime(value))throw new InferenceTokenError("ERR_INFERENCE_INPUT");return value;}
 private owner():{ownerId:string;disabled:boolean;version:number}|null {try{const row=this.db.prepare("SELECT owner_id,disabled,credential_version FROM owners WHERE singleton_key=1").get() as {owner_id:string;disabled:number;credential_version:number}|undefined;if(!row||!/^[a-f0-9]{32}$/.test(row.owner_id)||(row.disabled!==0&&row.disabled!==1)||!Number.isSafeInteger(row.credential_version))return null;return{ownerId:row.owner_id,disabled:row.disabled===1,version:row.credential_version};}catch{return null;}}
 private meta(v:StoredInferenceToken):InferenceTokenMetadata{return frozen<InferenceTokenMetadata>({tokenId:v.tokenId,ownerId:v.ownerId,label:v.label,scopes:Object.freeze([...INFERENCE_SCOPES]),credentialVersion:v.credentialVersion,createdAt:v.createdAt,lastUsedAt:v.lastUsedAt,expiresAt:v.expiresAt,revokedAt:v.revokedAt});}
 private active(v:StoredInferenceToken,now:string):boolean {const owner=this.owner();return v.revokedAt===null&&(v.expiresAt===null||Date.parse(now)<Date.parse(v.expiresAt))&&owner!==null&&!owner.disabled&&owner.ownerId===v.ownerId&&owner.version===v.credentialVersion;}
 async issue(authentication:unknown,input:unknown):Promise<IssuedInferenceToken|null>{if(!await this.safeAuthorize(authentication))return null;const parsed=issueInput(input),owner=this.owner();if(!parsed||!owner||owner.disabled)throw new InferenceTokenError("ERR_INFERENCE_INPUT");const now=this.now(),token=generateInferenceToken(this.random),idBytes=this.random(16);if(!(idBytes instanceof Uint8Array)||idBytes.length!==16)throw new InferenceTokenError("ERR_INFERENCE_INPUT");const tokenId=Buffer.from(idBytes).toString("hex"),expiresAt=new Date(Date.parse(now)+(parsed.ttlMs??this.ttl)).toISOString();this.repository.insert({tokenDigest:inferenceTokenDigest(token),tokenId,ownerId:owner.ownerId,label:parsed.label,credentialVersion:owner.version,createdAt:now,expiresAt});const metadata=this.repository.list(owner.ownerId).find(v=>v.tokenId===tokenId);if(!metadata)throw new InferenceTokenError("ERR_INFERENCE_DATABASE");return frozen<IssuedInferenceToken>({token,metadata});}
 async list(authentication:unknown):Promise<readonly InferenceTokenMetadata[]>{if(!await this.safeAuthorize(authentication))return Object.freeze([]);const owner=this.owner();return owner?this.repository.list(owner.ownerId):Object.freeze([]);}
 async revoke(authentication:unknown,tokenId:unknown):Promise<boolean>{if(!await this.safeAuthorize(authentication)||typeof tokenId!=="string")return false;const owner=this.owner();return owner?this.repository.revoke(owner.ownerId,tokenId,this.now()):false;}
 async revokeAll(authentication:unknown):Promise<number>{if(!await this.safeAuthorize(authentication))return 0;const owner=this.owner();return owner?this.repository.revokeAll(owner.ownerId,this.now()):0;}
 authenticateAuthorization(header:unknown):InferenceAuthorizationResult {const token=parseAuthorizationBearer(header);if(token===null)return unauthorized();const now=this.now(),presented=inferenceTokenDigest(token),stored=this.repository.getByDigest(presented);if(!stored||!equalInferenceDigest(stored.tokenDigest,presented)||!this.active(stored,now))return unauthorized();return frozen({ok:true,token:this.meta(stored)});}
 touchAuthorization(header:unknown):boolean {const token=parseAuthorizationBearer(header);if(token===null)return false;const now=this.now(),digest=inferenceTokenDigest(token),stored=this.repository.getByDigest(digest);return !!stored&&equalInferenceDigest(stored.tokenDigest,digest)&&this.active(stored,now)&&this.repository.touch(digest,now);}
 private async safeAuthorize(value:unknown):Promise<boolean>{try{return await this.authorizeManagement(value);}catch{return false;}}
}
export function createInferenceTokenManager(db:DatabaseSync,authorizeManagement:ManagementAuthorizer,options:InferenceTokenManagerOptions={}):InferenceTokenManager{return new InferenceTokenManager(db,authorizeManagement,options);}
