import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import type { PasswordCryptoEngine } from "./credentials.js";
import { CONTROLLER_MIGRATIONS,migrateControllerDatabase,openControllerDatabase } from "./database.js";
import { generateInferenceToken,parseAuthorizationBearer } from "./inference-bearer.js";
import { InferenceTokenError,INFERENCE_SCOPES } from "./inference-types.js";
import { InferenceTokenManager } from "./inference-manager.js";
import { createOwnerBootstrapService } from "./owner-service.js";
import { SessionManager } from "./session-manager.js";

const START="2026-09-27T12:00:00.000Z",PASSWORD="owner-password-123";
const cryptoEngine=():PasswordCryptoEngine=>({random:size=>Buffer.alloc(size,3),async derive(password,salt,p){const seed=createHash("sha256").update(password).update(salt).digest();return Buffer.alloc(p.keyLength,seed[0]);},equal:(a,b)=>Buffer.from(a).equals(Buffer.from(b))});
async function setup(db=openControllerDatabase(":memory:")){let now=START,sessionCounter=0,inferenceCounter=20;const owners=createOwnerBootstrapService(db,{now:()=>now,ownerId:()=>"a".repeat(32),crypto:cryptoEngine()});await owners.bootstrapOwner({username:"Admin",password:PASSWORD});const sessions=new SessionManager(db,owners,{clock:()=>now,random:size=>Buffer.alloc(size,++sessionCounter),policy:{absoluteTtlMs:3_600_000,idleTtlMs:600_000,touchAfterMs:60_000}});const manager=new InferenceTokenManager(db,async value=>typeof value==="string"&&sessions.authenticate(value)!==null,{clock:()=>now,random:size=>Buffer.alloc(size,++inferenceCounter),defaultTtlMs:3_600_000});const session=await sessions.create({username:"admin",password:PASSWORD});assert.ok(session);return{db,owners,sessions,manager,session,setNow:(v:string)=>{now=v;}};}

test("migration4 upgrades to canonical inference-token migration5",()=>{const dir=mkdtempSync(join(tmpdir(),"lanmm-inference-upgrade-"));try{const path=join(dir,"db.sqlite3");let db=new DatabaseSync(path);migrateControllerDatabase(db,CONTROLLER_MIGRATIONS.slice(0,4));db.close();db=openControllerDatabase(path);assert.equal((db.prepare("PRAGMA user_version").get() as any).user_version,5);const columns=(db.prepare("PRAGMA table_info(inference_tokens)").all() as Array<{name:string}>).map(r=>r.name);assert.deepEqual(columns,["token_digest","token_id","owner_id","label","scopes_json","credential_version","created_at","last_used_at","expires_at","revoked_at"]);assert.throws(()=>db.prepare("INSERT INTO inference_tokens VALUES(?,?,?,?,?,?,?,?,?,?)").run("0".repeat(64),"1".repeat(32),"a".repeat(32),"x",'["management:admin"]',1,START,null,null,null));db.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("strict Authorization parser accepts exactly one bearer token",()=>{const token=generateInferenceToken();assert.equal(parseAuthorizationBearer(`Bearer ${token}`),token);for(const bad of [token,`Basic ${token}`,`Bearer  ${token}`,`Bearer ${token} `,`Bearer ${token},Bearer ${token}`,`Bearer ${token}\n`,[ `Bearer ${token}` ],null,"Bearer short"])assert.equal(parseAuthorizationBearer(bad),null);});

test("issue returns raw token once while SQLite stores only digest",async()=>{const{db,manager,session}=await setup();try{const issued=await manager.issue(session.sessionToken,{label:"CI token"});assert.ok(issued);assert.equal(issued.token.length,43);assert.equal("tokenDigest" in issued.metadata,false);assert.ok(Object.isFrozen(issued)&&Object.isFrozen(issued.metadata)&&Object.isFrozen(issued.metadata.scopes));const dump=JSON.stringify(db.prepare("SELECT * FROM inference_tokens").all());assert.equal(dump.includes(issued.token),false);assert.deepEqual(issued.metadata.scopes,["inference:invoke","model:list"]);}finally{db.close();}});

test("issue DTO is strict and scopes must be canonical, unique, and complete",async()=>{const{db,manager,session}=await setup();try{assert.ok(await manager.issue(session.sessionToken,{label:"valid",scopes:["inference:invoke","model:list"]}));for(const bad of [{label:""},{label:"x",scopes:["model:list"]},{label:"x",scopes:["model:list","inference:invoke"]},{label:"x",scopes:["inference:invoke","model:list","model:list"]},{label:"x",scopes:["management:admin"]},{label:"x",extra:true}])await assert.rejects(manager.issue(session.sessionToken,bad),InferenceTokenError);}finally{db.close();}});

test("metadata lists deterministically without raw token or digest",async()=>{const{db,manager,session}=await setup();try{await manager.issue(session.sessionToken,{label:"a"});await manager.issue(session.sessionToken,{label:"b"});const list=await manager.list(session.sessionToken);assert.equal(list.length,2);assert.ok(Object.isFrozen(list));for(const row of list){assert.ok(Object.isFrozen(row)&&Object.isFrozen(row.scopes));assert.equal("token" in row,false);assert.equal("tokenDigest" in row,false);}}finally{db.close();}});

test("bearer inference auth and management session auth are not interchangeable",async()=>{const{db,manager,session,sessions}=await setup();try{const issued=await manager.issue(session.sessionToken,{label:"scope"});assert.ok(issued);assert.equal(manager.authenticateAuthorization(`Bearer ${issued.token}`).ok,true);assert.equal(manager.authenticateAuthorization(`Bearer ${session.sessionToken}`).ok,false);assert.equal(sessions.authenticate(issued.token),null);assert.equal(await manager.issue(issued.token,{label:"forbidden"}),null);}finally{db.close();}});

test("inference guard returns generic 401 and never accepts cookies or bare values",async()=>{const{db,manager,session}=await setup();try{const issued=await manager.issue(session.sessionToken,{label:"guard"});assert.ok(issued);for(const bad of [issued.token,`__Host-lanmm_session=${issued.token}`,null,"Bearer wrong"]){const result=manager.authenticateAuthorization(bad);assert.deepEqual({...result},{ok:false,status:401,challenge:"Bearer"});assert.equal(JSON.stringify(result).includes(issued.token),false);}}finally{db.close();}});

test("expiry is strict and owner disable/version rotation invalidate tokens",async()=>{const{db,manager,session,setNow}=await setup();try{const issued=await manager.issue(session.sessionToken,{label:"expiry",ttlMs:60_000});assert.ok(issued);setNow("2026-09-27T12:00:59.999Z");assert.equal(manager.authenticateAuthorization(`Bearer ${issued.token}`).ok,true);setNow("2026-09-27T12:01:00.000Z");assert.equal(manager.authenticateAuthorization(`Bearer ${issued.token}`).ok,false);setNow(START);const next=await manager.issue(session.sessionToken,{label:"owner"});assert.ok(next);db.prepare("UPDATE owners SET disabled=1 WHERE singleton_key=1").run();assert.equal(manager.authenticateAuthorization(`Bearer ${next.token}`).ok,false);db.prepare("UPDATE owners SET disabled=0,credential_version=credential_version+1 WHERE singleton_key=1").run();assert.equal(manager.authenticateAuthorization(`Bearer ${next.token}`).ok,false);}finally{db.close();}});

test("usage touch is monotonic and cannot update expired or revoked tokens",async()=>{const{db,manager,session,setNow}=await setup();try{const issued=await manager.issue(session.sessionToken,{label:"touch",ttlMs:60_000});assert.ok(issued);setNow("2026-09-27T12:00:30.000Z");assert.equal(manager.touchAuthorization(`Bearer ${issued.token}`),true);assert.equal(manager.touchAuthorization(`Bearer ${issued.token}`),false);assert.equal((db.prepare("SELECT last_used_at FROM inference_tokens").get() as any).last_used_at,"2026-09-27T12:00:30.000Z");assert.equal(await manager.revoke(session.sessionToken,issued.metadata.tokenId),true);setNow("2026-09-27T12:00:40.000Z");assert.equal(manager.touchAuthorization(`Bearer ${issued.token}`),false);}finally{db.close();}});

test("single and owner-wide revocation preserve metadata but invalidate credentials",async()=>{const{db,manager,session}=await setup();try{const one=await manager.issue(session.sessionToken,{label:"one"}),two=await manager.issue(session.sessionToken,{label:"two"});assert.ok(one&&two);assert.equal(await manager.revoke(session.sessionToken,one.metadata.tokenId),true);assert.equal(manager.authenticateAuthorization(`Bearer ${one.token}`).ok,false);assert.equal(manager.authenticateAuthorization(`Bearer ${two.token}`).ok,true);assert.equal(await manager.revokeAll(session.sessionToken),1);assert.equal(manager.authenticateAuthorization(`Bearer ${two.token}`).ok,false);assert.equal((await manager.list(session.sessionToken)).length,2);}finally{db.close();}});

test("tokens and revocation persist across restart",async()=>{const dir=mkdtempSync(join(tmpdir(),"lanmm-inference-reopen-"));try{const path=join(dir,"db.sqlite3");let context=await setup(openControllerDatabase(path));const issued=await context.manager.issue(context.session.sessionToken,{label:"restart"});assert.ok(issued);context.db.close();const db=openControllerDatabase(path),owners=createOwnerBootstrapService(db,{crypto:cryptoEngine()}),sessions=new SessionManager(db,owners,{clock:()=>START}),manager=new InferenceTokenManager(db,async value=>typeof value==="string"&&sessions.authenticate(value)!==null,{clock:()=>START});assert.equal(manager.authenticateAuthorization(`Bearer ${issued.token}`).ok,true);db.prepare("UPDATE inference_tokens SET revoked_at=?").run(START);db.close();const reopened=openControllerDatabase(path),owners2=createOwnerBootstrapService(reopened,{crypto:cryptoEngine()}),sessions2=new SessionManager(reopened,owners2,{clock:()=>START}),manager2=new InferenceTokenManager(reopened,async value=>typeof value==="string"&&sessions2.authenticate(value)!==null,{clock:()=>START});assert.equal(manager2.authenticateAuthorization(`Bearer ${issued.token}`).ok,false);reopened.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("issue DTO rejects getters, symbols, custom prototypes, and revoked proxies",async()=>{const{db,manager,session}=await setup();try{let calls=0;const accessor=Object.defineProperty({},"label",{enumerable:true,get(){calls++;return"x";}});const scopeAccessor=Object.defineProperty(["inference:invoke","model:list"],"0",{enumerable:true,get(){calls++;return"inference:invoke";}});const revoked=Proxy.revocable({label:"x"},{});revoked.revoke();const revokedScopes=Proxy.revocable(["inference:invoke","model:list"],{});revokedScopes.revoke();for(const bad of [accessor,{label:"x",scopes:scopeAccessor},{label:"x",scopes:revokedScopes.proxy},{label:"x",[Symbol("x")]:1},Object.assign(Object.create({}),{label:"x"}),revoked.proxy])await assert.rejects(manager.issue(session.sessionToken,bad),InferenceTokenError);assert.equal(calls,0);}finally{db.close();}});
