import type { InferenceTokenManager } from "./inference-manager.js";
export interface InferenceModelObservation{readonly canonicalName:string;readonly state:"available"|"installed"|"running";readonly hostHealth:"active"|"degraded"|"offline"|"revoked";readonly observedAt:string}
export interface InferenceApiRequest{readonly method:string;readonly url:string;readonly headers:unknown}
export interface InferenceApiResponse{readonly status:number;readonly headers:Readonly<Record<string,string>>;readonly body:Readonly<Record<string,unknown>>}
export interface InferenceApiDependencies{readonly tokens:InferenceTokenManager;readonly inventory:()=>readonly InferenceModelObservation[];readonly rateLimit?:(tokenId:string)=>boolean;readonly clock?:()=>string;readonly maxObservationAgeMs?:number}
const HEADERS=Object.freeze({"content-type":"application/json; charset=utf-8","cache-control":"no-store"});
function error(status:number,code:string,message:string):InferenceApiResponse{return Object.freeze({status,headers:HEADERS,body:Object.freeze({error:Object.freeze({message,type:"invalid_request_error",code})})});}
function authorization(headers:unknown):string|null{try{if(typeof headers!=="object"||headers===null||Array.isArray(headers))return null;const proto=Object.getPrototypeOf(headers);if(proto!==Object.prototype&&proto!==null)return null;const descriptors=Object.getOwnPropertyDescriptors(headers),keys=Reflect.ownKeys(headers);if(keys.some(key=>typeof key!=="string"||!descriptors[key]||!("value" in descriptors[key]!)))return null;let value:string|null=null;for(const key of keys as string[]){if(key.toLowerCase()==="authorization"){if(value!==null||typeof descriptors[key]!.value!=="string")return null;value=descriptors[key]!.value;}else if(key.toLowerCase()==="cookie")return null;}return value;}catch{return null;}}
function validObservation(value:unknown):value is InferenceModelObservation{try{if(typeof value!=="object"||value===null||Array.isArray(value))return false;const d=Object.getOwnPropertyDescriptors(value),keys=Reflect.ownKeys(value),expected=["canonicalName","state","hostHealth","observedAt"];if(keys.length!==expected.length||keys.some(key=>typeof key!=="string"||!expected.includes(key)||!d[key]||!("value" in d[key]!)))return false;return typeof d.canonicalName!.value==="string"&&/^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$/.test(d.canonicalName!.value)&&["available","installed","running"].includes(d.state!.value)&&["active","degraded","offline","revoked"].includes(d.hostHealth!.value)&&typeof d.observedAt!.value==="string"&&!Number.isNaN(Date.parse(d.observedAt!.value));}catch{return false;}}
export function createInferenceApiHandler(deps:InferenceApiDependencies){const now=deps.clock??(()=>new Date().toISOString()),maxAge=deps.maxObservationAgeMs??120_000;if(!Number.isSafeInteger(maxAge)||maxAge<1_000)throw new Error("ERR_INFERENCE_CONFIG");return async(input:unknown):Promise<InferenceApiResponse>=>{let request:InferenceApiRequest;try{if(typeof input!=="object"||input===null||Array.isArray(input))throw 0;const d=Object.getOwnPropertyDescriptors(input),keys=Reflect.ownKeys(input);if(keys.length!==3||keys.some(key=>typeof key!=="string"||!["method","url","headers"].includes(key)||!d[key]||!("value" in d[key]!)))throw 0;request={method:d.method!.value,url:d.url!.value,headers:d.headers!.value};if(typeof request.method!=="string"||typeof request.url!=="string")throw 0;}catch{return error(400,"invalid_request","Invalid request.");}if(request.url!=="/v1/models")return error(404,"not_found","Not found.");if(request.method!=="GET")return error(405,"method_not_allowed","Method not allowed.");const auth=deps.tokens.authenticateAuthorization(authorization(request.headers));if(!auth.ok||!auth.token.scopes.includes("model:list"))return Object.freeze({...error(401,"invalid_api_key","Invalid authentication credentials."),headers:Object.freeze({...HEADERS,"www-authenticate":"Bearer"})});if(deps.rateLimit&&!deps.rateLimit(auth.token.tokenId))return error(429,"rate_limit_exceeded","Rate limit exceeded.");let inventory:readonly InferenceModelObservation[];try{inventory=deps.inventory();}catch{return error(503,"service_unavailable","Model inventory unavailable.");}const timestamp=Date.parse(now()),seen=new Set<string>(),models:Array<Readonly<{id:string;object:"model";created:number;owned_by:"lan-model-manager"}>>=[];try{for(const item of inventory){if(!validObservation(item))throw 0;if(item.hostHealth!=="active"||timestamp-Date.parse(item.observedAt)>maxAge||Date.parse(item.observedAt)>timestamp+30_000)continue;if(seen.has(item.canonicalName))continue;seen.add(item.canonicalName);models.push(Object.freeze({id:item.canonicalName,object:"model",created:Math.floor(Date.parse(item.observedAt)/1000),owned_by:"lan-model-manager"}));}}catch{return error(503,"service_unavailable","Model inventory unavailable.");}models.sort((a,b)=>a.id.localeCompare(b.id));deps.tokens.touchAuthorization(authorization(request.headers));return Object.freeze({status:200,headers:HEADERS,body:Object.freeze({object:"list",data:Object.freeze(models)})});};}
