import test from "node:test";
import assert from "node:assert/strict";
import { createChatCompletionsHandler,type ChatDependencies,type ChatUpstreamRequest } from "./inference-chat.js";

const encoder=new TextEncoder();
const token={tokenId:"token-a",ownerId:"a".repeat(32),label:"test",scopes:["inference:invoke","model:list"],credentialVersion:1,createdAt:"2026-09-28T10:00:00.000Z",lastUsedAt:null,expiresAt:"2026-09-28T12:00:00.000Z",revokedAt:null};
const request=(body:unknown,overrides:Record<string,unknown>={})=>({method:"POST",url:"/v1/chat/completions",headers:{authorization:"Bearer valid"},contentType:"application/json",body:encoder.encode(JSON.stringify(body)),signal:new AbortController().signal,...overrides});
function setup(overrides:Partial<ChatDependencies>={}){let acquired=0,released=0,touched=0,upstream:ChatUpstreamRequest|null=null;const dependencies:ChatDependencies={tokens:{authenticateAuthorization:(value:unknown)=>value==="Bearer valid"?{ok:true,token}:{ok:false,status:401,challenge:"Bearer"},touchAuthorization:()=>{touched++;return true;}} as never,resolve:async()=>({targetId:"target-1",model:"resolved/model"}),acquireLease:async()=>{acquired++;return{release(){released++;}}},transport:async value=>{upstream=value;return{kind:"json",value:{id:"chatcmpl-1",object:"chat.completion",model:value.model,choices:[]}}},...overrides};return{handler:createChatCompletionsHandler(dependencies),counts:()=>({acquired,released,touched}),upstream:()=>upstream};}

test("chat proxy authenticates inference bearer only and validates boundary",async()=>{const x=setup();assert.equal((await x.handler(request({model:"a",messages:[{role:"user",content:"hi"}]},{headers:{cookie:"session=x",authorization:"Bearer valid"}}))).status,401);assert.equal((await x.handler(request({model:"a",messages:[{role:"user",content:"hi"}]},{method:"GET"}))).status,405);assert.equal((await x.handler(request({model:"a",messages:[{role:"user",content:"hi"}]},{contentType:"text/plain"}))).status,415);assert.equal((await x.handler(request({model:"a",messages:[{role:"user",content:"hi"}],endpoint:"http://evil"}))).status,400);let calls=0;const headers=Object.defineProperty({},"authorization",{get(){calls++;return"Bearer valid";}});assert.equal((await x.handler(request({model:"a",messages:[{role:"user",content:"hi"}]},{headers}))).status,401);assert.equal(calls,0);assert.deepEqual(x.counts(),{acquired:0,released:0,touched:0});});

test("non-stream request binds only resolved target and releases lease exactly once",async()=>{const x=setup(),response=await x.handler(request({model:"requested/model",messages:[{role:"system",content:"safe"},{role:"user",content:"hello"}],temperature:0.5,max_tokens:12}));assert.equal(response.status,200);assert.ok("body" in response);assert.deepEqual(x.counts(),{acquired:1,released:1,touched:1});assert.deepEqual(x.upstream(),{targetId:"target-1",model:"resolved/model",messages:[{role:"system",content:"safe"},{role:"user",content:"hello"}],stream:false,temperature:0.5,maxTokens:12,signal:x.upstream()!.signal});const text=JSON.stringify("body" in response?response.body:{});assert.match(text,/requested_model/);for(const forbidden of ["target-1","endpoint","hostId","providerId","digest","snapshot"])assert.equal(text.includes(forbidden),false);});

test("standard OpenAI token usage survives response redaction",async()=>{const x=setup({transport:async()=>({kind:"json",value:{id:"one",object:"chat.completion",choices:[],usage:{prompt_tokens:2,completion_tokens:3,total_tokens:5}}})}),response=await x.handler(request({model:"requested/model",messages:[{role:"user",content:"hello"}]}));assert.equal(response.status,200);assert.equal(JSON.stringify(response).includes("total_tokens"),true);assert.deepEqual(x.counts(),{acquired:1,released:1,touched:1});});

test("upstream failure releases lease and returns a generic error",async()=>{const x=setup({transport:async()=>{throw new Error("secret endpoint http://10.0.0.2");}}),response=await x.handler(request({model:"requested/model",messages:[{role:"user",content:"hello"}]}));assert.equal(response.status,502);assert.deepEqual(x.counts(),{acquired:1,released:1,touched:0});assert.equal(JSON.stringify(response).includes("10.0.0.2"),false);});

test("stream frames ordered events and releases on completion",async()=>{async function* events(){yield{id:"one",object:"chat.completion.chunk",choices:[{delta:{content:"A"}}]};yield{id:"two",object:"chat.completion.chunk",choices:[{delta:{content:"B"}}]};}const x=setup({transport:async()=>({kind:"stream",events:events()})}),response=await x.handler(request({model:"requested/model",messages:[{role:"user",content:"hello"}],stream:true}));assert.equal(response.status,200);assert.ok("stream" in response);const chunks:string[]=[];if("stream" in response)for await(const chunk of response.stream)chunks.push(chunk);assert.equal(chunks.at(-1),"data: [DONE]\n\n");assert.match(chunks[0]!,/requested_model/);assert.match(chunks[0]!,/A/);assert.match(chunks[1]!,/B/);assert.deepEqual(x.counts(),{acquired:1,released:1,touched:1});});

test("invalid stream events fail closed and release the lease",async()=>{async function* events(){yield{endpoint:"http://internal"};}const x=setup({transport:async()=>({kind:"stream",events:events()})}),response=await x.handler(request({model:"requested/model",messages:[{role:"user",content:"hello"}],stream:true}));assert.ok("stream" in response);if("stream" in response)await assert.rejects(async()=>{for await(const _chunk of response.stream){/* consume */}});assert.deepEqual(x.counts(),{acquired:1,released:1,touched:1});});

test("stream cancellation closes iterator and releases lease once",async()=>{let returned=0;const events={async *[Symbol.asyncIterator](){try{yield{id:"one",object:"chat.completion.chunk",choices:[]};yield{id:"two",object:"chat.completion.chunk",choices:[]};}finally{returned++;}}};const x=setup({transport:async()=>({kind:"stream",events})}),response=await x.handler(request({model:"requested/model",messages:[{role:"user",content:"hello"}],stream:true}));assert.ok("stream" in response);if("stream" in response){const iterator=response.stream[Symbol.asyncIterator]();await iterator.next();await iterator.return?.();}assert.equal(returned,1);assert.deepEqual(x.counts(),{acquired:1,released:1,touched:1});});

test("abort after stream admission releases an unconsumed lease",async()=>{async function* events(){yield{id:"one"};}const controller=new AbortController(),x=setup({transport:async()=>({kind:"stream",events:events()})}),response=await x.handler(request({model:"requested/model",messages:[{role:"user",content:"hello"}],stream:true},{signal:controller.signal}));assert.ok("stream" in response);controller.abort();assert.deepEqual(x.counts(),{acquired:1,released:1,touched:1});});

test("oversize and malformed requests fail before placement",async()=>{const x=setup();assert.equal((await x.handler(request({model:"a",messages:[{role:"user",content:"x".repeat(65_537)}]}))).status,400);assert.equal((await x.handler({...request({}),body:new Uint8Array(1_048_577)})).status,400);assert.deepEqual(x.counts(),{acquired:0,released:0,touched:0});});
