import assert from "node:assert/strict";
import test from "node:test";
import { authorizationDigest, commandPolicyOperation, policyHash, type AuthorizationIntent, type CommandOperation, type OperationPolicy } from "@lan-model-manager/core";
import { openControllerDatabase } from "./database.js";
import { createControllerRepositories } from "./repositories.js";
import { PolicyService } from "./policy-service.js";
import { createJobStores } from "./jobs-store.js";
import { CommandDispatcher } from "./command-dispatch.js";
import { LifecycleService } from "./lifecycle-service.js";
import { createAdmissionController } from "./admission-accounting.js";

const NOW="2026-09-28T08:00:00.000Z", AFTER="2026-09-28T08:00:01.000Z";
const operations=["artifact-install","artifact-remove","model-drain","model-load","model-set-options","model-unload"] as const;
const policy:OperationPolicy={version:1,allowedOperations:operations,approvalOperations:[],allowArtifactAcquisition:true,allowArtifactRemoval:true,allowSubstitution:false,allowPublicExposure:false,minimumMemoryHeadroomBytes:0,minimumVramHeadroomBytes:0,minimumStorageHeadroomBytes:0,maxConcurrentOperations:10,maxOperationsPerMinute:100};
const owner={ok:true as const,session:{ownerId:"owner-1",sessionVersion:1,credentialVersion:1,createdAt:NOW,lastSeenAt:NOW,absoluteExpiresAt:"2026-09-29T08:00:00.000Z",idleExpiresAt:"2026-09-28T09:00:00.000Z",revokedAt:null}};
function intent(operation:CommandOperation,requestId:string):AuthorizationIntent{return{requestId,actorKind:"controller",actorId:"controller",operation:commandPolicyOperation(operation),targetKind:"model",targetId:"model-1",hostId:"host-1",modelId:"model-1",observationFresh:true,hostRevoked:false,modelCompatible:true,publicExposure:false,availableMemoryBytes:1,availableVramBytes:1,availableStorageBytes:1,activeOperations:0,operationsLastMinute:0};}
function request(operation:CommandOperation,id:string,i:AuthorizationIntent){return{requestId:id,jobId:`job-${id}`,hostId:"host-1",operation,idempotencyKey:`idem-${id}`,sequence:1,deadline:"2026-09-28T09:00:00.000Z",capability:{operation:i.operation,targetKind:i.targetKind,targetId:i.targetId,hostId:i.hostId,modelId:i.modelId,requestDigest:authorizationDigest(i,policy.version,policyHash(policy)),expiresAt:"2026-09-28T09:00:00.000Z"},params:{providerId:"provider-1",model:"acme/bert:latest"}};}
function setup(runtimeState:string,activeRequests=0,managedTemporary=false,pinned=false,observedAt=NOW){const db=openControllerDatabase(":memory:"),repositories=createControllerRepositories(db,{now:()=>NOW});repositories.hosts.upsert({hostId:"host-1",displayName:"Host",platform:"linux",observedAt:NOW,online:true,freshness:"fresh",snapshot:{}});repositories.providers.upsert({providerId:"provider-1",hostId:"host-1",kind:"ollama",endpoint:"http://127.0.0.1:11434",health:"ready",version:"",versionKnown:false,observedAt:NOW,snapshot:{}});repositories.models.upsert({modelId:"model-1",providerId:"provider-1",hostId:"host-1",canonicalName:"acme/bert:latest",state:runtimeState==="serving"?"running":"installed",type:"llm",digest:"",digestKnown:false,observedAt,snapshot:{runtimeState,activeRequests,managedTemporary,pinned}});const stores=createJobStores(db,{now:()=>NOW}),service=new PolicyService(db,{clock:()=>NOW,stores});assert.ok(service.install(policy,owner).ok);return{db,repositories,stores,policyService:service};}

test("verified load succeeds and stale post-observation fails closed",()=>{for(const stale of [false,true]){const x=setup("unloaded");try{const i=intent("load",stale?"2".repeat(64):"1".repeat(64)),r=request("load",i.requestId,i),wire={send:()=>({requestId:r.requestId,jobId:r.jobId,hostId:r.hostId,sequence:1,status:"succeeded",progress:100,observedAt:AFTER,observation:{observedAt:stale?NOW:AFTER,runtimeState:"loaded-idle",providerId:"provider-1",canonicalModelName:"acme/bert:latest"},errorCode:null})},lifecycle=new LifecycleService(x.policyService,new CommandDispatcher(x.stores,wire,()=>NOW),x.repositories),result=lifecycle.execute({intent:i,request:r});assert.equal(result.ok,!stale,JSON.stringify(result));if(!result.ok)assert.equal(result.error,"ERR_LIFECYCLE_OBSERVATION");assert.equal(x.stores.jobs.get(r.jobId)?.payload.state,stale?"failed":"succeeded");if(!stale){const replay=lifecycle.execute({intent:i,request:r});assert.ok(replay.ok);const divergent={...r,params:{providerId:"provider-1",model:"acme/bert:latest",keepAlive:"45s"}};assert.deepEqual(lifecycle.execute({intent:i,request:divergent}),{ok:false,error:"ERR_LIFECYCLE_DISPATCH"});}}finally{x.db.close();}}});

test("active unload requires and dispatches a verified drain first",()=>{const x=setup("serving",2);try{const ui=intent("unload","3".repeat(64)),ur=request("unload",ui.requestId,ui),di=intent("drain","4".repeat(64)),dr=request("drain",di.requestId,di),calls:string[]=[],wire={send:(r:any)=>{calls.push(r.operation);return{requestId:r.requestId,jobId:r.jobId,hostId:r.hostId,sequence:r.sequence,status:"succeeded",progress:100,observedAt:AFTER,observation:r.operation==="drain"?{observedAt:AFTER,runtimeState:"loaded-idle",activeRequests:0,providerId:"provider-1",canonicalModelName:"acme/bert:latest"}:{observedAt:AFTER,runtimeState:"unloaded",activeRequests:0,providerId:"provider-1",canonicalModelName:"acme/bert:latest"},errorCode:null}}},lifecycle=new LifecycleService(x.policyService,new CommandDispatcher(x.stores,wire,()=>NOW),x.repositories);const missing=lifecycle.execute({intent:ui,request:ur});assert.deepEqual(missing,{ok:false,error:"ERR_LIFECYCLE_STATE"},JSON.stringify(missing));const result=lifecycle.execute({intent:ui,request:ur,drainIntent:di,drainRequest:dr});assert.ok(result.ok);assert.deepEqual(calls,["drain","unload"]);}finally{x.db.close();}});

test("idle/options and managed-artifact preconditions fail closed",()=>{const x=setup("serving",1,false,true);try{for(const operation of ["set-options","remove-managed-artifact"] as const){const i=intent(operation,operation==="set-options"?"5".repeat(64):"6".repeat(64)),r=request(operation,i.requestId,i),wire={send:()=>{throw new Error("must not dispatch")}},lifecycle=new LifecycleService(x.policyService,new CommandDispatcher(x.stores,wire,()=>NOW),x.repositories);const result=lifecycle.execute({intent:i,request:r});assert.deepEqual(result,{ok:false,error:"ERR_LIFECYCLE_STATE"});}}finally{x.db.close();}});

test("hard policy denials, request binding, target binding, and unknown activity fail closed",()=>{const x=setup("unloaded",0);try{const base=intent("load","7".repeat(64)),r=request("load",base.requestId,base);let sent=0;const wire={send:()=>{sent++;throw new Error("must not dispatch")}},lifecycle=new LifecycleService(x.policyService,new CommandDispatcher(x.stores,wire,()=>NOW),x.repositories);const stale={...base,requestId:"8".repeat(64),observationFresh:false},staleRequest=request("load",stale.requestId,stale);assert.deepEqual(lifecycle.execute({intent:stale,request:staleRequest}),{ok:false,error:"ERR_LIFECYCLE_CAPABILITY"});assert.deepEqual(lifecycle.execute({intent:base,request:{...r,requestId:"9".repeat(64)}}),{ok:false,error:"ERR_LIFECYCLE_INPUT"});assert.deepEqual(lifecycle.execute({intent:base,request:{...r,params:{providerId:"other-provider",model:"acme/bert:latest"}}}),{ok:false,error:"ERR_LIFECYCLE_STATE"});assert.equal(sent,0);}finally{x.db.close();}});

test("wire failure is durably terminal instead of stranding a dispatched job",()=>{const x=setup("unloaded");try{const i=intent("load","a".repeat(64)),r=request("load",i.requestId,i),dispatcher=new CommandDispatcher(x.stores,{send:()=>{throw new Error("secret")}},()=>NOW),lifecycle=new LifecycleService(x.policyService,dispatcher,x.repositories),result=lifecycle.execute({intent:i,request:r});assert.deepEqual(result,{ok:false,error:"ERR_LIFECYCLE_DISPATCH"});assert.equal(x.stores.jobs.get(r.jobId)?.payload.state,"failed");const replay=lifecycle.execute({intent:i,request:r});assert.ok(replay.ok);assert.equal(replay.state,"failed");}finally{x.db.close();}});

test("authoritative admission accounting blocks unload until admission stopped and leases reach zero",async()=>{const x=setup("loaded-idle",0);try{const i=intent("unload","8".repeat(64)),r=request("unload",i.requestId,i),wire={send:()=>({requestId:r.requestId,jobId:r.jobId,hostId:r.hostId,sequence:1,status:"succeeded",progress:100,observedAt:AFTER,observation:{observedAt:AFTER,runtimeState:"unloaded",activeRequests:0,providerId:"provider-1",canonicalModelName:"acme/bert:latest"},errorCode:null})},admissions=createAdmissionController({clock:()=>NOW});admissions.register("model-1");const lease=admissions.acquire("model-1","request-1"),lifecycle=new LifecycleService(x.policyService,new CommandDispatcher(x.stores,wire,()=>NOW),x.repositories,admissions);assert.deepEqual(lifecycle.execute({intent:i,request:r}),{ok:false,error:"ERR_LIFECYCLE_STATE"});const drained=admissions.stopAdmission("model-1");lease.release();await drained;assert.equal(lifecycle.execute({intent:i,request:r}).ok,true);}finally{x.db.close();}});

test("unknown authoritative accounting fails lifecycle closed",()=>{const x=setup("loaded-idle",0);try{const i=intent("unload","9".repeat(64)),r=request("unload",i.requestId,i),wire={send:()=>{throw new Error("must not dispatch");}},admissions=createAdmissionController({clock:()=>NOW}),lifecycle=new LifecycleService(x.policyService,new CommandDispatcher(x.stores,wire,()=>NOW),x.repositories,admissions);assert.deepEqual(lifecycle.execute({intent:i,request:r}),{ok:false,error:"ERR_LIFECYCLE_STATE"});}finally{x.db.close();}});

test("missing active-request observation is never treated as idle",()=>{const x=setup("loaded-idle",0);try{x.repositories.models.upsert({modelId:"model-1",providerId:"provider-1",hostId:"host-1",canonicalName:"acme/bert:latest",state:"running",type:"llm",digest:"",digestKnown:false,observedAt:AFTER,snapshot:{runtimeState:"loaded-idle",managedTemporary:true,pinned:false}});const i=intent("unload","b".repeat(64)),r=request("unload",i.requestId,i),lifecycle=new LifecycleService(x.policyService,new CommandDispatcher(x.stores,{send:()=>{throw new Error("must not dispatch")}},()=>NOW),x.repositories);assert.deepEqual(lifecycle.execute({intent:i,request:r}),{ok:false,error:"ERR_LIFECYCLE_STATE"});}finally{x.db.close();}});
