import type { GuardResult } from "./guard.js";
import { guardManagementRequest } from "./guard.js";
import type { SessionManager } from "./session-manager.js";
import type { FleetQueryService } from "./fleet-queries.js";
import type { JobStores } from "./jobs-store.js";
import type { PolicyService } from "./policy-service.js";
import type { InferenceTokenManager } from "./inference-manager.js";
import { parseSessionCookieHeader } from "./cookie-parser.js";
import type { OriginPolicyOptions } from "./origin.js";

export const MANAGEMENT_BODY_LIMIT = 65_536;
export interface ManagementHttpRequest { readonly method: string; readonly url: string; readonly headers: unknown; readonly body?: string | null }
export interface ManagementHttpResponse { readonly status: number; readonly headers: Readonly<Record<string,string>>; readonly body: Readonly<Record<string,unknown>> }
export interface ManagementApiDependencies { readonly sessions: SessionManager; readonly allowedOrigins: readonly string[]; readonly fleet: FleetQueryService; readonly jobs: JobStores; readonly policy: PolicyService; readonly inference: InferenceTokenManager; readonly originOptions?: OriginPolicyOptions }

type Headers = Readonly<Record<string,string>>;
const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const STATES=new Set(["submitted","validated","authorized","dispatched","accepted","running","succeeded","failed","timed-out","cancelled"]);
const RESPONSE_HEADERS=Object.freeze(Object.assign(Object.create(null),{"content-type":"application/json; charset=utf-8","cache-control":"no-store"})) as Headers;
function ownRecord(value:unknown):Record<string,PropertyDescriptor>|null{try{if(typeof value!=="object"||value===null||Array.isArray(value))return null;const p=Object.getPrototypeOf(value);if(p!==Object.prototype&&p!==null)return null;const d=Object.getOwnPropertyDescriptors(value);if(Reflect.ownKeys(value).some(k=>{if(typeof k!=="string")return true;const descriptor=d[k];return !descriptor||!("value" in descriptor);} ))return null;return d;}catch{return null;}}
function headers(value:unknown):Headers|null{const d=ownRecord(value);if(!d)return null;const out=Object.create(null) as Record<string,string>;for(const [raw,v] of Object.entries(d)){if(!/^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(raw)||typeof v.value!=="string"||/[\u0000-\u001f\u007f]/u.test(v.value))return null;const key=raw.toLowerCase();if(key in out)return null;out[key]=v.value;}return Object.freeze(out);}
function deep(value:unknown,seen=new Set<object>()):unknown{if(value===null||typeof value==="string"||typeof value==="boolean"||typeof value==="number")return value;if(typeof value!=="object")return null;if(seen.has(value))return null;seen.add(value);if(Array.isArray(value))return Object.freeze(value.map(v=>deep(v,seen)));const out=Object.create(null) as Record<string,unknown>;for(const key of Object.keys(value as object).sort()){if(/(?:token|cookie|authorization|certificate|digest|snapshot|endpoint|private)/i.test(key))continue;let item:unknown;try{item=(value as Record<string,unknown>)[key];}catch{continue;}out[key]=deep(item,seen);}return Object.freeze(out);}
function response(status:number,ok:boolean,value?:unknown,code?:string):ManagementHttpResponse{const payload=ok?{ok:true,value:deep(value)}:{ok:false,error:Object.freeze(Object.assign(Object.create(null),{code:code??"INTERNAL_ERROR",message:message(code)}))};return Object.freeze({status,headers:RESPONSE_HEADERS,body:Object.freeze(Object.assign(Object.create(null),payload))});}
function message(code?:string):string{switch(code){case"UNAUTHORIZED":return"Authentication required.";case"FORBIDDEN":return"Request forbidden.";case"NOT_FOUND":return"Resource not found.";case"METHOD_NOT_ALLOWED":return"Method not allowed.";case"UNSUPPORTED_MEDIA_TYPE":return"JSON content type required.";case"PAYLOAD_TOO_LARGE":return"Request body too large.";case"INVALID_REQUEST":return"Invalid request.";case"CONFLICT":return"Request conflicts with current state.";default:return"Request failed.";}}
function query(url:URL):Record<string,unknown>|null{const allowed=new Set(["limit","cursor","platform","health","state"]);const out=Object.create(null) as Record<string,unknown>;for(const [key,value] of url.searchParams){if(!allowed.has(key)||key in out)return null;if(key==="limit"){if(!/^\d+$/.test(value))return null;out.limit=Number(value);}else out[key]=value;}return out;}
function jsonBody(request:ManagementHttpRequest,h:Headers):{ok:true;value:unknown}|{ok:false;response:ManagementHttpResponse}{const raw=request.body??"";if(typeof raw!=="string")return{ok:false,response:response(400,false,undefined,"INVALID_REQUEST")};if(Buffer.byteLength(raw)>MANAGEMENT_BODY_LIMIT)return{ok:false,response:response(413,false,undefined,"PAYLOAD_TOO_LARGE")};const type=(h["content-type"]??"").split(";",1)[0]?.trim().toLowerCase();if(type!=="application/json")return{ok:false,response:response(415,false,undefined,"UNSUPPORTED_MEDIA_TYPE")};try{return{ok:true,value:JSON.parse(raw)}}catch{return{ok:false,response:response(400,false,undefined,"INVALID_REQUEST")}}}
function statusFor(error:string):number{return /UNAUTHORIZED/.test(error)?401:/NOT_FOUND/.test(error)?404:/INPUT/.test(error)?400:/DENIED|APPROVAL|CAPABILITY|STATE|CONFLICT/.test(error)?409:500;}
function result(value:any):ManagementHttpResponse{return value&&value.ok===true?response(200,true,value.value??{state:value.state,observation:value.observation}):response(statusFor(String(value?.error??"")),false,undefined,statusFor(String(value?.error??""))===400?"INVALID_REQUEST":statusFor(String(value?.error??""))===404?"NOT_FOUND":statusFor(String(value?.error??""))===409?"CONFLICT":"INTERNAL_ERROR");}
function actorBound(input:unknown,guard:GuardResult):unknown{const d=ownRecord(input);if(!d||!guard.ok)return input;const out:Object=Object.create(null);for(const [k,v] of Object.entries(d))(out as Record<string,unknown>)[k]=v.value;(out as Record<string,unknown>).actorKind="owner";(out as Record<string,unknown>).actorId=guard.session.ownerId;return out;}
function publicJob(row:any){return{jobId:row.jobId,state:row.state,hostId:row.hostId,submittedAt:row.submittedAt,updatedAt:row.updatedAt,attempt:row.attempt};}
function publicHistory(row:any){return{cursor:row.cursor,jobId:row.jobId,fromState:row.fromState,toState:row.toState,attempt:row.attempt,occurredAt:row.occurredAt};}
function publicAudit(row:any){return{sequence:row.sequence,occurredAt:row.occurredAt,actorKind:row.actorKind,action:row.action,outcome:row.outcome,jobId:row.jobId??null,hostId:row.hostId??null};}
function publicToken(row:any){return{tokenId:row.tokenId,label:row.label,scopes:row.scopes,createdAt:row.createdAt,lastUsedAt:row.lastUsedAt,expiresAt:row.expiresAt,revokedAt:row.revokedAt};}
function issuedToken(value:any):ManagementHttpResponse{if(!value||typeof value.token!=="string"||! /^[A-Za-z0-9_-]{43}$/.test(value.token)||!value.metadata)return response(500,false,undefined,"INTERNAL_ERROR");return Object.freeze({status:200,headers:RESPONSE_HEADERS,body:Object.freeze(Object.assign(Object.create(null),{ok:true,value:Object.freeze(Object.assign(Object.create(null),{token:value.token,metadata:deep(publicToken(value.metadata))}))}))});}

/** Pure, dependency-injected management router. It never starts a listener. */
export async function routeManagementRequest(deps:ManagementApiDependencies,input:unknown):Promise<ManagementHttpResponse>{
 const d=ownRecord(input);if(!d)return response(400,false,undefined,"INVALID_REQUEST");const allowed=["method","url","headers","body"];if(Reflect.ownKeys(input as object).some(k=>typeof k!=="string"||!allowed.includes(k as string))||!d.method||!d.url||!d.headers)return response(400,false,undefined,"INVALID_REQUEST");const method=d.method.value,urlText=d.url.value;if(typeof method!=="string"||!/^[A-Z]+$/.test(method)||typeof urlText!=="string")return response(400,false,undefined,"INVALID_REQUEST");const h=headers(d.headers.value);if(!h)return response(400,false,undefined,"INVALID_REQUEST");let url:URL;try{url=new URL(urlText,"http://127.0.0.1");}catch{return response(400,false,undefined,"INVALID_REQUEST");}if(url.origin!=="http://127.0.0.1"||!url.pathname.startsWith("/api/v1/"))return response(404,false,undefined,"NOT_FOUND");
 const guard=guardManagementRequest(deps.sessions,deps.allowedOrigins,{method,cookieHeader:h.cookie??"",originHeader:h.origin??null,csrfHeader:h["x-csrf-token"]??null},deps.originOptions);if(!guard.ok)return response(guard.status,false,undefined,guard.code);
 const q=query(url);if(!q)return response(400,false,undefined,"INVALID_REQUEST");const path=url.pathname;if(path==="/api/v1/lifecycle/operations"||path==="/api/v1/lifecycle/cancel")return response(405,false,undefined,"METHOD_NOT_ALLOWED");
 try{
  if(method==="GET"&&path==="/api/v1/fleet/hosts")return result(deps.fleet.listHosts(q,guard));
  if(method==="GET"&&path==="/api/v1/fleet/summary")return result(deps.fleet.summary(guard));
  let m=path.match(/^\/api\/v1\/fleet\/hosts\/([^/]+)$/);if(method==="GET"&&m)return result(deps.fleet.getHost(decodeURIComponent(m[1]!),guard));
  m=path.match(/^\/api\/v1\/fleet\/hosts\/([^/]+)\/(providers|models)$/);if(method==="GET"&&m)return result(m[2]==="providers"?deps.fleet.listProviders(decodeURIComponent(m[1]!),guard):deps.fleet.listModels(decodeURIComponent(m[1]!),guard));
  if(method==="GET"&&path==="/api/v1/jobs"){const state=q.state,limit=q.limit??100,cursor=q.cursor??"";if(typeof state!=="string"||!STATES.has(state)||!Number.isSafeInteger(limit)||Number(limit)<1||Number(limit)>200||typeof cursor!=="string"||(cursor!==""&&!ID.test(cursor)))return response(400,false,undefined,"INVALID_REQUEST");const rows=deps.jobs.jobs.listAfter(state,cursor,Number(limit)+1),more=rows.length>Number(limit),items=rows.slice(0,Number(limit));return response(200,true,{items:items.map(publicJob),nextCursor:more?items.at(-1)!.jobId:null});}
  m=path.match(/^\/api\/v1\/jobs\/([^/]+)\/history$/);if(method==="GET"&&m){const limit=q.limit??100,cursor=q.cursor===undefined?0:Number(q.cursor);if(!Number.isSafeInteger(limit)||Number(limit)<1||Number(limit)>200||!Number.isSafeInteger(cursor)||cursor<0)return response(400,false,undefined,"INVALID_REQUEST");const rows=deps.jobs.jobs.listHistoryAfter(decodeURIComponent(m[1]!),cursor,Number(limit)+1),more=rows.length>Number(limit),items=rows.slice(0,Number(limit));return response(200,true,{items:items.map(publicHistory),nextCursor:more?items.at(-1)!.cursor:null});}
  if(method==="GET"&&path==="/api/v1/audit"){const limit=q.limit??100,cursor=q.cursor===undefined?0:Number(q.cursor);if(!Number.isSafeInteger(limit)||Number(limit)<1||Number(limit)>200||!Number.isSafeInteger(cursor)||cursor<0)return response(400,false,undefined,"INVALID_REQUEST");const rows=deps.jobs.audit.listAfter(cursor,Number(limit)+1),more=rows.length>Number(limit),items=rows.slice(0,Number(limit));return response(200,true,{items:items.map(publicAudit),nextCursor:more?items.at(-1)!.sequence:null});}
  if(method==="GET"&&path==="/api/v1/policy/approvals")return result(deps.policy.pending(guard));
  if(method==="GET"&&path==="/api/v1/policy/settings")return result(deps.policy.settings(guard));
  const sessionToken=parseSessionCookieHeader(h.cookie??"");
  if(method==="GET"&&path==="/api/v1/inference/tokens")return response(200,true,(await deps.inference.list(sessionToken)).map(publicToken));
  const knownPost=new Set(["/api/v1/policy/install","/api/v1/policy/evaluate","/api/v1/policy/approve","/api/v1/policy/convenience","/api/v1/inference/tokens","/api/v1/inference/tokens/revoke","/api/v1/inference/tokens/revoke-all"]);if(method==="POST"&&knownPost.has(path)){const parsed=jsonBody(input as ManagementHttpRequest,h);if(!parsed.ok)return parsed.response;const bd=ownRecord(parsed.value);if(!bd)return response(400,false,undefined,"INVALID_REQUEST");if(path==="/api/v1/policy/install")return result(deps.policy.install(parsed.value,guard));if(path==="/api/v1/policy/convenience")return result(deps.policy.setConvenience(parsed.value,guard));if(path==="/api/v1/inference/tokens"){const issued=await deps.inference.issue(sessionToken,parsed.value);return issued?issuedToken(issued):response(401,false,undefined,"UNAUTHORIZED");}if(path==="/api/v1/inference/tokens/revoke"){if(Reflect.ownKeys(parsed.value as object).length!==1||typeof bd.tokenId?.value!=="string"||!ID.test(bd.tokenId.value))return response(400,false,undefined,"INVALID_REQUEST");return response(200,true,{revoked:await deps.inference.revoke(sessionToken,bd.tokenId.value)});}if(path==="/api/v1/inference/tokens/revoke-all"){if(Reflect.ownKeys(parsed.value as object).length!==0)return response(400,false,undefined,"INVALID_REQUEST");return response(200,true,{revoked:await deps.inference.revokeAll(sessionToken)});}if(path==="/api/v1/policy/evaluate")return result(deps.policy.authorize(actorBound(parsed.value,guard)));if(path==="/api/v1/policy/approve"){if(Reflect.ownKeys(parsed.value as object).length!==1||typeof bd.requestId?.value!=="string")return response(400,false,undefined,"INVALID_REQUEST");return result(deps.policy.approve(bd.requestId.value,guard));}}
  const known=["/api/v1/fleet/hosts","/api/v1/fleet/summary","/api/v1/jobs","/api/v1/audit","/api/v1/policy/approvals","/api/v1/policy/settings","/api/v1/inference/tokens",...knownPost];if(known.includes(path)||/^\/api\/v1\/fleet\/hosts\/[^/]+(?:\/(?:providers|models))?$/.test(path)||/^\/api\/v1\/jobs\/[^/]+\/history$/.test(path))return response(405,false,undefined,"METHOD_NOT_ALLOWED");return response(404,false,undefined,"NOT_FOUND");
 }catch{return response(500,false,undefined,"INTERNAL_ERROR");}
}
