import type { DiscoveryCandidate, PairingRecord } from "@lan-model-manager/core";
import type { ControllerRuntimeHandle } from "./controller-runtime.js";
import { createDatabaseBackup, preflightDatabaseBackup } from "./database-backup.js";

const ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const HEX=/^[a-f0-9]{64}$/;
const NAME=/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
const VERSION=/^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$/;
const TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const frozen=<T>(value:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),value)) as T;

export type OperatorErrorCode="ERR_OPERATOR_INPUT"|"ERR_OPERATOR_NOT_FOUND"|"ERR_OPERATOR_CONFLICT"|"ERR_OPERATOR_UNAVAILABLE"|"ERR_OPERATOR_FAILED";
export class OperatorError extends Error{readonly code:OperatorErrorCode;constructor(code:OperatorErrorCode){super(code);this.name="OperatorError";this.code=code;}}

export interface OperatorDiscoverySource{list():readonly DiscoveryCandidate[];query?():void;start?():void;stop?():void}
export interface OperatorPackageMetadata{readonly supported:boolean;readonly role:"controller";readonly currentVersion:string;readonly packageName:string|null;readonly sha256:string|null;readonly unsigned:boolean;readonly sourceCommit:string|null;readonly rollbackVersion:string|null}
export interface OperatorPackageResult{readonly operation:"upgrade"|"rollback";readonly changed:boolean;readonly rolledBack:boolean;readonly previousVersion:string|null;readonly currentVersion:string;readonly checksumVerified:boolean}
export interface OperatorPackageManager{metadata():Promise<OperatorPackageMetadata>|OperatorPackageMetadata;upgrade(input:{version:string;packageName:string;sha256:string}):Promise<OperatorPackageResult>;rollback(input:{version:string}):Promise<OperatorPackageResult>}
export interface OperatorServiceOptions{readonly discovery?:OperatorDiscoverySource;readonly packages?:OperatorPackageManager;readonly clock?:()=>string}

export interface SetupStatusDto{readonly ownerInitialized:boolean;readonly caReady:boolean;readonly discoveredCandidates:number;readonly enrolledHosts:number;readonly activeCertificates:number;readonly packageManagement:boolean;readonly backupSupported:true}
export interface CaExportDto{readonly fingerprint:string;readonly version:number;readonly notBefore:string;readonly notAfter:string;readonly pem:string}
export interface CandidateDto{readonly candidateId:string;readonly displayName:string;readonly address:string;readonly port:number;readonly platform:"linux"|"darwin"|"windows";readonly protocolMajor:number;readonly protocolMinor:number;readonly firstSeen:string;readonly lastSeen:string;readonly expiresAt:string;readonly trustState:"untrusted"}
export interface PairingPresentationDto{readonly challengeId:string;readonly state:"presented";readonly code:string;readonly binding:{readonly candidateId:string;readonly address:string;readonly port:number;readonly protocolMajor:number;readonly protocolMinor:number};readonly createdAt:string;readonly expiresAt:string}
export interface PairingStatusDto{readonly challengeId:string;readonly state:string;readonly candidateId:string;readonly address:string;readonly failedAttempts:number;readonly createdAt:string;readonly expiresAt:string;readonly updatedAt:string;readonly enrolled:boolean}
export interface CertificateDto{readonly certificateId:string;readonly candidateId:string;readonly fingerprint:string;readonly serial:string;readonly status:"active"|"revoked";readonly notBefore:string;readonly notAfter:string;readonly issuedAt:string;readonly revokedAt:string|null}
export interface BackupExportDto{readonly databaseFile:string;readonly manifestFile:string;readonly sha256:string;readonly schemaVersion:number;readonly pages:number}
export interface RestorePreflightDto{readonly databaseFile:string;readonly sha256:string;readonly schemaVersion:number;readonly pages:number;readonly integrity:"ok";readonly compatible:true}
export interface DiagnosticsDto{readonly generatedAt:string;readonly schemaVersion:number;readonly runtimeState:"created"|"active"|"stopped";readonly counts:{readonly hosts:number;readonly providers:number;readonly models:number;readonly activeCertificates:number;readonly revokedCertificates:number;readonly activePairings:number};readonly checks:{readonly database:"ok";readonly ca:"ready"|"not-initialized";readonly packageManagement:"available"|"unavailable"};readonly redacted:true}

function exact(input:unknown,keys:readonly string[]):Record<string,unknown>{try{if(typeof input!=="object"||input===null||Array.isArray(input))throw 0;const p=Object.getPrototypeOf(input);if(p!==Object.prototype&&p!==null)throw 0;const own=Reflect.ownKeys(input),d=Object.getOwnPropertyDescriptors(input);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k)||!d[k]||!("value" in d[k]!)))throw 0;return Object.fromEntries(keys.map(k=>[k,d[k]!.value]));}catch{throw new OperatorError("ERR_OPERATOR_INPUT");}}
function validTime(value:string):boolean{return TIME.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value).toISOString()===value;}
function candidateDto(value:DiscoveryCandidate):CandidateDto{return frozen({candidateId:value.id,displayName:value.displayName,address:value.address,port:value.agentPort,platform:value.platform,protocolMajor:value.protocolVersion.major,protocolMinor:value.protocolVersion.minor,firstSeen:value.firstSeen,lastSeen:value.lastSeen,expiresAt:value.expiresAt,trustState:"untrusted"});}
function pairingDto(value:PairingRecord,enrolled:boolean):PairingStatusDto{return frozen({challengeId:value.challengeId,state:value.state,candidateId:value.binding.candidateId,address:value.binding.address,failedAttempts:value.failedAttempts,createdAt:value.createdAt,expiresAt:value.expiresAt,updatedAt:value.updatedAt,enrolled});}
function validPackage(value:unknown):OperatorPackageMetadata{const d=exact(value,["supported","role","currentVersion","packageName","sha256","unsigned","sourceCommit","rollbackVersion"]);if(typeof d.supported!=="boolean"||d.role!=="controller"||typeof d.currentVersion!=="string"||!VERSION.test(d.currentVersion)||(d.packageName!==null&&(typeof d.packageName!=="string"||!NAME.test(d.packageName)))||(d.sha256!==null&&(typeof d.sha256!=="string"||!HEX.test(d.sha256)))||d.unsigned!==true||(d.sourceCommit!==null&&(typeof d.sourceCommit!=="string"||!/^[a-f0-9]{40}(?:[a-f0-9]{24})?$/.test(d.sourceCommit)))||(d.rollbackVersion!==null&&(typeof d.rollbackVersion!=="string"||!VERSION.test(d.rollbackVersion))))throw new OperatorError("ERR_OPERATOR_FAILED");return frozen(d) as OperatorPackageMetadata;}
function validPackageResult(value:unknown,operation:"upgrade"|"rollback"):OperatorPackageResult{const d=exact(value,["operation","changed","rolledBack","previousVersion","currentVersion","checksumVerified"]);if(d.operation!==operation||typeof d.changed!=="boolean"||typeof d.rolledBack!=="boolean"||(d.previousVersion!==null&&(typeof d.previousVersion!=="string"||!VERSION.test(d.previousVersion)))||typeof d.currentVersion!=="string"||!VERSION.test(d.currentVersion)||typeof d.checksumVerified!=="boolean")throw new OperatorError("ERR_OPERATOR_FAILED");return frozen(d) as OperatorPackageResult;}

/** Owner-guarded controller workflows. The service returns only explicitly public DTOs. */
export class ControllerOperatorService{
 private readonly discovery:OperatorDiscoverySource;private readonly packages:OperatorPackageManager|undefined;private readonly clock:()=>string;
 constructor(private readonly runtime:ControllerRuntimeHandle,options:OperatorServiceOptions={}){this.discovery=options.discovery??{list:()=>Object.freeze([])};this.packages=options.packages;this.clock=options.clock??(()=>new Date().toISOString());}
 async setupStatus():Promise<SetupStatusDto>{const certs=this.runtime.services.certificates.listHosts(),metadata=await this.packageMetadata();return frozen({ownerInitialized:this.runtime.services.owner.isInitialized(),caReady:this.runtime.services.certificates.getCa()!==null,discoveredCandidates:this.discovery.list().length,enrolledHosts:new Set(certs.filter(c=>c.status==="active").map(c=>c.binding.candidateId)).size,activeCertificates:certs.filter(c=>c.status==="active").length,packageManagement:metadata.supported,backupSupported:true});}
 ca():CaExportDto|null{const value=this.runtime.services.certificates.getCa();return value?frozen({fingerprint:value.fingerprint,version:value.version,notBefore:value.notBefore,notAfter:value.notAfter,pem:value.certificatePem}):null;}
 initializeCa():CaExportDto{try{const value=this.runtime.services.certificates.initialize();return frozen({fingerprint:value.fingerprint,version:value.version,notBefore:value.notBefore,notAfter:value.notAfter,pem:value.certificatePem});}catch{throw new OperatorError("ERR_OPERATOR_FAILED");}}
 candidates(refresh=false):readonly CandidateDto[]{if(refresh)try{this.discovery.query?.();}catch{}return Object.freeze(this.discovery.list().map(candidateDto));}
 beginPairing(input:unknown):PairingPresentationDto{const d=exact(input,["candidateId","address"]);if(typeof d.candidateId!=="string"||!ID.test(d.candidateId)||typeof d.address!=="string")throw new OperatorError("ERR_OPERATOR_INPUT");const candidate=this.discovery.list().find(c=>c.id===d.candidateId&&c.address===d.address);if(!candidate)throw new OperatorError("ERR_OPERATOR_NOT_FOUND");const presentation=this.runtime.services.pairing.createAuthorized(candidate);if(!presentation)throw new OperatorError("ERR_OPERATOR_CONFLICT");const record=this.runtime.services.pairing.present(presentation.challengeId);if(!record)throw new OperatorError("ERR_OPERATOR_CONFLICT");return frozen({challengeId:presentation.challengeId,state:"presented",code:presentation.code,binding:presentation.binding,createdAt:presentation.createdAt,expiresAt:presentation.expiresAt});}
 pairingStatus(challengeId:unknown):PairingStatusDto{if(typeof challengeId!=="string"||!HEX.test(challengeId))throw new OperatorError("ERR_OPERATOR_INPUT");const value=this.runtime.services.pairing.get(challengeId);if(!value)throw new OperatorError("ERR_OPERATOR_NOT_FOUND");const enrolled=this.runtime.services.certificates.listHosts().some(c=>c.challengeId===challengeId&&c.status==="active");return pairingDto(value,enrolled);}
 confirmPairing(input:unknown):PairingStatusDto{const d=exact(input,["challengeId","code"]);if(typeof d.challengeId!=="string"||!HEX.test(d.challengeId)||typeof d.code!=="string")throw new OperatorError("ERR_OPERATOR_INPUT");const current=this.runtime.services.pairing.get(d.challengeId);if(!current)throw new OperatorError("ERR_OPERATOR_NOT_FOUND");const value=this.runtime.services.pairing.confirmAuthorized({challengeId:d.challengeId,code:d.code,binding:current.binding});if(!value)throw new OperatorError("ERR_OPERATOR_CONFLICT");return pairingDto(value,false);}
 cancelPairing(input:unknown):PairingStatusDto{const d=exact(input,["challengeId"]);if(typeof d.challengeId!=="string"||!HEX.test(d.challengeId))throw new OperatorError("ERR_OPERATOR_INPUT");if(!this.runtime.services.pairing.cancelAuthorized(d.challengeId))throw new OperatorError("ERR_OPERATOR_CONFLICT");return this.pairingStatus(d.challengeId);}
 certificates():readonly CertificateDto[]{return Object.freeze(this.runtime.services.certificates.listHosts().map(c=>frozen<CertificateDto>({certificateId:c.certificateId,candidateId:c.binding.candidateId,fingerprint:c.fingerprint,serial:c.serial,status:c.status,notBefore:c.notBefore,notAfter:c.notAfter,issuedAt:c.issuedAt,revokedAt:c.revokedAt})));}
 revokeCertificate(input:unknown):CertificateDto{const d=exact(input,["certificateId"]);if(typeof d.certificateId!=="string"||!HEX.test(d.certificateId))throw new OperatorError("ERR_OPERATOR_INPUT");const before=this.runtime.services.certificates.getHost(d.certificateId);if(!before)throw new OperatorError("ERR_OPERATOR_NOT_FOUND");const db=this.runtime.repositories.db,now=this.now();try{db.exec("BEGIN IMMEDIATE");if(!this.runtime.services.certificates.revoke(d.certificateId)){db.exec("ROLLBACK");throw new OperatorError("ERR_OPERATOR_CONFLICT");}db.prepare("UPDATE fleet_liveness SET health='revoked',revoked_at=?,health_updated_at=? WHERE host_id=?").run(now,now,before.binding.candidateId);db.exec("COMMIT");}catch(error){try{db.exec("ROLLBACK");}catch{}if(error instanceof OperatorError)throw error;throw new OperatorError("ERR_OPERATOR_FAILED");}return this.certificates().find(c=>c.certificateId===d.certificateId)!;}
 reEnroll(input:unknown):PairingPresentationDto{const d=exact(input,["certificateId","address"]);if(typeof d.certificateId!=="string"||!HEX.test(d.certificateId)||typeof d.address!=="string")throw new OperatorError("ERR_OPERATOR_INPUT");const certificate=this.runtime.services.certificates.getHost(d.certificateId);if(!certificate)throw new OperatorError("ERR_OPERATOR_NOT_FOUND");if(certificate.status!=="revoked")throw new OperatorError("ERR_OPERATOR_CONFLICT");return this.beginPairing({candidateId:certificate.binding.candidateId,address:d.address});}
 renameHost(input:unknown):{readonly hostId:string;readonly displayName:string}{const d=exact(input,["hostId","displayName"]);if(typeof d.hostId!=="string"||!ID.test(d.hostId)||typeof d.displayName!=="string"||Buffer.byteLength(d.displayName)<1||Buffer.byteLength(d.displayName)>128||d.displayName.trim()!==d.displayName||/[\u0000-\u001f\u007f]/u.test(d.displayName))throw new OperatorError("ERR_OPERATOR_INPUT");const result=this.runtime.repositories.db.prepare("UPDATE hosts SET display_name=?,updated_at=? WHERE host_id=?").run(d.displayName,this.now(),d.hostId);if(result.changes!==1)throw new OperatorError("ERR_OPERATOR_NOT_FOUND");return frozen({hostId:d.hostId,displayName:d.displayName});}
 async packageMetadata():Promise<OperatorPackageMetadata>{if(!this.packages)return frozen({supported:false,role:"controller",currentVersion:"0.0.0",packageName:null,sha256:null,unsigned:true,sourceCommit:null,rollbackVersion:null});try{return validPackage(await this.packages.metadata());}catch(error){if(error instanceof OperatorError)throw error;throw new OperatorError("ERR_OPERATOR_FAILED");}}
 async upgrade(input:unknown):Promise<OperatorPackageResult>{const d=exact(input,["version","packageName","sha256"]);if(!this.packages)throw new OperatorError("ERR_OPERATOR_UNAVAILABLE");if(typeof d.version!=="string"||!VERSION.test(d.version)||typeof d.packageName!=="string"||!NAME.test(d.packageName)||typeof d.sha256!=="string"||!HEX.test(d.sha256))throw new OperatorError("ERR_OPERATOR_INPUT");try{return validPackageResult(await this.packages.upgrade({version:d.version,packageName:d.packageName,sha256:d.sha256}),"upgrade");}catch(error){if(error instanceof OperatorError)throw error;throw new OperatorError("ERR_OPERATOR_FAILED");}}
 async rollback(input:unknown):Promise<OperatorPackageResult>{const d=exact(input,["version"]);if(!this.packages)throw new OperatorError("ERR_OPERATOR_UNAVAILABLE");if(typeof d.version!=="string"||!VERSION.test(d.version))throw new OperatorError("ERR_OPERATOR_INPUT");try{return validPackageResult(await this.packages.rollback({version:d.version}),"rollback");}catch(error){if(error instanceof OperatorError)throw error;throw new OperatorError("ERR_OPERATOR_FAILED");}}
 async exportBackup(input:unknown):Promise<BackupExportDto>{const d=exact(input,["name"]);if(typeof d.name!=="string"||!NAME.test(d.name)||!d.name.endsWith(".sqlite3"))throw new OperatorError("ERR_OPERATOR_INPUT");try{const value=await createDatabaseBackup(this.runtime.repositories.db,this.runtime.plan.auditDir,d.name);return frozen({databaseFile:value.databaseFile,manifestFile:`${value.databaseFile}.manifest.json`,sha256:value.sha256,schemaVersion:value.schemaVersion,pages:value.pages});}catch{throw new OperatorError("ERR_OPERATOR_FAILED");}}
 async restorePreflight(input:unknown):Promise<RestorePreflightDto>{const d=exact(input,["manifestFile"]);if(typeof d.manifestFile!=="string"||!NAME.test(d.manifestFile)||!d.manifestFile.endsWith(".manifest.json"))throw new OperatorError("ERR_OPERATOR_INPUT");try{const value=await preflightDatabaseBackup(this.runtime.plan.auditDir,d.manifestFile),m=value.manifest;return frozen({databaseFile:m.databaseFile,sha256:m.sha256,schemaVersion:m.schemaVersion,pages:m.pages,integrity:value.integrity,compatible:value.compatible});}catch{throw new OperatorError("ERR_OPERATOR_FAILED");}}
 async diagnostics():Promise<DiagnosticsDto>{const db=this.runtime.repositories.db,scalar=(sql:string)=>Number((db.prepare(sql).get() as {count:number}).count),certs=this.runtime.services.certificates.listHosts(),pairings=scalar("SELECT count(*) AS count FROM pairing_challenges WHERE state IN ('created','presented','owner_confirmed','mutually_proven')"),metadata=await this.packageMetadata(),generatedAt=this.now();if(!validTime(generatedAt))throw new OperatorError("ERR_OPERATOR_FAILED");const state=this.runtime.isActive?"active":this.runtime.isClosed?"stopped":"created";return frozen({generatedAt,schemaVersion:Number((db.prepare("PRAGMA user_version").get() as {user_version:number}).user_version),runtimeState:state,counts:frozen({hosts:scalar("SELECT count(*) AS count FROM hosts"),providers:scalar("SELECT count(*) AS count FROM providers"),models:scalar("SELECT count(*) AS count FROM models"),activeCertificates:certs.filter(c=>c.status==="active").length,revokedCertificates:certs.filter(c=>c.status==="revoked").length,activePairings:pairings}),checks:frozen({database:"ok",ca:this.runtime.services.certificates.getCa()?"ready":"not-initialized",packageManagement:metadata.supported?"available":"unavailable"}),redacted:true});}
 private now():string{const value=this.clock();if(typeof value!=="string"||!validTime(value))throw new OperatorError("ERR_OPERATOR_FAILED");return value;}
}
