import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import { CONTROLLER_MIGRATIONS, migrateControllerDatabase, openControllerDatabase } from "./database.js";
import { PASSWORD_MAX_BYTES, PASSWORD_MIN_BYTES, SCRYPT_KEY_LENGTH, encodeCredential, hashPassword, normalizeUsername, parseCredential, validatePassword, verifyCredential, type PasswordCryptoEngine } from "./credentials.js";
import { OwnerRepository, OwnerRepositoryError } from "./owner-repository.js";
import { OwnerBootstrapError, createOwnerBootstrapService } from "./owner-service.js";

const NOW="2026-09-27T09:00:00.000Z",LATER="2026-09-27T10:00:00.000Z";
const deterministicEngine=():PasswordCryptoEngine&{deriveCalls:number;equalCalls:number}=>({
 deriveCalls:0,equalCalls:0,random:(size)=>Buffer.alloc(size,7),
 async derive(password,salt,parameters){this.deriveCalls++;const seed=createHash("sha256").update(password).update(salt).digest();return Buffer.alloc(parameters.keyLength,seed[0]);},
 equal(left,right){this.equalCalls++;return Buffer.from(left).equals(Buffer.from(right));},
});

test("migration3 creates a single-owner credential schema and migration2 upgrades",()=>{
 const dir=mkdtempSync(join(tmpdir(),"lanmm-owner-upgrade-"));try{const path=join(dir,"db.sqlite3");let db=new DatabaseSync(path);migrateControllerDatabase(db,CONTROLLER_MIGRATIONS.slice(0,2));assert.equal((db.prepare("PRAGMA user_version").get() as any).user_version,2);db.close();db=openControllerDatabase(path);assert.equal((db.prepare("PRAGMA user_version").get() as any).user_version,3);const columns=(db.prepare("PRAGMA table_info(owners)").all() as Array<{name:string}>).map(row=>row.name);assert.deepEqual(columns,["singleton_key","owner_id","username_display","username_normalized","credential_hash","disabled","credential_version","created_at","updated_at"]);db.close();}finally{rmSync(dir,{recursive:true,force:true});}
});

test("real async scrypt hashes round-trip with unique salts and no plaintext",async()=>{const password="correct horse battery staple";const first=await hashPassword(password),second=await hashPassword(password);assert.notEqual(first,second);assert.equal(first.includes(password),false);assert.equal(await verifyCredential(first,password),true);assert.equal(await verifyCredential(first,"incorrect password"),false);assert.ok(parseCredential(first));});

test("malformed and excessive credential parameters fail before derive",async()=>{const engine=deterministicEngine();const valid=await hashPassword("valid-password",engine);assert.equal(await verifyCredential(valid,"valid-password",engine),true);assert.equal(engine.deriveCalls,2);for(const bad of ["",valid.replace("$16384$","$999999999$"),valid.replace("$64$","$999$"),valid+"$extra",42])assert.equal(await verifyCredential(bad,"valid-password",engine),false);assert.equal(engine.deriveCalls,2);assert.equal(engine.equalCalls,1);});

test("password and username policy preserve Unicode secrets and normalize usernames only",()=>{assert.equal(PASSWORD_MIN_BYTES,12);assert.equal(validatePassword("12345678901"),false);assert.equal(validatePassword("pāssword-秘密-123"),true);assert.equal(validatePassword("12345678901\0x"),false);assert.equal(validatePassword("x".repeat(PASSWORD_MAX_BYTES+1)),false);assert.equal(normalizeUsername("Admin.User"),"admin.user");for(const bad of ["","a b","üser","../admin","x".repeat(65),null])assert.equal(normalizeUsername(bad),null);});

test("bootstrap is async, stores one owner, and public metadata never exposes hash or password",async()=>{const db=openControllerDatabase(":memory:");try{const engine=deterministicEngine();const service=createOwnerBootstrapService(db,{now:()=>NOW,ownerId:()=>"a".repeat(32),crypto:engine});const metadata=await service.bootstrapOwner({username:"Admin",password:"safe-password-123"});assert.deepEqual({...metadata},{ownerId:"a".repeat(32),username:"Admin",disabled:false,version:1,createdAt:NOW,updatedAt:NOW});assert.equal("credentialHash" in metadata,false);const row=db.prepare("SELECT * FROM owners").get() as Record<string,unknown>;assert.equal(row.username_normalized,"admin");assert.equal(JSON.stringify(row).includes("safe-password-123"),false);assert.equal(await service.authenticate({username:"ADMIN",password:"safe-password-123"}),true);assert.equal(await service.authenticate({username:"ADMIN",password:"wrong-password-123"}),false);}finally{db.close();}});

test("bootstrap input rejects accessors, symbols, prototypes, and revoked proxies before hashing",async()=>{const db=openControllerDatabase(":memory:");try{const engine=deterministicEngine();const service=createOwnerBootstrapService(db,{crypto:engine});let calls=0;const accessor=Object.defineProperty({password:"safe-password-123"},"username",{enumerable:true,get(){calls++;return"admin";}});const revoked=Proxy.revocable({username:"admin",password:"safe-password-123"},{});revoked.revoke();for(const bad of [accessor,{username:"admin",password:"safe-password-123",[Symbol("x")]:1},Object.assign(Object.create({}),{username:"admin",password:"safe-password-123"}),revoked.proxy])await assert.rejects(service.bootstrapOwner(bad),OwnerBootstrapError);assert.equal(calls,0);assert.equal(engine.deriveCalls,0);}finally{db.close();}});

test("second and concurrent bootstrap attempts leave exactly one owner",async()=>{const dir=mkdtempSync(join(tmpdir(),"lanmm-owner-race-"));try{const path=join(dir,"db.sqlite3");const db1=openControllerDatabase(path),db2=openControllerDatabase(path);const engine=deterministicEngine();const first=createOwnerBootstrapService(db1,{now:()=>NOW,ownerId:()=>"1".repeat(32),crypto:engine});const second=createOwnerBootstrapService(db2,{now:()=>NOW,ownerId:()=>"2".repeat(32),crypto:engine});const results=await Promise.allSettled([first.bootstrapOwner({username:"first",password:"first-password-123"}),second.bootstrapOwner({username:"second",password:"second-password-123"})]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);const rejected=results.find(result=>result.status==="rejected") as PromiseRejectedResult;assert.ok(rejected.reason instanceof OwnerBootstrapError);assert.equal((db1.prepare("SELECT count(*) AS count FROM owners").get() as any).count,1);await assert.rejects(first.bootstrapOwner({username:"third",password:"third-password-123"}),(error:unknown)=>error instanceof OwnerBootstrapError&&error.code==="ERR_OWNER_ALREADY_INITIALIZED");db1.close();db2.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("failed insert rolls back without a partial owner or leaked value",async()=>{const db=openControllerDatabase(":memory:");try{db.exec("CREATE TRIGGER reject_owner BEFORE INSERT ON owners BEGIN SELECT RAISE(ABORT,'secret-password-should-not-leak'); END;");const service=createOwnerBootstrapService(db,{now:()=>NOW,ownerId:()=>"b".repeat(32),crypto:deterministicEngine()});await assert.rejects(service.bootstrapOwner({username:"admin",password:"secret-password-123"}),(error:unknown)=>error instanceof OwnerBootstrapError&&error.code==="ERR_OWNER_BOOTSTRAP_DATABASE"&&!error.message.includes("secret"));assert.equal((db.prepare("SELECT count(*) AS count FROM owners").get() as any).count,0);}finally{db.close();}});

test("generic authentication uses the derive path for missing, wrong, disabled, and valid users",async()=>{const db=openControllerDatabase(":memory:");try{const engine=deterministicEngine();const service=createOwnerBootstrapService(db,{now:()=>NOW,ownerId:()=>"c".repeat(32),crypto:engine});await service.bootstrapOwner({username:"admin",password:"valid-password-123"});const before=engine.deriveCalls;assert.equal(await service.authenticate({username:"missing",password:"valid-password-123"}),false);assert.equal(await service.authenticate({username:"admin",password:"wrong-password-123"}),false);assert.equal(await service.authenticate({username:"admin",password:"valid-password-123"}),true);assert.equal(engine.deriveCalls,before+3);const repo=new OwnerRepository(db);const owner=repo.getMetadata()!;repo.setDisabled(owner.ownerId,owner.version,true,LATER);assert.equal(await service.authenticate({username:"admin",password:"valid-password-123"}),false);}finally{db.close();}});

test("owner metadata is frozen, credential lookup is narrow, and disable uses version CAS",async()=>{const db=openControllerDatabase(":memory:");try{const service=createOwnerBootstrapService(db,{now:()=>NOW,ownerId:()=>"d".repeat(32),crypto:deterministicEngine()});const created=await service.bootstrapOwner({username:"Owner",password:"owner-password-123"});assert.ok(Object.isFrozen(created)&&Object.getPrototypeOf(created)===null);const repo=new OwnerRepository(db);const credential=repo.findCredential("owner")!;assert.ok(Object.isFrozen(credential));assert.equal(credential.normalizedUsername,"owner");const disabled=repo.setDisabled(created.ownerId,1,true,LATER);assert.equal(disabled.disabled,true);assert.equal(disabled.version,2);assert.throws(()=>repo.setDisabled(created.ownerId,1,false,LATER),(error:unknown)=>error instanceof OwnerRepositoryError&&error.code==="ERR_OWNER_STALE");}finally{db.close();}});

test("owner and credential survive file reopen",async()=>{const dir=mkdtempSync(join(tmpdir(),"lanmm-owner-reopen-"));try{const path=join(dir,"db.sqlite3");let db=openControllerDatabase(path);let service=createOwnerBootstrapService(db,{now:()=>NOW,ownerId:()=>"e".repeat(32)});await service.bootstrapOwner({username:"Carol",password:"reopen-password-123"});db.close();db=openControllerDatabase(path);service=createOwnerBootstrapService(db);assert.equal(service.getOwner()?.username,"Carol");assert.equal(await service.authenticate({username:"carol",password:"reopen-password-123"}),true);db.close();}finally{rmSync(dir,{recursive:true,force:true});}});

test("generated hash has the declared key length",async()=>{const parsed=parseCredential(await hashPassword("length-check-password"));assert.ok(parsed);assert.equal(parsed.digest.length,SCRYPT_KEY_LENGTH);});
