import type { DatabaseSync } from "node:sqlite";
import { parsePairingRecord,type PairingBinding,type PairingRecord,type PairingState } from "@lan-model-manager/core";
import { PairingError,type NewPairingRow } from "./pairing-types.js";
const HEX64=/^[a-f0-9]{64}$/,TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;const validTime=(v:unknown):v is string=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
const fail=():never=>{throw new PairingError("ERR_PAIRING_DATABASE");};function query<T>(fn:()=>T):T{try{return fn();}catch(e){if(e instanceof PairingError)throw e;return fail();}}
function decode(row:Record<string,unknown>):PairingRecord{const parsed=parsePairingRecord({challengeId:row.challenge_id,state:row.state,version:row.version,ownerId:row.owner_id,ownerVersion:row.owner_version,binding:{candidateId:row.candidate_id,address:row.binding_address,port:row.binding_port,protocolMajor:row.protocol_major,protocolMinor:row.protocol_minor},codeDigest:row.code_digest,controllerNonceDigest:row.controller_nonce_digest,agentNonceDigest:row.agent_nonce_digest,proofDigest:row.proof_digest,failedAttempts:row.failed_attempts,createdAt:row.created_at,expiresAt:row.expires_at,updatedAt:row.updated_at,consumedAt:row.consumed_at,terminalAt:row.terminal_at});if(!parsed.ok)return fail();return parsed.value;}
export class PairingRepository {constructor(private readonly db:DatabaseSync){}
 insert(v:NewPairingRow):PairingRecord {return query(()=>{try{this.db.prepare("INSERT INTO pairing_challenges(challenge_id,state,version,owner_id,owner_version,candidate_id,binding_address,binding_port,protocol_major,protocol_minor,code_digest,controller_nonce_digest,agent_nonce_digest,proof_digest,failed_attempts,created_at,expires_at,updated_at,consumed_at,terminal_at) VALUES(?,'created',1,?,?,?,?,?,?,?,?,?,NULL,NULL,0,?,?,?,NULL,NULL)").run(v.challengeId,v.ownerId,v.ownerVersion,v.binding.candidateId,v.binding.address,v.binding.port,v.binding.protocolMajor,v.binding.protocolMinor,v.codeDigest,v.controllerNonceDigest,v.createdAt,v.expiresAt,v.createdAt);}catch{throw new PairingError("ERR_PAIRING_CONFLICT");}const row=this.get(v.challengeId);if(!row)return fail();return row;});}
 get(id:unknown):PairingRecord|null {if(typeof id!=="string"||!HEX64.test(id))return null;return query(()=>{const row=this.db.prepare("SELECT * FROM pairing_challenges WHERE challenge_id=?").get(id) as Record<string,unknown>|undefined;return row?decode(row):null;});}
 transition(id:string,version:number,from:PairingState,to:PairingState,now:string,patch:{agentNonceDigest?:string;proofDigest?:string;failedAttempts?:number;consumedAt?:string;terminalAt?:string}={}):PairingRecord|null {if(!HEX64.test(id)||!Number.isSafeInteger(version)||version<1||!validTime(now))throw new PairingError("ERR_PAIRING_INPUT");return query(()=>{const assignments=["state=?","version=version+1","updated_at=?"],args:Array<string|number|null>=[to,now];for(const [key,column] of [["agentNonceDigest","agent_nonce_digest"],["proofDigest","proof_digest"],["failedAttempts","failed_attempts"],["consumedAt","consumed_at"],["terminalAt","terminal_at"]] as const)if(patch[key]!==undefined){assignments.push(`${column}=?`);args.push(patch[key]!);}const result=this.db.prepare(`UPDATE pairing_challenges SET ${assignments.join(",")} WHERE challenge_id=? AND version=? AND state=?`).run(...args,id,version,from);return result.changes===1?this.get(id):null;});}
 incrementFailure(id:string,version:number,now:string,lock:boolean):PairingRecord|null {return query(()=>{const result=this.db.prepare("UPDATE pairing_challenges SET failed_attempts=failed_attempts+1,state=CASE WHEN ? THEN 'cancelled' ELSE state END,terminal_at=CASE WHEN ? THEN ? ELSE terminal_at END,version=version+1,updated_at=? WHERE challenge_id=? AND version=? AND state='presented' AND failed_attempts<5").run(lock?1:0,lock?1:0,now,now,id,version);return result.changes===1?this.get(id):null;});}
 expire(now:string):number {if(!validTime(now))throw new PairingError("ERR_PAIRING_INPUT");return query(()=>Number(this.db.prepare("UPDATE pairing_challenges SET state='expired',terminal_at=?,updated_at=?,version=version+1 WHERE state IN ('created','presented','owner_confirmed','mutually_proven') AND expires_at<=?").run(now,now,now).changes));}
}
