import { createHash,createHmac,randomBytes,timingSafeEqual } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import { canPairingTransition,pairingBindingFromCandidate,parsePairingBinding,parsePairingCandidate,type PairingBinding,type PairingRecord } from "@lan-model-manager/core";
import { PairingRepository } from "./pairing-repository.js";
import { PAIRING_CODE_ALPHABET,PAIRING_CODE_LENGTH,PAIRING_MAX_ATTEMPTS,PAIRING_MAX_TTL_MS,PairingError,type EnrollmentAuthorization,type PairingPresentation,type PairingProofInput } from "./pairing-types.js";
const TOKEN=/^[A-Za-z0-9_-]{43}$/,HEX=/^[a-f0-9]{64}$/;const frozen=<T>(v:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),v)) as T;
export type PairingManagementAuthorizer=(authentication:unknown)=>Promise<boolean>;
export interface PairingManagerOptions {readonly clock?:()=>string;readonly random?:(size:number)=>Uint8Array;readonly ttlMs?:number}
function digest(value:string):string{return createHash("sha256").update(value,"utf8").digest("hex");}
export function pairingTranscript(challengeId:string,controllerNonceDigest:string,agentNonceDigest:string,binding:PairingBinding):string{return["lanmm-pairing-v1",challengeId,controllerNonceDigest,agentNonceDigest,binding.candidateId,binding.address,String(binding.port),String(binding.protocolMajor),String(binding.protocolMinor)].join("\x1f");}
export function pairingProof(code:string,challengeId:string,controllerNonce:string,agentNonce:string,binding:PairingBinding):string {return createHmac("sha256",Buffer.from(digest(code),"hex")).update(pairingTranscript(challengeId,digest(controllerNonce),digest(agentNonce),binding)).digest("hex");}
function proofInput(input:unknown):PairingProofInput|null {try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const keys=["challengeId","controllerNonce","agentNonce","proof","binding"],own=Reflect.ownKeys(input);if(own.length!==keys.length||own.some(k=>typeof k!=="string"||!keys.includes(k)))return null;const d=Object.getOwnPropertyDescriptors(input);if(keys.some(k=>!d[k]||!("value" in d[k])))return null;const binding=parsePairingBinding(d.binding!.value);if(typeof d.challengeId!.value!=="string"||!HEX.test(d.challengeId!.value)||typeof d.controllerNonce!.value!=="string"||!TOKEN.test(d.controllerNonce!.value)||typeof d.agentNonce!.value!=="string"||!TOKEN.test(d.agentNonce!.value)||typeof d.proof!.value!=="string"||!HEX.test(d.proof!.value)||!binding.ok)return null;return{challengeId:d.challengeId!.value,controllerNonce:d.controllerNonce!.value,agentNonce:d.agentNonce!.value,proof:d.proof!.value,binding:binding.value};}catch{return null;}}
function bindingEqual(a:PairingBinding,b:PairingBinding):boolean{return a.candidateId===b.candidateId&&a.address===b.address&&a.port===b.port&&a.protocolMajor===b.protocolMajor&&a.protocolMinor===b.protocolMinor;}
export class PairingManager {private readonly repository:PairingRepository;private readonly clock:()=>string;private readonly random:(size:number)=>Uint8Array;private readonly ttl:number;
 constructor(private readonly db:DatabaseSync,private readonly authorize:PairingManagementAuthorizer,options:PairingManagerOptions={}){this.repository=new PairingRepository(db);this.clock=options.clock??(()=>new Date().toISOString());this.random=options.random??((n)=>randomBytes(n));this.ttl=options.ttlMs??PAIRING_MAX_TTL_MS;if(!Number.isSafeInteger(this.ttl)||this.ttl<60_000||this.ttl>PAIRING_MAX_TTL_MS)throw new PairingError("ERR_PAIRING_INPUT");}
 private now():string {const v=this.clock();if(typeof v!=="string"||Number.isNaN(Date.parse(v))||new Date(v).toISOString()!==v)throw new PairingError("ERR_PAIRING_INPUT");return v;}
 private owner():{ownerId:string;version:number;disabled:boolean}|null {try{const r=this.db.prepare("SELECT owner_id,credential_version,disabled FROM owners WHERE singleton_key=1").get() as {owner_id:string;credential_version:number;disabled:number}|undefined;return r&&/^[a-f0-9]{32}$/.test(r.owner_id)&&Number.isSafeInteger(r.credential_version)&&(r.disabled===0||r.disabled===1)?{ownerId:r.owner_id,version:r.credential_version,disabled:r.disabled===1}:null;}catch{return null;}}
 private token():string {const bytes=this.random(32);if(!(bytes instanceof Uint8Array)||bytes.length!==32)throw new PairingError("ERR_PAIRING_INPUT");return Buffer.from(bytes).toString("base64url");}
 private code():string {const bytes=this.random(PAIRING_CODE_LENGTH);if(!(bytes instanceof Uint8Array)||bytes.length!==PAIRING_CODE_LENGTH)throw new PairingError("ERR_PAIRING_INPUT");return Array.from(bytes,b=>PAIRING_CODE_ALPHABET[b&31]!).join("");}
 private active(record:PairingRecord,now:string):boolean {const owner=this.owner();return Date.parse(now)<Date.parse(record.expiresAt)&&owner!==null&&!owner.disabled&&owner.ownerId===record.ownerId&&owner.version===record.ownerVersion;}
 async create(authentication:unknown,candidate:unknown):Promise<PairingPresentation|null>{if(!await this.safeAuth(authentication))return null;return this.createAuthorized(candidate);}
 /** Create a challenge after an outer owner-session guard has already authorized the mutation. */
 createAuthorized(candidate:unknown):PairingPresentation|null{const owner=this.owner(),parsedCandidate=parsePairingCandidate(candidate),binding=pairingBindingFromCandidate(candidate),now=this.now();if(!owner||owner.disabled||!binding.ok||!parsedCandidate.ok)return null;if(Date.parse(parsedCandidate.value.expiresAt)<=Date.parse(now))return null;this.repository.expire(now);const challengeId=Buffer.from(this.random(32)).toString("hex"),controllerNonce=this.token(),code=this.code(),expiresAt=new Date(Date.parse(now)+this.ttl).toISOString();if(!HEX.test(challengeId))throw new PairingError("ERR_PAIRING_INPUT");let record:PairingRecord;try{record=this.repository.insert({challengeId,ownerId:owner.ownerId,ownerVersion:owner.version,binding:binding.value,codeDigest:digest(code),controllerNonceDigest:digest(controllerNonce),createdAt:now,expiresAt});}catch(error){if(error instanceof PairingError&&error.code==="ERR_PAIRING_CONFLICT")return null;throw error;}return frozen<PairingPresentation>({challengeId,code,controllerNonce,binding:record.binding,createdAt:now,expiresAt});}
 present(challengeId:unknown):PairingRecord|null {if(typeof challengeId!=="string"||!HEX.test(challengeId))return null;const record=this.repository.get(challengeId),now=this.now();if(!record)return null;if(!this.active(record,now)){this.repository.expire(now);return null;}if(!canPairingTransition(record.state,"presented"))return null;return this.repository.transition(challengeId,record.version,"created","presented",now);}
 async confirm(authentication:unknown,input:unknown):Promise<PairingRecord|null>{if(!await this.safeAuth(authentication))return null;return this.confirmAuthorized(input);}
 /** Confirm a challenge after an outer owner-session + CSRF guard has authorized the mutation. */
 confirmAuthorized(input:unknown):PairingRecord|null{try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const own=Reflect.ownKeys(input);if(own.length!==3||own.some(k=>typeof k!=="string"||!["challengeId","code","binding"].includes(k)))return null;const d=Object.getOwnPropertyDescriptors(input);if(!d.challengeId||!("value" in d.challengeId)||!d.code||!("value" in d.code)||!d.binding||!("value" in d.binding))return null;const id=d.challengeId.value,code=d.code.value,binding=parsePairingBinding(d.binding.value);if(typeof id!=="string"||!HEX.test(id)||typeof code!=="string"||code.length!==PAIRING_CODE_LENGTH||![...code].every(c=>PAIRING_CODE_ALPHABET.includes(c))||!binding.ok)return null;const record=this.repository.get(id),now=this.now();if(!record||record.state!=="presented"||!bindingEqual(record.binding,binding.value))return null;if(!this.active(record,now)){this.repository.expire(now);return null;}const supplied=Buffer.from(digest(code),"hex"),stored=Buffer.from(record.codeDigest,"hex");if(!timingSafeEqual(supplied,stored)){const attempts=record.failedAttempts+1;this.repository.incrementFailure(id,record.version,now,attempts>=PAIRING_MAX_ATTEMPTS);return null;}return this.repository.transition(id,record.version,"presented","owner_confirmed",now);}catch{return null;}}
 pendingAgentProof(input:unknown):boolean {const parsed=proofInput(input);if(!parsed)return false;const record=this.repository.get(parsed.challengeId),now=this.now();if(!record)return false;if(!this.active(record,now)){this.repository.expire(now);return false;}if(record.state!=="presented"||!bindingEqual(record.binding,parsed.binding)||digest(parsed.controllerNonce)!==record.controllerNonceDigest)return false;const agentDigest=digest(parsed.agentNonce),expected=createHmac("sha256",Buffer.from(record.codeDigest,"hex")).update(pairingTranscript(record.challengeId,record.controllerNonceDigest,agentDigest,record.binding)).digest("hex");return timingSafeEqual(Buffer.from(expected,"hex"),Buffer.from(parsed.proof,"hex"));}
 verifyAgentProof(input:unknown):PairingRecord|null {const parsed=proofInput(input);if(!parsed)return null;const record=this.repository.get(parsed.challengeId),now=this.now();if(!record)return null;if(!this.active(record,now)){this.repository.expire(now);return null;}if(record.state!=="owner_confirmed"||!bindingEqual(record.binding,parsed.binding)||digest(parsed.controllerNonce)!==record.controllerNonceDigest)return null;const agentDigest=digest(parsed.agentNonce),expected=createHmac("sha256",Buffer.from(record.codeDigest,"hex")).update(pairingTranscript(record.challengeId,record.controllerNonceDigest,agentDigest,record.binding)).digest("hex");if(!timingSafeEqual(Buffer.from(expected,"hex"),Buffer.from(parsed.proof,"hex")))return null;return this.repository.transition(record.challengeId,record.version,"owner_confirmed","mutually_proven",now,{agentNonceDigest:agentDigest,proofDigest:digest(parsed.proof)});}
 consume(challengeId:unknown):EnrollmentAuthorization|null {if(typeof challengeId!=="string"||!HEX.test(challengeId))return null;const record=this.repository.get(challengeId),now=this.now();if(!record)return null;if(!this.active(record,now)){this.repository.expire(now);return null;}if(record.state!=="mutually_proven")return null;const consumed=this.repository.transition(record.challengeId,record.version,"mutually_proven","consumed",now,{consumedAt:now});if(!consumed||!consumed.agentNonceDigest||!consumed.proofDigest)return null;return frozen<EnrollmentAuthorization>({challengeId:consumed.challengeId,ownerId:consumed.ownerId,binding:consumed.binding,transcriptDigest:digest(pairingTranscript(consumed.challengeId,consumed.controllerNonceDigest,consumed.agentNonceDigest,consumed.binding)),authorizedAt:now});}
 async cancel(authentication:unknown,challengeId:unknown):Promise<boolean> {if(!await this.safeAuth(authentication))return false;return this.cancelAuthorized(challengeId);}
 cancelAuthorized(challengeId:unknown):boolean {if(typeof challengeId!=="string"||!HEX.test(challengeId))return false;const r=this.repository.get(challengeId),now=this.now();return !!r&&canPairingTransition(r.state,"cancelled")&&this.repository.transition(r.challengeId,r.version,r.state,"cancelled",now,{terminalAt:now})!==null;}
 get(challengeId:unknown):PairingRecord|null{return this.repository.get(challengeId);}
 private async safeAuth(v:unknown):Promise<boolean>{try{return await this.authorize(v);}catch{return false;}}
}
