import assert from "node:assert/strict";
import test from "node:test";
import { commandAuthorizationDigest, commandPolicyOperation, type AuthorizationIntent, type OperationPolicy } from "@lan-model-manager/core";
import { createAdmissionController } from "./admission-accounting.js";
import { AgentCommandStore } from "./agent-command-channel.js";
import { CommandDispatcher } from "./command-dispatch.js";
import { openControllerDatabase } from "./database.js";
import { createJobStores } from "./jobs-store.js";
import { LifecycleService } from "./lifecycle-service.js";
import { PolicyService } from "./policy-service.js";
import { RemoteLifecycleController } from "./remote-lifecycle.js";
import { createControllerRepositories } from "./repositories.js";

const T0="2026-09-29T10:00:00.000Z",T1="2026-09-29T10:00:01.000Z";
const policy:OperationPolicy={version:1,allowedOperations:["model-load","model-drain","model-unload"],approvalOperations:[],allowArtifactAcquisition:false,allowArtifactRemoval:false,allowSubstitution:false,allowPublicExposure:false,minimumMemoryHeadroomBytes:0,minimumVramHeadroomBytes:0,minimumStorageHeadroomBytes:0,maxConcurrentOperations:10,maxOperationsPerMinute:100};
const owner={ok:true as const,session:{ownerId:"owner",sessionVersion:1,credentialVersion:1,createdAt:T0,lastSeenAt:T0,absoluteExpiresAt:"2026-09-30T10:00:00.000Z",idleExpiresAt:"2026-09-29T11:00:00.000Z",revokedAt:null}};
function command(operation:"load"|"drain"|"unload",n:number){const requestId=String(n).repeat(64),intent:AuthorizationIntent={requestId,actorKind:"controller",actorId:"controller",operation:commandPolicyOperation(operation),targetKind:"model",targetId:"model-1",hostId:"host-1",modelId:"model-1",observationFresh:true,hostRevoked:false,modelCompatible:true,publicExposure:false,availableMemoryBytes:1,availableVramBytes:1,availableStorageBytes:1,activeOperations:0,operationsLastMinute:0};const capability:any={operation:intent.operation,targetKind:"model",targetId:"model-1",hostId:"host-1",modelId:"model-1",expiresAt:"2026-09-29T10:10:00.000Z"},request:any={requestId,jobId:`job-${n}`,hostId:"host-1",operation,idempotencyKey:`idem-${n}`,sequence:1,deadline:"2026-09-29T10:05:00.000Z",capability,params:operation==="load"?{providerId:"ollama-1",model:"qwen:latest",keepAlive:"5m"}:{providerId:"ollama-1",model:"qwen:latest"}};capability.requestDigest=commandAuthorizationDigest(request);return{intent,request};}
function response(request:any,operation:string,at:string=T1){return{requestId:request.requestId,jobId:request.jobId,hostId:request.hostId,sequence:1,status:"succeeded",progress:100,observedAt:at,observation:{action:operation,providerId:"ollama-1",canonicalModelName:"qwen:latest",outcome:"succeeded",runtimeState:operation==="unload"?"unloaded":"loaded",...(operation==="drain"?{activeRequests:0}:{}),observedAt:at},errorCode:null};}
function setup(){let now=T0;const db=openControllerDatabase(":memory:"),repos=createControllerRepositories(db,{now:()=>now});repos.hosts.upsert({hostId:"host-1",displayName:"Host",platform:"linux",observedAt:T0,online:true,freshness:"fresh",snapshot:{}});repos.providers.upsert({providerId:"ollama-1",hostId:"host-1",kind:"ollama",endpoint:"http://127.0.0.1:11434",health:"ready",version:"",versionKnown:false,observedAt:T0,snapshot:{}});repos.models.upsert({modelId:"model-1",providerId:"ollama-1",hostId:"host-1",canonicalName:"qwen:latest",state:"installed",type:"llm",digest:"",digestKnown:false,observedAt:T0,snapshot:{runtimeState:"unloaded",activeRequests:0}});const jobs=createJobStores(db,{now:()=>now}),queue=new AgentCommandStore(db,()=>now,30_000,jobs,true),dispatcher=new CommandDispatcher(jobs,queue,()=>now),policyService=new PolicyService(db,{clock:()=>now,stores:jobs});assert.ok(policyService.install(policy,owner).ok);const admissions=createAdmissionController({clock:()=>now});admissions.register("model-1");const lifecycle=new LifecycleService(policyService,dispatcher,repos,admissions),remote=new RemoteLifecycleController(lifecycle,queue,repos,jobs,admissions,()=>now);return{db,repos,jobs,queue,remote,admissions,setNow:(v:string)=>now=v};}
async function run(x:ReturnType<typeof setup>,value:ReturnType<typeof command>,reply:()=>void){const promise=x.remote.execute(value,new AbortController().signal);await new Promise(resolve=>setImmediate(resolve));assert.equal(x.queue.poll("host-1").command?.jobId,value.request.jobId);reply();return promise;}

test("remote load applies a verified serving observation and replays idempotently",async()=>{const x=setup();try{const value=command("load",1),result=await run(x,value,()=>{x.setNow(T1);assert.ok(x.queue.complete("host-1",response(value.request,"load")));});assert.ok(result.ok);assert.equal(x.repos.models.get("model-1")?.state,"running");assert.equal((x.repos.models.get("model-1")?.snapshot as any).runtimeState,"loaded-idle");assert.ok((await x.remote.execute(value,new AbortController().signal)).ok);assert.equal(x.jobs.audit.list().filter(e=>e.action==="lifecycle-observation-applied").length,1);}finally{x.db.close();}});

test("active inference lease blocks drain and unload until released",async()=>{const x=setup();try{x.setNow(T1);x.repos.models.upsert({modelId:"model-1",providerId:"ollama-1",hostId:"host-1",canonicalName:"qwen:latest",state:"running",type:"llm",digest:"",digestKnown:false,observedAt:T1,snapshot:{runtimeState:"serving",activeRequests:1}});const lease=x.admissions.acquire("model-1","inference-1"),drain=command("drain",2),unload=command("unload",3);assert.deepEqual(await x.remote.execute(drain,new AbortController().signal),{ok:false,error:"ERR_LIFECYCLE_STATE"});assert.deepEqual(await x.remote.execute(unload,new AbortController().signal),{ok:false,error:"ERR_LIFECYCLE_STATE"});const waiting=x.admissions.stopAdmission("model-1");lease.release();await waiting;x.setNow("2026-09-29T10:00:02.000Z");x.repos.models.upsert({modelId:"model-1",providerId:"ollama-1",hostId:"host-1",canonicalName:"qwen:latest",state:"running",type:"llm",digest:"",digestKnown:false,observedAt:"2026-09-29T10:00:02.000Z",snapshot:{runtimeState:"serving",activeRequests:1}});const drained=await run(x,drain,()=>{x.setNow("2026-09-29T10:00:03.000Z");assert.ok(x.queue.complete("host-1",response(drain.request,"drain","2026-09-29T10:00:03.000Z")));});assert.ok(drained.ok);const unloaded=await run(x,unload,()=>{x.setNow("2026-09-29T10:00:04.000Z");assert.ok(x.queue.complete("host-1",response(unload.request,"unload","2026-09-29T10:00:04.000Z")));});assert.ok(unloaded.ok);assert.equal(x.repos.models.get("model-1")?.state,"installed");const reload=command("load",4),reloaded=await run(x,reload,()=>{x.setNow("2026-09-29T10:00:05.000Z");assert.ok(x.queue.complete("host-1",response(reload.request,"load","2026-09-29T10:00:05.000Z")));});assert.ok(reloaded.ok);const next=x.admissions.acquire("model-1","inference-2");next.release();}finally{x.db.close();}});

test("newer inventory and lifecycle completion settle atomically as failed",async()=>{const x=setup();try{const value=command("load",5),promise=x.remote.execute(value,new AbortController().signal);await new Promise(resolve=>setImmediate(resolve));assert.ok(x.queue.poll("host-1").command);x.setNow("2026-09-29T10:00:02.000Z");x.repos.models.upsert({modelId:"model-1",providerId:"ollama-1",hostId:"host-1",canonicalName:"qwen:latest",state:"installed",type:"llm",digest:"",digestKnown:false,observedAt:"2026-09-29T10:00:02.000Z",snapshot:{runtimeState:"unloaded",activeRequests:0}});assert.ok(x.queue.complete("host-1",response(value.request,"load",T1)));assert.deepEqual(await promise,{ok:false,error:"ERR_LIFECYCLE_OBSERVATION"});assert.equal(x.jobs.jobs.get(value.request.jobId)?.state,"failed");assert.equal(x.repos.models.get("model-1")?.observedAt,"2026-09-29T10:00:02.000Z");}finally{x.db.close();}});

test("wrong target, stale/late result and cancellation fail closed",async()=>{const x=setup();try{const value=command("load",4),controller=new AbortController(),promise=x.remote.execute(value,controller.signal);await new Promise(resolve=>setImmediate(resolve));assert.ok(x.queue.poll("host-1").command);assert.equal(x.queue.complete("host-1",response(value.request,"load","2027-09-29T10:00:00.000Z")),null);assert.equal(x.queue.complete("host-1",response(value.request,"load",T0)),null);assert.equal(x.queue.complete("other",response(value.request,"load")),null);assert.equal(x.remote.cancel(value.request.jobId).ok,true);controller.abort();assert.equal(x.queue.complete("host-1",response(value.request,"load")),null);assert.deepEqual(await promise,{ok:false,error:"ERR_LIFECYCLE_DISPATCH"});}finally{x.db.close();}});
