import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import { CONTROLLER_MIGRATIONS, PersistenceError, migrateControllerDatabase, migrationChecksum, openControllerDatabase } from "./database.js";
import { RepositoryError, createControllerRepositories, parseHostRecord } from "./repositories.js";

const t0="2026-09-27T05:00:00.000Z",t1="2026-09-27T06:00:00.000Z",t2="2026-09-27T07:00:00.000Z";
const host=(o:Record<string,unknown>={})=>({hostId:"host-1",displayName:"Host One",platform:"linux",observedAt:t0,online:true,freshness:"fresh",snapshot:{cpu:8},...o});
const provider=(o:Record<string,unknown>={})=>({providerId:"provider-1",hostId:"host-1",kind:"ollama",endpoint:"http://127.0.0.1:11434",health:"ready",version:"1.0.0",versionKnown:true,observedAt:t0,snapshot:{models:1},...o});
const model=(o:Record<string,unknown>={})=>({modelId:"model-1",providerId:"provider-1",hostId:"host-1",canonicalName:"acme/model:latest",state:"installed",type:"llm",digest:"a".repeat(64),digestKnown:true,observedAt:t0,snapshot:{size:123},...o});
const memory=()=>openControllerDatabase(":memory:");

function withFile(run:(path:string)=>void){const dir=mkdtempSync(join(tmpdir(),"lanmm-db-"));try{run(join(dir,"controller.sqlite3"));}finally{rmSync(dir,{recursive:true,force:true});}}

test("migration ledger stores and verifies immutable checksums",()=>{const db=memory();try{const rows=db.prepare("SELECT version,name,checksum FROM schema_migrations").all();assert.deepEqual(rows.map(row=>({...row})),[{version:1,name:"inventory-v1",checksum:CONTROLLER_MIGRATIONS[0]?.checksum}]);assert.equal(migrateControllerDatabase(db),1);db.prepare("UPDATE schema_migrations SET checksum=? WHERE version=1").run("0".repeat(64));assert.throws(()=>migrateControllerDatabase(db),(e:any)=>e instanceof PersistenceError&&e.code==="ERR_MIGRATION_MISMATCH");}finally{db.close();}});

test("future schemas, name mismatch, and failed migration fail closed",()=>{for(const mode of ["future","name"]){const db=memory();try{if(mode==="future")db.exec("PRAGMA user_version=99");else db.prepare("UPDATE schema_migrations SET name='tampered' WHERE version=1").run();assert.throws(()=>migrateControllerDatabase(db),PersistenceError);}finally{db.close();}}const db=memory();try{const sql="CREATE TABLE transient(value TEXT); SELECT * FROM absent;";const migrations=[...CONTROLLER_MIGRATIONS,{version:2,name:"broken",sql,checksum:migrationChecksum(sql)}];assert.throws(()=>migrateControllerDatabase(db,migrations),(e:any)=>e instanceof PersistenceError&&e.code==="ERR_MIGRATION_APPLY");assert.equal(db.prepare("SELECT name FROM sqlite_master WHERE name='transient'").get(),undefined);assert.equal((db.prepare("PRAGMA user_version").get() as any).user_version,1);}finally{db.close();}});

test("file-backed database survives close/reopen and enables WAL/FK",()=>withFile(path=>{let db=openControllerDatabase(path);const repos=createControllerRepositories(db,{now:()=>t1});assert.equal(repos.hosts.upsert(host()),"inserted");db.close();db=openControllerDatabase(path);try{assert.equal(createControllerRepositories(db).hosts.get("host-1")?.displayName,"Host One");assert.equal((db.prepare("PRAGMA foreign_keys").get() as any).foreign_keys,1);assert.equal((db.prepare("PRAGMA journal_mode").get() as any).journal_mode,"wal");}finally{db.close();}}));

test("strict upserts distinguish insert update and equal/older stale",()=>{const db=memory();try{const r=createControllerRepositories(db,{now:()=>t2});assert.equal(r.hosts.upsert(host()),"inserted");assert.equal(r.hosts.upsert(host({displayName:"equal"})),"ignored_stale");assert.equal(r.hosts.upsert(host({displayName:"new",observedAt:t1})),"updated");assert.equal(r.hosts.get("host-1")?.displayName,"new");assert.equal(r.providers.upsert(provider({observedAt:t1})),"inserted");assert.equal(r.providers.upsert(provider({observedAt:t1,health:"failed"})),"ignored_stale");assert.equal(r.models.upsert(model({observedAt:t1})),"inserted");assert.equal(r.models.upsert(model({observedAt:t0,state:"running"})),"ignored_stale");}finally{db.close();}});

test("foreign keys are wrapped without SQLite or value leakage and cascade deliberately",()=>{const db=memory();try{const r=createControllerRepositories(db);assert.throws(()=>r.providers.upsert(provider()),(e:any)=>e instanceof RepositoryError&&e.code==="ERR_REPOSITORY_DATABASE"&&!/FOREIGN|provider-1|INSERT/i.test(e.message));r.hosts.upsert(host());r.providers.upsert(provider());r.models.upsert(model());db.prepare("DELETE FROM hosts WHERE host_id=?").run("host-1");assert.equal(r.providers.get("provider-1"),null);assert.equal(r.models.get("model-1"),null);}finally{db.close();}});

test("read APIs validate identifiers and SQL-looking IDs remain inert",()=>{const db=memory();try{const r=createControllerRepositories(db);r.hosts.upsert(host({hostId:"drop-table"}));assert.equal(r.hosts.get("drop-table")?.hostId,"drop-table");for(const bad of ["", "../x", "x' OR 1=1 --",{},null])assert.throws(()=>r.hosts.get(bad),RepositoryError);assert.equal(r.hosts.list().length,1);}finally{db.close();}});

test("DTO boundaries reject prototypes, accessors, symbols, revoked and hostile proxies without invocation",()=>{let calls=0;const accessor=Object.defineProperty({},"hostId",{enumerable:true,get(){calls++;return"host-1";}});for(const bad of [accessor,Object.create({}),{...host(),[Symbol("x")]:1}])assert.throws(()=>parseHostRecord(bad),RepositoryError);const revoked=Proxy.revocable(host(),{});revoked.revoke();assert.throws(()=>parseHostRecord(revoked.proxy),RepositoryError);for(const trap of ["getPrototypeOf","ownKeys","getOwnPropertyDescriptor"] as const){const p=new Proxy(host(),{[trap](){throw new Error("secret");}} as any);assert.throws(()=>parseHostRecord(p),RepositoryError);}assert.equal(calls,0);});

test("reads are detached, deeply frozen, and deterministically sorted",()=>{const db=memory();try{const r=createControllerRepositories(db);r.hosts.upsert(host({hostId:"z"}));r.hosts.upsert(host({hostId:"a",snapshot:{nested:[1,2]}}));const list=r.hosts.list();assert.deepEqual(list.map(v=>v.hostId),["a","z"]);assert.ok(Object.isFrozen(list)&&Object.isFrozen(list[0])&&Object.isFrozen((list[0] as any).snapshot)&&Object.isFrozen((list[0] as any).snapshot.nested));assert.throws(()=>((list[0] as any).snapshot.nested[0]=9));assert.equal((r.hosts.get("a") as any).snapshot.nested[0],1);}finally{db.close();}});

test("provider and model scoped reads are deterministic and parent-safe",()=>{const db=memory();try{const r=createControllerRepositories(db);r.hosts.upsert(host());r.providers.upsert(provider({providerId:"p2"}));r.providers.upsert(provider({providerId:"p1"}));r.models.upsert(model({modelId:"m2",providerId:"p1",canonicalName:"z"}));r.models.upsert(model({modelId:"m1",providerId:"p1",canonicalName:"a"}));assert.deepEqual(r.providers.listByHost("host-1").map(v=>v.providerId),["p1","p2"]);assert.deepEqual(r.models.listByProvider("p1").map(v=>v.modelId),["m1","m2"]);assert.deepEqual(r.models.listByHost("host-1").map(v=>v.modelId),["m1","m2"]);assert.throws(()=>r.models.upsert(model({providerId:"p1",hostId:"other"})),RepositoryError);r.hosts.upsert(host({hostId:"other-host"}));assert.throws(()=>r.providers.upsert(provider({providerId:"p1",hostId:"other-host",observedAt:t2})),RepositoryError);assert.throws(()=>r.models.upsert(model({modelId:"m1",providerId:"p2",observedAt:t2})),RepositoryError);}finally{db.close();}});

test("atomic host reconciliation inserts and removes only rows at or before cutoff",()=>{const db=memory();try{const r=createControllerRepositories(db,{now:()=>t2});const first=r.reconcileHostInventory({cutoffObservedAt:t1,host:host({observedAt:t1}),providers:[provider({observedAt:t1}),provider({providerId:"old",observedAt:t1})],models:[model({observedAt:t1}),model({modelId:"old-model",providerId:"old",canonicalName:"old",observedAt:t1})]});assert.equal(first.providersInserted,2);assert.ok(Object.isFrozen(first));r.providers.upsert(provider({providerId:"newer",observedAt:t2}));r.models.upsert(model({modelId:"newer-model",providerId:"newer",canonicalName:"newer",observedAt:t2}));const second=r.reconcileHostInventory({cutoffObservedAt:t1,host:host({observedAt:t2}),providers:[provider({observedAt:t2})],models:[model({observedAt:t2})]});assert.equal(second.providersDeleted,1);assert.equal(second.modelsDeleted,1);assert.ok(r.providers.get("newer")&&r.models.get("newer-model"));assert.equal(r.providers.get("old"),null);}finally{db.close();}});

test("reconciliation validates the whole snapshot and rolls back on database failure",()=>{const db=memory();try{const r=createControllerRepositories(db);r.hosts.upsert(host());const before=JSON.stringify(r.hosts.list());assert.throws(()=>r.reconcileHostInventory({cutoffObservedAt:t1,host:host({observedAt:t1}),providers:[provider({hostId:"other"})],models:[]}),RepositoryError);assert.equal(JSON.stringify(r.hosts.list()),before);const original=db.prepare("SELECT count(*) AS count FROM providers").get();assert.deepEqual({...original},{count:0});assert.throws(()=>r.reconcileHostInventory({cutoffObservedAt:t1,host:host({observedAt:t1}),providers:[provider({observedAt:t1})],models:[model({providerId:"missing",observedAt:t1})]}),RepositoryError);assert.deepEqual({...db.prepare("SELECT count(*) AS count FROM providers").get() as object},{count:0});
// Both model rows are valid at the DTO boundary, but collide on the schema's
// provider/canonical-name uniqueness after earlier writes in the transaction.
assert.throws(()=>r.reconcileHostInventory({cutoffObservedAt:t1,host:host({observedAt:t1}),providers:[provider({observedAt:t1})],models:[model({modelId:"m1",observedAt:t1}),model({modelId:"m2",canonicalName:"acme/model:latest",observedAt:t1})]}),RepositoryError);
assert.equal(r.hosts.get("host-1")?.observedAt,t0);assert.equal(r.providers.get("provider-1"),null);assert.equal(r.models.listByHost("host-1").length,0);
}finally{db.close();}});

test("reconciliation arrays reject accessors and hostile proxies without invocation",()=>{const db=memory();try{const r=createControllerRepositories(db);let calls=0;const providers=Object.defineProperty([],"0",{enumerable:true,get(){calls++;return provider();}});Object.defineProperty(providers,"length",{value:1});assert.throws(()=>r.reconcileHostInventory({cutoffObservedAt:t0,host:host(),providers,models:[]}),RepositoryError);const revoked=Proxy.revocable([] as unknown[],{});revoked.revoke();assert.throws(()=>r.reconcileHostInventory({cutoffObservedAt:t0,host:host(),providers:revoked.proxy,models:[]}),RepositoryError);assert.equal(calls,0);}finally{db.close();}});

test("snapshot bounds and malformed JSON values fail before writes",()=>{const db=memory();try{const r=createControllerRepositories(db);for(const snap of [{x:"x".repeat(70_000)},{x:1.5},{x:undefined}])assert.throws(()=>r.hosts.upsert(host({snapshot:snap})),RepositoryError);assert.equal(r.hosts.list().length,0);}finally{db.close();}});
