import type { DatabaseSync } from "node:sqlite";
import type { OwnerBootstrapService } from "./owner-service.js";
import { digestSessionToken,equalDigest,generateSessionToken,validSessionToken } from "./session-digest.js";
import { SessionRepository } from "./session-repository.js";
import { SESSION_ABSOLUTE_TTL_MS,SESSION_IDLE_TTL_MS,SessionError,type CreatedSession,type SessionMetadata,type SessionPolicy,type StoredSession } from "./session-types.js";
const TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const validTime=(v:unknown):v is string=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
const frozen=<T>(o:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),o)) as T;
export interface SessionManagerOptions {readonly clock?:()=>string;readonly random?:(size:number)=>Uint8Array;readonly policy?:Partial<SessionPolicy>}
export class SessionManager {
 private readonly repository:SessionRepository;private readonly clock:()=>string;private readonly random:((size:number)=>Uint8Array)|undefined;private readonly policy:SessionPolicy;
 constructor(private readonly db:DatabaseSync,private readonly owners:OwnerBootstrapService,options:SessionManagerOptions={}){this.repository=new SessionRepository(db);this.clock=options.clock??(()=>new Date().toISOString());this.random=options.random;this.policy=Object.freeze({absoluteTtlMs:options.policy?.absoluteTtlMs??SESSION_ABSOLUTE_TTL_MS,idleTtlMs:options.policy?.idleTtlMs??SESSION_IDLE_TTL_MS,touchAfterMs:options.policy?.touchAfterMs??60_000});if(!Number.isSafeInteger(this.policy.absoluteTtlMs)||this.policy.absoluteTtlMs<60_000||this.policy.absoluteTtlMs>SESSION_ABSOLUTE_TTL_MS||!Number.isSafeInteger(this.policy.idleTtlMs)||this.policy.idleTtlMs<60_000||this.policy.idleTtlMs>this.policy.absoluteTtlMs||!Number.isSafeInteger(this.policy.touchAfterMs)||this.policy.touchAfterMs<1_000||this.policy.touchAfterMs>this.policy.idleTtlMs)throw new SessionError("ERR_SESSION_INPUT");}
 private now():string {const value=this.clock();if(!validTime(value))throw new SessionError("ERR_SESSION_INPUT");return value;}
 private ownerState(ownerId:string):{disabled:boolean;version:number}|null {try{const row=this.db.prepare("SELECT disabled,credential_version FROM owners WHERE owner_id=?").get(ownerId) as {disabled:number;credential_version:number}|undefined;if(!row||!Number.isSafeInteger(row.credential_version)||(row.disabled!==0&&row.disabled!==1))return null;return{disabled:row.disabled===1,version:row.credential_version};}catch{return null;}}
 private active(stored:StoredSession,now:string):boolean {const state=this.ownerState(stored.ownerId);return stored.revokedAt===null&&Date.parse(now)<Date.parse(stored.absoluteExpiresAt)&&Date.parse(now)<Date.parse(stored.idleExpiresAt)&&state!==null&&!state.disabled&&state.version===stored.credentialVersion;}
 private metadata(value:StoredSession):SessionMetadata{return frozen<SessionMetadata>({ownerId:value.ownerId,credentialVersion:value.credentialVersion,sessionVersion:value.sessionVersion,createdAt:value.createdAt,lastSeenAt:value.lastSeenAt,absoluteExpiresAt:value.absoluteExpiresAt,idleExpiresAt:value.idleExpiresAt,revokedAt:value.revokedAt});}
 async create(authentication:unknown):Promise<CreatedSession|null> {if(!await this.owners.authenticate(authentication))return null;const owner=this.owners.getOwner();if(!owner||owner.disabled)return null;const now=this.now(),time=Date.parse(now),sessionToken=generateSessionToken(this.random),csrfToken=generateSessionToken(this.random),record:StoredSession={sessionDigest:digestSessionToken(sessionToken),csrfDigest:digestSessionToken(csrfToken),ownerId:owner.ownerId,credentialVersion:owner.version,sessionVersion:1,createdAt:now,lastSeenAt:now,absoluteExpiresAt:new Date(time+this.policy.absoluteTtlMs).toISOString(),idleExpiresAt:new Date(time+this.policy.idleTtlMs).toISOString(),revokedAt:null};this.repository.insert(record);return frozen<CreatedSession>({sessionToken,csrfToken,metadata:this.metadata(record),maxAgeSeconds:Math.floor(this.policy.absoluteTtlMs/1000)});}
 authenticate(token:unknown):SessionMetadata|null {if(!validSessionToken(token))return null;const now=this.now(),presented=digestSessionToken(token),stored=this.repository.get(presented);return stored&&equalDigest(stored.sessionDigest,presented)&&this.active(stored,now)?this.metadata(stored):null;}
 authenticateCsrf(token:unknown,csrf:unknown):SessionMetadata|null {if(!validSessionToken(token)||!validSessionToken(csrf))return null;const now=this.now(),stored=this.repository.get(digestSessionToken(token));if(!stored||!equalDigest(stored.csrfDigest,digestSessionToken(csrf))||!this.active(stored,now))return null;return this.metadata(stored);}
 touch(token:unknown):SessionMetadata|null {if(!validSessionToken(token))return null;const now=this.now(),digest=digestSessionToken(token),stored=this.repository.get(digest);if(!stored||!this.active(stored,now))return null;const nowMs=Date.parse(now);if(nowMs-Date.parse(stored.lastSeenAt)<this.policy.touchAfterMs)return this.metadata(stored);const idle=new Date(Math.min(nowMs+this.policy.idleTtlMs,Date.parse(stored.absoluteExpiresAt))).toISOString();try{return this.metadata(this.repository.touch(digest,stored.sessionVersion,now,idle,now));}catch{return null;}}
 revoke(token:unknown):boolean {return validSessionToken(token)&&this.repository.revoke(digestSessionToken(token),this.now());}
 revokeAll():number {const owner=this.owners.getOwner();return owner?this.repository.revokeAll(owner.ownerId,this.now()):0;}
}
