import type { DatabaseSync } from "node:sqlite";
import { SessionError,type StoredSession } from "./session-types.js";
const HASH=/^[a-f0-9]{64}$/,OWNER=/^[a-f0-9]{32}$/,TIME=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/;
const validTime=(v:unknown):v is string=>typeof v==="string"&&TIME.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString()===v;
const frozen=<T>(o:Record<string,unknown>):T=>Object.freeze(Object.assign(Object.create(null),o)) as T;
const fail=():never=>{throw new SessionError("ERR_SESSION_DATABASE");};
function query<T>(fn:()=>T):T{try{return fn();}catch(e){if(e instanceof SessionError)throw e;return fail();}}
function decode(row:Record<string,unknown>):StoredSession {const sessionDigest=row.session_digest,csrfDigest=row.csrf_digest,ownerId=row.owner_id,credentialVersion=row.credential_version,sessionVersion=row.session_version,createdAt=row.created_at,lastSeenAt=row.last_seen_at,absoluteExpiresAt=row.absolute_expires_at,idleExpiresAt=row.idle_expires_at,revokedAt=row.revoked_at;if(typeof sessionDigest!=="string"||!HASH.test(sessionDigest)||typeof csrfDigest!=="string"||!HASH.test(csrfDigest)||typeof ownerId!=="string"||!OWNER.test(ownerId)||typeof credentialVersion!=="number"||!Number.isSafeInteger(credentialVersion)||credentialVersion<1||typeof sessionVersion!=="number"||!Number.isSafeInteger(sessionVersion)||sessionVersion<1||!validTime(createdAt)||!validTime(lastSeenAt)||!validTime(absoluteExpiresAt)||!validTime(idleExpiresAt)||(revokedAt!==null&&!validTime(revokedAt)))return fail();return frozen<StoredSession>({sessionDigest,csrfDigest,ownerId,credentialVersion,sessionVersion,createdAt,lastSeenAt,absoluteExpiresAt,idleExpiresAt,revokedAt});}
export class SessionRepository {constructor(private readonly db:DatabaseSync){}
 insert(value:StoredSession):void {if(!HASH.test(value.sessionDigest)||!HASH.test(value.csrfDigest)||!OWNER.test(value.ownerId)||!validTime(value.createdAt)||!validTime(value.lastSeenAt)||!validTime(value.absoluteExpiresAt)||!validTime(value.idleExpiresAt)||value.revokedAt!==null)throw new SessionError("ERR_SESSION_INPUT");query(()=>this.db.prepare("INSERT INTO sessions(session_digest,csrf_digest,owner_id,credential_version,session_version,created_at,last_seen_at,absolute_expires_at,idle_expires_at,revoked_at) VALUES(?,?,?,?,?,?,?,?,?,NULL)").run(value.sessionDigest,value.csrfDigest,value.ownerId,value.credentialVersion,value.sessionVersion,value.createdAt,value.lastSeenAt,value.absoluteExpiresAt,value.idleExpiresAt));}
 get(digest:unknown):StoredSession|null {if(typeof digest!=="string"||!HASH.test(digest))return null;return query(()=>{const row=this.db.prepare("SELECT * FROM sessions WHERE session_digest=?").get(digest) as Record<string,unknown>|undefined;return row?decode(row):null;});}
 touch(digest:string,expectedVersion:number,lastSeenAt:string,idleExpiresAt:string,now:string):StoredSession {if(!HASH.test(digest)||!validTime(lastSeenAt)||!validTime(idleExpiresAt)||!validTime(now))throw new SessionError("ERR_SESSION_INPUT");return query(()=>{const result=this.db.prepare("UPDATE sessions SET last_seen_at=?,idle_expires_at=?,session_version=session_version+1 WHERE session_digest=? AND session_version=? AND revoked_at IS NULL AND absolute_expires_at>? AND idle_expires_at>?").run(lastSeenAt,idleExpiresAt,digest,expectedVersion,now,now);if(result.changes!==1)throw new SessionError("ERR_SESSION_STALE");const row=this.get(digest);if(!row)return fail();return row;});}
 revoke(digest:string,now:string):boolean {if(!HASH.test(digest)||!validTime(now))throw new SessionError("ERR_SESSION_INPUT");return query(()=>this.db.prepare("UPDATE sessions SET revoked_at=?,session_version=session_version+1 WHERE session_digest=? AND revoked_at IS NULL").run(now,digest).changes===1);}
 rotateCsrf(sessionDigest:string,csrfDigest:string,now:string):boolean {if(!HASH.test(sessionDigest)||!HASH.test(csrfDigest)||!validTime(now))throw new SessionError("ERR_SESSION_INPUT");return query(()=>this.db.prepare("UPDATE sessions SET csrf_digest=?,session_version=session_version+1 WHERE session_digest=? AND revoked_at IS NULL AND absolute_expires_at>? AND idle_expires_at>?").run(csrfDigest,sessionDigest,now,now).changes===1);}
 revokeAll(ownerId:string,now:string):number {if(!OWNER.test(ownerId)||!validTime(now))throw new SessionError("ERR_SESSION_INPUT");return query(()=>Number(this.db.prepare("UPDATE sessions SET revoked_at=?,session_version=session_version+1 WHERE owner_id=? AND revoked_at IS NULL").run(now,ownerId).changes));}
}
