import test from "node:test";
import assert from "node:assert/strict";
import {execFileSync,spawnSync} from "node:child_process";
import {chmodSync,cpSync,existsSync,mkdirSync,mkdtempSync,readFileSync,readdirSync,rmSync,symlinkSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join,resolve} from "node:path";
import {createHash} from "node:crypto";

const repo=resolve(import.meta.dirname,"../../.."),install=join(repo,"scripts/alpha/install-fedora-alpha.sh"),uninstall=join(repo,"scripts/alpha/uninstall-fedora-alpha.sh"),generatedArtifacts=mkdtempSync(join(repo,"artifacts/alpha-test-source-")),sourceArtifacts=join(generatedArtifacts,"packages");
execFileSync("node",[join(repo,"scripts/packaging/build.js"),sourceArtifacts],{cwd:repo,stdio:"ignore",env:{...process.env,LAN_ALLOW_DIRTY:"1"}});
process.on("exit",()=>rmSync(generatedArtifacts,{recursive:true,force:true}));
function fixture(){const root=mkdtempSync(join(tmpdir(),"lanmm-alpha-test-")),bin=join(root,"bin"),artifacts=join(root,"artifacts"),home=join(root,"home"),log=join(root,"commands.log"),health=join(root,"health");mkdirSync(bin);mkdirSync(home);mkdirSync(artifacts);for(const name of ["lan-model-controller-linux-any.tar.gz","checksums.txt","package-inventory.json"])cpSync(join(sourceArtifacts,name),join(artifacts,name));const tool=(name,body)=>{const p=join(bin,name);writeFileSync(p,`#!/bin/sh\nset -eu\n${body}\n`);chmodSync(p,0o755)};tool("git",`case " $* " in *" rev-parse --show-toplevel "*) printf '%s\\n' '${repo}' ;; *" status "*) test "\${LANMM_TEST_GIT_DIRTY:-0}" = 0 || echo ' M reviewed-file' ;; *) exit 2;; esac`);tool("systemctl",`printf 'systemctl %s\\n' "$*" >>"$LANMM_TEST_LOG"\ncase " $* " in *" show-environment "*) exit 0;; *" is-enabled "*) test -f "$LANMM_TEST_ROOT/enabled";; *" is-active "*) test -f "$LANMM_TEST_ROOT/active";; *" enable "*) : >"$LANMM_TEST_ROOT/enabled"; case " $* " in *" --now "*) : >"$LANMM_TEST_ROOT/active";; esac;; *" disable "*) rm -f "$LANMM_TEST_ROOT/enabled"; case " $* " in *" --now "*) rm -f "$LANMM_TEST_ROOT/active";; esac;; *" stop "*) rm -f "$LANMM_TEST_ROOT/active";; *" restart "*) : >"$LANMM_TEST_ROOT/active";; esac`);tool("curl",`printf 'curl %s\\n' "$*" >>"$LANMM_TEST_LOG"\nvalue=ok\nif test -s "$LANMM_TEST_HEALTH"; then value=$(sed -n '1p' "$LANMM_TEST_HEALTH"); if test "$value" != fail-always; then sed '1d' "$LANMM_TEST_HEALTH" >"$LANMM_TEST_HEALTH.tmp"; mv "$LANMM_TEST_HEALTH.tmp" "$LANMM_TEST_HEALTH"; fi; fi\ntest "$value" = ok`);tool("xdg-open",`printf 'xdg-open %s\\n' "$*" >>"$LANMM_TEST_LOG"`);const env={...process.env,HOME:home,XDG_DATA_HOME:join(root,"data"),XDG_STATE_HOME:join(root,"state"),XDG_CONFIG_HOME:join(root,"config"),PATH:`${bin}:${process.env.PATH}`,LANMM_TEST_LOG:log,LANMM_TEST_ROOT:root,LANMM_TEST_HEALTH:health};return{root,artifacts,home,log,health,env,run(script,args=[],extra={}){return spawnSync(script,args,{encoding:"utf8",env:{...env,...extra}})},cleanup(){rmSync(root,{recursive:true,force:true})}};}
function pointer(f){return join(f.root,"data/lan-model-manager-alpha/controller.current")}
function makeUpgrade(f,version){const unpack=join(f.root,"upgrade-unpack"),out=join(f.root,"upgrade");mkdirSync(unpack);mkdirSync(out);execFileSync("tar",["-xzf",join(f.artifacts,"lan-model-controller-linux-any.tar.gz"),"-C",unpack]);const manifestPath=join(unpack,"install/install-manifest.json"),manifest=JSON.parse(readFileSync(manifestPath,"utf8"));manifest.version=version;writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+"\n");const archive=join(out,"lan-model-controller-linux-any.tar.gz");execFileSync("tar",["-czf",archive,"-C",unpack,...readdirSync(unpack).sort()]);const bytes=readFileSync(archive),digest=createHash("sha256").update(bytes).digest("hex");writeFileSync(join(out,"checksums.txt"),`${digest}  lan-model-controller-linux-any.tar.gz\n`);const canonical=`lan-model-controller-linux-any.tar.gz\0${digest}\0${bytes.length}\n`,inventoryDigest=createHash("sha256").update(canonical).digest("hex"),sourceCommit=JSON.parse(readFileSync(join(f.artifacts,"package-inventory.json"),"utf8")).sourceCommit;writeFileSync(join(out,"package-inventory.json"),JSON.stringify({schemaVersion:1,sourceCommit,inventoryDigest,packages:[{name:"lan-model-controller-linux-any.tar.gz",role:"controller",target:"linux-any",size:bytes.length,sha256:digest}]},null,2)+"\n");return out;}

test("dirty sources, checksum failure, and symlink redirection fail before mutation",()=>{const f=fixture();try{let r=f.run(install,["--artifact-dir",f.artifacts],{LANMM_TEST_GIT_DIRTY:"1"});assert.notEqual(r.status,0);assert.match(r.stderr,/repository is dirty/);assert.equal(existsSync(join(f.root,"data")),false);writeFileSync(join(f.artifacts,"checksums.txt"),`${"0".repeat(64)}  lan-model-controller-linux-any.tar.gz\n`);r=f.run(install,["--artifact-dir",f.artifacts]);assert.notEqual(r.status,0);assert.match(r.stderr,/checksum verification failed/);assert.equal(existsSync(join(f.root,"data")),false);cpSync(join(sourceArtifacts,"checksums.txt"),join(f.artifacts,"checksums.txt"));mkdirSync(join(f.root,"outside"));symlinkSync(join(f.root,"outside"),join(f.root,"data"));r=f.run(install,["--artifact-dir",f.artifacts]);assert.notEqual(r.status,0);assert.match(r.stderr,/symlink path redirection rejected/);assert.equal(existsSync(join(f.root,"outside/lan-model-manager-alpha")),false);}finally{f.cleanup();}});

test("successful install waits for delayed readiness, remains rootless and loopback-only, and is idempotent",()=>{const f=fixture();try{writeFileSync(f.health,"fail\nfail\nok\nok\n");let r=f.run(install,["--artifact-dir",f.artifacts]);assert.equal(r.status,0,r.stdout+r.stderr);assert.equal(readFileSync(pointer(f),"utf8"),"0.0.0\n");const unit=readFileSync(join(f.root,"config/systemd/user/lan-model-manager-alpha.service"),"utf8");assert.match(unit,/LANMM_BIND_HOST=127\.0\.0\.1/);assert.match(unit,/LANMM_PORT=7340/);assert.match(unit,/LANMM_INFERENCE_PORT=7341/);assert.match(unit,/LANMM_TLS_REQUIRED=false/);assert.match(unit,/LANMM_DISCOVERY_ENABLED=false/);assert.match(unit,/UMask=0077/);assert.doesNotMatch(unit,/\/opt|\/etc\/|0\.0\.0\.0/);writeFileSync(join(f.root,"config/systemd/user/lan-model-manager-alpha.service"),"damaged\n");r=f.run(install,["--artifact-dir",f.artifacts]);assert.equal(r.status,0,r.stdout+r.stderr);assert.match(readFileSync(join(f.root,"config/systemd/user/lan-model-manager-alpha.service"),"utf8"),/UMask=0077/);const log=readFileSync(f.log,"utf8");assert.match(log,/systemctl --user daemon-reload/);assert.match(log,/systemctl --user enable --now lan-model-manager-alpha\.service/);assert.match(log,/systemctl --user restart lan-model-manager-alpha\.service/);assert.match(log,/curl .*http:\/\/127\.0\.0\.1:7340\/auth\/v1\/status/);assert.match(log,/xdg-open http:\/\/127\.0\.0\.1:7340/);}finally{f.cleanup();}});

test("explicit private-LAN agent plane preserves loopback console and binds only the selected address",()=>{const f=fixture();try{writeFileSync(f.health,"ok\n");const r=f.run(install,["--artifact-dir",f.artifacts,"--agent-plane-address","192.168.50.10","--agent-plane-port","7443"]);assert.equal(r.status,0,r.stdout+r.stderr);const unit=readFileSync(join(f.root,"config/systemd/user/lan-model-manager-alpha.service"),"utf8");assert.match(unit,/LANMM_BIND_HOST=127\.0\.0\.1/);assert.match(unit,/LANMM_INFERENCE_HOST=127\.0\.0\.1/);assert.match(unit,/LANMM_DISCOVERY_ENABLED=true/);assert.match(unit,/LANMM_AGENT_PLANE_ENABLED=true/);assert.match(unit,/LANMM_AGENT_PLANE_HOST=192\.168\.50\.10/);assert.match(unit,/LANMM_AGENT_PLANE_PORT=7443/);assert.match(unit,/LANMM_AGENT_PLANE_ADVERTISED_ADDRESS=192\.168\.50\.10/);assert.doesNotMatch(unit,/0\.0\.0\.0/);}finally{f.cleanup();}});

test("failed same-version private-plane reconfiguration restores prior unit and service state",()=>{const f=fixture();try{writeFileSync(f.health,"ok\n");let r=f.run(install,["--artifact-dir",f.artifacts]);assert.equal(r.status,0,r.stdout+r.stderr);const unitPath=join(f.root,"config/systemd/user/lan-model-manager-alpha.service"),before=readFileSync(unitPath,"utf8");assert.equal(existsSync(join(f.root,"enabled")),true);assert.equal(existsSync(join(f.root,"active")),true);writeFileSync(f.health,"fail-always\n");r=f.run(install,["--artifact-dir",f.artifacts,"--agent-plane-address","192.168.50.10","--agent-plane-port","7443"]);assert.notEqual(r.status,0);assert.match(r.stderr,/existing installation rolled back: health check failed/);assert.equal(readFileSync(unitPath,"utf8"),before);assert.equal(existsSync(join(f.root,"enabled")),true);assert.equal(existsSync(join(f.root,"active")),true);assert.match(readFileSync(f.log,"utf8"),/systemctl --user restart lan-model-manager-alpha\.service/);}finally{f.cleanup();}});
test("agent-plane arguments reject non-private, noncanonical, and conflicting values",()=>{const f=fixture();try{for(const args of [["--agent-plane-address","8.8.8.8"],["--agent-plane-address","192.168.001.10"],["--agent-plane-address","192.168.1.10","--agent-plane-port","7340"],["--agent-plane-port","7444"]]){const r=f.run(install,["--dry-run","--artifact-dir",f.artifacts,...args]);assert.notEqual(r.status,0);assert.equal(existsSync(join(f.root,"data")),false);}}finally{f.cleanup();}});

test("failed upgrade health rolls back the prior release and service",()=>{const f=fixture();try{writeFileSync(f.health,"ok\nfail-always\n");let r=f.run(install,["--artifact-dir",f.artifacts]);assert.equal(r.status,0,r.stdout+r.stderr);const upgrade=makeUpgrade(f,"0.1.0");r=f.run(install,["--artifact-dir",upgrade]);assert.notEqual(r.status,0);assert.match(r.stderr,/installation rolled back: health check failed/);assert.equal(readFileSync(pointer(f),"utf8"),"0.0.0\n");assert.equal(existsSync(join(f.root,"data/lan-model-manager-alpha/releases/controller/0.1.0")),false);assert.match(readFileSync(f.log,"utf8"),/systemctl --user restart lan-model-manager-alpha\.service/);}finally{f.cleanup();}});

test("uninstall preserves state by default and purge removes it explicitly",()=>{const f=fixture();try{writeFileSync(f.health,"ok\n");let r=f.run(install,["--artifact-dir",f.artifacts]);assert.equal(r.status,0,r.stdout+r.stderr);const sentinel=join(f.root,"state/lan-model-manager-alpha/controller/keep.db");writeFileSync(sentinel,"keep");r=f.run(uninstall);assert.equal(r.status,0,r.stdout+r.stderr);assert.equal(readFileSync(sentinel,"utf8"),"keep");assert.equal(existsSync(join(f.root,"data/lan-model-manager-alpha")),false);r=f.run(uninstall,["--purge"]);assert.equal(r.status,0,r.stdout+r.stderr);assert.match(r.stderr,/permanently removes controller state/);assert.equal(existsSync(sentinel),false);}finally{f.cleanup();}});

test("dry runs verify but do not invoke mutating service commands",()=>{const f=fixture();try{const r=f.run(install,["--dry-run","--artifact-dir",f.artifacts]);assert.equal(r.status,0,r.stdout+r.stderr);assert.match(r.stdout,/DRY RUN: verified/);const log=readFileSync(f.log,"utf8");assert.doesNotMatch(log,/enable|disable|daemon-reload/);assert.equal(existsSync(join(f.root,"data")),false);}finally{f.cleanup();}});

test("entrypoints contain no privileged or exposure operations",()=>{for(const path of [install,uninstall,join(repo,"scripts/alpha/fedora-alpha.mjs")]){const body=readFileSync(path,"utf8");assert.doesNotMatch(body,/\bsudo\b|firewall-cmd|\bufw\b|\/opt\/|\/etc\/systemd\/system|0\.0\.0\.0|run\("systemctl",\[(?!"--user")/);}});
