import assert from "node:assert/strict";import { readFileSync } from "node:fs";import test from "node:test";import { advertisementRecords,assembleCandidates,buildQuery,decodeMessage,encodeMessage,MDNS_IPV4,MDNS_PORT,MDNS_SERVICE,type DnsRecord } from "./dns.js";import { DiscoveryListener,type DiscoverySocket } from "./listener.js";
const input={id:"agent-1",displayName:"Office GPU",protocolVersion:{major:1,minor:0},agentPort:7443,platform:"linux" as const,addresses:["192.168.1.20","2001:db8::1"],ttlSeconds:120};
function packet(){const records=advertisementRecords(input);assert.ok(records.ok);const encoded=encodeMessage(records.value);assert.ok(encoded.ok);return encoded.value;}
test("mDNS advertisement round-trips and assembles only source-bound untrusted candidates",()=>{const decoded=decodeMessage(packet());assert.ok(decoded.ok);if(decoded.ok)assert.deepEqual(decoded.value.map(r=>r.data.kind),["ptr","srv","txt","a","aaaa"]);const candidates=assembleCandidates(packet(),"192.168.1.20","2026-09-27T20:00:00.000Z");assert.equal(candidates.length,1);assert.equal(candidates[0]!.trustState,"untrusted");assert.equal(candidates[0]!.address,"192.168.1.20");assert.equal(assembleCandidates(packet(),"192.168.1.99","2026-09-27T20:00:00.000Z").length,0);});
test("decoder accepts a compressed answer name and rejects pointer cycles and truncation",()=>{const query=buildQuery(),target=Buffer.from([5,97,103,101,110,116,7,115,101,114,118,105,99,101,0]);const header=Buffer.from(query);header.writeUInt16BE(1,6);const answer=Buffer.concat([Buffer.from([0xc0,0x0c,0,12,0,1,0,0,0,60,0,target.length]),target]);const decoded=decodeMessage(Buffer.concat([header,answer]));assert.ok(decoded.ok);const cycle=Buffer.from([0,0,0x84,0,0,0,0,1,0,0,0,0,0xc0,0x0c,0,12,0,1,0,0,0,60,0,2,0xc0,0x0c]);assert.equal(decodeMessage(cycle).ok,false);assert.equal(decodeMessage(packet().subarray(0,20)).ok,false);});
test("decoder enforces packet counts, trailing bytes, duplicate and extra TXT keys",()=>{
  const tooMany=Buffer.alloc(12);tooMany.writeUInt16BE(129,6);assert.equal(decodeMessage(tooMany).ok,false);
  assert.equal(decodeMessage(Buffer.concat([packet(),Buffer.from([0])])).ok,false);
  const records=advertisementRecords(input);assert.ok(records.ok);
  const txt=records.value.find(r=>r.data.kind==="txt")!;
  const base=txt.data.kind==="txt"?txt.data.entries:[];
  const duplicate=records.value.map(r=>r===txt?{...r,data:{kind:"txt" as const,entries:[...base,["id","evil"] as const]}}:r);
  const extra=records.value.map(r=>r===txt?{...r,data:{kind:"txt" as const,entries:[...base,["secret","no"] as const]}}:r);
  for(const set of [duplicate,extra]){const encoded=encodeMessage(set);assert.ok(encoded.ok);assert.equal(assembleCandidates(encoded.value,"192.168.1.20","2026-09-27T20:00:00.000Z").length,0);}
});
class FakeSocket implements DiscoverySocket {listeners:{message?: (message:Buffer,info:{address:string})=>void;error?:()=>void}={};bound=0;members:string[]=[];sends:Array<{port:number,address:string,message:Buffer}>=[];closed=0;on(event:"message"|"error",listener:any){this.listeners[event]=listener;return this;}bind(port:number,callback:()=>void){this.bound=port;callback();}addMembership(address:string){this.members.push(address);}send(message:Buffer,port:number,address:string,callback?:(error:Error|null)=>void){this.sends.push({message,port,address});callback?.(null);}close(){this.closed++;}}
test("listener is explicit, bounded, deduplicating, refreshes and prunes candidates",()=>{let now="2026-09-27T20:00:00.000Z",created=0,snapshots=0;const sockets:FakeSocket[]=[];const listener=new DiscoveryListener({now:()=>now,socketFactory:()=>{created++;const socket=new FakeSocket();sockets.push(socket);return socket;},onSnapshot:()=>snapshots++});assert.equal(created,0);listener.start();listener.start();assert.equal(created,1);assert.equal(sockets[0]!.bound,MDNS_PORT);assert.deepEqual(sockets[0]!.members,[MDNS_IPV4]);assert.equal(sockets[0]!.sends.length,1);assert.doesNotThrow(()=>sockets[0]!.listeners.error?.());sockets[0]!.listeners.message?.(packet(),{address:"192.168.1.20"});assert.equal(listener.list().length,1);now="2026-09-27T20:01:00.000Z";listener.ingest(packet(),"192.168.1.20");assert.equal(listener.list()[0]!.firstSeen,"2026-09-27T20:00:00.000Z");assert.equal(listener.list()[0]!.lastSeen,now);now="2026-09-27T20:03:01.000Z";assert.equal(listener.prune(),1);assert.equal(listener.list().length,0);assert.ok(snapshots>=2);listener.stop();listener.stop();assert.equal(sockets[0]!.closed,1);});
test("listener ignores malformed, oversized, incompatible and capacity-excess packets without throwing",()=>{const socket=new FakeSocket(),listener=new DiscoveryListener({socketFactory:()=>socket,maxCandidates:1});listener.start();assert.doesNotThrow(()=>socket.listeners.message?.(Buffer.alloc(70_000),{address:"192.168.1.20"}));assert.doesNotThrow(()=>socket.listeners.message?.(Buffer.from([1,2,3]),{address:"192.168.1.20"}));const valid=advertisementRecords(input);assert.ok(valid.ok);const incompatible=valid.value.map(r=>r.data.kind==="txt"?{...r,data:{kind:"txt" as const,entries:r.data.entries.map(([k,v])=>[k,k==="proto"?"2.0":v] as const)}}:r);const badBytes=encodeMessage(incompatible);assert.ok(badBytes.ok);listener.ingest(badBytes.value,"192.168.1.20");assert.equal(listener.list().length,0);listener.ingest(packet(),"192.168.1.20");const second=advertisementRecords({...input,id:"agent-2"});assert.ok(second.ok);const secondBytes=encodeMessage(second.value);assert.ok(secondBytes.ok);listener.ingest(secondBytes.value,"192.168.1.20");assert.equal(listener.list().length,1);assert.equal(listener.list()[0]!.id,"agent-1");listener.stop();});
test("Go advertisement fixture decodes identically in TypeScript",()=>{const hex=readFileSync("agents/host-agent/internal/discovery/testdata/advertisement.hex","utf8").trim();const decoded=decodeMessage(Buffer.from(hex,"hex"));assert.ok(decoded.ok);const candidates=assembleCandidates(Buffer.from(hex,"hex"),"192.168.1.20","2026-09-27T20:00:00.000Z");assert.equal(candidates.length,1);assert.equal(candidates[0]!.id,"agent-1");});
