import { isIPv4,isIPv6 } from "node:net";
import { parseDiscoveryAdvertisement,parseDiscoveryCandidate,type DiscoveryCandidate } from "@lan-model-manager/core";
export const MDNS_SERVICE="_lanmodelmanager._tcp.local";
export const MDNS_IPV4="224.0.0.251";
export const MDNS_IPV6="ff02::fb";
export const MDNS_PORT=5353;
export const MAX_MDNS_PACKET=65_535;
const A=1,PTR=12,TXT=16,AAAA=28,SRV=33,IN=1,MAX_RECORDS=128,MAX_POINTERS=16,MAX_TXT=8;
export type DnsData={kind:"ptr";target:string}|{kind:"srv";port:number;target:string}|{kind:"txt";entries:readonly (readonly [string,string])[]}|{kind:"a"|"aaaa";address:string}|{kind:"unknown"};
export interface DnsRecord {readonly name:string;readonly type:number;readonly ttl:number;readonly data:DnsData}
export type DnsResult<T>={readonly ok:true;readonly value:T}|{readonly ok:false;readonly error:string};
const fail=<T>(error:string):DnsResult<T>=>({ok:false,error});
function nameBytes(name:string):number[]|null {if(name.length<1||Buffer.byteLength(name)>253)return null;const out:number[]=[];for(const label of name.split(".")){const bytes=Buffer.from(label,"utf8");if(bytes.length<1||bytes.length>63)return null;out.push(bytes.length,...bytes);}out.push(0);return out;}
function u16(out:number[],n:number){out.push((n>>>8)&255,n&255);}function u32(out:number[],n:number){out.push((n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255);}
function ipv4Bytes(value:string):number[]|null {if(!isIPv4(value))return null;const parts=value.split(".").map(Number);return parts.length===4?parts:null;}
function ipv6Bytes(value:string):number[]|null {if(!isIPv6(value)||value.includes("."))return null;const halves=value.toLowerCase().split("::");if(halves.length>2)return null;const left=halves[0]?halves[0].split(":"):[],right=halves[1]?halves[1].split(":"):[];if(halves.length===1&&left.length!==8)return null;const zeros=8-left.length-right.length;if(zeros<(halves.length===2?1:0))return null;const groups=[...left,...Array(zeros).fill("0"),...right];if(groups.length!==8||groups.some(g=>!/^[0-9a-f]{1,4}$/.test(g)))return null;const out:number[]=[];for(const group of groups){const n=parseInt(group,16);out.push(n>>>8,n&255);}return out;}
function ipv6String(bytes:Uint8Array):string {const groups:number[]=[];for(let i=0;i<16;i+=2)groups.push((bytes[i]!<<8)|bytes[i+1]!);let start=-1,length=0;for(let i=0;i<8;){if(groups[i]!==0){i++;continue;}let j=i;while(j<8&&groups[j]===0)j++;if(j-i>length){start=i;length=j-i;}i=j;}const pieces=groups.map(n=>n.toString(16));if(length>1){pieces.splice(start,length,"");let value=pieces.join(":");if(start===0)value=":"+value;if(start+length===8)value=value+":";return value;}return pieces.join(":");}
function encodeRdata(record:DnsRecord):number[]|null {const d=record.data;if(d.kind==="ptr")return nameBytes(d.target);if(d.kind==="srv"){const target=nameBytes(d.target);if(!target||d.port<1||d.port>65535)return null;return[0,0,0,0,d.port>>>8,d.port&255,...target];}if(d.kind==="txt"){if(d.entries.length<1||d.entries.length>MAX_TXT)return null;const out:number[]=[];for(const [key,value] of d.entries){const bytes=Buffer.from(`${key}=${value}`,"utf8");if(bytes.length<3||bytes.length>255)return null;out.push(bytes.length,...bytes);}return out;}if(d.kind==="a")return ipv4Bytes(d.address);if(d.kind==="aaaa")return ipv6Bytes(d.address);return null;}
export function encodeMessage(records:readonly DnsRecord[]):DnsResult<Buffer>{if(records.length>MAX_RECORDS)return fail("ERR_DNS_COUNT");const out:number[]=[];u16(out,0);u16(out,0x8400);u16(out,0);u16(out,records.length);u16(out,0);u16(out,0);for(const record of records){const name=nameBytes(record.name),data=encodeRdata(record);if(!name||!data||!Number.isSafeInteger(record.ttl)||record.ttl<0||record.ttl>3600)return fail("ERR_DNS_RECORD");out.push(...name);u16(out,record.type);u16(out,IN);u32(out,record.ttl);u16(out,data.length);out.push(...data);if(out.length>MAX_MDNS_PACKET)return fail("ERR_DNS_SIZE");}return{ok:true,value:Buffer.from(out)};}
export function buildQuery():Buffer {const out:number[]=[];u16(out,0);u16(out,0);u16(out,1);u16(out,0);u16(out,0);u16(out,0);out.push(...nameBytes(MDNS_SERVICE)!);u16(out,PTR);u16(out,IN);return Buffer.from(out);}
function read16(b:Uint8Array,o:number):number|null{return o+2<=b.length?(b[o]!<<8)|b[o+1]!:null;}function read32(b:Uint8Array,o:number):number|null{return o+4<=b.length?((b[o]!<<24)|(b[o+1]!<<16)|(b[o+2]!<<8)|b[o+3]!)>>>0:null;}
function decodeName(packet:Uint8Array,start:number):DnsResult<{name:string;end:number}>{let offset=start,end=-1,pointers=0;const labels:string[]=[],visited=new Set<number>();while(true){if(offset>=packet.length)return fail("ERR_DNS_TRUNCATED");const size=packet[offset]!;if(size===0){if(end<0)end=offset+1;break;}if((size&0xc0)===0xc0){if(offset+1>=packet.length)return fail("ERR_DNS_TRUNCATED");const target=((size&0x3f)<<8)|packet[offset+1]!;if(target>=packet.length)return fail("ERR_DNS_POINTER");if(visited.has(target)||++pointers>MAX_POINTERS)return fail("ERR_DNS_POINTER");visited.add(target);if(end<0)end=offset+2;offset=target;continue;}if((size&0xc0)!==0||size>63||offset+1+size>packet.length)return fail("ERR_DNS_NAME");const bytes=packet.slice(offset+1,offset+1+size);const label=Buffer.from(bytes).toString("utf8");if(Buffer.from(label,"utf8").length!==size||/[\u0000-\u001f\u007f.]/.test(label))return fail("ERR_DNS_NAME");labels.push(label);if(labels.length>128||Buffer.byteLength(labels.join("."))>253)return fail("ERR_DNS_NAME");offset+=1+size;}return{ok:true,value:{name:labels.join("."),end}};}
function decodeRecord(packet:Uint8Array,start:number):DnsResult<{record:DnsRecord;end:number}>{const name=decodeName(packet,start);if(!name.ok)return name;let o=name.value.end;const type=read16(packet,o),cls=read16(packet,o+2),ttl=read32(packet,o+4),length=read16(packet,o+8);if(type===null||cls===null||ttl===null||length===null)return fail("ERR_DNS_TRUNCATED");if((cls&0x7fff)!==IN)return fail("ERR_DNS_CLASS");o+=10;const end=o+length;if(end>packet.length)return fail("ERR_DNS_TRUNCATED");let data:DnsData={kind:"unknown"};if(type===PTR){const target=decodeName(packet,o);if(!target.ok||target.value.end!==end)return fail("ERR_DNS_RDATA");data={kind:"ptr",target:target.value.name};}else if(type===SRV){if(length<7)return fail("ERR_DNS_RDATA");const port=read16(packet,o+4),target=decodeName(packet,o+6);if(port===null||port<1||!target.ok||target.value.end!==end)return fail("ERR_DNS_RDATA");data={kind:"srv",port,target:target.value.name};}else if(type===TXT){const entries:Array<readonly [string,string]>=[];const keys=new Set<string>();let p=o;while(p<end){const n=packet[p++]!;if(n===0||p+n>end||entries.length>=MAX_TXT)return fail("ERR_DNS_TXT");const raw=packet.slice(p,p+n),value=Buffer.from(raw).toString("utf8");if(Buffer.from(value,"utf8").length!==n)return fail("ERR_DNS_TXT");p+=n;const eq=value.indexOf("=");if(eq<1)return fail("ERR_DNS_TXT");const key=value.slice(0,eq),item=value.slice(eq+1);if(keys.has(key)||!/^[a-z]+$/.test(key)||Buffer.byteLength(item)>128)return fail("ERR_DNS_TXT");keys.add(key);entries.push([key,item]);}data={kind:"txt",entries:Object.freeze(entries)};}else if(type===A){if(length!==4)return fail("ERR_DNS_RDATA");data={kind:"a",address:Array.from(packet.slice(o,end)).join(".")};}else if(type===AAAA){if(length!==16)return fail("ERR_DNS_RDATA");data={kind:"aaaa",address:ipv6String(packet.slice(o,end))};}return{ok:true,value:{record:Object.freeze({name:name.value.name,type,ttl,data}),end}};}
export function decodeMessage(packet:Uint8Array):DnsResult<readonly DnsRecord[]>{if(!(packet instanceof Uint8Array)||packet.length<12||packet.length>MAX_MDNS_PACKET)return fail("ERR_DNS_SIZE");const q=read16(packet,4),a=read16(packet,6),ns=read16(packet,8),ar=read16(packet,10);if(q===null||a===null||ns===null||ar===null||q>16||a+ns+ar>MAX_RECORDS)return fail("ERR_DNS_COUNT");let o=12;for(let i=0;i<q;i++){const name=decodeName(packet,o);if(!name.ok||name.value.end+4>packet.length)return fail("ERR_DNS_TRUNCATED");o=name.value.end+4;}const records:DnsRecord[]=[];for(let i=0;i<a+ns+ar;i++){const decoded=decodeRecord(packet,o);if(!decoded.ok)return decoded;o=decoded.value.end;if(decoded.value.record.data.kind!=="unknown")records.push(decoded.value.record);}if(o!==packet.length)return fail("ERR_DNS_TRAILING");return{ok:true,value:Object.freeze(records)};}
export interface AdvertisementInput {readonly id:string;readonly displayName:string;readonly protocolVersion:{readonly major:number;readonly minor:number};readonly agentPort:number;readonly platform:"linux"|"darwin"|"windows";readonly addresses:readonly string[];readonly ttlSeconds:number}
function parseAdvertisementInput(input:unknown):AdvertisementInput|null {try{if(typeof input!=="object"||input===null||Array.isArray(input))return null;const proto=Object.getPrototypeOf(input);if(proto!==Object.prototype&&proto!==null)return null;const keys=["id","displayName","protocolVersion","agentPort","platform","addresses","ttlSeconds"];const own=Reflect.ownKeys(input);if(own.length!==keys.length||own.some(key=>typeof key!=="string"||!keys.includes(key)))return null;const d=Object.getOwnPropertyDescriptors(input);if(keys.some(key=>!d[key]||!("value" in d[key])))return null;const base=parseDiscoveryAdvertisement({id:d.id!.value,displayName:d.displayName!.value,protocolVersion:d.protocolVersion!.value,agentPort:d.agentPort!.value,platform:d.platform!.value});if(!base.ok)return null;const addresses=d.addresses!.value,ttl=d.ttlSeconds!.value;if(!Array.isArray(addresses)||addresses.length>16||typeof ttl!=="number"||!Number.isSafeInteger(ttl)||ttl<1||ttl>3600)return null;const descriptors=Object.getOwnPropertyDescriptors(addresses);const arrayKeys=Reflect.ownKeys(addresses);if(arrayKeys.length!==addresses.length+1||arrayKeys.some(key=>typeof key!=="string"||(key!=="length"&&!/^(0|[1-9]\d*)$/.test(key))))return null;const values:string[]=[];for(let i=0;i<addresses.length;i++){const item=descriptors[String(i)];if(!item||!("value" in item)||typeof item.value!=="string")return null;const value=item.value;if(isIPv4(value))values.push(value);else if(isIPv6(value)&&!value.includes("%")){try{if(new URL(`http://[${value}]/`).hostname.slice(1,-1)!==value)return null;}catch{return null;}values.push(value);}else return null;}return{id:base.value.id,displayName:base.value.displayName,protocolVersion:base.value.protocolVersion,agentPort:base.value.agentPort,platform:base.value.platform,addresses:Object.freeze(values),ttlSeconds:ttl};}catch{return null;}}
export function advertisementRecords(raw:AdvertisementInput):DnsResult<readonly DnsRecord[]>{const input=parseAdvertisementInput(raw);if(!input)return fail("ERR_DNS_RECORD");const instance=`${input.id}.${MDNS_SERVICE}`,host=`${input.id}.local`,txt:readonly (readonly [string,string])[]=Object.freeze([["id",input.id],["name",input.displayName],["platform",input.platform],["proto",`${input.protocolVersion.major}.${input.protocolVersion.minor}`]]);const records:DnsRecord[]=[{name:MDNS_SERVICE,type:PTR,ttl:input.ttlSeconds,data:{kind:"ptr",target:instance}},{name:instance,type:SRV,ttl:input.ttlSeconds,data:{kind:"srv",port:input.agentPort,target:host}},{name:instance,type:TXT,ttl:input.ttlSeconds,data:{kind:"txt",entries:txt}}];for(const address of input.addresses){if(isIPv4(address))records.push({name:host,type:A,ttl:input.ttlSeconds,data:{kind:"a",address}});else records.push({name:host,type:AAAA,ttl:input.ttlSeconds,data:{kind:"aaaa",address}});}return encodeMessage(records).ok?{ok:true,value:Object.freeze(records)}:fail("ERR_DNS_RECORD");}
export function assembleCandidates(packet:Uint8Array,sourceAddress:string,observedAt:string):readonly DiscoveryCandidate[]{
  const decoded=decodeMessage(packet);if(!decoded.ok)return Object.freeze([]);
  const pointerRecords=decoded.value.filter(r=>r.name===MDNS_SERVICE&&r.data.kind==="ptr");
  const pointers=new Set(pointerRecords.map(r=>(r.data as {kind:"ptr";target:string}).target));
  const out:DiscoveryCandidate[]=[];
  for(const instance of [...pointers].sort()){
    const pointer=pointerRecords.find(r=>r.data.kind==="ptr"&&r.data.target===instance);
    const srv=decoded.value.find(r=>r.name===instance&&r.data.kind==="srv"),txt=decoded.value.find(r=>r.name===instance&&r.data.kind==="txt");
    if(!srv||!txt||srv.data.kind!=="srv"||txt.data.kind!=="txt")continue;
    const srvData=srv.data,txtData=txt.data;
    const allowed=new Set(["id","name","platform","proto"]);if(txtData.entries.length!==4||txtData.entries.some(([k])=>!allowed.has(k)))continue;
    const values=Object.fromEntries(txtData.entries);const proto=/^(0|[1-9]\d*)\.(0|[1-9]\d*)$/.exec(values.proto??"");if(!proto||instance!==`${values.id}.${MDNS_SERVICE}`||srvData.target!==`${values.id}.local`)continue;
    const addressRecords=decoded.value.filter(r=>r.name===srvData.target&&(r.data.kind==="a"||r.data.kind==="aaaa"));
    if(addressRecords.length===0||!addressRecords.some(r=>(r.data as {address:string}).address===sourceAddress))continue;
    const ttl=Math.max(1,Math.min(3600,...[pointer!,srv,txt,...addressRecords].map(r=>r.ttl)));
    const candidate=parseDiscoveryCandidate({id:values.id,displayName:values.name,protocolVersion:{major:Number(proto[1]),minor:Number(proto[2])},agentPort:srvData.port,platform:values.platform,address:sourceAddress,observedAt,ttlSeconds:ttl});if(candidate.ok)out.push(candidate.value);
  }
  return Object.freeze(out);
}
