import dgram from "node:dgram";
import { refreshDiscoveryCandidate,type DiscoveryCandidate } from "@lan-model-manager/core";
import { assembleCandidates,buildQuery,MDNS_IPV4,MDNS_IPV6,MDNS_PORT,MAX_MDNS_PACKET } from "./dns.js";
export interface DiscoverySocket {on(event:"message",listener:(message:Buffer,info:{address:string})=>void):this;on(event:"error",listener:()=>void):this;bind(port:number,callback:()=>void):void;addMembership(address:string):void;send(message:Buffer,port:number,address:string,callback?:(error:Error|null)=>void):void;close():void}
export interface DiscoveryListenerOptions {readonly now?:()=>string;readonly socketFactory?:(kind:"udp4"|"udp6")=>DiscoverySocket;readonly ipv6?:boolean;readonly maxCandidates?:number;readonly onSnapshot?:(candidates:readonly DiscoveryCandidate[])=>void}
export class DiscoveryListener {private readonly now:()=>string;private readonly factory:(kind:"udp4"|"udp6")=>DiscoverySocket;private readonly ipv6:boolean;private readonly cap:number;private readonly callback?:((candidates:readonly DiscoveryCandidate[])=>void)|undefined;private sockets:Array<{socket:DiscoverySocket;group:string}>=[];private readonly candidates=new Map<string,DiscoveryCandidate>();
 constructor(options:DiscoveryListenerOptions={}){this.now=options.now??(()=>new Date().toISOString());this.factory=options.socketFactory??((kind)=>dgram.createSocket({type:kind,reuseAddr:true}) as unknown as DiscoverySocket);this.ipv6=options.ipv6===true;this.cap=options.maxCandidates??1024;this.callback=options.onSnapshot;if(!Number.isSafeInteger(this.cap)||this.cap<1||this.cap>1024)throw new Error("ERR_DISCOVERY_LIMIT");}
 start():void {if(this.sockets.length)return;this.open("udp4",MDNS_IPV4);if(this.ipv6)this.open("udp6",MDNS_IPV6);}
 private open(kind:"udp4"|"udp6",group:string):void {let socket:DiscoverySocket;try{socket=this.factory(kind);}catch{return;}const entry={socket,group};this.sockets.push(entry);socket.on("message",(message,info)=>this.ingest(message,info.address));socket.on("error",()=>{});try{socket.bind(MDNS_PORT,()=>{try{socket.addMembership(group);socket.send(buildQuery(),MDNS_PORT,group,()=>{});}catch{}});}catch{try{socket.close();}catch{}this.sockets=this.sockets.filter(item=>item!==entry);}}
 query():void {const packet=buildQuery();for(const {socket,group} of this.sockets)try{socket.send(packet,MDNS_PORT,group,()=>{});}catch{}}
 ingest(message:Uint8Array,sourceAddress:string):void {if(message.length>MAX_MDNS_PACKET)return;let now:string;try{now=this.now();}catch{return;}for(const candidate of assembleCandidates(message,sourceAddress,now)){const key=`${candidate.id}\u0000${candidate.address}`,existing=this.candidates.get(key);if(existing){const refreshed=refreshDiscoveryCandidate(existing,{id:candidate.id,displayName:candidate.displayName,protocolVersion:candidate.protocolVersion,agentPort:candidate.agentPort,platform:candidate.platform,address:candidate.address,observedAt:candidate.lastSeen,ttlSeconds:candidate.ttlSeconds});if(refreshed.ok)this.candidates.set(key,refreshed.value);}else if(this.candidates.size<this.cap)this.candidates.set(key,candidate);}this.prune();this.emit();}
 list():readonly DiscoveryCandidate[]{this.prune();return Object.freeze([...this.candidates.values()].sort((a,b)=>a.id.localeCompare(b.id)||a.address.localeCompare(b.address)));}
 prune():number {let now:number;try{now=Date.parse(this.now());}catch{return 0;}let removed=0;for(const[key,value]of this.candidates)if(Date.parse(value.expiresAt)<=now){this.candidates.delete(key);removed++;}if(removed)this.emit();return removed;}
 private emit(){if(this.callback)try{this.callback(this.listWithoutPrune());}catch{}}
 private listWithoutPrune():readonly DiscoveryCandidate[]{return Object.freeze([...this.candidates.values()].sort((a,b)=>a.id.localeCompare(b.id)||a.address.localeCompare(b.address)));}
 stop():void {const sockets=this.sockets;this.sockets=[];for(const {socket} of sockets)try{socket.close();}catch{}}
}
